### ISSUE TITLE
As a user, I'd like to have a "Delete All Failed Records" on the NPSP Data Import tab, so I can easily delete records I want to reimport.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1111]
From John Fine:

 It would be nice to have a button on the DI list view to "Delete All Failed Records". I happened to import a bunch of DI records with an incorrectly mapped field (my mistake), which made them all fail to be processed by DI. The easy fix was to delete all the failure records, fix the mapping error in my source data, then re-import to DI. I had to use Apsona to find and delete the failed records.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsjAAA" target="_blank">W-008280</a>

**Comment by mpusto** [comment]
This can be accomplished by using the "Delete All Data Import Records" list view button on a list view filtered by Status=Failed.

**Comment by davidhabib** [comment]
Note true.  Delete All Data Import Records does exactly what it says, and is not tied to what is currently displayed.

**Comment by mpusto** [comment]
Good catch. Thanks @davidhabib
