### ISSUE TITLE
BUG: Open Ended Recurring Donations lose their Next Installment Date when the last open opp is closed.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1124]
From John Fine.

Isssue #4: When I edit my last open Opp to set its STage to a closed Stage, and set its Close Date to whatever date I want (usually the date that the donation check has written on it), the RD code apparently sets Next Donation Date to blank (maybe because there are no more open donations - although there should always be 1 more open Opp as per Issue 3). Then after running the nightly batch which gen's 2 more open Opps, the Next Donation Date of the RD is set to my Close Date (not by me - presumably by RD trigger code), and the Close Date of the newly gen'd Opps is based on that Close Date also (1 year and 2 years after it). This prevents me from continuing to get auto-gen'd Opps indefinitely based on the original Date Established, which is the behavior I am after. In other words, I want my series of Opps that I started (by setting RD.DateEstablished to 9/1/2014),to be due on 9/1 of each year after that, forever, irrespective of what I set each Opp's Close Date to when I edit it to indicate that the money has arrived.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fmUAAQ" target="_blank">W-008241</a>

**Comment by mpusto** [comment]
We are close to releasing new RD features and will not be addressing bugs in the old RD code.
