### ISSUE TITLE
As a user, I would like to be able to verify all my unverified addresses, even if the service doesn't support a bulk mode.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1140]
Smarty Streets supports bulk, but Cicero and Google do not.  However, any addresses imported through a batch will never get verified (since we can't make the web service callout).  Users need to manually run Verify All Addresses.  We should allow that to be done even if it will be one call at a time, as long as we clearly tell the user the implications. 

Shannon: I think the cautionary note is OK, but it needs to call out the potential consequences -- e.g. "Depending on the service you're using, calls may be limited per day or incur charges. Check your provider plan before using this functionality." Probably not in those exact words. :)

**Comment by davidhabib** [comment]
Sarah Cordivano scordivano@azavea.com from Cicero, has requested that we enable this feature even though they do not have a specific bulk api.  Her email:

I just wanted to follow up regarding the possibility of adding batch matching/validation by Cicero in the NPSP. Our API does allow it as long as calls stay below an average of 200 per minute. We recently saw that Smarty Streets removed their free credits for nonprofits so we though this might be a good opportunity to support this functionality as an alternative to smarty streets. Let us know if you have any questions or thoughts. I included my previous message below for reference.

I just wanted to reach out and say we saw some interest on the hub in allowing a batch update of address verification and district matching for all contacts in SF. I wanted to let you know that our API does allow series of calls to do batch updates. We only ask that the calls be throttled to about one per second. If you have any questions or any future interest in updating the NPSP to support these batch updates, please let us know!

**Comment by njjc** [comment]
I'm not sure that it's technically feasible to ensure under 200 calls per minute while allowing execution over large data sets.

**Comment by kbromer** [comment]
**lurch: attach W-007245

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXrAAI" target="_blank">W-007245</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
