### ISSUE TITLE
As a user, I would like to be able lock down Closed opps to prevent any further modifications.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1152]
potentially a global to control this.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsXAAQ" target="_blank">W-008275</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
