### ISSUE TITLE
As an allocations user, I'd like rollups to populate the default GAU even without allocations records.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1192]
Allocations rollups only function on allocations records, but it would be nice to roll up unallocated opps to the default fund if defaults are disabled.

**Comment by kbromer** [comment]
**lurch: attach W-007330

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZEAAY" target="_blank">W-007330</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
