### ISSUE TITLE
As a user, I'd like stack traces from the managed NPSP package to be available to the user

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1222]
Ideally, these would be available in the custom error log and custom error notifications.

Alternatively, we could think wether to send error information (with stack traces) data back from the LMO to the originating org. Maybe we could use Salesforce-to-Salesforce (https://developer.salesforce.com/page/An_Introduction_to_Salesforce_to_Salesforce). If that is not available, we could send a message to a web service we create to process errors sent from the LMO.

**Comment by kbromer** [comment]
**lurch: attach W-007281

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYRAAY" target="_blank">W-007281</a>
