### ISSUE TITLE
As a user, I'd like to know the date and time a notification was sent

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1246]
Also, we may consider adding a "recipient" field. Right now we have checkboxes to know if it was emailed or posted in Chatter.

**Comment by kbromer** [comment]
**lurch: attach W-007342

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZQAAY" target="_blank">W-007342</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.c
