### ISSUE TITLE
As a user, I want to be able to store zip codes > 10 characters when using the Household object, so my zips don't get truncated.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1266]
Household Object has MailingZip set to text(10).  Address object has MailingZip set to test(255).  Salesforce standard mailing zip fields are text(20).  The shortened version in Household Object is causing some international postal codes to get truncated.  This was reported by Click & Pledge here: https://powerofus.force.com/0D58000001maPqf

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ft2AAA" target="_blank">W-008290</a>

**Comment by mbeaty-sf** [comment]
W-7782156

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlGDQAY&title=zip-codes-are-currently-limited-to-10-characters-on-household-object) in the Trailblazer Community for updates.
