### ISSUE TITLE
Changes to the default page layout for the Relationship object

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/NPSP#1331]
https://success.salesforce.com/ideaView?id=08730000000Dj5BAAS&sort=2

**Comment by force2b** [comment]
Interesting. I didn't realize there was an NPSP Category available in the Idea Exchange. Could this cover the need we identified on Friday to allow the community to vote on priority of features to be addressed?

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ft7AAA" target="_blank">W-008292</a>

**Comment by coriobriensfdo** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x800000001ft7AAA" target="_blank">W-008292</a>

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x800000001ft7AAA" target="_blank">W-008292</a>

**Comment by coriobriensfdo** [comment]
**lurch: attach W-008292

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ft7AAA" target="_blank">W-008292</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
