### ISSUE TITLE
Update ApexDocumentation and Code Contributor's Guide to match new styles

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1362]
The style of http://developer.salesforcefoundation.org/ has changed. We should update the following to match it:

http://developer.salesforcefoundation.org/Cumulus/ApexDocumentation/
http://developer.salesforcefoundation.org/Cumulus/Contributor/

It'd be a good time to also add the same header from the home page to these other pages.

**Comment by kbromer** [comment]
**lurch: attach W-007338

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZMAAY" target="_blank">W-007338</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
