### ISSUE TITLE
As a user, I have access to the current Address object from the Account object.

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1411]
Much like we have on Contact, this request is for a similar lookup on Account.  This allows easy creation of formula fields on the object to pull in Address fields.  https://powerofus.force.com/0D58000001twLfh

**Comment by kbromer** [comment]
**lurch: attach W-007242

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXoAAI" target="_blank">W-007242</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
