### ISSUE TITLE
Feature Request: More specific Verification Status

### ISSUE THREAD

**Issue by NathanSpiwak** [SalesforceFoundation/NPSP#1412]
I love the SmartyStreets integration with NPSP 3! I've been looking through my "Pending Verification" addresses and I notice that the API Response has much more useful information than the Verification Status. API Response says things like, "Invalid Zip Code" and "Conflicting Zip Code/City/State" and "Invalid City for given State". I was hoping that you could add that kind of information into the Verification Status field.

**Comment by ceiroa** [comment]
Glad you like it! "Pending verification" should be the status we give the address only until we receive the response from SmartyStreet. Once we do, it should change, even if the verification isn't successful. For example, this is where we set the status when the zipcode is invalid: https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ADDR_SmartyStreets_Validator.cls#L256

There are definitely things to improve with the address validation integrations. If by any chance you are interested in contributing to the project in this area, just let me know. I could help you get set up.

**Comment by NathanSpiwak** [comment]
I've got about 50k records with Verification Status = Pending Verification
so it looks like it's not always being updated. Should the be a bug request
then? I would be happy to help in any way I can, but I'm not a developer
(I'm a certified SF consultant). Are there still ways I can lend a hand?

**Comment by ceiroa** [comment]
No worries. We can keep tracking this issue here. Could you maybe provide
some screenshots and a reproducible case?

**Comment by NathanSpiwak** [comment]
Carlos,

I have over 5,000 records with "Pending Verification" and an API response
(Invalid Zip, Conflicting Zip/City/State Information etc.). I'm not sure
how to reproduce it. I've just been importing and updating contact
addresses. Maybe using the Bulk API has something to do with it? Let me
know if there's anything else you need from me.

[image: Inline image 1]

**Comment by ceiroa** [comment]
The main problem is that when the address is invalid, we don't change the status from "Pending Verification" to anything else. It's verified in the sense that we have sent the verification request (we don't want to send it again), but it's not valid, so we never change the status. We just need to add the error info from the response. 

I believe we give more granular information regarding the problem with the address if we are using the SmartyStreets zipcode endpoint, but not if we are using the address endpoint.

**Comment by NathanSpiwak** [comment]
That sounds like a great improvement. Thanks!

**Comment by kbromer** [comment]
**lurch: attach W-007061

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001c5rAAA" target="_blank">W-007061</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
