### ISSUE TITLE
As a developer, I want to include a basic set of fundraising reports that can be used as "templates".

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1428]

**Comment by bradstruss** [comment]
This sounds pretty techie/niche. I might rewrite this as: 
1. "As a nonprofit admin who has upgraded to NPSP v3 from v2, I want the nice set of v3 reports to be automatically included in my upgrade"

or

2. "As a nonprofit admin who did a fresh install of NPSP v3 into an existing instance, I want the nice set of v3 reports to be automatically included"

**Comment by kbromer** [comment]
**lurch: attach W-007279

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYPAAY" target="_blank">W-007279</a>

**Comment by mbeaty-sf** [comment]
A Reports & Dashboards package is included in the Trial Source Org already, there is a manual installer for those that have upgraded from NPSP 2 > NPSP 3

NPSP Reports Workbook - https://powerofus.force.com/s/article/NPSP-Reports-Workbook
Configure the Reports & Dashboards Package - https://powerofus.force.com/s/article/NPSP-Configure-Reports-and-Dashboards-Package
