### ISSUE TITLE
As a user, I want to see VF Household edit page buttons revert to default values if save fails.

### ISSUE THREAD

**Issue by Zosoled** [SalesforceFoundation/NPSP#1441]
Currently, when a Household is edited and then saved, the three buttons "Save", "Delete", and "Cancel" all switch to the label "Saving..." to denote progress. If the save fails, the labels remain "Saving..." when they should revert to the original values like the standard behavior.

**Comment by kbromer** [comment]
**lurch: attach W-007375

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZyAAI" target="_blank">W-007375</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
