### ISSUE TITLE
As an administrator, add fields to HH_ManageHHAccount VF Page

### ISSUE THREAD

**Issue by pherzogchc** [SalesforceFoundation/NPSP#1480]
Our org would love to use the HH_ManageHHAccount VF page to add new contacts (it's so fast and easy on the eyes) but we require our contacts to have a couple fields populated (Membership Status, Email, etc).  We would like the ability to add fields to the new contact card on the HH_ManageHHAccount VF Page .  

![screen shot 2015-03-25 at 10 36 45 am](https://cloud.githubusercontent.com/assets/9168719/6828296/eeffe93e-d2da-11e4-9164-f325917731f1.png)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fuUAAQ" target="_blank">W-008298</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
