### ISSUE TITLE
Avoid attempting email sends in unit tests

### ISSUE THREAD

**Issue by mscholtz** [SalesforceFoundation/NPSP#1486]
Often, when running NPSP tests in a sandbox, I get errs because usually non-system email is turned off in sandbox, and you guys have tests that attempt to send it.  IMHO it's best to not attempt email sends in tests.  It never sends, but it does still throw an err if it's disabled.

Example from today:

Apex Test Result Detail

```
Time Started    3/27/2015 5:29 PM
Class   ADDR_Validator_TEST
Method Name test400
Pass/Fail   Fail
Error Message   System.EmailException: SendEmail failed. First exception on row 0; first error: NO_MASS_MAIL_PERMISSION, Single email is not enabled for your organization or profile. Single email must be enabled for you to use this feature.: []
Stack Trace (npsp)
```

Looking at that test method, it doesn't do any email sends itself.  Guessing it's some error handling routine that's doing it.  Anyway, I would humbly recommend looking for sendEmail() methods, and wrapping them in

```
 if (!Test.isRunningTest())
```

its not that this err is such a big deal, many folks will understand why it's happening.  but it does mean that when we're debugging it's one more thing we have to look at, and could conceivably be obfuscating a real error.

Thanks!

**Comment by silne30** [comment]
@mscholtz: 
Looking to reproduce this issue. When you say "non-system email is turned off in sandbox", is that a preference you set up in your org? If so, can you give me the steps to do the same. I ran the tests and had no failures. So I figure there is a difference in our environments.

**Comment by mscholtz** [comment]
Yeah, I mean the Access Level setting here:
https://help.salesforce.com/HTViewHelpDoc?id=emailadmin_deliverability.htm

It's set to System Email Only by default for all new sandboxes

On Fri, Apr 10, 2015 at 4:26 PM, John Dorlus <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz>:
> Looking to reproduce this issue. When you say "non-system email is turned
> off in sandbox", is that a preference you set up in your org? If so, can
> you give me the steps to do the same. I ran the tests and had no failures.
> So I figure there is a difference in our environments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1486#issuecomment-91715282>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by silne30** [comment]
Got it. Thanks for your help, @mscholtz. Going to be submitting a PR in a bit.

**Comment by davidhabib** [comment]
@kbromer I think this should remain open as an issue we should fix.  the pull request was closed because it was not the desired solution.

**Comment by kbromer** [comment]
**lurch: attach W-007365

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZoAAI" target="_blank">W-007365</a>
