### ISSUE TITLE
BUG: if the npe01__Account_Processor__c field in the Contacts and Orgs settings is blank, no Household Account gets created

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1493]
However, a household account is created if there is no Contacts and Orgs custom setting at all. It's just if the value of that field is null that an account doesn't get created.

One way to fix it is to add the following code where an account is created in ACCT_IndividualAccounts_TEST:

```
ID recordTypeID = Schema.SObjectType.Account.RecordTypeInfosByName.get(
                                            UTIL_CustomSettingsFacade.getContactsSettings().Account_Processor__c).getRecordTypeId();
                a.RecordTypeId = recordTypeID;
```

If this is fixed, I think the following condition can be removed from all the tests in ACCT_IndividualAccounts_TDTM:

```
if (CAO_Constants.HH_ACCOUNT_PROCESSOR == CAO_Constants.HH_ACCOUNT_PROCESSOR)
```

**Comment by kbromer** [comment]
**lurch: attach W-007366

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZpAAI" target="_blank">W-007366</a>
