### ISSUE TITLE
As a user, I'd like to have relationships automatically created between members of a Household when a member is added or created in an existing Household so I can more easily track how my Contacts are connected

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/NPSP#1545]
- Inserts or updates that add members to a Household should have a relationship of "Household Member" (or something else?) created between the Contacts automatically
-  Removing a member from a Household could update an existing "Household Member" relationship (or perhaps not, depending on the type?  Obviously mother-daughter relationships wouldn't change if the daughter leaves the Household, as an example)
- This could be a configuration option within the Relationships Settings.  "Automatically Create Relationships Between Household Members" and "Automatic Household Relationship Creation Type" 

This also dovetails somewhat with #283

**Comment by kbromer** [comment]
**lurch: attach W-007169

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cS2AAI" target="_blank">W-007169</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
