### ISSUE TITLE
use more realistic zip codes in ADDR_Validator_TEST

### ISSUE THREAD

**Issue by mscholtz** [SalesforceFoundation/NPSP#1568]
in testContactZipOnly it inserts a text value into MailingPostalCode.  This ran afoul of a client routine that was expecting a well-formatted zipcode.  Their code should be more tolerant of non-well-formed data, but in the meantime, unless that text value is needed, could your code use more realistic zip data?  Seems like it would be less likely to run afoul of client code, validation rules, etc if it did.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.46 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.46

**Comment by davidhabib** [comment]
@njjc I think the changes to this have caused a few tests in ADDR_Validator_Batch_TEST to fail against orgs with State & Country picklists enabled.  I'm reopening this issue for that reason.

**Comment by davidhabib** [comment]
also in ADDR_Validator_TEST

**Comment by kbromer** [comment]
**lurch: attach W-007371

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZuAAI" target="_blank">W-007371</a>
