### ISSUE TITLE
Moving Contact to different Household w/ no address has minor issue.

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1593]
Hub thread: https://powerofus.force.com/0D580000029TbDM

If Household B had a default address, and Contact A was just using Household A's default address, then on the move Contact A would get Household B's default address. 

If Contact A had an address override, that address would get copied over to Household B, and Contact A would keep its address and have its override updated to the new address object.

You've found an edge case that I will enter an issue on. In this scenario, the logic was Contact A should get Household B's default address. But since there is no default Address, nothing happened. NPSP should either clear Contact A's address, or copy over the address to Household B.

**Comment by kbromer** [comment]
**lurch: attach W-007454

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cbzAAA" target="_blank">W-007454</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
