### ISSUE TITLE
If Address Management is disabled in Settings, deleting Address records should not clear Address fields on Account/Contact

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#1624]
If an organization decides to disable Household Address management in NPSP Settings, it's logical that they would then want to delete the Address object records to save data storage space. If they do that, the Mailing (contact) and Billing (account) address fields are deleted as if Address Management were still enabled.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwGAAQ" target="_blank">W-008310</a>
