### ISSUE TITLE
As a developer, I'd like to be able to call custom NPSP convert lead methods from apex

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1639]
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjxL&fId=0D58000002BO1wX&emtm=1435840687752&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterPostNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4

**Comment by judisohn** [comment]
Another thread/use case: https://powerofus.force.com/0D58000002J2phQ

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwRAAQ" target="_blank">W-008316</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
