### ISSUE TITLE
Show Household Contacts with Affiliations/Relationships on the Household Account Record

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/NPSP#1649]
Can all Contacts within a household, and their Affiliations to other organizations and Relationships to other Contacts be shown on the Household Account record?  This has come up several times as an enhancement request from clients who do substantial donor cultivation work with Households. Potentially this could be two additional Related Lists, akin to Household Summary Affiliations and Household Summary Relationships?  But, it would require adding logic to both the Relationships and Affiliations Objects to consider Contact Household Account Records (should they exist) separately.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwMAAQ" target="_blank">W-008313</a>

**Comment by riordan** [comment]
Any progress on this one?

**Comment by judisohn** [comment]
@riordan This is still on our backlog and has not been started for development yet.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
