### ISSUE TITLE
As a user, I'd like to change the Opportunity that a Payment is related to

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#1660]
Power of Us thread with a good use case if this is technically possible in packaging: https://powerofus.force.com/0D58000002CI6Wz

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwWAAQ" target="_blank">W-008321</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
