### ISSUE TITLE
As a user, I would like to specify the role in an affiliation record as a picklist similar to relationships, in addition to the Title

### ISSUE THREAD

**Issue by donners77** [SalesforceFoundation/NPSP#1664]
e.g.
contact1: Mary Bloggs
account1: Acme Ltd
role: Director

e.g.
contact1: Joe Bloggs
account1: Christ Church
role: Church member

**Comment by donners77** [comment]
Actually, for the affiliation role, I'd also like to be able to define a list of allowed values that can be entered via the user interface. I guess this is not possible as it is a standard Salesforce text field? Maybe it would be good to have a NPSP specific field with a set of managed values similarish to how the Reciprocal relationships function.

e.g.
Empoyer-Director
Church-Church Member

**Comment by judisohn** [comment]
@donners77 If you complete the Title column in the Data Import template, that will populate down to the Role field on the Affiliation record.

**Comment by BrightStepTracy** [comment]
Hmm... Though the Title is sometimes different than the role, for example, "Director" might be a title and "Employee" would be a role.  Any way to add some if/then logic to the import so that a custom role on the Affiliation could be specified, and if not, it would default to the Title?

**Comment by judisohn** [comment]
@BrightStepTracy True - but that's a completely separate issue than what was posted as a Data Import issue. I am updating the title of this so it's a more accurate reflection of the request.

**Comment by BrightStepTracy** [comment]
@judisohn I see :)  And, I +1 the Role Picklist on Affiliations.

**Comment by send2wsr** [comment]
We added a "Type" field to Affiliations to categorize contacts into general groups: Employee, Board Member, Teacher, Student, Parent etc.  We leave the Role as the title they provide us, which we often use on correspondence or name tags.  I don't think one field can do both things.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwbAAA" target="_blank">W-008325</a>
