### ISSUE TITLE
Merge Account custom fields when Household Merge done from ManageHouseholdUI

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1668]
Hub thread: https://powerofus.force.com/0D58000002DMIsj

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwcAAA" target="_blank">W-008326</a>

**Comment by davidhabib** [comment]
I have a visualforce page and controller in Volunteers for Salesforce that allows one to construct custom URL buttons that will lookup the report by developer name, and then redirect to the report, passing along any URL parameters.

Unfortunately, I don't believe this will work under Lightning Experience, and so I can't proceed on this feature until we figure out what is a valid way to do this under LEX.  @judisohn

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
