### ISSUE TITLE
Have Cicero Address verification not get called for partial addresses

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1682]
hub thread: https://powerofus.force.com/0D58000002EKNu5

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fweAAA" target="_blank">W-008328</a>

**Comment by davidhabib** [comment]
we should decide whether each verification service needs these smarts (because only they know what is incomplete to them), or maybe we just change ADDR_Validator.verifyAddressRecords() to ignore any empty or partial addresses.  for example, if the user has a default value on contact for Primary Address Type, then even contacts with no addresses will still get an address object (to save the address type), which then causes the validation, which fails for Cicero.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
