### ISSUE TITLE
As a user I want to see which Allocations represent cash-received

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/NPSP#1684]
There is no current way to tell what allocated revenue has been received versus simply pledged. Seems connecting GAU Allocations to payments is a more appropriate data model overall (albeit Payments aren't as widely used)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwfAAA" target="_blank">W-008329</a>
