### ISSUE TITLE
Setting address override doesn't populate address fields on contact insert

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1723]
Insert a new contact with is_Address_Override__c = true and Current_Address__c pointing to an address. Contact address fields are blank after insert.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZLAAY" target="_blank">W-008161</a>
