### ISSUE TITLE
Deleting more than 10K NPSP Data Import records throws warning

### ISSUE THREAD

**Issue by ghost** [SalesforceFoundation/NPSP#1740]
From a Hub post:

I'm trying to delete 36,000 previously imported records in the NPSP Data Imports object. I can delete one record at a time, but when I click the "Delete All Data Import Records" or "Delete Imported Data Import Records" buttons, no records are deleted and I receive the following email:

---

From: ApexApplication [mailto:info@emea.salesforce.com]
Sent: Wednesday, 7 October 2015 11:47 AM
To: xxxxxxxxxxxxxx
Subject: Apex governor limit warning

Operation: /apex/npsp__BDI_DataImport

By user/organization: xxxxxxxxxxxxxxxxxxxx

Caused the following Apex resource warnings:

npsp:Number of DML rows: 10000 out of 10000

https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000002J453W

**Comment by tet3** [comment]
Pretty sure there's no issue here - the code deletes 10k records at a time, as it should. This Apex Warning email is merely saying that the limit was reached, not that anything actually failed.

**Comment by njjc** [comment]
The 10k limit does indeed [exist](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/BDI_DataImport_CTRL.cls#L65), and the message looks like a warning. I think deleting the records 10k at a time is fine, although it would be ideal to avoid that error. Maybe if we change the limit to 9999 that message won't be sent.

**Comment by tet3** [comment]
The message will still be sent - it comes from the ["Send Apex Warning Emails" field on User](https://help.salesforce.com/apex/HTViewSolution?id=000130339&language=en_US), which triggers when 50% of a governor limit is hit.  Definitely not worth lowering it to 4999 to avoid that email, IMO.

**Comment by njjc** [comment]
Great, thanks. Looks like a documentation issue unless we decide to write a batch class.

**Comment by kbromer** [comment]
Can we log a doc story for this @njjc and close out this issue?

**Comment by njjc** [comment]
Reopening this as it requires front end text changes.

[Interesting hub thread on current UX around this feature.](https://powerofus.force.com/0D58000002J453W)


It would be nice if the page: 
1) It told the user how many records it had deleted
2) It asked the user to confirm the delete operation before proceeding in case they pressed the delete button by accident (the 10,000 delete limit could also be mentioned at that point to remind the user they may need to run the process several times)
3) There was an easy way for a non-technical user to see the count of their data import records if it is greater than 2000 (on the bottom left corner of the view it just says 1-200 of 2000+)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fzvAAA" target="_blank">W-008345</a>
