### ISSUE TITLE
Investigate again whether it'd be possible to run tests in parallel

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1745]
Changes were made some time ago to try to address this:
1. Always read from the Facade instead of directly from settings
2. Have the Facade store settings in memory and return those if populated
3. Don't write settings changes to DB but only to in-memory copy if in tests

But even with these changes we were still getting row lock issues in settings. It might be worth it revisiting the issue.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fzlAAA" target="_blank">W-008343</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
