### ISSUE TITLE
Investigate bringing TDTM filtering functionality from HEDAP

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1746]
This would involve importing https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/TDTM_Filter.cls (and its matching test class), and making the changes to TDTM_TriggerHandler seen in https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/TDTM_TriggerHandler.cls#L180-L185.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fzqAAA" target="_blank">W-008344</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
