### ISSUE TITLE
Investigate importing Affiliations functionality from HEDAP

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1747]
This involves the following files from HEDAP:

https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/AFFL_MultiRecordType_TDTM.cls

https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/AFFL_MultiRecordType_TEST.cls

https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/AFFL_AccRecordType_TDTM.cls

https://github.com/SalesforceFoundation/HEDAP/blob/master/src/objects/Affl_Mappings__c.object

WARNING: this is meant to replace the existing affiliations functionality.

**Comment by ceiroa** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fzwAAA" target="_blank">W-008346</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
