### ISSUE TITLE
When all household members are deceased, use different household naming convention

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1750]
https://powerofus.force.com/0D58000002K4x6Y

**Comment by davidhabib** [comment]
**lurch: add

**Comment by mrbelvedere** [comment]
Included in beta release version 3.61 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.61

**Comment by judisohn** [comment]
FYI: see conversation on #1881 as to why this wasn't implemented as described.

**Comment by davidhabib** [comment]
shouldn't we leave this issue as open since it really is about a custom naming scheme, or at least some differentiator, rather than us just not renaming the household on the last deceased?

**Comment by judisohn** [comment]
Frankly, that would be my inclination as well. I was configuring 3.61 in my instance and was surprised the name didn't change given that I saw that this issue closed. Had to dig in to the PR to see the conversation that it wasn't, and if it confused me it would likely confuse others which is why I left the comment.

**Comment by davidhabib** [comment]
re-opened the issue since we did not implement any custom deceased naming scheme.

**Comment by mbeaty-sf** [comment]
This is categorized as a feature request, and subsequently:
- One Idea has been delivered from the Idea Exchange - https://trailblazer.salesforce.com/ideaView?id=0874V0000015JkmQAE
- A related idea is still currently open - https://trailblazer.salesforce.com/ideaView?id=0874V0000015JnMQAU
