### ISSUE TITLE
Update Default GAU settings page to use lookup instead of picklist.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1758]
[Per Judi.](https://github.com/SalesforceFoundation/Cumulus/issues/1753#issuecomment-149481389)

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001g5eAAA" target="_blank">W-008407</a>

**Comment by mbeaty-sf** [comment]
This Issue was fixed via https://github.com/SalesforceFoundation/NPSP/issues/1753 and included in release [NPSP 3.53](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.53)
