### ISSUE TITLE
NPSP Accounting using Payments/Opportunities

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/NPSP#1772]
From the Seattle Sprint in conjunction with @njjc 

NPSP Accounting

• Work with predominantly Opps/Payments, except genuine Recurring (remove Pledges from it)
• NPSP needs a lever to switch between Cash/Accrual
o   This defines Opp Stage, Picklist, and other settings with a configuration recommendation for SysAdmins
o   Explains these data structures accordingly
• Created default reports to support either method

**Comment by kbromer** [comment]
**lurch: attach W-008191

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fg7AAA" target="_blank">W-008191</a>

**Comment by mbeaty-sf** [comment]
NPSP now has an integration with the Accounting Subledger product which provides the ability to create custom data-modelled Accounting Sets for specific organization accounting processes.

- https://powerofus.force.com/s/article/ASL-How-Accounting-Subledger-Runs-the-Numbers
- https://www.salesforce.org/accounting-subledger/
