### ISSUE TITLE
French Translation NPSP

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1776]
**External Contribution Issue created by @pelicanlaurich**

Translating NPSP

**Comment by jlangelaan** [comment]
Has there been any further action on this issue?

**Comment by mpusto** [comment]
At the moment, I don't have someone (volunteer) who is working on this. I'm currently looking into hiring someone but I may not have the budget to do so.

**Comment by pelicanlaurich** [comment]
hello,

I sent the Spanish translations to Mary Pustejovsky, on an excel file as
she said it was ok.

Regards, Laura

2016-01-29 4:15 GMT+01:00 mpusto <notifications@github.com>:

> At the moment, I don't have someone (volunteer) who is working on this.
> I'm currently looking into hiring someone but I may not have the budget to
> do so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1776#issuecomment-176549445>
> .
>



-- 
*_____*
*Laura Díaz*

**Comment by mbeaty-sf** [comment]
French is one of the primary supported languages in NPSP - https://powerofus.force.com/s/article/NPSP-and-Translation#ariaid-title3
