### ISSUE TITLE
As a developer, I'd like to enter and view notes on user managed entries found in table-driven trigger management

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/NPSP#1783]
Ideally class names would be self-evident, but they aren't always, or going to the class to view the comments can take too long. It would be nice to have a description field to populate and view when viewing settings in TDTM so that notes about what the class does, or why the specific order was selected, would be visible at a glance.

**Comment by davidhabib** [comment]
nice idea.  I'm actually putting together a document we want to ultimately publish which says which are safe for async and which are not.  we discussed whether this should just be in the table or not, and it was shot down, but maybe this might reopen that discussion.

**Comment by kbromer** [comment]
:+1:

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gcTAAQ" target="_blank">W-008552</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
