### ISSUE TITLE
As an Administrator: Have the ability to  define when allocations should be automatically created

### ISSUE THREAD

**Issue by lyndsayneer** [SalesforceFoundation/NPSP#1784]
The ability to enable default allocations allows you to specify which opportunities to exclude based on Opportunity Record Type and Type, but it would be useful to also include stage criteria. 

Ideally it would be great to set criteria based on the Opportunity Status: Open, Closed, Closed Won.

**Comment by judisohn** [comment]
@lyndsayneer Interesting idea - can you describe the use case where you would want to exclude by Opportunity Stage?

**Comment by kbromer** [comment]
:+1:

**Comment by lyndsayneer** [comment]
@judisohn We have a client who would prefer to only have an allocation created when the opportunity is considered won in the pipeline. In the initial prospecting and cultivation stages it seems pre-mature to add an allocation for this client because these are budget codes within their instance.

**Comment by njjc** [comment]
Interesting idea! For your clients' peace of mind, the GAU rollups only happen for closed/won opportunities.

**Comment by judisohn** [comment]
**lurch: add

**Comment by lyndsayneer** [comment]
@njjc Yes we mentioned this to them as well, but they still have reservations with user adoption as this is a new implementation and still getting used to reporting filters!

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gd7AAA" target="_blank">W-008559</a>

**Comment by mbeaty-sf** [comment]
NPSP now has an integration with the Accounting Subledger product which achieves part of what is requested. Additionally, generating Allocations based on a default GAU, or Campaign Specific GAU Allocation is possible currently - 

**NPSP Allocation Configuration**
https://powerofus.force.com/s/article/NPSP-Configure-Donation-Allocations

**Accounting Subledger**
https://powerofus.force.com/s/article/ASL-How-Accounting-Subledger-Runs-the-Numbers
https://www.salesforce.org/accounting-subledger/
