### ISSUE TITLE
Health Check should test for Opps with at least 1 Contact Role but none marked Primary

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/NPSP#1785]
Since various operations can leave Opportunities with at least one Contact Role, but none with isPrimary=TRUE, add a healthcheck test for this state.

Here's a POU post in which a user could have benefitted from this test:

https://powerofus.force.com/0D58000002LzPwC

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gdMAAQ" target="_blank">W-008562</a>

**Comment by judisohn** [comment]
This should only look for missing contact roles on Opportunities from Household Accounts. For non-Household Account Opportunities, it's fine for there to be no contacts connected.

**Comment by johnfine** [comment]
To be complete, I'd suggest (only on Opps from HH Accounts as Judi says),
testing for two different things:

* No Contact Role records at all (while I believe this can be achieved by
turning off the right trigger, I'd say it is very uncommon and worth
warning about).

* 1 or more existing Contact Role records but none with Primary=TRUE.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
