### ISSUE TITLE
Payment Amount should be updated if closed/won opportunity amount is updated.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1794]
Found through LDV testing and manual confirmation.

**Comment by njjc** [comment]
Probably not a bug, just wanted a placeholder to discuss.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gr2AAA" target="_blank">W-008590</a>
