### ISSUE TITLE
TDTM needs to serialize Old List and New List for asynchronous trigger handler invocations

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1795]

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gq4AAA" target="_blank">W-008581</a>

**Comment by manikrai29** [comment]
I wanna fix this bug.

**Comment by coriobriensfdo** [comment]
@manikrai29 When you're ready, go ahead and create a PR with your changes and I'll start the process of review. Thanks!

**Comment by coriobriensfdo** [comment]
**lurch: attach W-008581

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phXMQAY&title=npsp-tdtm-deleted-objects-not-passed-to-afterdelete-triggers) in the Trailblazer Community for updates.
