### ISSUE TITLE
Permission Set/Profile for Contact Merge for Delegated Administrators

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/NPSP#1809]
As a delegated administrator, I don't want to have full SysAdmin rights to Objects and fields, but I do want to have the one-off ability to use Contact Merge for periodic deduplication maintenance. Is is possible to create a "Contact Merge" Permission Set for the NPSP, or is the merge tool itself not designed to work with anything other than a System Administrator Profile? @njjc - any thoughts on this?

**Comment by mbeaty-sf** [comment]
You don't require a System Admin profile to merge, just the Create, Edit and Delete and one of the following (as per documentation):

- You are the owner of the Contacts being merged.
- You are above the owners of the Contacts being merged in the role hierarchy.
- You have the Modify All permission on Contacts.
