### ISSUE TITLE
As a user, I would like to have a County custom field on Account and Contact synced to/from the Address record

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#1817]
Hub thread: https://powerofus.force.com/0D58000002Mymxi

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001h4lAAA" target="_blank">W-008687</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
