### ISSUE TITLE
Google address verification returning ambiguous addresses

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1820]
There have been two recent reports of this issue:

https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001jLTWQ

https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000007VOga&tab=sfdc.ProfilePlatformFeed&fId=0D58000002LymeB

**Comment by ceiroa** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001h9qAAA" target="_blank">W-008710</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  W-9363537
