### ISSUE TITLE
GAU Allocation sharing

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/NPSP#1826]
The current set-up has Lookup fields that connect Allocations to GAU and Opportunities. From a security standpoint this makes it difficult to institute a permission structure around revenue records.  

Opportunities that are secured via the Opportunity Owner field will still have important revenue information exposed to users via GAU Allocations (Opportunity name, amount, fund).  To secure that information a separate Sharing structure would need to be set-up and maintained for GAU Allocations.

The use-case is a fundraising organization that allows all users to access some opportunities but not others.

Using Master-Detail fields would solve the issue but of course this comes with other changes that would need to be considered.

**Comment by brianpickett** [comment]
What's the reason Lookup fields were chosen? That might help explain the benefits to the current approach.

If there is no discernible benefit, I understand its complex to change but security is an important facet for mid- to enterprise- clients. After preliminary testing, the work around now would involve multiple process-builder/flows to set the Allocation owner only at which point would duplicate sharing rules take over. Its a small audience that will care about this and likely one that can afford the work around but its not great to leave them with the feeling they have to put in place complex workarounds for what is in essence structural issues.

**Comment by njjc** [comment]
For the GAU lookup the concern was possible data skew for many records
associated with a single GAU via master-detail. For the Opportunity side,
it's because allocations can be associated with either opportunities,
campaigns, or recurring donations.

**Comment by brianpickett** [comment]
Thanks Nic. I can see where Master-Details didn't make sense. Back to the drawing board.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
