### ISSUE TITLE
Invocable method for Opportunity Naming

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1837]
[Per this hub thread](https://powerofus.force.com/0D58000002NuYqp) it would be nice to be able to rename an opportunity programatically.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hO7AAI" target="_blank">W-008798</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
