### ISSUE TITLE
UTIL_CustomSettingsFacade test methods should default unspecified values

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1869]
When calling e.g. getContactsSettingsForTests and specifying a single value, all other values for that setting are set to null. It would be nice to set them to default values so those don't have to be specified for tests that are expecting defaults.

We still need a way to specify a null value, so the design will have to include that possibility.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hf2AAA" target="_blank">W-008897</a>

**Comment by kbromer** [comment]
We just pass it an object, right?

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
