### ISSUE TITLE
Provide functionality to mark address as "bad" and clear from both household and contacts

### ISSUE THREAD

**Issue by mhiman** [SalesforceFoundation/NPSP#1871]
I'd love to keep track of historical addresses using the address object so that if an address ever pops up again we can know it is bad, by checking a "bad" box - which then clears it from the household and contact so that it doesn't get mailed again.

**Comment by judisohn** [comment]
**lurch: add

**Comment by kbromer** [comment]
Added W-008908

**Comment by mbeaty-sf** [comment]
Custom fields can be added to the Address Object, and historical address records can be saved with those custom values.
