### ISSUE TITLE
If an Address record has an Address Type value, that should be copied to the Primary Address Type on a new Contact

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#1878]
Hub thread: https://powerofus.force.com/0D58000002Q5yKj

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hmwAAA" target="_blank">W-008954</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
