### ISSUE TITLE
Updating a seasonal address that is in effect (value was copied to Account and Contacts) does not propagate

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/NPSP#1891]
If you update the address information of a seasonal address that was previously automatically copied to the parent Account and related Contacts, the change doesn't propagate to them.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001iTvAAI" target="_blank">W-009075</a>

**Comment by ceiroa** [comment]
The fix for this and another issue related to addresses are in https://github.com/SalesforceFoundation/HEDAP/commit/ced22292a1f59a66d0dc6a99328c6a83a8b0dc96. The way in which the other issue (changing an address from default to non-default) is debatable (clearing the address in the related Account and Contact), but I think it's the right approach.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
