### ISSUE TITLE
Eliminate Pre-Created Role Hierarchy in Trialforce and all NPSP Deployments?

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/NPSP#1910]
See this thread on the Hub: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000002Tv5SR

Pretty please with sugar on top?  There's probably 3-4 different deployment templates where this is provided.  Thank you!

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kPnAAI" target="_blank">W-009208</a>
