### ISSUE TITLE
Health Check incorrectly tests RD creation of Opps

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1917]
https://powerofus.force.com/0D58000002Udkb0

health check just creates an opp directly to detect any required fields that might interfere. But it isn't taking into account any RD field mappings the user may have created.   

Change the code to create an RD with a single opp instead?

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kcNAAQ" target="_blank">W-009262</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
