### ISSUE TITLE
Updating Opportunity Primary Contact from Contact Role batch job should also update null account attribution to household accounts.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1921]

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kgFAAQ" target="_blank">W-009285</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
