### ISSUE TITLE
latest Manage Allocation page has styling issues in Internet Explorer

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/NPSP#1939]
The updated version of Manage Allocations looks wrong in IE: 
- the large Xs should not be there
- on a small screen the red box is too tall

![screen shot 2016-02-11 at 10 40 02 am](https://cloud.githubusercontent.com/assets/204643/12984658/fcecb322-d0ab-11e5-942d-37659bf043fb.png)

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
