### ISSUE TITLE
RecordType Translations making the package to fail

### ISSUE THREAD

**Issue by gonzalos4g** [SalesforceFoundation/NPSP#1953]
When using the Standard Salesforce Translation Workbench, to translate the Record Type Names and also custom installment periods, the package fails. The Automatic Naming for Opportunities is not working although the batch process does not give any error. 
Also the Health check shows errors when you translate teh picklist values for the Installment period picklist.
This Package should support other languages rather than only English. I am handling projects for more than 8 spanish non profits with this issues.

**Comment by judisohn** [comment]
What happens when you create the Record Types and Custom Installment Period values directly in Spanish rather trying to translate the ones provided?

**Comment by gonzalos4g** [comment]
Thanks for the Reply.
The issue is that mostly all of the non-profits need to have English and Spanish depending on the user config. That´s why I need to translate. If I create the Custom Installment periods directly in Spanish it works for Spanish, but not for English...

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001vhoAAA" target="_blank">W-009344</a>

**Comment by gonzalos4g** [comment]
I can´t access the tracking link...

**Comment by judisohn** [comment]
It's okay - It's an internal link for our agile project management system meant for our development team.

**Comment by gonzalos4g** [comment]
Ok. Thanks for the great support!

**Comment by gonzalos4g** [comment]
Hi, I would like to know if this issue has been resolve as I have 5 spanish non-profits needing to translate values on RecordTypes or installment periods.
Thanks in advance,

Gonzalo

**Comment by mpusto** [comment]
Is this the same issue as what was reported in the HUB in the Traducción al Español group? https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D9ER

**Comment by kbromer** [comment]
Not sure which post you're referring to (that's a group link, not a post link), is it this one? https://powerofus.force.com/0D58000002ari3c

If so, its similar - basically there are a few places where the original author (<gulp>) coded dependencies to a translatable label of either a custom label or rec type. Though that said, in the link above, there shouldn't be an issue, everything should be coded to the label reference and not the value, so it should be fine to translate. Definitely get repro instructions on that one if you can-

**Comment by mpusto** [comment]
Yes, that's the correct link. @gonzalos4g Can you look at the link I provided in the HUB? Also, could you provide detailed steps to reproduce? Thanks!

**Comment by judisohn** [comment]
@RBLopez It's still on the backlog.

**Comment by mbeaty-sf** [comment]
W-7782157

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlGIQAY&title=recordtype-translations-cause-batch-to-fail) in the Trailblazer Community for updates.
