### ISSUE TITLE
Strip out system noise from error messages shown to users

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1973]
Hub thread: https://powerofus.force.com/0D58000002WVC6W

probably requires us coming up with a common utility routine to do the stripping out of the confusing stuff, and then hooking it up in (unfortunately) all places we are doing apexPages.addMessage().  We might want to also consider it in our core error handling routines that do error logging and error emailing, thought it might be better to leave those with full system information.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000033WuAAI" target="_blank">W-009493</a>

**Comment by cdcarter** [comment]
The linked Hub post is in a private group. Would be great to have the contents here.

**Comment by judisohn** [comment]
It was originally raised by John Fine. With permission, here's his post:

> Error handling
> In some places, the NPSP "skin" is thick (NPSP feels like a whole consistent experience).  When errors occur, sometimes it's thin (the user sees something they cannot understand how to react to, that shakes their confidence in the "NPSP experience").  No user should ever see words like "exception", "row 0", "null pointer", or "de-reference".  Here's an example:
>  
> * Manage HH VF page: If duplicate mgmt is turned on and a dup Contact or dup HH name is attempted to be created, the error msg is:
>  
> Insert failed. First exception on row 0; first error: DUPLICATES_DETECTED, CAREFUL! Looks like someone already has this name in the database. Are they the same person? If they are, you're creating a duplicate record. We recommend you use an existing record instead.: []
>  
> It's the first 8 words I object to, of course :)
>  
> Would you say that cases like this are just bugs and NPSP's error handling framework provides a thick enough "skin", or is this a road-map-ish sort of thing?

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
