### ISSUE TITLE
Provide the option to calculate NPSP donation rollups based on Oppportunity Products (product family)

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/NPSP#1979]
The structure of NPSP rollups basically requires that an organization represent a single 'type' of gift as a single Opportunity. This structure is overly simplistic for some organizations particularly those where multiple 'types' of revenue can be generated from a single transaction (event registration, membership, donations -- paid all at once). 

The 'umbrella' record for all this revenue is best managed in the standard Salesforce model as the Opportunity record, with Opportunity Products representing the types of revenue included in that single commitment. Yet the NPSP rollups do not work in this scenario and must be recreated with custom code (or third party apps) which creates a significant burden for organizations wishing to follow this best practice. As well, the option to involve Opportunity Products in the data model opens up other possibilities with regards to third-party integrations (accounting, etc) and native features like Forecasting. 

It seems to be the most meaningful change to expand the available data models would be to provide the OPTION for the NPSP roll-ups to be based on Opportunity Products (with a filter on Product Family to distinguish donations from memberships).

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
