### ISSUE TITLE
Rename "Getting Started" Tab

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/NPSP#1980]
This is a really small thing, but can we rename the "Getting Started" Tab to something akin to "NPSP Getting Started?"  It's great when it's the only Getting Started Tab in a Salesforce instance, but when there's about a half-dozen Apps and they all have a "Getting Started" Tab, it's a PITA for Profile-based security measures.

**Comment by judisohn** [comment]
**lurch: add

**Comment by judisohn** [comment]
Good point, Tracy - thanks!

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000004BooAAE" target="_blank">W-009568</a>

**Comment by mbeaty-sf** [comment]
This Issue is related to a larger revamp of the Getting Started Tab: Get Started with NPSP that was part of [NPSP 3.193](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.193)

[Internal WIs](https://gus.lightning.force.com/lightning/r/ADM_Epic__c/a3QB000000012WYMAY/view)
