### ISSUE TITLE
Address Verification Settings page: batch verify bug

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1988]
The Mass Verify Existing Addresses box only displays when you pick Smarty Streets, but if the user switched from another service the verify button is disabled, and there is a message that the selected service does not support Batch Address Validation.

**Comment by kbromer** [comment]
I think that's the correct behavior.  SmartyStreets was the only one that supported a bulk verification API, all the others we implemented required a callout-per-address.  @ceiroa was the original implementer on this IIRC

**Comment by ceiroa** [comment]
We changed this to completely hide the "Mass Verify Existing Addresses" box if anything other than SmartyStreets is selected. That's what it's doing in my NPSP dev org (which may not have the latest version). Could this be a regression?

**Comment by davidhabib** [comment]
The bug is that when you change to smarty streets, we do correctly show the Mass Verify section, but the  mass verify button is disabled.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
