### ISSUE TITLE
Pass SF Duplicate Management suggested Contact back to Data Importer field on found duplicate

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/NPSP#1989]
If SF Duplicate Management is turned on with Contact FIrstName and LastName fuzzy matching, then DI correctly reports duplicate mgmt failures msgs when a name is a near match.  This is great!

Feature suggestion: It would be convenient to also report the SF duplicate mgmt "suggested Contact" field as a lookup on a DI field, so the user can see which Contact SF duplicate mgmt thinks it's matching.

**Comment by mbeaty-sf** [comment]
W-9458482

**Comment by jesslopez-sf** [comment]
This is still open in our backlog. As it's more of a feature request than a Bug, I won't be moving it over to the Trailblazer Known Issues site.
