### ISSUE TITLE
Make affiliations visible in relationship viewer

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/NPSP#1997]
Hub request here: https://powerofus.force.com/0D58000002ZuJqS

Looking to see a contact's affiliations in addition to their relationships in the relationship viewer (gives a more 360d view, I'd say!)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ON3bAAG" target="_blank">W-009666</a>

**Comment by afaubel** [comment]
Hi, Please could you tell me what the status of this request is? Is it in progress? If it isn't and if there aren't any immediate plans to work on it, would it be possible to contribute to this code?
Cheers
Alan

**Comment by davidhabib** [comment]
@afaubel no one is currently working on this, so I'm sure we'd be open to code contributions.  @judisohn , our open source manager, is out for the week.  But she would be the one to connect with about it.

**Comment by judisohn** [comment]
@afaubel Do you already have working code/implementation for this that you'd like us to consider? We have some high level information about our contribution process [here](http://www.salesforce.org/help/nonprofitstarterpack/contribute/). 

I'd also recommend adding your vote/comment to [this Idea](https://powerofus.force.com/hub-ideas/1047), as that will help our development team set priority for working on this. But if you have already worked something out, we'd love to see it!

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
