### ISSUE TITLE
Recurring Donation Custom Installment Period translation support

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2001]
The RD Custom Installment Period value is hardcoded as Days, Weeks, Months, and Years in both STG_PanelRDCustomInstallment_CTRL.listSORDCustomPeriod() and RD_RecurringDonations.getNextDate().  The ui value in listSORDCustomPeriod() should come from custom labels, so the ui can be translated.  It's correct, however, to always store the internal period in english.

Note that the use of custom labels in the RD processing code for Status and Multiply By is actually misleading.  The translator should translate the Picklist Values for these fields, but the internal storage should always be english.  Thus translators must not change these custom labels, but just translate the UI picklist values.

@mpusto fyi

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OvnBAAS" target="_blank">W-009670</a>

**Comment by judisohn** [comment]
FYI @jjbennett

**Comment by mpusto** [comment]
Resolved in our new recurring donations functionality.
