### ISSUE TITLE
Adding a "Primary Contact First Name" and "Primary Contact Last Name" formula fields to the Opportunity for ease of acknowledgement

### ISSUE THREAD

**Issue by mbaizman** [SalesforceFoundation/NPSP#2006]
Can we add a new "Primary Contact First Name" and "Primary Contact Last Name" formula fields to the Opportunity to help with email acknowledgement setup for the sysadmin.

**Comment by kbromer** [comment]
Why wouldn't you just get this via cross-object at the time of the creation of the acknowledgement? You shouldn't need a formula field to get at this info...

**Comment by mbaizman** [comment]
Sadly, using HMTL Email templates, you are unable to do cross-object, it needs to live right on the Opp.

**Comment by kbromer** [comment]
Seems like we'd want to just add these custom as needed?  

The concern is with the primary OCR, the primary contact, and the account household all referenced to the Oppty, we're already copying a lot of data over to the record via formula as it is.  

This looks like the right idea to vote up FWIW: https://success.salesforce.com/ideaview?id=08730000000Brk7AAC

**Comment by mbaizman** [comment]
I hear you on the idea voting, but it makes Acknowledgement easier if the fields are already created by the NPSP rather than an admin "figuring out" how to create a cross-object formula field from the lookup.  It's fine.

**Comment by davidhabib** [comment]
@mbaizman why isn't the email template we ship good enough to use?  it uses {!Account.npo02__Informal_Greeting__c} which seems reasonable.  

Have to admit I can't recall why this account reference works, but {!Primary_Contact__r.FirstName} doesn't.

**Comment by mbaizman** [comment]
The stock email is probably good enough, especially if you're already
copying over lots of data from other objects. However, I could see a use
case wanting to thank the individual donor specifically, rather than the
Household, and because OCRs suck, that was the only way around it that I
could see.
--

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
