### ISSUE TITLE
Create a Global "API" class for Rollup helper methods

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/NPSP#2008]
There are a lot of useful methods in `RLLP_OppRollup_UTIL` that would be very useful to be exported into the global namespace. 

For ISVs or consultants who want to build additional rollups on top of the NPSP, having quick access to properties like `recordTypesToExcludeAccts` (as a set of IDs already) or `getCurrentFY()` using an implementation that is guaranteed to match current NPSP behavior would be a huge win.

Discussed this on site at the sprint with @njjc.

**Comment by kbromer** [comment]
:+1:

**Comment by cdcarter** [comment]
In the work done by me (and Megan Himan, Nikole Pagan, Vered Meir, and TJ Wakefield) at the sprint did on some new rollups, I started work on this. But I only implemented the methods I was using, as opposed to a well thought through idea of what out to be `global`. I'm going to try and put some thought as to what really should be there, and pull together a PR as next steps to start conversation on this.

**Comment by cdcarter** [comment]
Symbols I plan to export in the first version of this PR:

- Boolean useFiscalYear
- Set<Id> recordTypesToExcludeAccts
- Set<Id> recordTypesToExcludeCons
- Set<Id> mbrRecordTypes
- Set<String> softCreditRoles
- Boolean areRecordTypesOnOpps()
- Boolean useSoftCredits()
- Boolean isMultiCurrency()
- Map<String, SObjectField> mcFieldValues
- Decimal convertFromCorporate(String,Decimal)
- Decimal convertCurrency(String,String,Decimal)
- Integer getCurrentFY()
- Integer getFiscalYearForDate(Date, Integer, Boolean)

I think that these would all be implemented in the RLLP_RollupUtils_API class as static methods, and not properties.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
