### ISSUE TITLE
Clicking the Email Acknowledgement Button should create an Activity record in the Activity History

### ISSUE THREAD

**Issue by mbaizman** [SalesforceFoundation/NPSP#2009]
When I click the Email Acknowledgement Button to send an email to the Primary Contact, I want it to create an Activity record in the Activity History in addition to changing the Acknowledgment Status.

**Comment by kbromer** [comment]
:+1:

**Comment by mbaizman** [comment]
Kevin Bromer thumbs-up = assigned immediately + live in next release

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RqZJAA0" target="_blank">W-009907</a>

**Comment by judisohn** [comment]
Sure @mbaizman  - that's exactly how it works. ;-) 

Challenge with this declaratively has always been getting the contents of the email in to the activity detail. Our solution just launches a workflow rule. May take some work to programmatically get the contents of the Email Alert. Otherwise, the admin could easily right now just clone the workflow rule and add a task with generic contents.

**Comment by mbaizman** [comment]
Hmm - when I tested this for the video recording, I didn't get the auto-activity logging, but it could certainly be an issue with my configuration (perhaps the WF rule wasn't activated). The contents aren't super necessary, but I could see them being a "nice to have."

**Comment by judisohn** [comment]
No, I meant 'that's how it works' in response to your comment that 'Kevin Bromer thumbs-up = assigned immediately + live in next release' 

As it stands right now, our workflow rule does not include an action to add an activity. Easy enough to add one, although I question if it's something we should necessarily do given that it would have to be a generic 'Acknowledgment Sent' subject with no specific customization for the message. They'd have the same data by reporting on the Acknowledgment fields. It's easy enough for the organization to clone and customize the workflow rule we provide, should that be important to them.

**Comment by mbaizman** [comment]
I don't know how much ppl need the actual body text of the ack - although I
guess if they are customizing it then maybe they would want to know. I
don't know. I hear you that they can get the same info by reporting on the
fields, which actually then makes the case that you *should* store the
actual body text and subject in the Activity, as it gives you all the info.

---
Marc Baizman
Customer Success Director | Salesforce.org
Office: +1 (617) 960-5863
Mobile: +1 (617) 982-3336
mbaizman@salesforce.com

<https://powerofus.force.com>
--
--

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.

**Comment by mbaizman** [comment]
Well, good thing this issue from 2016 wasn't keep me awake at night 😆
