### ISSUE TITLE
Contact Merge: Better defaulting of master record, show number of contacts in account

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2010]
In the contact merge UI, the current default is selected based on the last modified contact record. Ideally, the contact whose household has the most members would be defaulted, and the number of household members would be shown in the merge UI.

**Comment by njjc** [comment]
Also we need more information in the search function besides name: number of household members, number of donations, potentially other fields.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OvpRAAS" target="_blank">W-009673</a>

**Comment by njjc** [comment]
Maybe we could use search layouts for displaying the contact search results.

**Comment by mpusto** [comment]
I like that. It gives more control to the admin.  As long as we can access that in the metadata API I say go for it

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
