### ISSUE TITLE
Last Membership Date not consistently computed for Accounts, Contacts, Households

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2013]
I've looked at the code and Account is setting Last Membership Date to the MAX(CloseDate) of Won membership opps grouped by AccountId and CalendarYear (or Fiscal Year), whereas Contact and Household membership queries are only grouping by ContactId or HouseholdId, and NOT grouping by calendar/fiscal year.  So you are correct that they are computing different things!  I'll enter an issue in gitHub so we can look further into this and make appropriate adjustments to they are consistent.

Hub thread: https://powerofus.force.com/0D58000002as3a9

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OvqjAAC" target="_blank">W-009674</a>

**Comment by mbeaty-sf** [comment]
Customizable Rollups (CRLPs) addressed this issue upon their introduction. 

To learn more check this Knowledge Article - https://powerofus.force.com/s/article/NPSP-Cust-Rollups-Overview
