### ISSUE TITLE
3.69+ Settings Text/Logo Fixes

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/NPSP#2016]
Create Missing Payments, Refresh Household Names and Refresh Opportunity Names in settings all use similar language, but the formatting is different between the three tabs.  For example, view the alignment of "This is an irreversible process".  Sometimes it its own line, sometimes there's a space between it and the list of things to disable, sometimes there's a space above.  

NPSP Logo on the main page needs to be replaced with the one being used on the Getting Started page.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Ovt4AAC" target="_blank">W-009685</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
