### ISSUE TITLE
Add a Health Check report for 1:1 accounts w/o Contacts

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2019]
hub thread: https://powerofus.force.com/0D58000002auLRZ

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Q9LHAA0" target="_blank">W-009738</a>

**Comment by kbromer** [comment]
We need to make sure the language on this is clear too:  

1.  Its usual causes (validation/required fields) on Account, and;
2.  That in some scenarios, 'private' contacts might be the correct behavior for certain types of organizations

**Comment by mbeaty-sf** [comment]
This was addressed and One-to-One Accounts without Contacts can be viewed through the Health Check Report that is available with NPSP. 

To read more check this Knowledge Article - https://powerofus.force.com/s/article/NPSP-Common-Health-Check-Errors#ariaid-title3
