### ISSUE TITLE
Prevent a Contact from being saved without an Account

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2035]
This came up as @davidhabib and I were helping Support troubleshoot through developer logs. This common scenario (where another process or validation rule is preventing the Household Account from being created and/or attached to the Contact) should be prevented so a Contact is never saved improperly. Better to force an early error than have the orphaned record.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003REyVAAW" target="_blank">W-009889</a>

**Comment by kbromer** [comment]
This would need to configurable - there are some (albeit narrow) use cases where the 'Private Contacts' feature that is at the root of the Account requiredness could be used

**Comment by judisohn** [comment]
Isn't that what the 'Private' field on Contact is meant to address? I'd recommend that if that box is checked, then allow the Account to be blank, as I believe already happens. But warn/not allow for others.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
