### ISSUE TITLE
SmartyStreets address verification response handler should handle other HTTP status codes

### ISSUE THREAD

**Issue by mdwhatcott** [SalesforceFoundation/NPSP#2040]
There are a few cases missing in the response handling logic:

https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ADDR_SmartyStreets_Gateway.cls#L120

See the docs for additional status codes that should be handled:

https://smartystreets.com/docs/us-street-api#http-response-status

Also, the last case (HTTP 500) should probably encompass any status code greater than or equal to 500.

Finally, 5xx level status codes should elicit retry behavior (ideally with exponential back-off).

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RpBCAA0" target="_blank">W-009898</a>
