### ISSUE TITLE
Affirm or address Contact Role behavior in Account change scenarios

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/NPSP#2050]
Contact Role behavior thread: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CkCM&fId=0D58000002d5HBy&fromEmail=1

Scenarios: 
- Data cleanup
- Divorce/Seperation
- Co-habitation

What is the correct Contact Role behavior vis-a-vis the Opportunities: Closed or Open

**Comment by kbromer** [comment]
**lurch: add

**Comment by kbromer** [comment]
Could branch into record locking behavior as well

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003VoViAAK" target="_blank">W-009965</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
