### ISSUE TITLE
NPSP Error Notifications to users should not filter by 'System Administrator'

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2058]
code currently puts users with profile = 'System Administrator' in the recipeints dropdown.  But if an org clones this profile, that won't work!  need a better way to filter for these type of users.

if we make a change to fix this, we also need to update the help text on the settings page for this field.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003abODAAY" target="_blank">W-010054</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
