### ISSUE TITLE
Add endpoint URL field to Address Settings

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2059]
[Per this hub thread](https://powerofus.force.com/0D58000002f8U8P) in order to use smarty streets' international verification service, a different endpoint must be entered. We should surface the address verification settings' Address_Verification_Endpoint__c field so that users can edit the end point manually.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003abRRAAY" target="_blank">W-010057</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
