### ISSUE TITLE
Health Check for Non-Household Record Types with Individual/Household criteria

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2066]
https://powerofus.force.com/0D58000002flGFN

Could look for Accounts where Record Type does not equal value that matches Account Model and (_SYSTEM:IsIndividual equals TRUE or _SYSTEM:AccountType is not blank).

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000FdSNAA0" target="_blank">W-010220</a>

**Comment by mbeaty-sf** [comment]
NPSP Health Check and related Reports should address this issue.

Check out this Knowledge Article to learn more - https://powerofus.force.com/s/article/NPSP-Common-Health-Check-Errors#ariaid-title5
