### ISSUE TITLE
Do not copy Contact Other Address to Household Account Shipping Address on Contact create

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2068]
POU thread: https://powerofus.force.com/0D58000002fnQuE

While this may have made sense in the 1:1 model, with Household Account model a contact's other address should not be assumed to be a Household's shipping address. That secondary address should remain solely on the Contact and not be copied up.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000GEwXAAW" target="_blank">W-010238</a>

**Comment by kbromer** [comment]
https://github.com/SalesforceFoundation/Cumulus/blob/e717a398ba91976e9c12b0d3d9f8ace5ea52e053/src/classes/ACCT_IndividualAccounts_TDTM.cls#L550

and

https://github.com/SalesforceFoundation/Cumulus/blob/e717a398ba91976e9c12b0d3d9f8ace5ea52e053/src/classes/ACCT_IndividualAccounts_TDTM.cls#L606

We explicitly included this behavior at some point, lets go back to the original notes and make sure we understand why before unraveling it.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
