### ISSUE TITLE
Add Trigger on Trigger_Hander object to prevent duplicates

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2070]
over the last year, I've encountered 3 orgs who had all of there TDTM trigger handlers duplicated 2 or more times.  We really don't know what caused it to occur, and we have no reproducible scenario.  But we could consider adding a trigger on BeforeInsert to Trigger_Handler__c to prevent duplicate entries.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000GEwrAAG" target="_blank">W-010243</a>

**Comment by davidhabib** [comment]
comment from Carlos:
Didn't we see this once when a user didn't have access to the Trigger Handler object, and thus the code running under it thought the table was empty and proceeded to populate it? I might be misremembering...

It seems like TDTM_TriggerHandler doesn't have with or without sharing, in order to inherit the trigger or caller's sharing context: https://github.com/SalesforceFoundation/Cumulus/commit/b4e72b3a7e325140b036e21af7f08bc572bc80c9. Neither does the class that queries the object (TDTM_ObjectDataGateway). So it seems like it's possible for this to occur... Maybe TDTM_ObjectDataGateway should be "without sharing"?

**Comment by kbromer** [comment]
Just thinking about this, and in particular about the fact that we auto-populate the table if its empty. There are some scenarios where we might not actually want to do this.  Consider an API integration or bulk process profile - you want to load data, but are doing the transformation external to the instance. In that case, you'd want to keep triggers off entirely for that user/profile/sharing group, and allow the transformation to handle the upload.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
