### ISSUE TITLE
New Contact & Account issues when current user is Portal User

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2084]
hub thread with info: https://org62.my.salesforce.com/0D50M00002iKsC3

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003nhihAAA" target="_blank">W-010309</a>

**Comment by kbromer** [comment]
@mpusto did you have an existing issue for this based on our conversation earlier last week?

**Comment by mpusto** [comment]
Yes, it should be attached to W-010023

**Comment by kbromer** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x80000003nhihAAA" target="_blank">W-010309</a>

**Comment by kbromer** [comment]
**lurch: attach W-010023

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003abLdAAI" target="_blank">W-010023</a>

**Comment by cdcarter** [comment]
Is there a link to the report in the Hub instead of Org62?

**Comment by mpusto** [comment]
It started from this one but doesn't get into the entire detail, which was a private email chain. https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000002cj72y

**Comment by cdcarter** [comment]
Thanks!

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
