### ISSUE TITLE
Checkbox to prevent batch Opportunity renaming on individual records

### ISSUE THREAD

**Issue by dschach** [SalesforceFoundation/NPSP#2085]
A user wants to give an Opportunity a specific name and not have it overwritten when saving the Opportunity. Please create a checkbox to prevent the automatic renaming tool from overwriting the Opportunity name .

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003nhjpAAA" target="_blank">W-010322</a>

**Comment by judisohn** [comment]
Thanks for the suggestion @dschach - I've added it to our backlog.

**Comment by kbromer** [comment]
Feels like the right way to do this is the same way we handle Household naming, which is understand when its been user edited automatically and not override it.  The challenge, of course, is that often times a user puts a placeholder in the opportunity name expecting it to be overridden - maybe appending the name with a "locking" character?  "My custom opportunity name not to be renamed %"?

**Comment by davidhabib** [comment]
I think having a checkbox is easier for users to understand and for npsp to manage.

**Comment by kbromer** [comment]
Maybe, but you know how I feel about field proliferation :)

**Comment by njjc** [comment]
Maybe we just don't do anything to locked opportunities, once that is implemented, instead of a checkbox just for this purpose.

**Comment by mbeaty-sf** [comment]
W-7781130

**Comment by dschach** [comment]
Unsure if this is being handled, but if it is, that's very cool.

**Comment by jesslopez-sf** [comment]
This is still open in our backlog but I won't be transferring this one over to the Trailblazer Known Issues page as this is more of a feature request than a bug.
