### ISSUE TITLE
Recurring Donations object should be set to 'Allow Activities'

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2089]
thread: https://powerofus.force.com/0D58000002iOnnJ

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003nhqCAAQ" target="_blank">W-010378</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
