### ISSUE TITLE
Allow Lead convert page to be accessed in Salesforce1 mobile

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/NPSP#2090]
This would involve modifying the metadata for the LD_ConvertOverride page to allow for use in SF1. Need to test that doing so would work on mobile devices.

**Comment by mpusto** [comment]
lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003nhqHAAQ" target="_blank">W-010379</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
