### ISSUE TITLE
Include 'Number of Household Members' in overnight batch processes

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2119]
thread: https://powerofus.force.com/0D58000002lIn5p

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qFPmAAM" target="_blank">W-010669</a>

**Comment by kbromer** [comment]
Pretty sure this would need to be an entirely new job, we don't query for this during the course of our standard rollups

**Comment by mscholtz** [comment]
+1

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
