### ISSUE TITLE
error scenarios with DemandTools Single Table Dedupe

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2158]
From John Fine:

All of the below is when using DemandTools Single Table Dedup to dedup Contacts. This is a similar, but not identical, operation to using Contact Merge in the NPSP UI. (And of course the usage scenario is dedup many Contacts all at once.)

STD (single table dedup) lets the user pick which record among the group of records being merged is the "winner". Unlike NPSP Contact Merge, if the winner has null in a field and the loser has nonnull in the same field, then STD copies the loser's field value into the winner's field. 

I tried deduping 2 Contacts of the same FName and LNAme, in 2 different Accounts, one of whose Account had a related Address record, and the other of which had no Address record (I created the latter by creating a Contact and not filling in any address fields).

I told STD that the winner was the Contact whose Account had no related Address record. I expected that the street, city, etc values from the "loser" would get copied to the "winner".

STD reported back that the dedup operation failed, with this error. Notice that only one Contact ID is listed (there should be 2):

2016-07-13T09:35:06-07:00,Single Table Dedupe,"Merge To Master",Contact,Merge,003P000000t5aJPIAY,,,,""
2016-07-13T09:35:06-07:00,,"Merge Call Failure",,,,,,,"Msg:entity is deleted StatusCode:75 Fields: "

After STD was done I was left with 2 Contacts, both in the same Account, and no related Address record.

Then I tried the same operation with 2 COntacts each of whose Account had its own related Address record, and STD succeeded.

So I reasoned that the problem was related to either the absence of an Address record, or an Address record with blank field value for Street, City, etc. So then I tried to:
1. Create a Contact with blank in all address fields.
2. Visit the Contact's Account, click New on the Address related list, and save the Address record with Primary Address checked but with blank in Street, City, etc.

I received the error:

The record you attempted to access has been deleted.

Visiting the recycle bin I saw that a just-created Address record had been deleted. I undeleted it and ended up with the Account having that related Address record, Primary Address=true, all addy fields blank. Looks like NPSP created the Address record when I created the Contact, then immediately deleted it.

Then I tried the STD dedup operation above using this just-created Contact that had the "blank" Address record related to its Account, and STD succeeded, including STD copying the "losing" COntact's address fields to the winning Contact's address fields. I was left with 1 Contact, 1 Account, and 1 Address. Here's the STD log which shows both of the 2 Contact records (presumably arguments to the SF merge call):

2016-07-13T10:12:25-07:00,Single Table Dedupe,"Merge to Master",Contact,Merge,003P000000t5aaQIAQ,003P000000t5aY0IAI,,,""
2016-07-13T10:12:25-07:00,Single Table Dedupe,"Dedupe complete",,,,,,,""
2016-07-13T10:12:25-07:00,Single Table Dedupe,"Batch Dedupe",Contact,,,,,,"2 Contact objects were merged into 1 Contact(s)<CR><LF>There were 0 errors."

My suspicion is that there is an NPSP issue related to either saving or deleting Address records when the all the street, city, etc fields are blank, and that this issue is causing STD to fail somehow. But I don't understand the exact order of operations between STD and NPSP.

Or, another way to put it: when the Account "winning" COntact in and STD merge has no Address record, STD merge fails. If the "winner" has a related Address record, STD succeeds.

From David Habib:
Thanks for trying to narrow this down John.  I can say that we have explicit code in NPSP to delete the address if it is blank.  this is to fix an issue where new contacts without addresses specified were creating new blank address records.  I forget why we couldn't prevent the creation rather than later just deleting it, but I do recall spending quite a bunch of time on it and finally going with that solution.  So I doubt that behavior will be changing.

I'll enter your scenario as a bug to investigate, though I will be truthful and say its probably low priority and won't get looked into anytime soon, since it is specific to an external tool's utility, rather than NPSP's Contact Merge.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003x6LTAAY" target="_blank">W-010825</a>

**Comment by davidhabib** [comment]
@mpusto Mary, I've told John to add comments on this bug with his plea to make this higher priority.

**Comment by johnfine** [comment]
@mpusto I feel that I should advocate a bit more for this user scenario: It's pretty common for a SF instance, over years of use, to accumulate 100's of Contacts which are duplicate in pairs, triplets, or worse (I've seen plenty of groups of 4,5,6 in various orgs). NPSP Contact Merge is too time consuming for this many dup sets - a rule-based, bulk method is required to merge 100's of dups all at once, and DemandTools' Single Table Dedup (STD) is the only tool that anyone uses to do the job. Orgs want to keep their data clean as shown by the many HUB questions about how to perform Contact deduping using STD.  There would be major community benefit for NPSP functioning with Contact STD.  Here's another example of how this scenario does not currently work correctly : a recent HUB post by TJ Warfield:

"Oh! When merging contacts in DemandTools, I have found that if the non-master contact has data in any address, phone or email fields the data doesn't make it into the master once merged - even if the master had no data in that field. have to do a data upload prior to merge to get that non-master data into the master record prior to merging otherwise, all that data goes bye-bye."

**Comment by tjwarfield** [comment]
Not sure if this is relevant to this post or not, but having a mass tool
like DemandTools that allows you to find contacts (like spouses) that
should live within the same household based on a set of criteria
(name/address).  I still haven't found a good way to do this, not even in
DemandTools.

**Comment by force2b** [comment]
I'm seeing this same error in the following scenario:

* Contact has blank address fields
* Contact is attached to an "Organization" account.
* User clears the Account field and clicks Save to allow the NPSP to create a new Household Account for the Contact.

I was able to get it to work by entering a dummy value in the Contact's Mailing City field.

Even though the above allowed me to save the record and for NPSP to create the Household Account record, I'm now unable to clear out the dummy values in the Mailing City field.  Doing so generates the same "The record you attempted to access has been deleted. The user who deleted this record may be able to recover it from the Recycle Bin. Deleted data is stored in the Recycle Bin for 15 days." error.

**Comment by davidhabib** [comment]
@force2b since this issue is strictly about Single Table Dedupe scenarios with DemandTools, adding your issue on this thread is not the best way to get it addressed.  In general, we prefer people to post their issue in the hub so we can see if it is something in their config vs our bug.  In cases where the person is much more clear in their understanding of NPSP, such as yourself, and have a true reproducible scenario, it's ok to enter a new issue directly in gitHub.  So if you do that with simple repro steps, that would be great.  thanks.

**Comment by force2b** [comment]
Sorry @davidhabib, I was looking at it as a larger issue with the Address object, not specifically for DemandTools. I'll re-enter as a new issue, and delete my comment from above so it's not duplicated.

**Comment by judisohn** [comment]
My hunch is that [this](https://powerofus.force.com/0D58000003bM466) may be related.

**Comment by milkchug2015** [comment]
Here is another possible solution
I was still getting this error even when all the contacts had addresses (I had 7 duplicates). It seems the problem was that even though the addresses themselves were the same, the CASE of the letters were not. 4 contacts addresses were all CAPS and 3 were all lowercase. Only the contacts whose addresses matched the letter case were successfully merged. When I was down to 2 contacts (one all CAPS and the other all lowercase) I manually changed the caps to lowercase and merged them.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
