### ISSUE TITLE
Review "untranslatable" strings from filter list to determine how they can be made translatable

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/NPSP#2176]
There is a [list of strings](https://github.com/SalesforceFoundation/Cumulus/blob/dev/scripts/stf/filters.json) that we should never translate, since [it was determined](https://docs.google.com/spreadsheets/d/1Z9HsXtt4ioIVFm1D5CAnLcWWYSMgxCzeeJnYVBtVubI) that translating these values might lead to issues in the way the code operates (comparison against hard coded values, etc).

Many of the the "untranslatable" fields are documented in the "[Nonprofit Starter Pack and Translation](https://powerofus.force.com/articles/Resource/Nonprofit-Starter-Pack-and-Translation)" knowledge article.

However, Elena recently [posted in the hub](https://powerofus.force.com/0D58000002nmmMB) that she tried translating some of the disallowed values, and she found that the workflow rules relating to these values do still work.  (Our documentation says that translating these values will break workflow rules).

It seems that _some_ of these picklist values actually can be safely translated.  This could be because I think that querying a picklist value in SOQL will return the untranslated label, [unless you specify `toLabel()`](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_tolabel.htm) for the field in the query.  The only way to be sure is to look carefully at where each of these values is being queried and used, and to experiment/test to verify the behavior of the system after translation.

This task is to perform an investigation and experiments to determine if any of the items on the filter list can be removed, or if the code needs to be modified to be able to remove them.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySsTAAU" target="_blank">W-010898</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySsYAAU" target="_blank">W-010899</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000049ihEAAQ" target="_blank">W-011675</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
