### ISSUE TITLE
inappropriate error message for large number of Recurring Donation installments

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/NPSP#2178]
Create a Recurring Donation. Enter an installment period, and In the "Installments" field enter a number greater than 50. Resulting error message says "...this error message is no longer used"
![screen shot 2016-07-26 at 10 14 14 am](https://cloud.githubusercontent.com/assets/204643/17148085/70dd8658-531a-11e6-90c7-ce01632d6b40.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003yStCAAU" target="_blank">W-010902</a>

**Comment by mpusto** [comment]
We are almost ready to release new RD features, so we will not be making fixes to legacy RD code.
