### ISSUE TITLE
Creating multiple Opportunity Naming Settings records within the same clock minute throws an exception

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/NPSP#2179]
Steps to reproduce:
1. Visit NPSP Settings tab
2. Via Donations > Opportunity Names click 'New Opportunity Name'
3. Save the record (quickly)
4. Click 'New Opportunity Name' again (quickly)
5. Save the record (quickly)

Expected result:
Two Opportunity Naming Settings records are created, with default settings.

Actual result:
When attempting to save the second record, a FIELD_INTEGRITY_EXCEPTION is thrown due to a naming collision of the custom setting.

Notes:
The issue seems to be because the settings are being named using a timestamp with minute resolution.  If you attempt to create and save two ONS records within the same clock minute, then they will end up with the same timestamp/name and the second one will not be able to be saved.

(screenshot of exception attached)

<img width="1180" alt="screen shot 2016-07-26 at 1 09 31 pm" src="https://cloud.githubusercontent.com/assets/1058323/17149852/b993c9f8-5332-11e6-9690-e2569e068921.png">

**Comment by dospromptman** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003yStDAAU" target="_blank">W-010903</a>

**Comment by mpusto** [comment]
This is an obscure bug that we will not be addressing.
