### ISSUE TITLE
mass convert Leads option

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/NPSP#2183]
See Idea here: https://powerofus.force.com/hub-ideas/1066

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySuoAAE" target="_blank">W-010921</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004WCSnAAO" target="_blank">W-017415</a>

**Comment by mbeaty-sf** [comment]
This Issue was logged as an idea several years ago, please follow the idea for any future updates - https://powerofus.force.com/hub-ideas/1066
