### ISSUE TITLE
Percent allocations of opportunities with a null or 0 amount behave strangely

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2216]
[Per this hub post](https://powerofus.force.com/0D58000002sVZMh).

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003g7TnAAI" target="_blank">W-011028</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
