### ISSUE TITLE
Manage Soft Credits page is not nice in small window

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/NPSP#2223]
The new Manage Soft Credits page should be more responsive for page size 1024 px horizontally. Right side of page is truncated, see screen shot. 

![screen shot 2016-08-16 at 3 04 32 pm](https://cloud.githubusercontent.com/assets/204643/17717448/dcdfee8c-63c2-11e6-87e2-b11d0076d528.png)

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
