### ISSUE TITLE
Manage Household Contact Cards don't wrap o IE in Classic

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2231]
The contact cards do correctly dynamically wrap/unwrap on IE in LEX, as well as in all other browsers in both Classic and Aloha.

This is just handled by our SLDS styling, we don't have any javascript code involved here.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003tp9aAAA" target="_blank">W-011097</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
