### ISSUE TITLE
If 'Address Override' is checked, treat small changes as update Setting should be ignored

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2309]
Thread: https://powerofus.force.com/0D58000002xSqew

This was worked out in a support case. Turned out the problem was the small changes treated as updates setting in Address NPSP Settings. With that option checked, even if a contact had 'Address Override' checked, it was still updating the same Address and overwriting the address of the household and other contacts. Use case is work address and home address or multiple family members who have addresses that are just slightly different (maybe on same street).

Propose change that if Address Override is checked, then it doesn't matter if it's a small change or not, it should still be treated as a unique address for that Contact.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002xRBZAA2" target="_blank">W-011424</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
