### ISSUE TITLE
Greater Start/End Date Autofill Control

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/NPSP#2310]
When an Affiliation is created via updating the Primary Affiliation field on a Contact record, the Start Date field is populated automatically with Today() and, if there was a previous value in the Primary Affiliation lookup, the associated Affiliation record will auto-populate the End Date field with Today().

Can this be more granularly controlled to be turned on/off for Affiliations, and/or potential future use of SFDC multi-Account/Contact association?

**Comment by mpusto** [comment]
Is there a reason you didn't log this as an Idea?

**Comment by TracyKronzak** [comment]
I was doing cleanup of my GitHub account as was already there?  Which is
basically, no particular reason.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
