### ISSUE TITLE
Set WhoID on tasks when Engagement Plan is associated to an object that has a Contact or Lead Relationship

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/NPSP#2313]
I don't know if this can be handled generically, but that's the way I've written the ticket.

Right now, when you create an Engagement Plan on an object like Opportunity, Case, or Affiliation (which have a "Primary" or only Contact), the tasks are not associated with that Contact. When I create an Engagement Plan on an Opportunity, I'd like to see those next steps and tasks on the Contact (and rolled up to the primary account, natively).

**Comment by judisohn** [comment]
@cdcarter Are you submitting this as a request or something that you might work on yourself?

**Comment by mpusto** [comment]
If you haven't done so, please add it as an Idea so that people can vote on it

**Comment by cdcarter** [comment]
@judisohn I'd love to work on it, but I suspect there needs to be some discussion around whether it could be handled in the abstract or just needs to be built in for the objects EPs support. Is that best done on the idea exchange, here, or in a post-DF call? cc @mpusto.

**Comment by mpusto** [comment]
Let's set up a time to discuss, particularly with @njjc who did a lot of work on it

**Comment by cdcarter** [comment]
Great! Just had a quick chat with Judi too and confirmed that we can keep the convo going here, and I'll work with y'all to make sure the work I do on this is NPSP architecture sound! I'll follow up after DF with an idea of how this might work and then we can get on a GTM!

**Comment by njjc** [comment]
@cdcarter Thanks for this and for the recent pull request! I'd love to meet up after dreamforce and discuss your experience with EPs and possible enhancements!

**Comment by njjc** [comment]
I like this idea. I'm trying to think of a way to do this generically to apply to all custom objects without sometimes including a junk WhoId... we could make a list setting with the object name and contact/lead lookup field name, which means that by not creating a setting for an object we're choosing not to auto-populate WhoId for Tasks created for that object.

**Comment by cdcarter** [comment]
https://docs.google.com/document/d/1tOJ3cmjkhqrmcMm_pFWaq-6LfK0rvYFga2MMWDzsHbQ/edit - link to spec

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009gP2DAAU" target="_blank">W-022855</a>

**Comment by cdcarter** [comment]
in programs demo today Ben Mozenter also expressed a desire to be able to set the OwnerId to the UserId of the Contact's community user if it exists.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
