### ISSUE TITLE
CON_DoNotContact_TDTM resets fields changed in workflow rule field updates

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2316]
When a contact is part of a household with non deceased household members, and a workflow rule is created to uncheck "exclude from household name", the checkbox field is being overwritten by the trigger the second time it runs, i.e. the trigger context is still showing that the "deceased field" has changed, even though we're running through triggers a second time. [Reported here.](https://powerofus.force.com/0D58000002zMp66)

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002y9shAAA" target="_blank">W-011494</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
