### ISSUE TITLE
Contact Merge does not work for Customer Community w/1:1 model

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2343]
thread: https://powerofus.force.com/0D580000032F0gb

Tested and this is not an issue for Household Account model, only 1:1. 

One contact is non-Community, other contact is Community. 

Error when merge (regardless of which is set as master):

![image](https://cloud.githubusercontent.com/assets/4614343/19965925/b6b8bf7a-a19f-11e6-85fe-b1615711748a.png)

Note: NPSP is emailing errors.

----------
 Error #1:

Error Type: System.DmlException
Error Date: 2016-11-03 12:28:31
Message: "Update failed. First exception on row 0 with id 0031a00000Z0WTIAA3; first error: FIELD_INTEGRITY_EXCEPTION, A portal user's contact record must include an account. Furthermore, the owner of the account must be associated with a role.: [AccountId]"

Stack Trace:
 Stacktrace available at the time of saving the record - (npsp)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWxTAAW" target="_blank">W-016770</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
