### ISSUE TITLE
suppress errors from outside address verification services

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/NPSP#2363]
Power of Us HUB thread [here](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D580000034b2w9).

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBKhAAO" target="_blank">W-016922</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
