### ISSUE TITLE
Health Check for Recurring Donation data

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2369]
We have Health Check looking for bad Recurring Donation metadata, but we are seeing a number of rollup errors such as this that are due to bad data:

Error Type: Batch Apex error
Error Date: 2016-11-08 16:48:26
Message: "First error: Attempt to de-reference a null object"
Context: npsp__RD_RecurringDonations_BATCH

The suggested Health Check and corresponding reports will help identify the leading causes of this error:

* Open Recurring Donation records with no Contact or Organization
* Open Recurring Donation records with both Contact and Organization (should be one or the other)
* Open Recurring Donation records with Contact, and that Contact is not Individual account (Household, One to One, Individual)
* Open Recurring Donation records with Organization, and that Account is Individual (Household, One to One, Individual)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBLaAAO" target="_blank">W-016933</a>

**Comment by mpusto** [comment]
We will not be providing additional fixes for legacy recurring donations. We recommend customers consider Enhanced Recurring Donations and upgrade at a time that is appropriate for their organization.
