### ISSUE TITLE
Users can't delete default allocations on closed/lost opportunities.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2384]

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXxhAAG" target="_blank">W-017010</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXxmAAG" target="_blank">W-017012</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXxqAAG" target="_blank">W-017013</a>

**Comment by judisohn** [comment]
Customer reporting this [in the Hub.](https://powerofus.force.com/0D58000004Qp381)

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
