### ISSUE TITLE
Warn users in lead conversion if profile default account record type is same as One-to-One

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2405]
In #1571 a warning was added if the Account Record Type matched for Household Account. We should also do the same warning for One-to-One Account Model.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004HJcWAAW" target="_blank">W-017123</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
