### ISSUE TITLE
Update Trial Template Metadata

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/NPSP#2406]
There are two repositories on the SFDO github account that theoretically contain the trial metadata included in the new template:

https://github.com/SalesforceFoundation/CumulusTemplate

https://github.com/SalesforceFoundation/NPSP-SignupOrg

These repos are both multiple years out of date. Per #1619 - there are now actions and other pieces of metadata that are in the template, expected for regular use of NPSP in LEX, and not included in the managed package. 

Where can we get the latest metadata that isn't included in the package?

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Ii3EAAS" target="_blank">W-017177</a>

**Comment by judisohn** [comment]
@cdcarter I think this is great and will continue the conversation among the team. In the meantime, you could always spin up an org with the latest Trial Template ID? Not ideal, and not nearly what you're asking but at least a compare against that might get you started?

**Comment by cdcarter** [comment]
In today's NPSP Adv Board meeting we discussed the need for consultants and partners to put together demos. Someone at SFDO is going to take a look at the expiration times on orgs set up from the template ID (please, and thanks :) )
