### ISSUE TITLE
Manage Household enforces security that the standard UI does not

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2427]
Thread: https://powerofus.force.com/0D580000038OWn5

I have tested and confirmed this behavior in a test org.

In the standard UI, a user without Modify All or Delete perms on Account can edit a Contact, change their Household Account to a different Account and the now-orphaned Account is deleted as expected. 

However, if the same user uses the Manage Household interface to add a Contact from an existing one-Contact Account, they get this [error](https://github.com/SalesforceFoundation/Cumulus/blob/80a222491bc91e291cb0b0b680883aeb2fbc7798/src/labels/CustomLabels.labels#L2799): You must have update and delete permissions on Households (Accounts) in order to add an existing contact to the Household.

Consider making sure the behavior in and out of the Manage Household interface is the same in this respect.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004K75DAAS" target="_blank">W-017288</a>

**Comment by mbeaty-sf** [comment]
W-7782880

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlG9QAI&title=manage-households-enforces-security-that-the-standard-ui-does-not) in the Trailblazer Community for updates.
