### ISSUE TITLE
With State & Country Picklists enabled, can't save Contact from Canada

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2432]
- have State & Country picklists enabled
- have United States specified as the default country (not sure if this is required to reproduce the bug)
- create a new contact, and specify BC, Canada in their picklists
- save

Apex trigger djhcumulus2.TDTM_Contact caused an unexpected exception, contact your administrator: djhcumulus2.TDTM_Contact: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id 001G0000022jmK9IAI; first error: FIELD_INTEGRITY_EXCEPTION, The existing country/territory doesn't recognize the state value for field: Billing State/Province Code: [BillingStateCode]: Class.djhcumulus2.TDTM_TriggerHandler.processDMLAllOrNothing: line 231, column 1

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004PkDhAAK" target="_blank">W-017307</a>

**Comment by davidhabib** [comment]
if default country is empty, or address management is disabled, this problem will not reproduce.

**Comment by judisohn** [comment]
As per this [thread](https://powerofus.force.com/0D58000003O8TdT), it may be related this [known issue.](https://success.salesforce.com/issues_view?id=a1p30000000T4OMAA0)

**Comment by davidhabib** [comment]
on that thread, person from Classy also added some useful info.
https://powerofus.force.com/0D58000003O8TdT

**Comment by sam-knox** [comment]
It also appears that you only get the error if you choose a non-default Country that has a defined list of States. For example, if you follow the steps to reproduce above and choose Algeria, you don't get an error. If you choose Canada and British Columbia you get the error. You don't get it though if you just choose Canada and leave mailing State blank.

**Comment by mbeaty-sf** [comment]
This Issue was fixed in a previously release, and is no longer reproducible.
