### ISSUE TITLE
Add 'Payment Status' formula on Payment to combine multiple fields in related list (LEX)

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2434]
In LEX, you can only see 4 fields in a related list, making it difficult to see Payment Number, Payment Date, Amount, Paid and Written Off at the same time.

Suggest formula field for 'Payment Status' to combine multiple fields and update layout.

`IF( npe01__Written_Off__c , "Written Off", IF ( npe01__Paid__c , "Paid", "Unpaid"))`

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBUGAA4" target="_blank">W-017314</a>
