### ISSUE TITLE
rename label on old system fields no longer used with DEPRECATED

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2442]
don't delete them to avoid problems with 3rd party packages, but go ahead and relabel them DEPRECATED and update comments/help text to say no longer used.  I'm aware of Contact._SYSTEM: ACCOUNT PROCESSOR .  there might be others.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBaOAAW" target="_blank">W-017385</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
