### ISSUE TITLE
Allocations should inherit the OwnerID of the parent object before insert

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2464]
If none is set, inherit the OwnerId of the parent opportunity/recurring donation/campaign before insert to allow simple inserts via the API without explicitly setting the field value. [Issue described in the hub.](https://powerofus.force.com/0D58000003BEoRC)

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004kdb6AAA" target="_blank">W-017616</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
