### ISSUE TITLE
Deprecated fields on Account can't be deleted in subscriber orgs

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/NPSP#2481]
The Account fields npe01__FirstDonationDate__c, npe01__LastDonationDate__c, npe01__LifetimeDonationHistory_Amount__c, and npe01__LifetimeDonationHistory_Number__c show a delete option in the field list, but cannot actually be deleted because they are available to the packaged BDE List FS field set.

I found a couple other similar situations on Contact and will update with details later.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004v1aQAAQ" target="_blank">W-017691</a>

**Comment by jesslopez-sf** [comment]
Wanted to post the solution here in case anyone else has the same issue.

1. Remove all fields from the BDE List FS (Managed) Field Set on Contact.
2. Remove all fields from the BDE List FS (Managed)  Field Set on Account.
3. Delete two Contact fields

- DEPRECATED - Last Transaction Date (npe01__Last_Donation_Date__c)

- Lifetime Transaction Total (npe01__Lifetime_Giving_History_Amount__c)

 4. Delete four Account fields:

- DEPRECATED - First Donation Date (npe01__FirstDonationDate__c)

- DEPRECATED - Last Donation Date (npe01__LastDonationDate__c)

- DEPRECATED - Lifetime Donation Amount (npe01__LifetimeDonationHistory_Amount__c)

- DEPRECATED - Lifetime Donation Number (npe01__LifetimeDonationHistory_Number__c)
