### ISSUE TITLE
EP_EngagementPlans_TEST.testSkipWeekendsMonday() fails at certain times

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/NPSP#2489]
I think the failure condition is when it's Sunday in the running user's TZ (so that `daysUntilWeekend` == 0), but it's after midnight Monday GMT. 

I added debugs of the relevant details right before the failing assert:

    System.debug('Reminder date/time: ' + results[0].ReminderDateTime + ' and just date: ' + results[0].ReminderDateTime.Date() );
    System.debug('Now + days til w/e: ' + System.now().addDays(daysUntilWeekend));
    System.assert(results[0].ReminderDateTime.Date() > System.now().addDays(daysUntilWeekend), 'Reminder should be set after the weekend.');

And when running the test at 11:14 pm EST on Sunday as a user in the America/NewYork TZ, got these results:

    23:14:41:954 USER_DEBUG [171]|DEBUG|Reminder date/time: 2017-02-13 16:00:00 and just date: 2017-02-13 00:00:00
    23:14:41:955 USER_DEBUG [172]|DEBUG|Now + days til w/e: 2017-02-13 04:14:

The test passes when the user's TZ is set to GMT.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000050EphAAE" target="_blank">W-017797</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
