### ISSUE TITLE
Google geocoder only using short names for state/country

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/NPSP#2498]
(This has only become apparent with the fix to Google geocoder in 3.90)

## Problem as observed:

When a user sets an Account's BillingCountry to Belgium, the country field shortly thereafter changes to BE.  If the user then "corrects" the address, it changes back once again.  Since we have external integrations and reports that rely on the values of BillingAddress, this really makes things difficult.  In an extreme case (e.g., "Uttar Pradesh, India", for American users), the textual data becomes opaque for all purposes, even mailing labels (USPS will not deliver to the country of India, but to the state of Indiana).

## Problem diagnosis:

Then, `ADDR_GoogleGeoAPI_Validator#verifyAddress` sets the new Address__c record's MailingCountry__c and MailingState__c to `add.short_name` (lines 188-192) which forces "Belgium" to "BE" (or "Arkansas" to "AR", or "Uttar Pradesh" to "UP").  Then (since that newly added address is default), that address is used to set BillingAddress.

## Suggestions:
There are several pieces I'd recommend changing.  I don't know if these should be global changes or just configurable.

1. I would like to also keep long names and ISO codes in my Address__c records for search purposes (perhaps add another two fields to Address__c for the long names)
2. I would like to keep long countries and states in my Mailing/BillingAddress fields.  It's fine if that's not the default option, though I do think that Uttar Pradesh, India, would be an issue for many of your US users.

## Work around:

My current work-around is to turn off geocoding for Organizational Account Addresses.  Households will still have illegible addresses, but in my case, that is largely fine.

**Comment by ckoppelman** [comment]
split off the separate tickets.

**Comment by mbeaty-sf** [comment]
Given that there has been no subsequent activity on this Issue for the past 4 years, we are going to assume this is no longer occurring.
