### ISSUE TITLE
Google geocoder Street Address not formatted properly for all non-US addresses

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/NPSP#2499]
## Problem:
Not all countries format street addresses in the same way.  Here's a long list of [official postal service formats, by country](http://www.bitboost.com/ref/international-address-formats.html#Formats).

However, ADDR_GoogleGeoAPI_Validator sets MailingStreet__c to an American-style address (lines 196-215).

This makes international addresses wrong, and difficult to read, use, or even update (since the geocoder may fail if the order is wrong)

This is a similar problem in Address__c.Formula_MailingAddress__c.

## Examples:

> Piedras 623
> C1070AAM CABA
> Argentina

Piedras is the street_name, 623 is street_number, C1070AAM is the zip plus suffix, and CABA is the "state" short_name.

Formula_MailingAddress__c may even cause problems in Queens, NY:

> 35-01 Union St
> Flushing, NY 11354
> USA

Note that Flushing is the "neighborhood", Queens is the sublocality, and there is no locality (though other points in Queens have a locality of New York).

## Suggested Solution:

I would suggest taking whatever formatted_address Google gives you.  If you want to break out a separate street address in order to set BillingAddress better, you can perhaps delimit based on commas and take the first row, but it can be quite complicated to figure out if there's a MailingStreet2 (although it seems you don't set that anyway).  Honestly, you are handicapped by how Salesforce treats addresses anyway (c.f., [the Success idea to fix Addresses](https://success.salesforce.com/ideaView?id=08730000000BrVWAA0))

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000059swgAAA" target="_blank">W-017823</a>

**Comment by ckoppelman** [comment]
Any timeline for this?

**Comment by judisohn** [comment]
It is still on the backlog @ckoppelman - thanks for your patience.

**Comment by sam-nolan-tearfund** [comment]
This issue doesn't appear to be fully resolved.

Here in Australia, we prefer our addresses to be formatted like:
28 Buckingham Ave
Bentleigh VIC 3204
Australia

Again, the formatted_address when received from the geocoding API gets it right: "28 Buckingham Ave, Bentleigh VIC 3204, Australia". But NPSP will format it in a very US style, expanding Ave to Avenue and shortening Australia to AU: "28 Buckingham Avenue<br>Bentleigh, VIC 3204<br>AU"

I'd give the same recommendation as above. It would be good to simply use the "formatted_address" field if possible, or if not give some other field that can let people access it, or provide better settings to control whether the short name or long name is used.
