### ISSUE TITLE
As an employee, I want to be able to view the Household Account Management page natively in the Salesforce1 environment so that I can manage household members and view household information on a mobile/tablet device

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#25]
- Implement Salesforce1 style controls for the Household Management page

**Comment by davidhabib** [comment]
**lurch: attach W-007315

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYzAAI" target="_blank">W-007315</a>

**Comment by kbromer** [comment]
**lurch: review

**Comment by LurchTheButler** [comment]
Test

**Comment by kbromer** [comment]
**lurch: review

**Comment by kbromer** [comment]
**lurch: review apex

**Comment by kbromer** [comment]
**lurch: review

**Comment by kbromer** [comment]
**lurch: review

**Comment by kbromer** [comment]
**lurch: review

**Comment by kbromer** [comment]
**lurch: review

**Comment by kbromer** [comment]
**lurch: review

**Comment by LurchTheButler** [comment]
#### General
- [ ] All new pages, classes or metadata conform to naming conventions

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
