### ISSUE TITLE
Allow for 0 Amount GAU Allocation on insert/update if Opportunity is 0

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2520]
[Thread.](https://powerofus.force.com/0D58000003H14Bg)

If an Allocation is created for 0 for a 0 Amount on the Opportunity, upon update the Allocation is deleted. The Manage Allocation page does not allow for 0 Allocations. There is a valid use case for 0 Opportunities and Allocations (In-Kind donations).

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCgkAAG" target="_blank">W-018040</a>

**Comment by mbeaty-sf** [comment]
This issue was addressed in a previous release.
