### ISSUE TITLE
Custom Labels for Data Import Donation Donor field so values can be translated

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2524]
[Thread](https://powerofus.force.com/0D58000003HRG50).

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCmdAAG" target="_blank">W-018100</a>

**Comment by mbeaty-sf** [comment]
W-7781140
