### ISSUE TITLE
RLLP_OppRollup - Coding Error?

### ISSUE THREAD

**Issue by 3-14159265358979323864** [SalesforceFoundation/NPSP#2540]
This section of code (line 477) ...

        `for (id cid : cmap.keySet()) {
            contact c1 = cmap.get(cid);
            contact c2 = contactsToUpdate.get(cid);

            if (c1.npo02__TotalOppAmount__c == c2.npo02__TotalOppAmount__c &&
                    c1.npo02__OppsClosedThisYear__c == c2.npo02__OppsClosedThisYear__c &&
...`

does not include a check for
`c1.npo02__LastOppAmount__c == c2.npo02__LastOppAmount__c`

even though `npo02__LastOppAmount__c` is updated in `updateRollupFromResult` (line 851) ...
`obj.put('npo02__LastOppAmount__c', lastAmt);`

Clearly an edge case, but if the last opp amount increased by £1 and another opp amount decreased by £1 then `obj.put('npo02__LastOppAmount__c', lastAmt);` would change, but `npo02__TotalOppAmount__c`, etc would stay the same, and so the record would be `contactsToUpdate.remove(cid);` and not persisted to the DB.

This my first week developing in Salesforce so I apologise if I'm missing something obvious!
**
It looks like `npo02__NumberOfClosedOpps__c` doesn't get checked for changes either

**Comment by 3-14159265358979323864** [comment]
Off topic, but what exactly is my Avatar meant to represent?!!!!

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005fH5lAAE" target="_blank">W-018176</a>

**Comment by davidhabib** [comment]
hmm, that is a questionable image!  blame gitHub!  Maybe you should upload your actual photo!

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
