### ISSUE TITLE
Recurring Donation Refresh on fixed-length naming error on Amount

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2552]
![image](https://cloud.githubusercontent.com/assets/4614343/24769606/1886b19a-1ad5-11e7-990a-dcdf7cbeda46.png)

When the Open Opps are adjusted to account for a Closed/Won opp that is not the expected installment, the naming of the Opps in combination with the Opp Naming rule does not round correctly.

STR:
1. Opp Naming rule that includes {!Amount}
2. Create fixed-length RD with 4 installments for $1000
3. Mark first installment as Closed/Won and change Amount from 250 to 500
4. Back on RD, Refresh Opportunities

Note: This only happens when you click Refresh Opportunities on the RD (which is recreating the Opportunities). If you make the change in step 3, but then only 'Refresh Name' on the Opportunity itself, the name does not update incorrectly.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005kjmgAAA" target="_blank">W-018292</a>

**Comment by davidhabib** [comment]
I assume you'll get the same problem if you just initially create the RD for $100 w/ three installments, no?

**Comment by judisohn** [comment]
Believe it or not...No. Which is why this was so hard to replicate I guess. It's only when the change happens and Refresh Opportunities is clicked. 

Stays the same even after Refresh:

![image](https://cloud.githubusercontent.com/assets/4614343/24770948/c7ed4226-1ad9-11e7-8799-868486e3c9f7.png)

**Comment by mpusto** [comment]
We are almost ready to release new RD features, so we will not be making fixes to legacy RD code.
