### ISSUE TITLE
If matching gift is populated on Opportunity, Find Matching Gifts page not creating Contact Role 

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2583]
[Thread.](https://powerofus.force.com/0D58000003Ob5RX)

While not exactly the workflow we imagined, it makes sense that a known record might be populated on the donor Opp to the matching gift. When that happens, Contact Role on matching gift and update of donor opportunity is not happening exactly as customer describes.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PFiJAAW" target="_blank">W-018670</a>

**Comment by mbeaty-sf** [comment]
W-7781126

**Comment by kporray1** [comment]
Please follow this [Known Issue ](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlG3QAI&title=find-matching-gifts-page-does-not-create-contact-role-if-matching-gift-is-populated-on-opportunity)in the Trailblazer Community for updates.
