### ISSUE TITLE
If lead conversion creates the Household account, the Type field is not updated as with other HH Accounts

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2585]
[Thread.](https://powerofus.force.com/0D58000003PumFY)

Needs an update [here](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/LD_LeadConvertOverride_CTRL.cls#L395) to add the correct picklist value using the same constant for HH_Type?

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006V7KxAAK" target="_blank">W-018741</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
