### ISSUE TITLE
Update Find Matching Gifts to not rely on Matching Status field

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2603]
[Thread.](https://powerofus.force.com/0D58000003Ob5RX)

It is challenging for customers to rely on auto matching as [our code](https://github.com/SalesforceFoundation/Cumulus/blob/482c5f391edae931e1dfbd11ac745049fa2f6d56/src/classes/MTCH_FindGifts_CTRL.cls#L99) depends on the value in the Matching Status field if they only populate the Matching Account and don't populate the matching gift. They have to remember to also select the status which may not be necessary? 

` WHERE ((Matching_Gift__c = null AND StageName IN :closedWonStages AND Account.Name = :opp.Account.Name AND (Matching_Gift_Status__c = 'Potential' or Matching_Gift_Status__c = 'Submitted')) 
                        OR (Matching_Gift__c = null AND StageName IN :closedWonStages AND Matching_Gift_Account__r.Name = :opp.Account.Name AND (Matching_Gift_Status__c = 'Potential' or Matching_Gift_Status__c = 'Submitted')) 
                        OR Matching_Gift__c = :opp.Id)`

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006oasQAAQ" target="_blank">W-019021</a>

**Comment by mbeaty-sf** [comment]
W-7781125

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  W-7781125
