### ISSUE TITLE
Merge Households and Merge Contacts functionality does not support Salesforce Files

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/NPSP#2621]
The current behavior for these handle moving Activities and Attachments the new primary record, but Files attached to the Household or Contact being deleted are lost. Salesforce files will be the replacement for Attachments in LEX going forward, so it's important that the merge functionality support these.

**Comment by force2b** [comment]
**lurch: add

**Comment by judisohn** [comment]
@kbromer can you make sure @force2b can Lurch? Thanks!

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000070JOCAA2" target="_blank">W-019155</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
