### ISSUE TITLE
Records are not matched if there are multiple rows for the same new Donation/Payment in NPSP Data Import

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2624]
With the new Donation/Payment matching, if a Donation/Payment is created in a row in the NPSP Data Import batch, and there's another row in the same batch meant to match to that new record, it does not match and behavior is unpredictable. 

I discussed this with @davidhabib and it will be challenging to address, but putting on the backlog for future consideration if there is customer demand.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000070Lc1AAE" target="_blank">W-019176</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
