### ISSUE TITLE
When Organization Address Management enabled, Contact Addresses should behave the same regardless of Account

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2626]
If Organization Address Management enabled, the Default Address for an Account does not update Contacts whose primary Account is that Organization. 

While we don't recommend a Contact/direct Organization Account model, there are use cases where it is a valid choice. In those cases, the Mailing Address on the Contact should be assumed to be the same as the Billing Address on the Account. Like with Household Accounts, the address should update on change to the Account address unless overridden to use a different address.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000076D3AAAU" target="_blank">W-019210</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
