### ISSUE TITLE
If a Contact is unchecked as Deceased, Naming fields should update

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2627]
[Thread.](https://powerofus.force.com/0D58000003UEDh0)

This feels like an oversight and not the intended behavior [here](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/CON_DoNotContact_TDTM.cls#L138). If Deceased is unchecked, the 'Exclude from...' fields should also be unchecked and it's not happening. It's not toggling, it's only working in one direction.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000076EoNAAU" target="_blank">W-019217</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
