### ISSUE TITLE
Updating Contact address fields ignores Address Override if no Address record

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/NPSP#2628]
1. Turn NPSP HH Address Mgmt off (use case; your org doesn't want any address syncing at all).
2. For a 2-Contact HH Acct, fill in the Mailing fields for one Contact and set AddressOverride=TRUE and PrimaryAddressType = WORK
3. For a second Contact in the same HH, leave the mailing fields blank and AddressOverride = FALSE (use case; the first Contact is a parent that wants their work address primary; the second is a kid in the HH, and your org doesn't do mailings to kids)
4. Turn on NPSP HH Address Mgmt (some time has gone by and your org decides they want address syncing after all)
5. Fill in the Mailing fields on the kid's Contact record (now your org decides they want to mail kids)

Issue: The kid's address is sync'd to the parent's Contact record, even though the latter record has AddressOverride = TRUE.  The latter's mailing fields are overwritten, AddressOverride is unchecked, and PrimaryTypeType is set to the kid's address.

Syncing should never occur to a Contact that has AddressOverride=TRUE.

Note that this behavior only occurs if there is no Address record associated with the HH Acct.  If Address Mgmt is on when step 2 is performed, then a non-Default Address record is created and this issue doesn't occur.  Whether it is an issue or a feature that a non-default Address record is created when AddressOverride=TRUE is a separate question.

**Comment by judisohn** [comment]
@johnfine Thanks. I did some testing and this happens if a Contact does not have a 'Current Address' and another Contact without Address Override is updated. You don't necessarily have to disable Address Management. Just deleting the Current Address (while leaving Override checked) and updating another Contact shows the issue.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007CEdIAAW" target="_blank">W-019298</a>

**Comment by johnfine** [comment]
Ah, that is super useful for me to know, thank you Judi.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
