### ISSUE TITLE
Primary Contact can be the same on two Household Accounts. Bad.

### ISSUE THREAD

**Issue by jessingrass** [SalesforceFoundation/NPSP#2645]
Repro steps:

1. go to Account Tab
2. select NEW -> create a household account 
3. Name the account
4. Select a Primary Contact (you are forced to use the lookup field, to choose a pre-existing contact, see screenshot)

<img width="706" alt="screen shot 2017-07-18 at 1 45 39 pm" src="https://user-images.githubusercontent.com/1976801/28331518-65800a60-6bbf-11e7-923a-3ae4490d66c6.png">

5. Press Save

Expected Behavior: We expect that someone who is a primary contact on another account will NOT be able to be selected for this new account.

Actual Behavior: When we select a contact who is primary on another account, they are also saved as primary on this account, even though they do not belong to this household.

**Comment by jessingrass** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007O6umAAC" target="_blank">W-019580</a>

**Comment by judisohn** [comment]
also see #2631

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
