### ISSUE TITLE
Manage Household: Re-adding a Contact from another Household results in an exception or unexpected result

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/NPSP#2646]
**Scenario I:** Adding, removing and then adding a Contact adds the Contact to another new Household
1.  Find/Create a Household A having one or more Contacts
2. Find/Create a Household B having two or more Contacts
3. View Household A > Manage Household > search for a Contact from Household B > Click + to add the Contact
4. Click X to remove just added Contact and confirm removal
5. Add the same Contact to the Household again
6. Save

**Expected Result:**
The Contact is added to Household A.

**Actual Result:**
The Contact is added to a new Household C.

**Scenario II:** Adding, removing and then adding the only Contact in a Household generates an exception
1. Find/Create a Household A having one or more Contacts
2. Find/Create a Household B having one Contact only
3. View Household A > Manage Household > search for the Contact from Household B > Click + to add the Contact
4. Click X to remove just added Contact and confirm removal
5. Add the same Contact again
6. Save

**Expected Result:**
The Contact is added to Household A.

**Actual Result:**
Merge failed. First exception on row 0 with id 001Z000001F9woVIAR; first error: ENTITY_IS_DELETED, entity is deleted: []

**Comment by RadSFDeveloper** [comment]
**lurch: attach w-019572

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007O5HGAA0" target="_blank">W-019572</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
