### ISSUE TITLE
Control affiliations auto-create based on account criteria

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/NPSP#266]
I have clients that want to use various named accounts as bucket accounts. However with the Affiliations package installed and set-up to automatically create they will always have an affiliation created if the account name isn't Individual. I think it would be great to be able to control whether a given account should automatically have an affiliation created/updated from the account instead of hard-coded to Individual.

**Comment by davidhabib** [comment]
**lurch: attach W-007251

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXxAAI" target="_blank">W-007251</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
