### ISSUE TITLE
Google Address Verification Parsing Error

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2660]
Null object exception [at this line](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ADDR_GoogleGeoAPI_Validator.cls#L170) if reject partial addresses setting is set.

Google sometimes returns partial_match as null, so we need to check for null case in our processing.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007U2I6AAK" target="_blank">W-019698</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
