### ISSUE TITLE
Double clicking Convert button on Lead Conversion VF page creates duplicate Contact records

### ISSUE THREAD

**Issue by igoode** [SalesforceFoundation/NPSP#2683]
LD_LeadConvertOverride convert button allows users to double click and either create two contacts or throw an error if duplicate management is enabled

**Comment by judisohn** [comment]
Replicated. Thanks for reporting @igoode 

It may go without saying, but it's the Convert button within the VF page, not the overridden button on the Lead layout.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007a1iOAAQ" target="_blank">W-019831</a>

**Comment by jamesbsfdc** [comment]
[Hub post about the issue](https://powerofus.force.com/s/question/0D51E00005d3VVKSA2/npsp-lead-conversion-bug-create-multiple-records)

**Comment by jamesbsfdc** [comment]
W-9229029

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlFoQAI&title=double-clicking-convert-button-on-lead-conversion-visualforce-page-creates-duplicate-contact-records) in the Trailblazer Community for updates.
