### ISSUE TITLE
"Re-Center on this contact" link broken in lightning

### ISSUE THREAD

**Issue by igoode** [SalesforceFoundation/NPSP#2685]
**Issue**
Clicking on "Re-Center on this Contact" in the Relationship Viewer on a Contact record, results in an error, reading:

`Page REL_RelationshipViewer does not exist`

**Cause**
In the Relationship viewer page, "Re-Center on this contact" link looks to be using relative URL rather than the URLFOR function.

**Workaround**
None currently available

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007qTHEAA2" target="_blank">W-020124</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
