### ISSUE TITLE
Health Check should check for Relationship records with a blank "Reciprocal Relationship" field

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/NPSP#2697]
Records with a blank value in `npe4__ReciprocalRelationship__c` are technically invalid and may have been created by bulk uploads with disabled NPSP triggers or other possible scenarios.  Health Check should be able to detect these to alert the Admin that there are records to be fixed or recreated.

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007qFQHAA2" target="_blank">W-020027</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
