### ISSUE TITLE
Validate invalid seasonal Address dates

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2705]
[Thread.](https://powerofus.force.com/0D58000003az6WN)

It's possible to have a Seasonal Start Date in the picklists on Address as February (2) 30, and it appears that there is no error thrown. Consider validation to prevent invalid Month/Day combinations.

**Comment by judisohn** [comment]
**lurch: add

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
