### ISSUE TITLE
Inconsistent NPSP scheduled job name

### ISSUE THREAD

**Issue by zizhang** [SalesforceFoundation/NPSP#2730]
The documentation on NPSP Scheduled Jobs located does not match what's in the code UTIL_MasterSchedulableHelper class

https://powerofus.force.com/articles/Resource/NPSP-Edit-or-Reschedule-NPSP-Scheduled-Jobs

Default job name is NPSP 06 - Recurring Donation**s** Updates on the documentation.

In UTIL_MasterSchedulableHelper.cls

`/*******************************************************************************************************
    * @description This map contains all necessary information for scheduling default NPSP jobs:
    * Job name as key, and a list containing the cron expression for that job and its class name.
    */
    public static Map<String, List<String>> defaultScheduledJobs = new Map<String, List<String>>{
        'NPSP 00 - Error Processing'                => new List<String>{'0 0 * * * ?',  'ERR_AsyncErrors_SCHED'},
        'NPSP 01 - Opportunity Account Rollups'     => new List<String>{'0 0 23 ? * *', 'RLLP_OppAccRollup_BATCH'},
        'NPSP 02 - Opportunity Contact Rollups'     => new List<String>{'0 0 23 ? * *', 'RLLP_OppContactRollup_BATCH'},
        'NPSP 03 - Opportunity Household Rollups'   => new List<String>{'0 0 23 ? * *', 'RLLP_OppHouseholdRollup_BATCH'},
        'NPSP 04 - Opportunity Soft Credit Rollups' => new List<String>{'0 0 23 ? * *', 'RLLP_OppSoftCreditRollup_BATCH'},
        'NPSP 05 - GAU Allocation Rollups'          => new List<String>{'0 0 23 ? * *', 'ALLO_Rollup_SCHED'},
        'NPSP 06 - Recurring Donation Updates'      => new List<String>{'0 0 23 ? * *', 'RD_RecurringDonations_BATCH'},
        'NPSP 07 - Seasonal Address Updates'        => new List<String>{'0 0 23 ? * *', 'ADDR_Seasonal_SCHED'},
        'NPSP 08 - Level Assignment Updates'        => new List<String>{'0 0 4 ? * *',  'LVL_LevelAssign_SCHED'}
    };`

**Comment by jesslopez-sf** [comment]
This article was recently updated with the correct Recurring Donation Scheduled job name.
