### ISSUE TITLE
Changing Primary Contact behavior inconsistent between Manage Household and standard UI

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2733]
If you change a Household Account with multiple member's Primary Contact using the standard lookup field on the account record, the Name and Greetings are updated to reflect that Contact as the first in naming order. However, if you are using the Manage Household page and use the Primary Contact field that is there via the field set to change the Primary Contact, then the naming is not touched and the record is saved with the original naming order. 

This behavior should be consistent between methods (recommend that we follow behavior as is in the UI and change the order, but still allow for the naming to be changed manually even if the Primary no longer remains as the first named).

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005uZ3EAAU" target="_blank">W-020349</a>

**Comment by mbeaty-sf** [comment]
W-7781127

**Comment by jthall1** [comment]
What's the status of this issue? I'm actually experiencing an error where even directly editing the Primary Contact field on the Household layout does not result in an updated Household Name/Formal/Informal Greetings. Right now the **only** way I can get the name to update is via drag-and-drop to reorder on the Manage Household page.

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlFfQAI&title=changing-primary-contact-behavior-inconsistent-between-manage-household-and-ui) in the Trailblazer Community for updates.

**Comment by kporray1** [comment]
Hi @jthall1 - please make sure to check 'This Issue Affects Me' on this [Known Issue ](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlFfQAI&title=changing-primary-contact-behavior-inconsistent-between-manage-household-and-ui)to raise visibility and get notified of updates.  Thank you!
