### ISSUE TITLE
Update page layouts with better button ordering for LEX

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2740]
Currently in LEX, the default buttons shown on page layouts correspond to default Actions, and end up showing non-relevant actions, e.g.

![image](https://user-images.githubusercontent.com/1018198/30230426-1c9b6dda-949b-11e7-949d-9300e7133547.png)

Update page layouts by overriding pre-defined actions, then reordering "Salesforce1 and Lightning Experience Actions" to put relevant buttons first.

**Comment by njjc** [comment]
**lurch: add

**Comment by njjc** [comment]
@judisohn we should do this in the DOT as well.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005ugIIAAY" target="_blank">W-020411</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
