### ISSUE TITLE
Contact Role Trigger is not running when restoring the Primary Contact

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/NPSP#2747]
Steps to replicate:
- Delete an Opportunity with a Primary Contact associated.
- Delete the Primary Contact.
- Restore the Opportunity. (initially Primary Contact will be null)
- Restore the Primary Contact. (The Primary Contact will also be restored on the Opportunity but the Primary Contact Role is not restored)

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008F9zCAAS" target="_blank">W-020437</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
