### ISSUE TITLE
BDI.html in ApexDoc is missing

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/NPSP#2760]
This 404s and shouldn't: http://developer.salesforce.org/Cumulus/ApexDocumentation/BDI.html

This is also duplicative to the 'BatchDataImport' grouping, and should probably just be removed

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008LNS4AAO" target="_blank">W-020541</a>
