### ISSUE TITLE
UTIL_Describe.checkFieldFLS() should not namespace

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2764]
the utility routine UTIL_Describe.checkFieldFLS() for checking FLS assumes that both the object and fields are from the NPSP namespace.  Currently, this public method is only used in one routine in Engagement Plans, and it is OK.  But because this is a public utility method, I fear in the future other devs might use it and not realize it blindly namespaces any custom field.  I'd recommend that we change UTIL_Describe.checkFieldFLS() to NOT namespace fields, and that the callers be responsible for using UTIL_Namespace.StrTokenNSPrefix() on the appropriate fields.  This is critical if this routine is ever used with a page that uses field sets, since those can contain fields from npsp, other packages, and customer unmanaged custom fields.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003cEZEAA2" target="_blank">W-020596</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
