### ISSUE TITLE
Manage Allocations results in "DML currently not allowed" error

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/NPSP#2768]
If an Allocations Settings record does not exist, viewing Manage Allocations page will result in "DML currently not allowed" error. The cause is insert of a default Settings record in the constructor.

Stack trace:
> 13:42:05.1 (45789948)|METHOD_EXIT|[69]|01p0q000000HMr5|UTIL_CustomSettingsFacade.getAllocationsSettings()
13:42:05.1 (45894688)|FATAL_ERROR|System.LimitException: DML currently not allowed
Class.UTIL_CustomSettingsFacade.getOrgAllocationsSettings: line 438, column 1
Class.UTIL_CustomSettingsFacade.getAllocationsSettings: line 246, column 1
Class.ALLO_ManageAllocations_CTRL.__sfdc_settings: line 69, column 1
Class.ALLO_ManageAllocations_CTRL.<init>: line 139, column 1

**Comment by RadSFDeveloper** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003cNYSAA2" target="_blank">W-020623</a>

**Comment by mbeaty-sf** [comment]
W-7783090
