### ISSUE TITLE
Control auto-add affiliations by Account Record Type

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#277]
_Issue by **[boxfoot](https://github.com/boxfoot)** from Friday Jan 11, 2013 at 19:14 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Affiliations/issues/1_

---

Would be great if we could enable "auto-add affiliations" from some contact record types while disabling it for others.  I realize that might be opening a can of worms, but it would be handy.

Use case:  We have 2 RecordTypes:  CRM Contact (we care about affiliations) and Clients (we don't).  Clients are accessible via Customer Portal, but ideally affiliations shouldn't be.  When a Customer Portal user creates a Client, the affiliations trigger tries to create an affiliation but fails since affiliations aren't available in the customer portal.

---

Could potentially repurpose some of Carlos' HEDAF code.

**Comment by davidhabib** [comment]
**lurch: attach W-007252

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXyAAI" target="_blank">W-007252</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
