### ISSUE TITLE
Contact Roll-Ups are not recalculated when the Contact.Currency code is changed

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/NPSP#2771]
See https://powerofus.force.com/0D58000003bMns3

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003cRSDAA2" target="_blank">W-020635</a>

**Comment by force2b** [comment]
**lurch: attach W-020211

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007aBgPAAU" target="_blank">W-020211</a>
