### ISSUE TITLE
Data Import: If user does not have Customize Application permission, they should be able to see  configuration options

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2779]
![image](https://user-images.githubusercontent.com/4614343/30986383-36b859f0-a461-11e7-9e3b-b22499fc6a8c.png)

Note that they are able to successfully process records, provided they have proper other access to objects.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003cYsVAAU" target="_blank">W-020694</a>

**Comment by mbeaty-sf** [comment]
W-7781142

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlFeQAI&title=data-import-if-user-does-not-have-customize-application-permission-they-should-be-able-to-see-configuration-options) in the Trailblazer Community for updates.
