### ISSUE TITLE
Manage Engagement Plan page does not display user applied changes after an error

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/NPSP#2787]
1. View Engagement Plan Templates > create or select a Template with two Tasks > Edit
2. Click Add Task so a new empty Task 3 is displayed
3. Change a Subject/Type/.. for an existing Task 1
4. Change a Subject/Type/.. for an existing Task 2 and specify an invalid "Days After" field value (1v1 for example) 
5. Click one of the following buttons:
- Add Task 
- Save
- Delete Task on Task 3

Expected Result: 
An error is displayed for invalid "Days After" field while user changes for Task 1 and 2 are still displayed.

Actual Result:
An error is displayed for invalid "Days After" field while user changes for Task 1 and 2 are reverted back to prior values.
Delete Task for a new Task expects Subject to be provided on delete even though this Task does not exist in Salesforce.

**Comment by RadSFDeveloper** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008SQdkAAG" target="_blank">W-020750</a>

**Comment by coriobriensfdo** [comment]
[Another Hub Thread.](https://powerofus.force.com/0D51E00004c3ADI)

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
