### ISSUE TITLE
Remove limit of 75 custom fields on the Payment object to use Payment Mapping from the NPSP Settings page

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2808]
If an instance has more than 75 custom fields on the Payment object, no Payment fields will appear available for mapping in NPSP Settings. This apparently is a limit that is no longer needed and should be considered for change. In the meantime, organizations can manually create Payment Mapping Settings records via Custom Settings in Setup, using the API names of the Opportunity and Payment fields they wish to map and unique Name fields (CustomMapping0, CustomMapping1, etc)

**Steps to Recreate**
1. Create a custom field on the Payment Object
2. Go to NPSP Settings > Donations > Payment Mappings and create a Payment Mapping to link an Opportunity field to a Payment Object custom field you created in Step 1
3. Create custom fields so that the total field on the Payment Object is > 75 fields total
4. Attempt to create another Payment Mapping, and encounter an "No Valid Field Available" in the Payment Field list (picture below)

![image](https://user-images.githubusercontent.com/53280203/76910608-ba068400-686b-11ea-8cda-eeeb84e5ee5f.png)

**Comment by judisohn** [comment]
*lurch: add

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SMxAAAW" target="_blank">W-020975</a>
