### ISSUE TITLE
BDI: Mapped Custom Address Field Causes Error When Address is Blank

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#2827]
When a user maps a custom Address field in the NPSP Data Import object and then imports a completely blank Address (no Street, City, State, Zip, Country), the user receives the following error (since there is no Address to write to):

`Update failed. First exception on row 0 with id a0Zf4000001u05TEAQ; first error: ENTITY_IS_DELETED, entity is deleted: []`

This gets added to our Error object and emailed if error notifications are enabled. However, it's unclear what's going on. The record in the Error object has limited information (***Full Message ***shows error message above;*** Error Type*** = System.DMLException; no stacktrace available).

Is it possible to prevent the insertion of an Address if all address fields are blank on the BDI record and there are custom mapped Address fields?

**Steps to reproduce:**

1. Verify _Household Account Addresses Disabled_ = false in NPSP Settings
2. Create custom text field on **Address** object called _Address Test_.
3. Create custom text field on **NPSP Data Import** object called _Address Test_ with help text of Address.Address_Test__c.
4. In import file, fill out Contact 1 info, don't fill in any address fields, but set Address_Test__c to 'test'
5. Import file
6. Start Data Import
7. You'll see that there was an error. When you click into the data import record, the failure is the error stated above.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008j93gAAA" target="_blank">W-021088</a>

**Comment by JavierFerreira** [comment]
**lurch: attach W-035081

**Comment by mbeaty-sf** [comment]
W-7781136

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlFZQAY&title=batch-data-import-mapped-custom-address-field-causes-error-when-address-is-blank) in the Trailblazer Community for updates.
