### ISSUE TITLE
If last Contact in Household Account is removed, set Naming to custom to avoid Anonymous Household

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2832]
We get frequent reports and frustration with 'Anonymous Households' that happen when an Household Account does not have any contacts. There are a variety of situations that can cause this, including incorrect Record Type default in lead conversion, merging, and now our new Contact Delete Override which gives the option of deleting a Contact and leaving the Account behind.

A possible solution here would be to set _SYSTEM: CUSTOM NAMING to Name when the last Contact is removed. That would preserve the name through any naming updates so the organization can better find and deal with these orphans and understand its original content and intent.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008jEcoAAE" target="_blank">W-021110</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
