### ISSUE TITLE
Schedule Payments page fails on null Opportunity amount.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#2845]
Uncaught exception when clicking Calculate Payments in the Schedule Payments wizard:

```
Attempt to de-reference a null object
Error is in expression '{!calculate}' in component <apex:commandButton> in page pmt_paymentwizard: Class.PMT_PaymentWizard_CTRL.calculate: line 252, column 1
```

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008n6r1AAA" target="_blank">W-021161</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
