### ISSUE TITLE
2nd order (green) Contacts in viewer have undefined ID

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#285]
_Issue by **[kbromer](https://github.com/kbromer)** from Thursday Jan 17, 2013 at 15:55 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Relationships/issues/12_

---

When using the context menu in the viewer, green-level relationships have an ID undefined and broken links associated with them.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fkxAAA" target="_blank">W-008232</a>

**Comment by mbeaty-sf** [comment]
[W-007374](https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x800000001cZxAAI/view)

Salesforce has determined that this issue will not be explored further.
