### ISSUE TITLE
Investigate supporting SmartyStreets verification for International addresses

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/NPSP#2853]
When our address verification tool was created, SmartyStreets did not support International addresses. Now that it is supported, we should review our code to determine if we can modify it to no longer strip out non-US addresses, and if so, update our code to properly support.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008nNxgAAE" target="_blank">W-021244</a>
