### ISSUE TITLE
Better clean up of empty Account when Contact is reparented

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2860]
[One](https://powerofus.force.com/0D58000003nK9CS) of a few threads on the subject.

It is reasonable that an organization will reparent a Contact from one Account to another from time to time, whether it's to move to a different household without using Manage Household or to assign directly to an Organization if that is best for their business process (even if it's not what we recommend).

When this happens, and if the now-prior Household no longer has a Contact, the Account is renamed to Anonymous Household and the Contact is still that Household's Primary Contact. This is really bad data and a source of a lot of confusion. It makes it theoretically possible for the same Contact to be Primary on 2 Households at once. Not good. It doesn't matter whether there are existing records on the Account or not. 

If a Household is left orphaned when a Contact is reparented, the Primary Contact field on the Account should be set to null and perhaps instead of 'Anonymous Household' we update the name to something that clearly informs the organization what happened so they can best clean up their data without guessing?

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008nUJUAA2" target="_blank">W-021289</a>

**Comment by mpusto** [comment]
Related to https://github.com/SalesforceFoundation/Cumulus/issues/2645

**Comment by annejackson** [comment]
Notes for how moving a primary contact from one household to another household functions differently in HEDA than it does in NPSP.

steps to check/see this:
1. Create two households each with 3 contacts. (the first contact created per household will be the primary.- this is correct for both NPSP and HEDA)
2. Go to one of the households/accounts- Household A. Move the primary contact for Household A to the other household/account- Household B.
--In NPSP- The primary contact from Household A remains the primary contact for household A (Even though the contact is now in Household B)
--In HEDA- The primary contact from Household A is removed from Household A (it is blank).

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.

**Comment by dodifriedenberg** [comment]
This is so needed. How is this helpful? Please reconsider
