### ISSUE TITLE
Test failure in EP_EngagementPlans_TEST when tests executed over a weekend

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/NPSP#2882]
Error message is 
> Class.npsp.EP_EngagementPlans_TEST.testSkipWeekendsMonday: line 169, column 1
Message: System.AssertException: Assertion Failed: Reminder should be set after the weekend.

https://mrbelvedereci.herokuapp.com/builds/14092/tests

The problem appears to have started on 12/2 or 12/3 (no commits on Saturday 12/2 to confirm against) and resolved itself on Tuesday 12/5. A build submitted at 2:33PM on Monday 12/4 still failed, which seems surprising since that was a Monday - assuming that the issue is weekend related. 

The failure is reproducible by submitting build on a Sunday afternoon (after 7PM ET)

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000093IEjAAM" target="_blank">W-021607</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
