### ISSUE TITLE
With 1:1 model, 1:1 Accounts without Contacts or Opportunities should be deleted when orphaned

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2886]
Our recent changes in Account deletion behavior works as expected with the Household Account model, but has undesirable behavior for those organizations on the 1:1 model. 

Replicate by setting to 1:1 model, Create a Contact and allow NPSP to create 1:1 Account. Now change Account on the Contact to an Organization (behavior that was typical for the 1:1 model since the Account is never meant to stand alone and be viewed independently). Result is that the 1:1 Account remains, but still has the Contact connected as its Primary (One2One) Contact, but no Contact is in the Account.

This causes problems for any Account-based reporting and can be challenging to clean up. Unlike with Household Accounts, it is less likely there will be other custom objects directly connected to the 1:1 Account. We should consider deleting those accounts (prior behavior). 

[Thread.](https://powerofus.force.com/0D58000003nK9CS)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009380qAAA" target="_blank">W-021519</a>

**Comment by schieco** [comment]
Pleeeeeeease! So many client's have malfunctioning instances now. Thanks!

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
