### ISSUE TITLE
Error message for Internet Explorer users with Manage Household page

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2889]
Report from user in the [Hub](https://powerofus.force.com/0D58000003rjUCF) who tested on multiple machines running Internet Explorer 11 (Windows 7 and Windows 10) and received error of 'Unable to read sObject' as well as other display issues (blank Contact fields). Unable to reproduce in Chrome or Firefox.

![image](https://user-images.githubusercontent.com/4614343/34009638-a9b33d5a-e0d7-11e7-95b6-b5977134a678.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000093CBxAAM" target="_blank">W-021569</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
