### ISSUE TITLE
Getting Started Tab - Latest Release Notes UX Suggestion

### ISSUE THREAD

**Issue by dextermilo** [SalesforceFoundation/NPSP#2916]
The current implementation creates an element that is not obviously scrollable and is difficult to read due to its limited vertical height.

## Suggestion 1

Just display the full content and allow the box to expand. Issues with unexpected length might be mitigated by making the column 2/3 width instead of 1/2. The videos could potentially be refactored into a 1/3 column.

### Sort of like this?

![image](https://user-images.githubusercontent.com/779557/34848291-7ad419f4-f6db-11e7-9b2b-06bcb95350bf.png)

## Suggestion 2 

Okay, maybe suggestion 1 is less palatable due to priority of the videos and wildly varying lengths of the release notes. Instead the remaining content could simply be disclosed using a link similar to the one present.

### Dev Console mockup of example closed

![image](https://user-images.githubusercontent.com/779557/34847687-713ab68e-f6d9-11e7-8596-45c8c4cc0f99.png)

(Oops, for some reason I failed to screenshot the "View more" link, use your imagination to add it with whatever verbiage you prefer. 😄)

### Open

![image](https://user-images.githubusercontent.com/779557/34847743-9f68afde-f6d9-11e7-9ce9-2fafedd8d34b.png)

## Suggestion 3

There are probably better options. This was just what I quickly thought of. I think the primary issue is that I enjoy having the content there but I don't enjoy reading it in the current format. Cheers.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KBg9AAG" target="_blank">W-022114</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
