### ISSUE TITLE
Inconsistent UI when NPSP Data Import page is loaded from Console app

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2926]
Create a Console app in Lightning Experience and add NPSP Data Import object. 

When 'Start Data Import' is run, the page does not load in the same way as it appears from Classic or non-Console apps.

![image](https://user-images.githubusercontent.com/4614343/35232047-6baee3b0-ff68-11e7-883f-26d2ed1a7e57.png)

Style sheet update needed?

**Comment by judisohn** [comment]
**lurch: add

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
