### ISSUE TITLE
Manage HH page causes duplicate contacts on error

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/NPSP#2932]
Steps to replicate:
1. Press the Manage HH button from the Account page.
2. Create a new Contact from the Contact search component.
3. Type the name of the new Contact into the Primary Contact field in the field set form.
4. Save the page. Note error at the top of the page.
5. Save the page again. Note error no longer at the top of the page but have not navigated away.
6. Save the page again. Note navigated back to Account page with 3 of the new contacts created above.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009UcUuAAK" target="_blank">W-022487</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
