### ISSUE TITLE
When Currency is changed on a Campaign in a multi-currency org related GAU Allocation records should be updated to match currency change

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2959]
[Thread.](https://powerofus.force.com/0D580000040A2sG)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009loJqAAI" target="_blank">W-022894</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
