### ISSUE TITLE
Settings: consider allowing customer code to provide custom settings during tests

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#2973]
hub thread: https://powerofus.force.com/0D580000041RjTu

customer would like to set our custom setting values before running their tests.  unfortunately, our current settings facade always constructs new default custom settings if we are in a test execution context.  I believe this was originally done for historical reasons when test data isolation was not provided by the platform (seeAllData=false).

Worth considering if we can come up with a solution that works both for our tests, as well as our customers writing tests that will then run our trigger handler code.

Conceptually it's similar to what we provide customers for trigger handlers. in your test, first get our cached set, and modify them as you like, and then continue your work and when any triggers run, our code will use the cached handlers you've provided.

It may be as simple as allowing our code to read the setting now that we have test data isolation. But I'm sure many of our settings don't have the full defaulting that the facade is doing in this scenario.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009rDVeAAM" target="_blank">W-022958</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
