### ISSUE TITLE
Adding or Deleting a Contact does not Update Household Account Card Without Refresh (in Lightning)

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/NPSP#2978]
Please see resolved but similar defects: https://github.com/SalesforceFoundation/Cumulus/issues/2930 and [W-022485](https://foundation--agf.na6.visual.force.com/apex/adm_bugdetail?id=a2x80000009UaRwAAK&sfdc.override=1)

_PreReq: Login to a Lightning org_

**PART 1 --> Deleted Contacts Should Not Show in the Household Account (should be deleted immediately without a refresh)**
1. Find a Household Account with more than one Contact
2. Click "Contacts" to get to Recent Contacts List
3. Locate one of the Contacts from the Household Account in Step 1
4. On the right of that Contact, click the drop-down arrow & select "Delete"
5. On the right of the "Accounts" tab, click the Drop-Down Arrow, & select the Household Account from the list
     **EXPECTED RESULT** : Deleted Contact does not appear in the "Contacts" section of the Account Card
     **ACTUAL RESULT** : Deleted Contact is still showing and is not removed until page is refreshed

**PART 2 --> Adding a Contact to a Household Account Should Show Immediately on the Household Account (should not require refresh)**
1. Click "Contacts"
2. Select a Contact by clicking on it.
3. Click "Edit"
4. In "Account Name," click the "X" to clear out the Account name, and select a new Account.
5. Click "Save"
6. In this screen (Account Card) click the new Account name.
     **EXPECTED RESULT** : Contact shows up in the Account card immediately
     **ACTUAL RESULT** : Contact does not appear in the Account card until the page is refreshed

**Comment by dgamboni** [comment]
**lurch: add

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009rTAZAA2" target="_blank">W-023063</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
