### ISSUE TITLE
Need to be able to automate OCR when Organization is Recurring

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#301]
_Issue by **[kbromer](https://github.com/kbromer)** from Monday Oct 29, 2012 at 03:13 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Recurring_Donations/issues/17_

---

When an organization is the recurring donor, it would be ideal to be able to automatically associate a Contact via OCR at the same time.

**Comment by njjc** [comment]
We need a strong use case for this, we haven't heard community requests for this.

**Comment by davidhabib** [comment]
**lurch: attach W-007254

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cY0AAI" target="_blank">W-007254</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
