### ISSUE TITLE
Unmapped Currency Symbol Results in Health Check Error and Opportunity Naming Does Not Work

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3015]
This Issue is related to #2931 but results in slightly different behavior.

Custom Opportunity Names that reference the Amount field do not work when multi-currency is enabled and the Currency Locale is set to a currency that we don't have mapped in UTIL_Currency. The Opportunity saves, but retains the manually entered Name value. It also results in a Health Check error: "Attempt to de-reference a null object", even if all tests have passed. (See screenshot)
![health check ils issue](https://user-images.githubusercontent.com/29731456/37910425-79e4f308-30db-11e8-8469-9847dbc7f44c.jpg)

Reference: Case 18611153 

Cause:
The UTIL_Currency class has a variable called currencySymbols which maps the three letter currency code to its symbol. ILS is not a mapped option, so it returns a null value when called in line 417 of the OPP_OpportunityNaming class. 

Steps to Repeat:

1. Go to Setup --> Company Information, hit Edit, and change Currency Locale to: Hebrew (Israel) - ILS 
2. Check off the "Activate Multiple Currencies" box and hit Save.
3. Click the Currency Setup button. 
4. In the Active Currencies section, click the New button and add USD.
5. Go to NPSP Settings --> Donations --> Opportunity Names and click the New Opportunity Name button.
6. Choose the following values:
-- Attribution: both
-- Opportunity Record Types: Donation 
-- Opportunity Name Format: {!Account.Name} {!Amount} {!RecordType.Name} {!CloseDate}  [Or any option that references the Amount field]
7. In NPSP Settings --> Run Health Check. You receive an error at the top that says "Error: Attempt to de-reference a null object"
8. Create a new Opportunity and save. The Name is not changed from your initial value.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000ADo1bAAD" target="_blank">W-023529</a>

**Comment by coriobriensfdo** [comment]
[Another thread.](https://powerofus.force.com/s/question/0D51E00004yQLiMSAW/opportunity-naming-with-multiple-currencies)

**Comment by jamesbsfdc** [comment]
Closing this issue as all Salesforce supported currency symbols were added in October 2019m though it appears this was missed in the release notes for 3.163. 

Have also logged a doc bug to update https://powerofus.force.com/s/article/NPSP-FAQ#topic-6742 to remove the text saying only certain currency codes/symbols are supported in Opportunity Naming
