### ISSUE TITLE
Getting Started Tab Error if YouTube videos on how to playlist are private

### ISSUE THREAD

**Issue by chrisbanm** [SalesforceFoundation/NPSP#3018]
On all my orgs, the NPSP Getting Started Tab suddenly stopped working (about 20 hours ago) and instead of showing all the great info I just get the following error:

**Attempt to de-reference a null object** 
An unexpected error has occurred. Your solution provider has been notified. (npsp)

This is the URL of that tab:

/one/one.app#/n/npsp__NPSP_Resources

I get the same behavior in my production org, my sandbox orgs and my scratch orgs. All of them have NPSP v3.124 installed.

**Comment by judisohn** [comment]
Thanks for reporting @chrisbanm - we'll get right on it!

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AJcMzAAL" target="_blank">W-023651</a>

**Comment by judisohn** [comment]
The videos have now been set to visible so the page will not error, but the underlying issue needs to be resolved so this won't happen accidentally again.

**Comment by chrisbanm** [comment]
Fabulous! Thanks, the tab works now.
