### ISSUE TITLE
Translated Picklist Labels for OCR Roles can affect Rollups

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/NPSP#3021]
I discovered the following regarding the use of Picklist Labels and API Names in the code:
* The Settings page will display the label value (including the translated labels) in the settings UI.
* The Settings page also stores the label value into the Custom Settings field instead of the API Name. For example, if the current User has a language other than English and the "Donor" picklist value has been translated into something different (ex: "La Donor"), the value stored in the NPSP Custom Settings field will be "La Donor".
* The actual data in the OpportunityContactRole.Role field is always the picklist api name regardless of the value of the label and regardless of any translations. The beauty of this implementation is that picklist values are translation and override agnostic, allowing system integrations and custom apex to "always" work regardless of what an admin might have translated a picklist value label to.
* The NPSP code base does not support this implementation because it always uses the picklist label. In the example above where the "Soft Credit" OCR Role was translated to "La Soft Credit" and an Admin with a default language of "French" modified the NPSP Settings for this Role, the legacy Rollup jobs will no longer work because the code will be looking for OCR records with a Role="La Soft Credit". 

https://releasenotes.docs.salesforce.com/en-us/spring17/release-notes/rn_forcecom_picklists_ui_and_api_labels.htm

**Steps to reproduce:**
1. Setup | Translation Settings
2. Enable the French language
3. In Setup | Translate, select "French"; "Picklist Value"; "Opportunity" and expand the section for "Opportunity Contact Role"
4. On the "Soft Credit" role row, double-click in the second column to enable entry. Enter a value such as "La Soft Credit".
5. Click Save
6. In NPSP Settings (while the current user's language is English) verify the current Contact Role settings (Primary and Soft Credit Donor roles) and then execute the Donor Rollup Batch job.
7. Select a Contact that has Soft Credit rollups on it.
8. Make a note of the Soft Credit rollup values.
9. Change the current User's default language to "French"
10. Open the NPSP Settings Page. Select "Rôles des contacts" under "Dons" and click the [Modifier] button.
11. In the section for "PARAMÈTRES DE DONS DE GROUPE", change the selected Role to "La Soft Credit". 
12. Click Save
13. Change the User's language back to English (only to make reading the page easier)
14. Form the NPSP Settings Page, execute the Donor Rollup Batch job again
15. Return to the contact selected in step 7 and refresh the page. Note that the Soft Credit values are now gone.

In the above, the objective is to translate the OCR Role Label (which is the recommended approach for localization) and then for an Admin using a non-English Language to update the NPSP Settings Page (which is also likely). The result of that update is that the translated label value is saved as the selected Contact Roles in the NPSP Custom Settings objects rather than the Role's API Name. When the rollup jobs use that information to select OCR records for Soft Credits, it's trying to filer for Role="La Soft Credit" whereas the database record itself actually contains "Soft Credit" (the api name for that picklist value) in the Role field.

Note that this likely applies to other picklist values that are stored in Custom Settings such as Opportunity.Type. 

https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/STG_Panel.cls#L256
https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/RLLP_OppRollup_UTIL.cls#L844

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AJfvgAAD" target="_blank">W-023677</a>

**Comment by judisohn** [comment]
@force2b @davidhabib Isn't this the same core issue as #2704?

**Comment by davidhabib** [comment]
yep! the same!

**Comment by judisohn** [comment]
Do we want to merge the WIs/Issues then?

**Comment by force2b** [comment]
Yes, though the other issue is more specific in terms of Label vs. API Name. Same basic root problem though.
