### ISSUE TITLE
Inconsistent Partial Soft Credit behavior when amount is full amount of opportunity

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3032]
[Thread.](https://powerofus.force.com/0D580000047gyyG)

I'm not entirely sure if this behavior has always been this way, or it has been introduced recently.

It has always been to the spec that a Contact Role that is the full amount of the Opportunity would not also have a corresponding Partial Soft Credit (PSC) record. You can see that if you use the 'Manage Soft Credit' interface and attempt to add a Role for the full amount. It simply creates a standard Contact Role record and does not create a PSC record.

Customer has pointed out, and this was confirmed in a scratch org, that this behavior is not enforced consistently which leads to potentially bad data quality. We should not rely entirely on the use of the Manage Soft Credit page.

For example:

1. Edit an existing PSC record in the UI to set amount to equal the Opportunity amount. The record saves without error. 
2. Go to 'Manage Soft Credits' and Save without making changes. The PSC is deleted.
3. When you are on a Matching Gift and link to a donor opportunity for the full amount, the PSC is saved for the full amount.
4. Again, when 'Manage Soft Credit' page is touched, the PSC is cleaned up. It is not cleaned up otherwise.

**Comment by judisohn** [comment]
cross referenced to [W-023931](https://foundation.lightning.force.com/one/one.app?source=aloha#/sObject/a2x8000000APeaIAAT/view)

**Comment by coriobriensfdo** [comment]
We have another instance of this issue, but with a twist. See [Hub Thread.](https://powerofus.force.com/s/question/0D51E00004puVaISAU/bizarre-manage-soft-creditspartial-soft-credits-issue) 

Details below. I've recreated this in a Trial org. 

_Shout out to Carlos Gallardo (Year Up.)_

**Steps to Reproduce:**
1. Create, or go to, an Opportunity/Donation Record Type record with an Amount of $50.00.
2. Click Manage Soft Credits button.
3. Find a Contact, select Soft Credit Role Name, select Full Type, Amount or Percent updates to 50.00. Click Save.
4. Returns to the Opportunity/Donation Record Type detail layout. New Opportunity Contact Role has been created under the Contact Role Related List with Soft Credit Role. No Partial Soft Credit is created. As expected.
5. Click Manage Soft Credits button.
6. Change the Type from Full to Partial, and type in 25, while keeping the Soft Credit Restriction's Amount radio button. Click Save.
7. Returns to the Opportunity/Donation Record Type detail layout. Opportunity Contact Role remains as is. New Partial Soft Credit record is created with Soft Credit Role and $25.00 Amount. As expected.
8. Click Manage Soft Credits button.
9. Keep Type as Partial, but change Soft Credit Restriction's Amount radio button to Percent radio button. This updates the Amount or Percent to 50.00 (as $25 is 50% of the $50 Total Amount). Click Save.

**Expected Result:**
- Partial Soft Credit record should remain as is with Amount of $25.00.
- If we click back into the Manage Soft Credits VF Page, the page should show that the Soft Credit remains as Type of Partial.
- All we did on the Manage Soft Credits VF Page was change the visual render Amount of $25.00 to Percent of 50.00.

**Actual Result:**
- The Partial Soft Credit record was deleted.
- If we click back into the Manage Soft Credits VF Page, the page shows that the Soft Credit Type is now Full with an Amount or Percent of 50.00 and the Soft Credit Restriction's Amount radio button is selected.

**Potential Issue:**
- For some reason the VF Page does not like if one uses the Soft Credit Restriction's Percent radio button, and the Amount or Percent Value is the same as the Amount of the Opportunity/Donation Record Type record.
- If you try the same Steps to Reproduce, but instead use a $20.00 Opportunity Amount --> Amount value of 4.00 --> then switch radio button to Percent value of 20.00 it will result in the same issue.
- If you try the same Steps to Reproduce, but instead use a $75.00 Opportunity Amount --> Amount value of 56.25 --> then switch radio button to Percent value of 75.00 it will result in the same issue.
- If you try the same Steps to Reproduce, but instead use a $120.00 Opportunity Amount --> Amount value of 144.00 --> then switch radio button to Percent value of 120.00 it will result in the same issue.

**Exception to the Rule:**
- If you try the same Steps to Reproduce, but instead use a $100.00 Amount and a Amount or Percent value of 100.00 it ACTUALLY does not hit this issue as $100 is 100 percent and not partial amount or percent to it (if that makes sense).

**See Hub Thread for weird twist.** I couldn't recreate the issue with a $300 Opty following the exact same steps, but can with a $50 Opty. We believe there is a correlation with $50 and 50% and $100 and 100% but need clarification via the code. 

**Images of Cori recreating in Trial with $50 Opty:**

<img width="1365" alt="Screen Shot 2019-04-25 at 3 40 51 PM" src="https://user-images.githubusercontent.com/37851761/56773317-7c3fcf00-6772-11e9-9d6f-0e914bdbed26.png">
<img width="1382" alt="Screen Shot 2019-04-25 at 3 41 07 PM" src="https://user-images.githubusercontent.com/37851761/56773318-7cd86580-6772-11e9-8962-8e8cfd682d1a.png">
<img width="1379" alt="Screen Shot 2019-04-25 at 3 41 33 PM" src="https://user-images.githubusercontent.com/37851761/56773319-7cd86580-6772-11e9-9220-3e71a4992731.png">
<img width="1363" alt="Screen Shot 2019-04-25 at 3 41 45 PM" src="https://user-images.githubusercontent.com/37851761/56773320-7cd86580-6772-11e9-8ad9-c913e63c44e2.png">
<img width="1379" alt="Screen Shot 2019-04-25 at 3 42 02 PM" src="https://user-images.githubusercontent.com/37851761/56773323-7cd86580-6772-11e9-860a-cda1b77b3b47.png">
<img width="1372" alt="Screen Shot 2019-04-25 at 3 44 40 PM" src="https://user-images.githubusercontent.com/37851761/56773324-7d70fc00-6772-11e9-8bed-95c4c7e541be.png">
<img width="1368" alt="Screen Shot 2019-04-25 at 3 45 00 PM" src="https://user-images.githubusercontent.com/37851761/56773331-83ff7380-6772-11e9-96a4-b1efcb26d0ed.png">

**Comment by mbeaty-sf** [comment]
W-7782852

**Comment by stallCloudBlazer** [comment]
What is the work around for this issue? The Hub Thread link does not work due to the salesforce.org link change.

**Comment by jamesbsfdc** [comment]
Hi @stallCloudBlazer Please log a support case if you need help with this. If you have already logged a support case please comment here with the case number

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlFAQAY&title=inconsistent-partial-soft-credit-behavior-when-amount-is-full-amount-of-opportunity-causes-incorrect-data-values) in the Trailblazer Community for updates.
