### ISSUE TITLE
PageMessages should follow best practices in escaping text.

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/NPSP#3033]
The UTIL_PageMessage component should no longer default to escape = true on the output text message.
The Cascade Delete message that requires html in the output text should escape the dynamic input field content of the message.

**Comment by jjbennett** [comment]
Attach W-023747

**Comment by mrbelvedere** [comment]
Included in beta release 3.126 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.126

**Comment by mbeaty-sf** [comment]
Closed in [NPSP Release 3.126](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.126)
