### ISSUE TITLE
Recurring Donation Warning should follow best practices and escape text

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/NPSP#3034]
The Recurring Donations Warning message uses an input field in the warning message which should be properly escaped.

**Comment by jjbennett** [comment]
Attach W-023747

**Comment by mrbelvedere** [comment]
Included in beta release 3.126 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.126

**Comment by mbeaty-sf** [comment]
Closed in [NPSP Release 3.126](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.126)
