### ISSUE TITLE
Recurring Donation: Refresh Opportunities button - Opportunity Naming {!Amount} does not constrain consistently to 2 decimals when recalculating 'Divide By' record

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3234]
![image](https://user-images.githubusercontent.com/4614343/40804930-b6d8b658-64ea-11e8-9972-18914bdf5261.png)

Steps to repeat:

1. Opportunity Naming rule formula that includes {!Amount} (example: {!Account.Name} {!Amount} {!RecordType.Name} {!CloseDate})
2. Create Recurring Donation record. Open Ended Status = None; Schedule Type  = Divide By; Installments = 10; Amount = 1000; Installment Period = Monthly (doesn't matter)
3. Edit first Opportunity and change Amount to a different, higher value such as $175.50, Stage = Closed Won. Use case: first payment higher than anticipated installment.
4. Click Refresh Opportunities button 

Note: this behavior only happens with Refresh Opportunities button. Standard Rollups Recurring Donation batch does not appear to recalculate installments on fixed-length.

Expected: Remaining Opportunities would have Amount in Name rounded to 2 decimal points (with any remainder added to final opportunity) to match Amount field on Opportunity.

Actual: Waaaay too many decimal points in Amount value in Name.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXooTAAT" target="_blank">W-025175</a>

**Comment by coriobriensfdo** [comment]
Affecting additional customers: https://powerofus.force.com/0D51E00004aH7Cp

**Comment by mpusto** [comment]
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide
