### ISSUE TITLE
NPSP Error Notifications cannot be posted to Private Chatter Group (Must be Public)

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#3236]
When NPSP Settings Error Notifications are set to Chatter Post, the group selected must be a public group, but should allow for a private group. 

Hub Post: https://powerofus.force.com/0D58000004GEMUM

Steps to Repro:
1. Create a new Chatter Group for testing with Access Type set to Public.
2. Change notification settings to post errors to a chatter group rather than to the default Sys Admin default. NPSP Settings -> System Tools -> Error Notifications. Change settings to post to a Chatter Group. Select new test group.
3. Force error message to fire, for example create Process Builder on Lead object to create new records when created, and add invalid values to update ID field during an update action. Create new lead to force the error to fire.
3. Notice the error message is posted to the Chatter Group as expected. You may still get error emails however.
4. Change new chatter group Access Type to Private.
5. Create another Lead to force error. Notice that error doesn't post to chatter group (you should still get emails however).

User Story from Customer: 
"Error Notifications configured to post error notifications to a private chatter group with a selected group of admins who were expected to monitor those failures as the only members."
"Changing to a public chatter group fixes this, and probably isn't really an issue as I suspect there shouldn't be anything particularly sensitive in those log messages. But this does pollute my global "All Updates" feed in chatter with a bunch of noise that won't be relevant to most users and could potentially confuse them, so would be nice to avoid this if possible."

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXp6gAAD" target="_blank">W-025183</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
