### ISSUE TITLE
Customizable Rollups are behaving differently than Legacy Rollups with multiple Partial Soft Credit

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#3333]
Hub Post: https://powerofus.force.com/0D58000004IyzBH

This post in the hub has unearthed a CRLP / Partial Soft Credit use case that wasn't addressed in Customizable Rollups. 
I've been able to recreate in my org. The Soft Credit rollups on the Contact are only counting one of the partial soft credit records regardless of what role is selected (ie. both as Soft Credit or one as Soft one as Influencer for example).

**Steps to Repro:**
1. Create an Opty for $500 against Contact 1 in an org with Customizable Rollups enabled.
2. Create Contact 2
3. Assign Partial Soft Credit on Opty two times for Contact 2. Both for $250.00.
4. Re-run CRLP rollups on Contact 2. 
5. Note that only $250 is showing in the Soft Credit Rollups.
6. Repeat with CRLP not enabled and note that $500 is showing in Contact 2 Soft Credit Rollups.

<img width="1334" alt="two partial soft credits assigned to the same contact" src="https://user-images.githubusercontent.com/37851761/41671526-36ade890-746c-11e8-9c33-6b7795f626cc.png">
<img width="776" alt="contact crlp only counting one psc record" src="https://user-images.githubusercontent.com/37851761/41671527-36dae778-746c-11e8-932f-1920989c31b2.png">

**Use Case:** Primarily for Employee Giving situations, NP will get a check for a month's worth of employee giving for the company with all the money taken out of employee paychecks and have 2 from the same employee/donor - one for each paycheck. Sometimes they are the same amount, sometimes not. This results in them creating one monthly Opty, with more than one partial soft credit assigned to the same donor to designate the two gift amounts.

Because Legacy Rollups counted multiple PSC records and there is a legitimate use case, CRLP should also count them.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBEAAA5" target="_blank">W-025773</a>

**Comment by RyanBeaver** [comment]
Thank you @coriobriensfdo! Sorry to be a nagger - any guess on how quickly issues like this get resolved?  Trying to game out whether I should wait for the fix or go with plan B.  Thanks!

**Comment by coriobriensfdo** [comment]
@RyanBeaver  Go ahead and post in the Hub if you like, but we don't maintain support here in GitHub. I don't have any updates on this change to Customizable Rollups however :)

**Comment by coriobriensfdo** [comment]
[Another Thread.](https://powerofus.force.com/s/question/0D51E00004puMY3SAM/can-you-get-two-partial-soft-credits-at-once)

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
