### ISSUE TITLE
Allow users to choose OCR role value for different Opp RTs

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#334]
_Issue by **[cozimek](https://github.com/cozimek)** from Tuesday Nov 27, 2012 at 17:28 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Contacts_and_Organizations/issues/11_

---

**Challenge**

In Contacts & Orgs, there's a custom setting for automatic Opportunity Contact Role (OCR) creation. Excellent. However, what if an org is using opps for tracking different things, say donations and event registration opps.

**Proposed Solution**

Provide a mechanism in the C&O custom settings screen for users to choose a different default OCR role value for each available record type in the Opportunity object.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fpxAAA" target="_blank">W-008259</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
