### ISSUE TITLE
Anonymous Household Created During NPSP Data Import Processing

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3347]
When an import file contains more than one Contact and you then relate a donation to the second contact on a separate line of the file, an Anonymous Household record is created. Both Contacts and Opportunities, however, are associated with the correct Household Account.

**Steps to Reproduce:**
This occurs if you have 2 Contacts (for example, Contact 1: John Doe, Contact 2: Jane Doe) on the same line. On that line, you also associate a Donation with John (Donation Donor = Contact1). On the next line, put Jane's information in the Contact 1 set of fields (this will match her up to the record in first line). Then associate a donation in that row with Contact1 (Jane). This all matches up correctly, but you get a duplicate Anonymous Account.

1. Import the CSV (attached to our Work Item) to the NPSP Data Imports object
2. Start Data Import.
3. Confirm that Opportunities were created for both Contacts and are associated with the same household Account record.
4. Also confirm that a new Anonymous Household record was created (with no related records).

The interesting thing is that the NPSP Data Import record for the second line (just Jane) shows an Import Status of "Created", where as the NPSP Data Import record for the first line (both Jane and John) shows Jane's Import Status as "Matched".

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by mbeaty-sf** [comment]
W-7783100
