### ISSUE TITLE
Contact Merge should respect Individual object regarding which Contact record to save 

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3435]
Raised in the Hub [here](https://powerofus.force.com/0D58000004Lkgo0). 

Rather than allowing the user to select the master, the Individual object [has a setting](https://releasenotes.docs.salesforce.com/en-us/summer18/release-notes/rn_determine_record_for_merge.htm) that determines what record is retained or not. Request is to respect this setting as part of our merge code (if customer is using Individual object as part of GDPR compliance, for example).

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBqJAAX" target="_blank">W-026233</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
