### ISSUE TITLE
Batch Data Import Handles Contact 2 Household Differently if Contact 1 is Matched in BDI vs Contacts Object

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3445]
When Contacts and Households are imported using the NPSP Data Import utility, there may be some unexpected matching behavior for similar names in the same BDI record set vs. when matching against existing Contacts already in Salesforce. Specifically there are two issues:

1. Unrelated Contacts are being merged into the same Household just because they have the same Contact 1 name. As a result, bad data is being imported into orgs. So, we may need to add some more documentation that BDI does some matching/combining prior to Contact matching and that it's a good idea to add unique field matching if there are no email addresses, etc.

2. When a BDI record's Contact 1 is matched to another Contact 1 within a BDI record set, Contact 2 should also join that Household. This happens when matching against existing Contact records, but not within a BDI record set (this Contact 2 ends up in their own Household).

**Note: CSV files are attached to the Work Item, along with Quip doc containing prior testing.**

In the sample CSV file imported to the NPSP Data Import (import test 1.csv), there are three rows with Contact 1 and Contact 2 filled out. In theory, they are separate households since they have separate Addresses, but there are no email addresses, phone numbers, or unique text fields to match against, so BDI thinks they are related. 

Row 1:
Contact 1: Jane Doe
Contact 2: Jess Doe

Row 2:
Contact 1: John Doe
Contact 2: Judi Doe

Row 3:
Contact 1: John Doe
Contact 2: Jane Doe

When these are all imported in the same batch and you select either First Name, Last Name, Email or First Name and Last Name as the Contact Matching rule, it creates 2 Households:

1. John, Jane, and Judi Doe Household
2. Jess Doe Household

On the other hand, if the rows for John + Judi and John + Jane were previously imported (and all merged into one household) and you then import Jane + Jess separately and match by First and Last Name, it finds the match for Jane, merges her into the existing Jane record and also adds Jess to the Household.

__*Steps to Repeat:*__

**Setup:**
1. Modify Household Naming to include first name (for easier troubleshooting). NPSP Settings → People —> Households → Household Name Format = {!{!FirstName}} {!LastName} Household
2. If using a scratch org, modify url in Start Data Import button on NPSP Data Import object (remove npsp namespace): /apex/BDI_DataImport?retURL={!URLFOR($Action.DataImport__c.Tab, $ObjectType.DataImport__c)}

**Contact 1 Matched within BDI Set and Contact 2 is put in own household**
3. Import the sample CSV to the NPSP Data Import object.
4. Start Data Import and choose Contact Matching of First Name and Last Name. Keep Batch Size at 50.
5. Confirm that two Households are created: John, Jane, and Judi Doe Household and Jess Doe Household
6. Now delete both Accounts (Contacts will be removed automatically).

**Batch size of 1 keeps Jane and Jess in their own Household**
7. Import the CSV into the NPSP Data Import object again. 
8. Start Data Import and choose Contact Matching of First Name and Last Name with a Batch Size of 1.
9. Confirm that 2 Households are created: John, Jane, and Judi Doe Household, Jane and Jess Doe Household.
10. Now delete both Accounts (Contacts will be removed automatically).

**Matching against existing Contacts merges both Jane and Jess into existing Household.**
11. Import just two rows (using import test 2.csv file) into the NPSP Data Import object. This file contains the rows for John + Judi and John + Jane.
12. Start Data Import and choose Contact Matching of First Name and Last Name. Keep Batch Size at 50.
13. Confirm that one Household was created: John, Judi, and Jane Doe Household.
14. Now import the third row (using import test 3.csv file) into the NPSP Data Import object. This file contains the row for Jane and Jess.
15. Start Data Import and choose Contact Matching of First Name and Last Name Keep Batch Size at 50.
16. Confirm that both Jane and Jess were merged into existing Household: John, Judi, Jane and Jess Doe Household.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBrRAAX" target="_blank">W-026247</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
