### ISSUE TITLE
Customizable Rollups: Allow for Deactivated CRLP to be Deleted when more than one CRLP attached to the same Target Field

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#3492]
Currently, we get an error message when attempting to delete a deactivated CRLP if there is another CRLP that is pointing to the same Target Field. 
Also, once Error Message is clicked to close, the Edit/Clone/Delete buttons are removed from the page. 

See images:

<img width="1304" alt="screen shot 2018-07-16 at 12 09 13 pm" src="https://user-images.githubusercontent.com/37851761/42779758-2f8f7724-88f6-11e8-9dcc-09c027e75eb1.png">
<img width="1064" alt="screen shot 2018-07-16 at 12 09 36 pm" src="https://user-images.githubusercontent.com/37851761/42779759-2fa96ba2-88f6-11e8-9099-ea93fa7d7e9e.png">
<img width="1015" alt="screen shot 2018-07-16 at 12 09 43 pm" src="https://user-images.githubusercontent.com/37851761/42779760-2fc69dee-88f6-11e8-884d-e4337a25e5b0.png">
<img width="943" alt="screen shot 2018-07-16 at 12 09 52 pm" src="https://user-images.githubusercontent.com/37851761/42779762-3040b3cc-88f6-11e8-8985-13d2f583306b.png">

Ideal outcome: Old deactivated CRLP should be removed from the UI when the Delete button is clicked.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBxoAAH" target="_blank">W-026338</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
