### ISSUE TITLE
Customizable Rollups: Donor Streak is 0 if Opportunity Date is in future year(s)

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3587]
[Hub thread.](https://powerofus.force.com/0D58000004MWqEm)

Use case: Customer is tracking donor streak using Customizable Rollups. They are including future commitments in that streak, not just closed/won Opportunities (in other words, they are not basing on the payment date(s))

Currently, if the Donor Streak rollup's Filter Group includes Opportunities with a Date in future years, the Streak is being set to 0. It should count *all* Opportunities in the Group, regardless of the date's reference to the current year. If a customer wishes to exclude future or unpaid gifts, they can account for this in the Filter Group.

Steps to repeat:

1. Custom field on Contact (Number) for Donor Streak
2. CRLP: Target: Contact; Field: Donor Streak; Operation: Donor Streak; FG: None (all Opps); Date: Close Date (also an issue with other date fields)
3. Add Opportunity to Contact with no prior giving history and date 1 year in past from today, Closed/Won. Donor Streak: 1 (Correct)
4. Add Opportunity to Contact and date 2 years in past from today, Open. Donor Streak: 1. Change to Closed/Won. Donor Streak: 2 **Donor Streak is assuming Closed/Won, regardless of Filter Group - if FG is all opportunities, the Streak should use the Opportunity or we should clearly document this.**
5. Add Closed/Won Opportunity to Contact with date set to today. Donor Streak: 3 (Correct)
6. Add Closed/Won Opportunity to Contact with date set to tomorrow. Donor Streak: 3 (Correct)
7. Add Closed/Won Opportunity to Contact with date set from one year from today. Donor Streak: 0. **Should be 4.**

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fMNNAA2" target="_blank">W-027007</a>

**Comment by judisohn** [comment]
[Thread](https://powerofus.force.com/s/question/0D51E00004pvFfpSAE/days-back-time-frame-on-customizable-rollups-is-including-closed-dates-in-the-future) related to this.

**Comment by mbeaty-sf** [comment]
W-7783087

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlF5QAI&title=customizable-rollups-donor-streak-is-0-if-opportunity-date-is-in-future-year-s) in the Trailblazer Community for updates.
