### ISSUE TITLE
Account Soft Credits : When Only 1 Acct Soft Credit Exists, Ensure CRLP fields Update Correctly

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/NPSP#3597]
**Subject Area** :
_Account Soft Credits -- Sandbox release upcoming, Aug 15, 2018_

**Description :** 
If there is only ONE AccSC, and any of the following updates are made, the Account Soft Credit Rollups are not updated properly:
- Opp'y is updated from Closed Won to something else [Closed Lost, Pledged, etc]
- The AcctSC is deleted 
- The AcctSC Account is changed to a different Account

Note that if there is more than 1 AccSC, the CRLPs will update correctly

**Steps to Reproduce :**
1. Create a Field, "Total Account Soft Credits" on the Account object
2. Assign the Field to all the Account Layouts
3. Create a CRLP on the Account object for "Total Account Soft Credits", rolling up to your new field 
4. Create a new Contact & Household Account ("Billy Bulldog", "Bulldog Household")
5. Create a new Organizational Account ("Bulldog Family Foundation")
6. Create a new Opportunity from a _different_ Organizational Account ("Fund Administrators, Inc.")
-- Amt = $9999
-- Date = Today's Date
-- Stage = Closed Won
7. Assign Account Soft Credits by going to the Oppy > AccSC Related Object > New
-- Bulldog Family Foundation = $9999, Role = Donation Source
-- Bulldog Household = $9999, Role = Influencer
8. Confirm (after clicking "Recalculate Rollups" and refreshing the page each Account's page) that:
-- We Send Paypal Direct = $9999 HC, $0 AccSC [in your new rollup fields]
-- Bulldog Family Foundation = $0 HC, $9999 AccSC [in your new rollup fields]
-- Bulldog Household = $0 HC, $9999 AccSC [in your new rollup fields]
9. On the Oppy, change the Stage from "Closed Won" to "Prospecting"
10. On each Account object, click "Recalculate Rollups" and refresh the page
--_Expected Result_ : All amounts have been reset to $0
--_Actual Result_ : Only the HC has been reset to $0; the AccSC fields still reflect $9999

**Notes :** 
- Retest this scenario, changing Step 9 to "Delete AccSC" and ensure amounts are reset
- Retest this scenario, changing Step 9 to "Change Account Name in AccSC" and ensure amounts are reset to $0 for old Account and show up in new Account
- Retest this scenario using TWO opportunities, assigning multiple AccSCs to each account (ie, the Bulldog Family Foundation & Bulldog Household have more than one AccSC. The use cases should work as expected.)

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fMTfAAM" target="_blank">W-027085</a>
