### ISSUE TITLE
Recurring Donations Produce Inconsistent Opp Close Dates with Custom Monthly Installment Periods and "Day" Field Functionality

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3603]
The **_Always Use Last Day of Month_** and **_Day of Month_** functionality produce inconsistent Close Dates for Opportunities created from Recurring Donations with custom monthly installment periods. The first pledged Opportunity has an incorrect day (defaults to the day of the Date Established), while the second Opportunity (in the case of a Bi-Annual Recurring Donation) has the correct day of the month. This leads to inconsistent and incorrect data. 

**Steps to Repeat:**

**Setup:**

1. Go to NPSP Settings → Recurring Donations → Recurring Donation Custom Installment Periods.
2. Add Bi-Annual Custom Installment Period
    1. Click New Custom Installment Period button
    2. Name = Bi-Annual
    3. Time Period Frequency = 6
    4. Time Period Days = Months
    5. Click Create Custom Installment Period button.
3. Add “Bi-Annual” to Installment Period field
    1. Go to Setup → Object Manager → Recurring Donations
    2. Go to Fields & Relationships
    3. Click on Installment Period.
    4. Add a new picklist value called “Bi-Annual”
4. Create a new Contact

**_Example 1: Custom Monthly (Bi-Annual) Recurring Donation, Always Use Last Day of Month_**

**The Control:**

1. Create a new Recurring Donation with the following values:
    1. Name = Bi-Annual Control Test 1
    2. Contact = your Contact
    3. Amount = 1
    4. Open Ended Status = Open
    5. Date Established = 8/31/2018
    6. Next Donation Date: blank
    7. Installment Period = Bi-Annual
2. Results:
    1. 2 pledged Opportunities with Close Dates of 8/31/2018 and 2/28/2019 (Expected). You get the same results if you do a Date Established of 8/15/2018 and a Next Donation Date of 8/31/2018.

**The Bug:**

1. Create new Recurring Donation with the following values:
    1. Name = Bi-Annual: Always Use Last Day of Month
    2. Contact = your Contact
    3. Amount = 1
    4. Open Ended Status = Open
    5. Date Established = today (in my case, 8/15/2018)
    6. Next Donation Date = blank
    7. Installment Period = Bi-Annual
    8. Always Use Last Day of Month = true
2. Results: 2 pledged Opportunities with Close Dates of 8/15/2018 and 2/28/2019 (since Always Use Last Day of Month = true, I would expect 8/31/2018 for the first date). This causes inconsistent data between installments.

**_Example 2: Bi-Annual, Day of Month set_**

**The Bug:**

1. Create a new Recurring Donation with the following values:
    1. Name = Bi-Annual Day of Month
    2. Contact = your Contact
    3. Amount = 2
    4. Open Ended Status = Open
    5. Date Established = today (8/15/2018 for me)
    6. Next Donation Date: blank
    7. Day of Month = 23
    8. Installment Period = Bi-Annual
2. Results: 2 pledged Opportunities with Close Dates of 8/15/2018 and 2/23/2019 (since Day of Month is set, I would expect 8/23/2018 for the first date). This causes inconsistent data between installments.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fMXSAA2" target="_blank">W-027131</a>

**Comment by mpusto** [comment]
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide
