### ISSUE TITLE
Default GAU Allocation for $0 is created but then deleted if GAU Allocation is edited

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3628]
[Thread](https://powerofus.force.com/0D58000004Qp381) (also related support ticket)

If Default GAU Allocations are enabled, a GAU Allocation is not created if the Amount on the Opportunity is null. They **are** created if the Amount = 0. See [related Idea here](https://powerofus.force.com/hub-ideas/1407) to prevent this behavior in the first place.

It appears the bug is that this Allocation is created when it shouldn't be, as if the GAU Allocation record is edited after creation, the GAU Allocation record is automatically deleted.

Steps to repeat:

1. Set default GAU Allocation in NPSP Settings
2. Create an Opportunity with Amount = 0
3. Confirm Default GAU Allocation created
4. Edit the GAU Allocation - you don't have to touch any fields, simply Edit then Save
5. GAU Allocation record is deleted

Either the GAU Allocation record for 0 should not be created, as suggested in the Idea - or this edit should not cause a deletion.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fNAyAAM" target="_blank">W-027981</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
