### ISSUE TITLE
Viewing NPSP Settings tab causes spurious updates to Trigger_Handler__c record

### ISSUE THREAD

**Issue by abeyerpath** [SalesforceFoundation/NPSP#3704]
Repro:
1. Install NPSP with default trigger handler configuration.
2. Visit settings tab page as any user with write access to `npsp__Trigger_Handler__c`

Expected:
No data updates

Actual:
A spurious update with no data changes is written to the `Trigger_Handler__c` record for `PMT_Payment_TDTM:npe01__OppPayment__c` causing the Last Modified user/time to update.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fOhtAAE" target="_blank">W-029129</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
