### ISSUE TITLE
Workflow Action Field Update called "Contact.OtherEmail.Update" is mislabeled

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#3744]
**Hub Post:** https://powerofus.force.com/0D58000004aF32z

**Issue:** 
There is a Workflow Action to update the other phone field when changes are made. The field to update and rule is correct, however the Field Update is mislabeled as Contact.OtherEmail.Update when it should be Contact.OtherPhone.Update

**Steps to recreate:**
1. Log into a Trial or Scratch org configured with NPSP.
2. Go to Setup -> Field Updates. 
3. Click into Contact.OtherEmail.Update
4. Notice the field to update and rule using the field update reference phone, not email.
 
**Code Link:** https://github.com/SalesforceFoundation/Contacts_and_Organizations/blob/master/src/workflows/Contact.workflow#L211-L220

<img width="1388" alt="screen shot 2018-10-24 at 3 36 47 pm" src="https://user-images.githubusercontent.com/37851761/47465671-ba980980-d7a2-11e8-831a-31bac42f46d2.png">

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fOvlQAE" target="_blank">W-029299</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
