### ISSUE TITLE
Default Allocations: If move/reparent an existing allocation record to another opportunity it does not auto-fill the original opportunity with the default gau allocation

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/NPSP#3760]
Per Pedro:  It looks like this is an existing bug in the original allocations code. I think it might make sense to prevent reparenting of allocations.

Setup:
-Had default allocations enabled with a default GAU of "Default GAU"
-Had an opportunity (Opportunity 1) of $100. It has two allocations, one office fund at $40 and one misc fund at $60. 
-Had another opportunity (Opportunity 2) of $80. It has two allocations, one office fund at 25% ($20) and one default gau of $60.

Steps to duplicate:
-In Opportunity 1 amount of $100, I am going to move the $60 misc fund allocation record and tie it to Opportunity 2. When I moved the misc fund out of Opportunity 1, that opportunity just had one allocation left, the office fund gau of $40. (incorrect as it doesn't total the $100 oppt amount- the default gau allocation should be created automatically and make up the difference of $60 for the rest of the payment amount.)
**Note- if I would have just deleted the $60 misc fund it would have correctly had two allocations, the office fund of $40 and then replaced the missing $60 with the default gau.
-For Opportunity 2 oppt amount of $80, it went from $60.00 default gau and $20 (or 25%) Office fund to...$60 Misc Fund and kept the $20/25% office fund. I'm not sure what should happen here, but I know that originally the GAU was listed at $60....could there be a bug here too?

![after reparenting an allocation record](https://user-images.githubusercontent.com/35311289/47761520-0b21d200-dc8f-11e8-829e-3ab4befbe886.png)

**Comment by annejackson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fP9EQAU" target="_blank">W-029457</a>

**Comment by annejackson** [comment]
fyi @njjc  and @pedrodalcol

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
