### ISSUE TITLE
Add New Relationship via Relationship Viewer not defaulting with Existing Contact in Lightning

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#3762]
[Thread](https://powerofus.force.com/0D51E00004aH6pg)

**Issue:**
Following our instructions to auto-default the existing contact when adding a new relationship via the Relationship Viewer isn't working in Lightning. It does work in Classic. 

**Documentation instructions:** https://powerofus.force.com/articles/Resource/NPSP-Auto-Populate-Contacts#!#ariaid-title3

**Steps to Repo** (in persistent org). Attempting to view the Relationship Viewer in a Trial org results in an error.
**Part 1: Follow steps to auto-default existing contact within Relationship Viewer:**
1. Click  Setup.
2. From Setup, enter Custom Settings in the Quick Find box, then select Custom Settings.
3. Click the letter R to narrow down the list.
4. Click Manage next to Relationship Settings.
5. Click Edit.
6. In a separate browser, locate the ID for the Contact field in the Relationship Object:
- a. In the new browser tab, click Setup.
- b. Click the Object Manager tab.
- c. In the list of objects, click Relationship.
- d. Click Fields & Relationships.
- e. Click on Contact (Field Label column).
- f. Copy the Contact field unique Salesforce ID from the URL in your browser. Should be the ID beginning with 00N...
7. Go back to the tab you had with the Relationships Custom Settings.
8. Paste this Contact Field ID into BOTH the Relationship Name Field Id and Relationship Name Id Field Id fields.
9. Modify these IDs as follows:
- Relationship Name Field Id: Add the characters “CF” to the beginning of the ID.
- Relationship Name Id Field Id: Add the characters “CF” to the beginning of the ID and the characters “_lkid” to the end of the ID.
10. Click save.
<img width="892" alt="screen shot 2018-10-31 at 10 48 34 am" src="https://user-images.githubusercontent.com/37851761/47807944-8bc9e800-dcfa-11e8-9e6d-999629a3e244.png">

**Part 2: Use Classic and Lighting to attempt to add a new relationship via the Viewer:**

Working in Classic:
1. In Classic, create or locate a contact with at least one existing Relationship to another Contact.
2. Click on the Relationship Viewer button.
3. Hover over one of the Contacts and click the "Create New Relationship" option. 
4. Notice that the contact is auto-populated as expected.
<img width="1202" alt="screen shot 2018-10-31 at 10 41 08 am" src="https://user-images.githubusercontent.com/37851761/47807616-c7b07d80-dcf9-11e8-8ef4-851485065c7e.png">
<img width="1215" alt="screen shot 2018-10-31 at 10 42 42 am" src="https://user-images.githubusercontent.com/37851761/47807620-cb440480-dcf9-11e8-8873-51cc12d07ea3.png">

Not Working in Lightning:
1. In Lightning, create or locate a contact with at least one existing Relationship to another Contact.
2. Click on the Relationship Viewer Button.
3. Hover over one of the Contacts and click the "Create New Relationship" option. 
4. Notice that the contact is NOT auto-populated.
<img width="1066" alt="screen shot 2018-10-31 at 10 45 40 am" src="https://user-images.githubusercontent.com/37851761/47807771-2544ca00-dcfa-11e8-9348-c1ee96c8c59e.png">

@jesslopez-sf and I took a look at the code and our working hunch is that the the new lightning URL format is causing the issue within the code of the VF page.

**GitHub Code reference:** https://github.com/SalesforceFoundation/Cumulus/blob/master/src/pages/REL_RelationshipsViewer.page#L399-L408

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPA7QAM" target="_blank">W-029468</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
