### ISSUE TITLE
Multiple Tribute - Remove current notification recipient fields, change relationship to Opportunity to Lookup (Instead of Master Detail)

### ISSUE THREAD

**Issue by jbrandolinisf** [SalesforceFoundation/NPSP#3787]
Based on feedback from @njjc, we want to make the following changes to Multiple Tributes before incorporating them into NPSP:

- Remove Notification Recipient fields
- Change Opportunity Master Detail Relationship to Lookup
- Update code appropriately based on changes.  Note: additional query will be enforcing rules concerning the different tribute modes.  This was formerly relying on a rollup summary field, which will also be removed.

**Comment by jbrandolinisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPNfQAM" target="_blank">W-029636</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
