### ISSUE TITLE
Batch Data Import incorrectly matches Contact2 to Contact1 if Email matching selected and no email specified

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3820]
While there are other issues that are similar to this such as #3445, this is slightly different. 

**Issue:**
If Email Only is set as the Contact Matching Rule, and neither Contact1 or Contact2 has an email address specified, then BDI is creating Contact1, matching Contact2 to the record created in Contact1, and as a result the Donation is being applied to Contact2 rather than Contact1 (which was overwritten with the data in Contact2).

**Steps to Repeat**
1. Create BDI record: Contact1: Test1 LastName. Leave all other fields, including email blank; Contact2: Test2 LastName. All other fields blank. Donation Amount: $10; Donation Date: Today
2. Process record using Email Only matching.

**Expected Result**
Household with Test1 and Test2 LastName contacts created and donation attributed to Test1. With no email to match on, BDI should have defaulted to create new records and no matching performed.

**Actual Result**
Contact1 was created. However, Contact2 was matched to Contact1 that was just created, overwriting the name value (so only Test2 LastName survived). Therefore, the donation was attributed to that sole Contact in the Household account.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPhZQAU" target="_blank">W-029926</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
