### ISSUE TITLE
Inconsistent Scheduled Dates for Payments Created with Payment Wizard

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3848]
When I use the Schedule Payments button on an Opportunity's Payment Related List and the Close Date of my Opportunity is near the end of the month, my Scheduled Dates for future Payments may get off schedule. For example, if my Opportunity's Close Date is 11/30 and I do 12 payments on a monthly basis, it schedules the next few Payment Scheduled Dates on the 30th, then hits February and chooses February 28 (expected), but then maintains the 28th for all future Payment Scheduled Dates. I would expect it to use the original day. (We may need to employ something similar to how we handled this for Recurring Donations -- with Day of Month or Last Day of Month).

See screenshot:
![payment dates](https://user-images.githubusercontent.com/29731456/49319450-f6716d80-f4ca-11e8-8302-7cbc0853f96b.png)

**Steps to Repeat:**
1. Create a Contact (First name = Jess, Last Name = Lopez)
2. Create an Opportunity for that Contact (Name = Test, Amount = 12000, Stage = Closed Won, Account = Lopez Household, Close Date = 11/30/2018).
3. Go to the Payments related list and click the Schedule Payments button. 
4. Make sure you have the following (# of Payments = 12, Interval = 1 Month, Date of First Payment = 11/30/2018). Click the Calculate Payments button.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPxSQAU" target="_blank">W-030123</a>

**Comment by mbeaty-sf** [comment]
W-7783099

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlEvQAI&title=inconsistent-scheduled-dates-for-payments-created-with-payment-wizard) in the Trailblazer Community for updates.
