### ISSUE TITLE
Campaign Allocations not added to Opportunity if Campaign added after Opportunity is saved

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#3878]
[Thread](https://powerofus.force.com/0D58000003aZLNA)

Steps to repeat:

1. Create GAU
2. Create Active Campaign. Apply GAU Allocation to Campaign for 50%
3. Create Opportunity. Stage: Prospecting. Amount $50. Save
4. Edit Opportunity and select Campaign created above

Expected: Opportunity updated with GAU Allocation from Campaign
Actual: No Allocation added to Opportunity

Note: STR is specific for an Open Opportunity as it's expected that a Closed/Won Opportunity would not be edited in this way after the fact.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQExQAM" target="_blank">W-030336</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
