### ISSUE TITLE
Legacy Rollups Calculating Installments for Open-Ended Recurring Donations

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3902]
When Customizable Rollups were released, we made changes to how legacy rollups ran on open-ended Recurring Donations. In our documentation, we state that the Installments field is not used for Open-Ended, yet now it is calculated. This behavior is not only different from how it functioned in the past, but is also different from how Customizable Rollups function (i.e. in Customizable Rollups, we do not update this field and prevent new rollups from being created for that field). Is it possible to match the behavior between both rollup systems and revert legacy rollups so that they do not update the Installments field?

Within the RD_RecurringDonations class, we are checking if CRLPS are [enabled](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/RD_RecurringDonations.cls#L166), and then set the Installments in the [following block of code](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/RD_RecurringDonations.cls#L218-L222): 
```
if (isClosed == null && isWon == null && rd.npe03__open_ended_status__c == system.label.npe03.RecurringDonationOpenStatus) {
     rd.npe03__Installments__c = (integer) obj.get('oppcount');
     updateMap.put(rdid, rd);
}
```

**Steps to Repeat:**
_**Legacy Rollups**_
1. Verify that Customizable Rollups are not enabled in NPSP Settings --> Donations -->Customizable Rollups.
2. Create a Contact (First Name = Jess, Last Name = Lopez)
3. Create a Recurring Donation for that Contact (Name = RD Test 1, Contact = Jess Lopez, Amount = 10, Open Ended Status = Open, Date Established  = Today, Installment Period = Monthly). Hit Save.
4. The Installments field on the Recurring Donation record  is set to 12. 

_**Customizable Rollups**_
1. Go to NPSP Settings --> Donations -->Customizable Rollups and enable Customizable Rollups.
2. Create a Recurring Donation for the existing Contact (Name = RD Test 2, Contact = Jess Lopez, Amount = 25, Open Ended Status = Open, Date Established  = Today, Installment Period = Monthly). Hit Save.
3. The Installments field on the Recurring Donation record  is set to 1.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQKMQA2" target="_blank">W-030403</a>
