### ISSUE TITLE
Matching a Gift with no Amount throws an error

### ISSUE THREAD

**Issue by sam-knox** [SalesforceFoundation/NPSP#3951]
If an Opportunity with no Amount is selected using Find Matched Gifts, NPSP throws this error:

"**Attempt to de-reference a null object**
Error is in expression '{!saveAction}' in component <apex:commandButton> in component npsp:util_pageheader
Error is in expression '{!saveAndClose}' in component <apex:commandButton> in page npsp:mtch_findgifts: (npsp)"

**Steps to Reproduce**:

1. Create an Organization Account (Voonix, for example).
2. Create a Contact (Miles Davidson, for example).
3. Create an individual Opportunity (Donation) for Miles Davidson. Enter as Closed/Won but leave the Amount blank. Enter Voonix in the Matching Gift Account field and set Matching Gift Status to Submitted.
4. Create an Opportunity (Matching Gift) for Voonix. Enter as Closed/Won and any Amount such as $100.
5. On the Voonix Opportunity, click the Find Matched Gifts action.
6. Select the Miles Davidson gift and click Save.
7. An error is thrown.

I'm not sure that being able to match a gift that has no amount should be supported but there should at least be a friendly error.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQTYQA2" target="_blank">W-030517</a>

**Comment by mbeaty-sf** [comment]
W-7783098
