### ISSUE TITLE
Opportunities with Inactive Currency Cause Rollup Null Pointer Errors

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3952]
This is happening in both legacy rollups and Customizable Rollups. 

When rollups are run on Opportunities using an inactive Currency, they result in Null Pointer Exceptions (Attempt to de-reference a null object).

**Sample Stack Trace (legacy Rollups):**
```
System.NullPointerException: Attempt to de-reference a null object
Class.UTIL_CurrencyCache.getEffectiveExchangeRate: line 82, column 1
Class.UTIL_CurrencyConversion.getExchangeRate: line 73, column 1
Class.UTIL_CurrencyConversion.convertAmount: line 99, column 1
Class.UTIL_CurrencyConversion.convertAmountUsingStandardRates: line 129, column 1
Class.RLLP_OppRollup.updateRollupFromResult: line 826, column 1
Class.RLLP_OppRollup.rollupAccounts: line 277, column 1
Class.RLLP_OppAccRollup_BATCH.execute: line 75, column 1
```

**Sample Stack Trace (Customizable Rollups)**
```
System.NullPointerException: Attempt to de-reference a null object
Class.UTIL_CurrencyCache.getEffectiveExchangeRate: line 81, column 1 
Class.UTIL_CurrencyConversion.getExchangeRate: line 73, column 1
Class.UTIL_CurrencyConversion.convertAmount: line 99, column 1 
Class.CRLP_Operation_SVC.doRollupOperation: line 153, column 1 
Class.CRLP_RollupContact_SVC.processRollups: line 85, column 1 Class.CRLP_RollupProcessor_SVC.completeRollupForParent: line 303, column 1 Class.CRLP_RollupProcessor_SVC.startRollupProcess: line 115, column 1 
Class.CRLP_Batch_Base_NonSkew.execute: line 286, column 1
```

### Steps To Repeat

1. Setup → Company Information → Edit. Check off the Activate Multiple Currencies box.
2. Click the Currency Setup button
3. Add a new Active Currency with a Conversion Rate of 1 for AUD. (Keep USD as org default).
4. Create a new Contact (First Name = Jess, Last Name = AUD, Currency = USD)
5. Create an Opportunity (Name = Test One: AUD, Account Name = AUD Household, Amount = 100, Close Date = Today, Opportunity Currency = AUD, Stage = Closed Won)
6. Go to NPSP Settings → Bulk Data Processes and run the Rollup Donations Batch. As expected, there are no errors reported in the Error object. 
7. Now inactivate the AUD currency by going to Setup → Manage Currencies → Deactivate link next to AUD.
8. Go to NPSP Settings → Bulk Data Processes and run the Rollup Donations Batch. Now there are Attempt to De-Reference a Null Object errors in the RLLP_OppAccRollup_BATCH and RLLP_OppContactRollup_BATCH batches. Sample Stack Trace:
```
System.NullPointerException: Attempt to de-reference a null object
Class.UTIL_CurrencyCache.getEffectiveExchangeRate: line 82, column 1
Class.UTIL_CurrencyConversion.getExchangeRate: line 73, column 1
Class.UTIL_CurrencyConversion.convertAmount: line 99, column 1
Class.UTIL_CurrencyConversion.convertAmountUsingStandardRates: line 129, column 1
Class.RLLP_OppRollup.updateRollupFromResult: line 826, column 1
Class.RLLP_OppRollup.rollupAccounts: line 277, column 1
Class.RLLP_OppAccRollup_BATCH.execute: line 75, column 1
```

_**Enabling Customizable Rollups allows you to run the batch without errors on the batch page (however, they are added to the NPSP Errors object).**_

1. Enable Customizable Rollups in NPSP Settings → Donations → Customizable Rollups.
2. Go to NPSP Settings → Bulk Data Processes and run the Rollup Donations Batch. There are no errors reported on the batch page. However, if you look in the Error Log, you see an error with the following stack trace:
```
System.NullPointerException: Attempt to de-reference a null object
Class.UTIL_CurrencyCache.getEffectiveExchangeRate: line 81, column 1 
Class.UTIL_CurrencyConversion.getExchangeRate: line 73, column 1
Class.UTIL_CurrencyConversion.convertAmount: line 99, column 1 
Class.CRLP_Operation_SVC.doRollupOperation: line 153, column 1 
Class.CRLP_RollupContact_SVC.processRollups: line 85, column 1 Class.CRLP_RollupProcessor_SVC.completeRollupForParent: line 303, column 1 Class.CRLP_RollupProcessor_SVC.startRollupProcess: line 115, column 1 
Class.CRLP_Batch_Base_NonSkew.execute: line 286, column 1
```

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQTOQA2" target="_blank">W-030515</a>
