### ISSUE TITLE
NPSP Contact Merge Fails When Contact Object has more than 35 Child-to-Parent Relationship Fields

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3999]
When an org has more than 35 parent relationship Fields on their Contact object, they receive an error when using our Contact Merge feature:
`SOQL statements cannot query more than 35 different parent types`

By default, orgs can have up to 25 lookup relationships on an object, but when an org installs multiple managed packages that do not have a limit, this may result in more than 35 fields. Our code queries for all fields, so I'm not sure if there's any fix from an engineering perspective. But this may result in a Work Item for the Doc team to note this as a limitation on our Contact Merge page (https://powerofus.force.com/articles/Resource/NPSP-Merging-Contacts). 

**Workaround:**
Remove unneeded lookups from the Contact to get below the 35 limit.

**Relevant Resources**

- [Understanding Relationship Query Limitations](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_relationships_query_limits.htm)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQmaQAE" target="_blank">W-030753</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
