### ISSUE TITLE
BGE/BDI: When matching to a Payment/Opportunity, Opportunity Stage on updated Opportunity set to Closed Won regardless of user entry

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4005]
[Thread](https://powerofus.force.com/0D51E00004gHgcC)

Replicated in scratch org with 3.144 for BDI and 3.146 for BGE

**Issue:**

If a customer is using BDI or BGE to match a payment, they are unable to include Donation Stage to set a specific Closed/Won value for the updated opportunity.

**Steps to repeat:**

- Create Contact & Opportunity, $100, Closed Date = today Stage = Pledged
- Set up Batch, populate Contact Imported and Payment Imported to match to the above records
- on BDI record (or batch row), set Date = today, Amount = $100, Stage = Posted
- Process Batch with matching to Single match or create

**Expected Result**

Opportunity and Payment updated to paid, Stage = Posted

**Actual Result**

Opportunity and Payment updated to paid, Stage = Closed Won

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQrLQAU" target="_blank">W-030811</a>

**Comment by judisohn** [comment]
Note - on further testing it does not appear to be related to the NPSP Setting value. Closed Won is being set regardless, perhaps because it's the first Closed/Won stage encountered in the code? Issue title and description updated.

**Comment by judisohn** [comment]
Another [thread](https://powerofus.force.com/s/question/0D51E00004w6dwVSAQ/batch-gift-entry-why-is-stage-set-to-the-wrong-closedwon-value).

**Comment by mbeaty-sf** [comment]
Another thread https://powerofus.force.com/s/question/0D51E00005EFfn8SAD/npsp-data-import-mapping-incorrectly

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
