### ISSUE TITLE
Existing End Date Value on Former Affiliation is being overwritten when new Affiliation created

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#4017]
*[Thread](https://powerofus.force.com/0D51E00004gHbOZ)*

***Issue:***

In NPSP Version 3.146 we [fixed a bug](https://github.com/SalesforceFoundation/Cumulus/issues/3860) that was preventing proper updates to former Affiliation records when a new Affiliation record was created. As part of this fix, we are now using today's date to update the End Date field on the now "Former" Affiliation record. 

We've received a report in the Hub that this is causing trouble in a particular user story. When an End Date is known and added to an existing Current and Primary Affiliation record, it's being overwritten with today's date when a new Current and Primary Affiliation is created. 

***One particular use case:***

Let's say an affiliation exists for a membership for a PTA or similar. Let's say the child is moving from an elementary to a middle school. If a contact's stint on the PTA ended June 31st 2018, but the Organization didn't create a new Affiliation for the new middle school until September 2018, then the old elementary school affiliation's end date would reflect September, not June and the correct end date would be lost.

***Steps to Repeat:***

1. In an org with "Automatic Affiliation Management" enabled in NPSP Settings, create a new Contact record. 
2. Using the Organizational Affiliation related list, create a new Affiliation record with the following fields:
- Organization: Any non-household account
- Admin (not relevant for test)
- Start Date: Jan 1st, 2019 (or any date)
- End Date: Feb 28th, 2019 (or any date)
- Status: Current
- Primary: Checked ON

3. Create a second Affiliation record with the following fields:
- Organization: Any non-household account
- Admin (not relevant for test)
- Start Date: Jan 28th, 2019 (or any date)
- End Date: leave blank
- Status: Current
- Primary: Checked ON

4. On the Contact record, hover over the Organization Affiliation related list and note that the first Affiliation record created is now marked Former as desired, however the original known End Date value of Feb 28th has been overwritten by today's date. 

This results in data loss of the correct value. The original affiliation may have had an end date in the past or the future, but either way should not be overwritten with today's date.
Can we modify the process to not overwrite the End Date field unless it is Null?

<img width="1357" alt="screen shot 2019-01-25 at 8 43 00 am" src="https://user-images.githubusercontent.com/37851761/51761075-f2a03880-2080-11e9-803f-c4f20c5a1de9.png">
<img width="1354" alt="screen shot 2019-01-25 at 8 44 19 am" src="https://user-images.githubusercontent.com/37851761/51761077-f2a03880-2080-11e9-8f4d-0fb795a9b088.png">

**Comment by coriobriensfdo** [comment]
Lurch: Add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQzoQAE" target="_blank">W-030914</a>

**Comment by mbeaty-sf** [comment]
W-7783097
