### ISSUE TITLE
Schedule Payments Wizard: Null Pointer Exception for Advanced Currency Management Orgs

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4050]
This is happening in orgs where Advanced Currency Management is enabled and the Opportunity's Amount is null. Null Amounts do not throw Null Pointer Exceptions for orgs with standard multicurrency enabled or in single Currency orgs.

```
System.NullPointerException: Attempt to de-reference a null object
Class.npsp.PMT_PaymentCreator.getAmountOutstanding: line 438, column 1
Class.npsp.PMT_PaymentWizard_CTRL.getAmountOutstanding: line 506, column 1
Class.npsp.PMT_PaymentWizard_CTRL.SetupPaymentWizard: line 186, column 1
Class.npsp.PMT_PaymentWizard_CTRL.<init>: line 164, column 1
```

### Steps to Repeat:

The Schedule Payments page loads properly when there is a single currency and you have an Opportunity with a blank Amount.

1. Create new Contact (First Name = Jess; Last Name = Lopez)
2. Create new Opportunity with blank Amount (Name = Test 1, Account Name = Lopez Household, Close Date = today, Stage = Prospecting, Opportunity Currency = CAD).
3. Go to the Payments Related List and click the Schedule Payments button (if you're in a scratch org with unmanaged code, go to this link instead (after force.com in URL: /apex/PMT_PaymentWizard?id=006R000000UCX3mIAH&wtype=payment [where ID is YOUR Opportunity Id... not the one here).
4. The page loads successfully.

_Now enable Advanced MultiCurrency._
1. Go to Setup → Company Information and hit Edit.
2. Check the box next to “Activate Multiple Currencies” and save.
3. Click the Currency Setup button
4. Add new Currencies
    1. Currency Type = CAD - Canadian Dolar
    2. Conversion Rate = 1
    3. Decimal Places = 2
5. Click the Change Corporate button and switch to CAD.
6. Click the Enable button for Advanced Currency Management.
7. Create new Opportunity with blank Amount (Name = Test 2, Account Name = Lopez Household, Close Date = today, Stage = Prospecting, Opportunity Currency = CAD). 
8. Go to the Payments Related List and click the Schedule Payments button (if you're in a scratch org with unmanaged code, go to this link instead (after force.com in URL: /apex/PMT_PaymentWizard?id=006R000000UCX3mIAH&wtype=payment [where ID is YOUR Opportunity Id... not the one here).
9. The page displays a null pointer error.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007x7DEQAY" target="_blank">W-031278</a>

**Comment by mbeaty-sf** [comment]
W-7783093

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlElQAI&title=schedule-payments-wizard-null-pointer-exception-for-advanced-currency-management-orgs) in the Trailblazer Community for updates.
