### ISSUE TITLE
404 link in NPSP managed package

### ISSUE THREAD

**Issue by X3Cutor** [SalesforceFoundation/NPSP#4063]
Line 392 of visualforce page REL_RelationshipsViewer contains the following:
`infoText += '<a href=/apex/REL_RelationshipsViewer?id=' + currentContact.id + ' target="_parent" style="color: white; font-weight: bold;">[ {!JSINHTMLENCODE($Label.REL_RECenter)} ]</a><br />';`

This would need to be:
`infoText += '<a href=/apex/npsp__REL_RelationshipsViewer....`
in an org where NPSP is installed as a managed package, like a brand new trial of NPSP where I noticed this problem.

Clearly just changing the hard-coding isn't a solution, instead the url should be created using URLFOR:
https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_variables_functions.htm
or if that fails for some reason, in Apex with appropriate methods.

**Comment by force2b** [comment]
** lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LkwnQAC" target="_blank">W-031386</a>

**Comment by jamesbsfdc** [comment]
W-7783091

**Comment by jamesbsfdc** [comment]
[Another post about the issue](https://powerofus.force.com/s/question/0D51E00005eNUW7SAO/relationship-viewer-error)

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phnUQAQ&title=404-error-in-relationships-viewer-when-clicking-re-center-on-this-contact-link) in the Trailblazer Community for updates.
