### ISSUE TITLE
Customizable Rollups: Contact soft credits not updated when Opportunity is deleted

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4080]
_Reference case 21621743_

**Issue:** With customizable rollups enabled, if a Contact is receiving soft credit for a gift, and that gift is deleted, the batch job is not updating the Contact correctly. This behavior does not appear with legacy rollups.

**Steps to repeat:**

1. Enable legacy rollups
2. Create a Household Account with 2 Contacts, AA and BB
3. Create Opportunity for AA (BB should get automatic soft credit as Household Member)
4. Run Rollup Donations Batch and confirm that BB has soft credit in rollup fields
5. Delete the Opportunity
6. Run Rollup Donations Batch and confirm BB no longer has soft credit in rollup fields
7. Enable customizable rollups
8. Repeat steps 3-5

**Expected result:** BB should no longer have soft credit in rollup fields

**Actual result:** The soft credit values are not changed. One can 'Recalculate Rollups' on the Contact to update the values correctly. [Note that the rollup that populates the Contact's "Number of Soft Credits" field must be enabled and accurate for this to work].

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Ll6OQAS" target="_blank">W-031501</a>

**Comment by mbeaty-sf** [comment]
Related to https://github.com/SalesforceFoundation/NPSP/issues/4927

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.

**Comment by Jahmaal-Plative** [comment]
Could this resolution potentially be documented somewhere to make it easier to find for others?
