### ISSUE TITLE
NPSP Settings "Donations" section is not properly formatted

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#4096]
The NPSP Settings Donation section UI is misaligned and there are spaces between some of the section labels. 

<img width="298" alt="screen shot 2019-03-05 at 11 29 00 am" src="https://user-images.githubusercontent.com/37851761/53836587-3cfcbb00-3f45-11e9-8e32-9ff85b1bd28d.png">

Steps to Repo: 
1. Log into an org with NPSP installed
2. Click on NPSP Settings. 
3. Click on Donations, and notice sub-sections have gaps per image.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlL9QAK" target="_blank">W-031685</a>

**Comment by bethbrains** [comment]
Only appears this way when CRLPs are enabled. It's due to the outputlink tags not being entirely hidden when display:none is applied when CRLPs is enabled. It was until recently. This is almost certainly a core change in rendering. No changes have happened to this section of the code in 7 months.

**Comment by mbeaty-sf** [comment]
W-7782877

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phnKQAQ&title=npsp-settings-donations-section-is-not-properly-formatted) in the Trailblazer Community for updates.
