### ISSUE TITLE
Data Import: Campaign Source lookup ignored outside of Batch Gift Entry

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4156]
A common scenario in NPSP Data Import is to import Contacts and Campaign/Campaign Members without any related Opportunities. To do this, administrators need to populate the Campaign Name field on the NPSP Data Import record (and optionally, the Campaign Member Status field). In that case, when processed the Contact in Contact1 is added to the Campaign matched or created based on the name.

In 3.149, a new Donation Campaign Source lookup to Campaign was added to the NPSP Data Import object. This is meant to be used with Batch Gift Entry to match a gift to a specific Campaign in data entry.

This lookup field does not appear to be functional outside of Batch Gift Entry, which can lead to confusion if Administrators attempt to use the field in non-Opportunity contexts.

Steps to repeat:

1. Create an Active Campaign.
2. Create a NPSP Data Import record. Populate Contact1 First/Last Name. Populate Donation Campaign Source with the Campaign just created.
3. Process the record, using any Contact matching rule.

**Expected Result:**

The Contact should be created (or matched) and added to the new Campaign

**Actual Result:**

The Contact is created or matched. The Campaign is indicated as Matched by Id, but the Contact is not added to the Campaign. Note that Campaign Name on the NPSP Data Import object remains blank.

If Campaign Name is populated, the Contact is added to the Campaign as expected.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Lm8aQAC" target="_blank">W-032290</a>

**Comment by judisohn** [comment]
GUS [W-7781021](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008EI3oIAG/view)

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phnFQAQ&title=npsp-data-import-campaign-source-lookup-ignored-outside-of-batch-gift-entry) in the Trailblazer Community for updates.
