### ISSUE TITLE
BGE- Mass Dry Run not working on 50 or more DIs - Matching

### ISSUE THREAD

**Issue by cpose** [SalesforceFoundation/NPSP#4170]
Details
On BGE, when having at least 50 records and attempting to run Mass Dry Run, the following error message is displayed: 
"An internal server error has occurred Error ID: 2019138713-11960 (119852647)"

Preconditions:
1- Having a BGE batch
2- Having 50 or more Data Imports with data that match to an Opportunity
3- All Opps related to one Account.

Reproducing Steps
1- Create a batch
2- Upload 50 or more data imports related to that batch
3- Click on Mass Dry Run

Actual behavior:
An error message appears and dry run does not work
"CPU Time limit exceeded"
Log attached.

Expected behavior:
No error message is displayed and the Data Imports are matched with the opportunities

**Comment by cpose** [comment]
**lurch: attach W-032472

**Comment by melissabarber** [comment]
**lurch: attach W-032472

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LmNQQA0" target="_blank">W-032472</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
