### ISSUE TITLE
CRLP Help Text Bubble Cut Off by Window

### ISSUE THREAD

**Issue by melissabarber** [SalesforceFoundation/NPSP#4173]
When adding a filter rule with the In List or Not In List operator, the help text is cut off by the edge of the popup window. Found this issue in both Chrome and Firefox. 

<img width="660" alt="Screen Shot 2019-04-10 at 11 31 52 AM" src="https://user-images.githubusercontent.com/19452076/55970675-d732db80-5c34-11e9-93c6-c464483d3d77.png">

**Comment by melissabarber** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LmQoQAK" target="_blank">W-032510</a>

**Comment by mbeaty-sf** [comment]
W-7782878

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phn0QAA&title=customizable-rollups-help-text-bubble-cut-off-by-window) in the Trailblazer Community for updates.
