### ISSUE TITLE
Campaign Household Deduplication Batch Uses Fixed Batch Size of 2000

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4185]
An [Idea](https://powerofus.force.com/s/idea/a1W1E000006zY9VUAU/reduce-the-batch-size-of-the-campaign-household-deduplication-process) was submitted to reduce the batch size of the Campaign Household Deduplication batch. This is an option, along with adding a configurable batch size like we have for most of our other batches.

**Context**:
When a customer clicks on the Household Mailing List button on a Campaign where the NumberOfContacts value is greater than 10,000, it kicks off a batch Apex class called HH_CampaignDedupe_BATCH, with a batch size of 2000. If they encounter Apex CPU Timeout errors, they are unable to lower the batch size.

[HH_CampaignDedupeBTN_CTRL, Lines 170-179](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/HH_CampaignDedupeBTN_CTRL.cls#L170-L173)

```
private void MarkDuplicatesBatch(string strSoql) {
        HH_CampaignDedupe_BATCH batch = new HH_CampaignDedupe_BATCH(campaign.Id, strSoql);
        database.executeBatch(batch, 2000);                 
    }

```

**Comment by jesslopez-sf** [comment]
**lurch: attach W-032598

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LmXkQAK" target="_blank">W-032598</a>

**Comment by mbeaty-sf** [comment]
W-7781110

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phmvQAA&title=campaign-household-deduplication-batch-uses-fixed-batch-size-of-2000) in the Trailblazer Community for updates.
