### ISSUE TITLE
Customizable Rollups: Timeout Issues

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4231]
We continue to receive many reports of customers hitting false timeout errors when creating or editing Rollups or Filter Groups. In most cases, the deployment does eventually go through, but unless a customer goes to Setup --> Deployment Status, they may not know this and create duplicates. 

We attempted to resolve this by setting a higher timeout in Issue #3346  / W-025874.

The issue is sporadic in existing customer orgs, but I have also experienced it in brand new scratch orgs and trial orgs.

**Steps to Repeat (again, sporadic...)**

- Create a new Filter Group, Add a Filter Rule, Save.
- Modify a Filter Group by editing a Filter Rule, Save.
- Create a new Rollup, Save.
- Edit an existing Rollup, Save.

I will capture logs the next time I replicate. I will also add some of @force2b 's notes to the Work Item.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087ugdQAA" target="_blank">W-033047</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
