### ISSUE TITLE
Batch Gift Entry - Selecting a specific Payment or Opty in BGE grid does not result in match when the Do Not Match setting for overall batch match is used

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#4233]
[Hub Thread.](https://powerofus.force.com/s/question/0D51E00004pvlULSAY/batch-gift-entry-not-updating-pledges)

**Issue:**
When creating a new batch in Batch Gift Entry, you need to select a "Donation Matching Behavior" to advise the behaviour for locating existing records. The selection here applies to all of the gifts entered into the BGE Grid and processed. 
If "Do Not Match - No matching is attempted; New records are created" is selected, and a particular payment or Opty is selected to be updated during batch process, a new record is created instead of the selected one getting updated as expected.  

**Use case:**
Customer is importing 30 gifts. All but 2 of them they know should not even accidentally match to an existing gift, but for 2 records they know that they will match to an existing record. They select 'Do Not Match' as the matching behaviour, and then select the records for the 2 gifts only. Those match/update, and the rest the code doesn't even try and look at existing gifts.

**Steps to Reproduce:**

1. Create a Contact record of any name, and a Pledged Opportunity for $20.00. 
2. Ensure a Payment record is created, and not marked Paid. 
3. On Batch Gift Entry tab, click "New Batch".
4. Give batch any name, and click next (keep all defaults as is)
5. Keep all defaults as is on next screen and click Next. 
6. Keep all defaults as is on next screen and click Next. 
7. Under Donation Matching, select "Do Not Match - No matching is attempted; New records are created" from the Donation Matching Behaviour field.
8. Click Save.
9. On the New Gift interface screen, select the new contact.
10. In the "This donor has pending donations" area above, click the Review Donations link.
11. Select Update this Payment on the open payment you created earlier. 
12. Enter details in the rest of the New Gift, matching the values on the Payment ($20). 
13. Click Process Batch. 
14. Note that the unpaid payment is still unpaid and Opportunity is Pledged. 

Customers expect that if they can manually select a payment or Opty in the Grid while entering the new gift, it will be matched and updated when the batch is run. They won't think to go back and update the settings for the entire batch. 

**Feature Change Suggestion:**
The suggestion is to allow for manual record selection from within the grid to override the Donation Matching Behaviour for those gifts only. The rest of the batch will follow the behaviour indicated.

**Comment by coriobriensfdo** [comment]
**add: lurch

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uioQAA" target="_blank">W-033074</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
