### ISSUE TITLE
Opportunity Stage Not Updated If Automatic Payments Turned Off

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4244]
When Automatic Payment Creation is unchecked in NPSP Settings --> Donations --> Payments (ContactSettings.npe01__Payments_Enabled__c), the Opportunity Stage is not automatically updated if the Payment Amount Received is >= the Opportunity Amount. It *is* updated, however, if Advanced Currency Management is enabled in the org. The functionality should match in ACM vs. single currency orgs and we don't believe this functionality should be dependent on whether Automatic Payment *Creation* is enabled.

This was initially discovered by @annejackson and confirmed by CCE, with the additional note re: ACM. 

### High-level description:
When a Payment is edited, the PMT_Payment_TDTM class runs on both the Payment and the Opportunity. When it runs for the Opportunity, we call PMT_PaymentCreator and there is a check on line 158 to see if the auto-payment custom setting is checked off. The closeOpportunityIfAllPaymentsReceived() method runs on line 183, but because it's nested within the if() statement, it will only run if auto-payments are turned on. The payment logic is handled differently if ACM is enabled. Meaning that if ACM is enabled, we set the Opp Stage Name to the Closed Won value in that field regardless of whether auto-payments are turned on. This is because we handle the logic for that within the PMT_Payment_TDTM class, completely separately from non-ACM code). There are notes within the class that state that ACM wasn't working as expected, which is why presumably the logic for each currency scenario was in 2 different classes.

### Steps to Repeat

**(Single Currency - not working as expected)**
1. Uncheck Automatic Payment Creation in NPSP Settings --> Donations --> Payments.
2. Create a Contact (First Name = Jess; Last Name = Lopez)
3. Create an Opportunity (Name = Test 1, Amount  = 25, Account = Jess Lopez Household, Close Date = today)
4. Create a Payment (Opportunity = Test 1, Payment Amount = 25, Paid = true, Payment Date = today)
5. Refresh Opportunity page and confirm that Stage is *NOT* changed to Closed Won.

**Advanced MultiCurrency - working as expected**
1. Go to Setup--> Company info and activate multiple currencies
2. Click the Currency Setup button, activate Advanced Multicurrency.
3. Add an additional Currency, but keep the default currency as USD.
4. Create an Opportunity (Name = Test 2, Amount  = 100, Account = Jess Lopez Household, Close Date = today)
4. Create a Payment (Opportunity = Test 2, Payment Amount = 100, Paid = true, Payment Date = today)
5. Refresh Opportunity page and confirm that Stage *IS* changed to Closed Won.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uoIQAQ" target="_blank">W-033142</a>

**Comment by chicagojcb** [comment]
I have a client for whom this is pretty important.  I am writing a Process Builder to make a workaround, but is anyone going to be looking at this?

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)

**Comment by mbeaty-sf** [comment]
Bug addressed in above reference PR in NPSP release 3.180.
