### ISSUE TITLE
CRLP: GAU Rollups not updated if the last Allocation record for a GAU has been deleted

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/NPSP#4255]
GAU Rollups execute only in Skew Mode where the main object queried is the Allocation object. As a result, if there are no Allocation records for a GAU that had previously had Allocations records that were rolled up, the GAU will not be updated to change the rollup totals to zero/null after the last Allocation is deleted when the next nightly job is executed or when the [Run Batch] button is used in NPSP Settings.

This can affect other Skew Mode rollups as well, though this is unlikely. For example, it would extremely rare for a single Contact to go from having more than 250 related Soft Credit Opportunities to having zero attached Soft Credit Opportunities at once (in a single day).

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087us0QAA" target="_blank">W-033186</a>

**Comment by judisohn** [comment]
Updated bug: [W-8276496](https://gus.lightning.force.com/a07B0000008hQRkIAM)
