### ISSUE TITLE
BDI - Standard Number fields with scale of zero, taken as int. Illegal assignment error when mapped to custom number field.

### ISSUE THREAD

**Issue by cpose** [SalesforceFoundation/NPSP#4294]
Mapping a standard number field with a scale of zero (0 decimal places) to a custom number field in the DI object, is causing "Illegal assignment from Decimal to Integer" error when processing.

Some standard number fields with a scale of zero are stored internally as integers so despite the fact that the precision and scale are the same it actually is trying to map a double from the data import record to an integer on the target object.

Preconditions:
Standard number field in Account - "NumberOfEmployees" Number(8,0)
Custom number field in DataImport - mapped to Account1.NumberOfEmployees - Number(8,0)

Steps:
Create a DI record, and add a number in the mapped field 
Add rest of Account1 and Donation info
Process DI

Expected:
Number inputted in DI is correctly impacted in the mapped Account field

Actual:
DI fails when processed, "Illegal assignment from Decimal to Integer"

**Comment by cpose** [comment]
**lurch: attach W-033445

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vCjQAI" target="_blank">W-033445</a>

**Comment by mbeaty-sf** [comment]
W-7783061

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phmlQAA&title=npsp-data-import-standard-number-fields-with-scale-of-zero-throw-illegal-assignment-error-when-mapped-to-custom-number-fields) in the Trailblazer Community for updates.
