### ISSUE TITLE
Customizable Rollups: Account Best Year Total Not Correct in MultiCurrency Orgs

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4318]
Thank you to @annejackson  for finding this!

The currency of the Best Year Total field is not being converted properly on Accounts, but is on Contacts.
![Screen Shot 2019-06-13 at 4 24 35 PM](https://user-images.githubusercontent.com/29731456/59465096-18439980-8df8-11e9-82c4-ac7f019801f8.png)

### Steps to Repeat
1. Go to Setup --> Company Info --> Edit and activate multiple currencies.
2.  Click the Currency Setup box. Add CAD as a Currency with a Conversion Rate of 2 and Save. Click the Change Corporate button and set the corporate currency default to CAD and hit Save. (Your User will stay as USD).
3. Create a new Contact (FirstName = Jess, LastName = Lopez, Contact Currency = USD). The household Account is created with USD as its Currency.
4. Create an Opportunity (Name = 'Test 1', Account = Lopez Household,  Amount = 100, Currency = CAD, Close Date = today, Stage = Closed Won)
5. Go to the Account. You may need to refresh until rollup calculations go through. Most rollup fields are correct with USD 50. However, the Best Year Total shows USD 100.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vaWQAQ" target="_blank">W-033733</a>

**Comment by judisohn** [comment]
Thanks @annejackson!
