### ISSUE TITLE
If One-to-One Model is enabled, Customizable Rollups can't be disabled

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4341]
[Thread](https://powerofus.force.com/s/feed/0D51E00004sGRROSA4)

We now enable Customizable Rollups automatically for all new Trials. However, there are some customers who have a legitimate use case for the One-to-One model instead of the Household Account model. We do support this configuration and customers are made aware of what they're not getting if they use this model.

If the customer changes the Account Model in NPSP Settings from Household Account to One-to-One Individual before they disable Customizable Rollups, they will be unable to disable Customizable Rollups at all. 

![image](https://user-images.githubusercontent.com/4614343/60051558-43a07100-96a1-11e9-9ad8-e00e45348dc6.png)

Workaround is to change the model back to Household, then disable Customizable Rollups. 

Better user experience would be to automatically disable Customizable Rollups if One-to-One Individual or Individual Bucket models are selected.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C6lNQAS" target="_blank">W-034018</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
