### ISSUE TITLE
Relationship Viewer: non alphanumeric characters are displaying with unicode values

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4348]
[Thread.](https://powerofus.force.com/s/question/0D51E00004sH5CQ/when-looking-at-relationships-viewer-in-npsp-if-a-person-has-an-apostrophe-in-their-name-it-is-not-shown-osullivan-reads-as-follows-o39sullivan-can-anybody-help-with-this-is-there-a-fix)

Replicated in scratch org.

Contact 1: Judi Sohn
Contact 2: Cori O'Brien

Set up Relationship between the two. 

Relationship Viewer displays &#39 rather than the ' in O'Brien

![image](https://user-images.githubusercontent.com/4614343/60125564-0c41cb00-975a-11e9-8e18-c789a8fb2a63.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C6nxQAC" target="_blank">W-034051</a>

**Comment by coriobriensfdo** [comment]
LOL story of my life!

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
