### ISSUE TITLE
NPSP Settings Opportunity Name error if multiple rules set with the same criteria but different record types

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4349]
[Thread.](https://powerofus.force.com/s/question/0D51E00004urIusSAE/error-when-creating-multiple-opportunity-names)

Replicated in scratch org. 

This will happen any time 2 rules are saved with the same format in the same session, even if the Attributes and/or Record Types are different (which should allow for separate settings).

**Steps to repeat:**

1. Create Opportunity Naming Rule. Set Attribute to 'Both' - select a record type - use the built-in '{!Account.Name} {!Amount} {!RecordType.Name} {!CloseDate}' format. Save.
2. Immediately select 'New Opportunity Name' - Set Attribute to 'Both' - select a *different* record type - use the same '{!Account.Name} {!Amount} {!RecordType.Name} {!CloseDate}' format. Save.

**Result:**

```
Upsert failed. First exception on row 0; first error: FIELD_INTEGRITY_EXCEPTION, There is already an item in this list with the name 6/26/2019 8:36 AM: [Name]
Error is in expression '{!saveONS}' in component <apex:commandButton> in page stg_paneloppnaming: Class.STG_PanelOppNaming_CTRL.saveONS: line 126, column 1
```

**Workaround:**

If you click out of NPSP Settings and then reload (click NPSP Settings again), you can create the exact same Naming Rule that errored out previously without an error.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C6peQAC" target="_blank">W-034072</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
