### ISSUE TITLE
Opportunity Naming not updating on save if user language is not English

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4377]
[Thread.](https://powerofus.force.com/s/question/0D51E00004w9NTvSAM/opportunity-name-convention-not-firing-for-nonenglish-language-users)

Replicated in scratch org.

1. Create an Opportunity Naming Rule using a default rule such as `{!Contact.Name} {!Amount} {!RecordType.Name} {!CloseDate} {!npsp__Recurring_Donation_Installment_Name__c}` using a default date format such as `MM/dd/yyyy`
2. Create an Opportunity and confirm that naming rule is firing correctly
3. Edit your user record and change language from English to Spanish
4. Create an Opportunity

**Expected behavior**

Naming rule should fire. There are no translations enabled in the org (same behavior if Spanish is active).

**Actual behavior**

Naming rule does not fire, so Opportunity retains the name entered.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7ViQAK" target="_blank">W-034395</a>

**Comment by coriobriensfdo** [comment]
[Another thread.](https://powerofus.force.com/s/question/0D51E000051ow06SAA/not-mapping-currencyisocode-in-opportunities-when-recurring-donation-are-modified-any-ideas)
