### ISSUE TITLE
Opportunity Exclusion Settings for GAUs Missing in Customizable Rollups

### ISSUE THREAD

**Issue by sam-knox** [SalesforceFoundation/NPSP#4379]
[Thread.](https://powerofus.force.com/s/question/0D51E00004w9XZI/where-are-gau-allocations-rollup-settings-located?s1oid=00D00000000hWLM&s1nid=0DB800000004Fa7&emkind=chatterBestAnswerNotification&s1uid=0058000000E8FUM&emtm=1562867791809&fromEmail=1&s1ext=0)

The GAU Allocations Rollup settings `Excluded Opp RecTypes` and `Excluded Opp Types` aren't visible in NPSP Settings when Customizable Rollups are enabled. The on-screen help text for Default General Accounting Unit states that "When Default Allocations Enabled is selected, NPSP creates a GAU Allocation for all new Opportunities not excluded in GAU Allocations Rollup Settings, and assigns them to this General Accounting Unit." However the GAU settings are not visible so it's not possible to adjust them.

**Expected Behavior**
In an org with Customizable Rollups enabled, the `Excluded Opp RecTypes` and `Excluded Opp Types` settings in GAU Allocation settings are visible.

**Actual Behavior**
Setting aren't visible. Customers must disable Customizable Rollups in order to adjust them.

**Comment by sam-knox** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7VsQAK" target="_blank">W-034397</a>

**Comment by mbeaty-sf** [comment]
W-7783084

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phmWQAQ&title=opportunity-exclusion-settings-for-gaus-missing-in-customizable-rollups) in the Trailblazer Community for updates.
