### ISSUE TITLE
Customizable Rollups: Force Certain Records to run in Skew Mode

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4388]
We use key fields (i.e. _Total Number of Gifts_ on Account/Contact) to determine whether a record should be processed in the skew vs. non-skew version of our Customizable Rollups batch jobs. This works great in most cases, with the following exceptions:

**1. Account Soft Credits**
We use the Total Number of Gifts (i.e. # of Closed/Won Opportunities) to determine skew vs. non-skew mode because we have no packaged Account Soft Credit rollups/fields out of the box. However, a record may have thousands of Account Soft Credits but less than 250 Closed/Won Gifts. It would then be picked up in non-skew mode and likely hit heap size and other limits.

**2. If a customer modifies the attributes of a key field**
There is nothing preventing a customer from modifying (or disabling entirely) the Filter Group or Filter Rules associated with the key fields (Total Number of Gifts, for instance). I've seen several instances where these rollups have been modified, thereby producing a smaller value in the key field which then pulls the record into the non-skew mode. Again, this can cause heap size and other limits to be hit if the non-skew job then has to process a large volume of related records.

**3. Initial import of data into LDV org**
When large amounts of data are imported in an LDV org (or an org with data skew), our key fields determining skew vs. non-skew modes will be null until the first time the rollups jobs runs. As a result, we will attempt to calculate all records in non-skew mode and many records will never be updated and properly moved to skew mode unless they are identified through other means and backfilled manually to a value more than the skew mode threshold. 

----
I will link my full investigations and potential solutions to the Work Item.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7eQQAS" target="_blank">W-034484</a>

**Comment by jesslopez-sf** [comment]
W-7783082
