### ISSUE TITLE
Disabled Advanced MultiCurrency Feature is Incorrectly Seen as Active

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4450]
If a customer enables Advanced MultiCurrency in their org and then disables it, NPSP still thinks it is enabled based on how we determine if the feature is on. Several areas of our codebase (e.g. PMT_Payment_TDTM, PMT_PaymentCreator, etc.) call UTIL_Currency’s _isAdvancedCurrencyManagementEnabled()_ method to determine if ACM is enabled. If so, it may calculate things slightly differently or modify the Opportunity Stage when Fully Paid slightly different (this actually caused the order of execution to be different). 

This method checks to see if standard MultiCurrency is enabled by returning _UserInfo.isMultiCurrencyOrganization()_ and then checks for Advanced based on the following query:
`Integer DCRCount = Database.query('SELECT Id FROM DatedConversionRate LIMIT 1').size();
if (DCRCount == 1) {
     isACMEnabled = true;
}`

The issue is that there are still records stored in **DatedConversionRate** even after disabling Advanced MultiCurrency completely. 

The Work Item will link to my full investigation and scenarios when this may be an issue.

### Steps To Repeat

**Setup**

1. Go to Setup → Company Information and hit Edit.
2. Check off the Enable Multiple Currencies box and hit Save.
3. Click the *Currency Setup* button.
4. Create a new Active Currency (Currency Type = CAD; Conversion Rate = 2; hit Save).
5. Open the Dev Console and run the following query in the Query Editor:
`    SELECT Id FROM DatedConversionRate
`
6. Confirm that 0 records were returned.

**Correct Behavior:**

1. On the Manage Currencies page in Setup, click the Enable button in the Advanced Currency Management section. In the pop-up window, check the “*Yes, I want to enable Advanced Currency Management.” *and click the Enable button.
2. Open the Dev Console and run the following query in the Query Editor:
    `SELECT Id FROM DatedConversionRate`
3. Confirm that 2 records were returned.

**Issue:**

1. Now disable Advanced Currency Management by clicking the Disable button on the Advanced Currency Management section of the Manage Currencies page. Click the box next to *“Yes, I want to disable Advanced Currency Management“ *and hit the Disable button.
2. Open the Dev Console and run the following query in the Query Editor:
`    SELECT Id FROM DatedConversionRate
`
3. Confirm that 2 records were returned.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C8S9QAK" target="_blank">W-034856</a>

**Comment by mpusto** [comment]
This is a known Salesforce issue: https://success.salesforce.com/issues_view?id=a1p3A0000017yARQAY

**Comment by mbeaty-sf** [comment]
As mentioned above, this is a Known Issue, please follow this link and click "This Affects Me" to get updates on changes to this issue in the future:

https://success.salesforce.com/issues_view?id=a1p3A0000017yARQAY
