### ISSUE TITLE
Update Opportunity amount if total of paid Payments differs from current Opportunity amount (Finalized Opp part 1)

### ISSUE THREAD

**Issue by vmartinov-sforg** [SalesforceFoundation/NPSP#4461]

**Comment by vmartinov-sforg** [comment]
**lurch: attach W-033110

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uliQAA" target="_blank">W-033110</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
