### ISSUE TITLE
Customizable Rollups: Years Ago Rollup Fields are not Calculating Properly when not using Opps: Won (HC) Filter Group

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4500]
Customizable Rollup using Years Ago > Last Year timeframe causes calculation to result in 1 if even if more than 1 Opportunity fulfilling the Filter Group criteria are present.

Tests to recreate validate in scratch org, with 3 Closed/Won Opportunities associated to test Contact:

1. No Filter Group - Rollup value = 1
2. Opps: Won (HC) Filter Group - Rollup value = 3
3. _(Cloned)_ Opps: Won (HC) Filter Group - Rollup value = 1 
4. _(Recreated Manually)_ Opps: Won (HC) Filter Group - Rollup value = 1

### Steps to Recreate

1. Create number field on Contact Object as Rollup target

2. Enable Customizable Rollups in NPSP Settings > Donations > Customizable Rollups

3. Create a Contact

4. Create 3 Opportunities with:
i. Close Date in between 01/01/2018 and 12/31/2018
ii. Stage = Closed/Won
iii. Amount = $100

### Rollup Tests

1. Create a Rollup on Contact:
i. Target field - The number field created on the Contact in the previous step
ii. Active = True
iii. Operation = Count
iv. Use Fiscal Year = False
v. Time Frame = Years Ago
vi. Years Ago = Last Year
vii. Rollup Type = Opportunity > Contact (Hard Credit)
viii. Filter Group = Opps: Won (HC)
ix. Date Field = Opportunity: Close Date

Start with the Rollup using "Opps: Won (HC)" Filter Group, and compare by swapping Filter Group and using "Recalculate Rollups" on the test Contact record. As stated above, testing with these Filter Groups on that Rollup should result in the following Rollup values:

1. No Filter Group - Rollup value = 1
2. Opps: Won (HC) Filter Group - Rollup value = 3
3. _Cloned_ Opps: Won (HC) Filter Group - Rollup value = 1
4. _Recreated Manually_ Opps: Won (HC) Filter Group - Rollup value = 1

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9CTQA0" target="_blank">W-035212</a>

**Comment by mbeaty-sf** [comment]
Relates to previous issue - https://github.com/SalesforceFoundation/Cumulus/issues/3988
Hub Post raising issue - https://powerofus.force.com/s/question/0D51E00004ySM7XSAW/troubleshooting-customizable-rollup-with-custom-filter-group

**Comment by coriobriensfdo** [comment]
[Additional Hub Thread](https://powerofus.force.com/s/question/0D51E00005B8mtCSAR/general-accounting-unit-rollups-filtering-by-year)

**Comment by coriobriensfdo** [comment]
[Another Hub Thread](https://powerofus.force.com/s/question/0D51E00005B9ic2SAB/customizable-rollup-not-calculating-as-expected)
