### ISSUE TITLE
Payment mapping can cause error in Payment Wizard

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4539]
_This issue relates to a previous issue (https://github.com/SalesforceFoundation/Cumulus/issues/1966)_ 

In Opportunity Payment Mappings, creating a mapping with a field that the payment wizard (Schedule Payments / Write Off Payments) uses, causes and error when attempting to access either of those payment wizards.

Creating a Payment Mapping with the field npe01__Number_of_Payments__c causes the following error when trying to access the payment wizard pages.

**duplicate field selected: npe01__Number_of_Payments__c** 
An unexpected error has occurred. Your solution provider has been notified. (npsp)

**Steps to replicate**

1. Create a custom field on on the Payment Object to link to the Payment Mapping in next step
2. NPSP Settings > Donations > Payment Mappings
3. Select "Number of Payments" as the Opportunity field, map it to the Payment field from Step 1, and create the custom mapping
4. Find or create an Opportunity record
5. Under the "Payments" related list, try selecting either "Schedule Payments" or "Write Off Payments" 
6. Error message should display:
- **duplicate field selected: npe01__Number_of_Payments__c** 
An unexpected error has occurred. Your development organization has been notified.

Removing the Payment Mapping will allow for the proper loading of those 2 payment wizard visualforce pages. This issue only seems to arise when a Payment Mapping is created for a field that is referenced in either of the two Visualforce pages, "Schedule Payments" or "Write Off Payments"

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CA2iQAG" target="_blank">W-035620</a>

**Comment by coriobriensfdo** [comment]
Related [Hub Thread](https://powerofus.force.com/s/question/0D51E00004zMSx5SAG/github-payment-mapping-can-cause-error-in-payment-wizard-and-opportunity-creation-1966).

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
