### ISSUE TITLE
Recurring Donation - Opportunity Naming not Updating Correctly with Next Donation Date Change

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4555]
**Issue**

Updating the field `npe03__Next_Payment_Date__c` (Next Donation Date) on a Recurring Donation record does not properly update the related Opportunity names, as defined by the NPSP Settings, when it includes {!CloseDate}. While it does update the Opportunity Close Date field, it appears that the trigger updating the related Opportunity names is updating the names _BeforeUpdate_, and subsequently pulling the previous value, not the updated value, into the naming from the Close Date field.

**Steps to Repeat**

1. Ensure that Opportunity Naming convention is setup via NPSP Settings > Donations > Opportunity Names, and that it includes "Close Date"
   1. _Example:_ {!Contact.Name} {!Amount} {!RecordType.Name} **{!CloseDate}** {!Recurring_Donation_Installment_Name__c}
1. Create a Recurring Donation record with `npe03__Next_Payment_Date__c` (Next Donation Date) populated.
1. Related Opportunities should reflect, in their name, the same date as the Close Date field, as expected
1. On the same Recurring Donation record, update the `npe03__Next_Payment_Date__c` (Next Donation Date) field to a date in the future.
1. Related Opportunities' Close Dates will update to reflect the change of the value from Next Donation Date; however, Opportunity name will show the Close Date from prior to the change.
1. Update the Recurring Donation `npe03__Next_Payment_Date__c` (Next Donation Date) again to see the change reflect once more: Opportunity name will show the Close date prior to the change, and the Opportunity Close Date will show the correct value associated with the Recurring Donation Next Donation Date

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CA7dQAG" target="_blank">W-035656</a>

**Comment by djtsystems** [comment]
As of latest 3.191 release around Jan. 31st, 2021, Auto Naming now fails for new opportunities whether created from scratch or cloned from an existing Opportunity.

Also, Form Assembly submitted data for creating Recurring Donations auto-names the 1st Installment incorrectly but names the additional installments as expected. This is Legacy and not Enhanced where I'm experiencing this. 

Nonprofit Success Package in Production shows a last modified Jan. 27th
NPSP in Sandbox from Jan. 5th shows last modified Jan. 21st

In my Sandbox auto-naming is still working. With no other Salesforce work around Opportunity naming on my side, I suspect a recent update broke the auto-naming in Production.

**Comment by jamesbsfdc** [comment]
Hi Deron, we don't provide support via GitHub issues. 

Please could you post about this in the Power of Us Hub? Feel free to @message me.

**Comment by mbeaty-sf** [comment]
W-7782875

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
