### ISSUE TITLE
Advanced Data Mapping ugly error if My Domain not enabled

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4590]
In an instance without My Domain configured, NPSP Settings appears to allow the enablement of Advanced Data Mapping, however attempting to enable ends in this not-so-friendly error:

![image](https://user-images.githubusercontent.com/4614343/64888795-de25a600-d639-11e9-90c5-37cfa12be868.png)

Enabling and deploying My Domain resolves the error.

Suggest editing the text on the Advanced Mapping page to remind user that My Domain is required (especially if not already deployed?)

**Comment by judisohn** [comment]
**lurch: add

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
