### ISSUE TITLE
BGE - Firefox - Persistent Unparseable number error message if autofill is used on Donation Amount field

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4593]
If autofill is used on BGE entry form for number/currency fields then persistent Unparseable error displays at the top.

By default, browsers have an autofill functionality which allows for previously inputted values such as passwords to be stored and reused from a list which displays when the user uses a field. For Chrome we are not allowing those values to be taken on the Donation Amount field as you can see in the attached video. Firefox on the other hand, allows the user to select one of these values, renders it as a string, displays $NaN and if they hit the Save button a persistent error message will be displayed like the one in the attached image, which cant be closed, forcing them to refresh the page to get rid of it.

Pre-conditions
1- being in bge
2- having previously added an import to the data table with any valid value on donation amount

Steps to reproduce:
1- input necessary values on the entry form and select the value from preconditions through the autofill list displayed below Donation Amount
2- Once the value is displayed as $NaN, hit save

Expected result:
When selecting the value from the autofill list, the behavior should mirror the behavior we implemented for Chrome. The value will be ignored and no value will populate the field

Actual result:
Persistent unparseable number error message is displayed and user is forced to refresh the page

![Screen Shot 2019-06-14 at 11 15 27 AM](https://user-images.githubusercontent.com/37851761/65359534-a8406e80-dbb1-11e9-8474-1b563ab0b332.png)

Additional details can be found on WI.

Updated by CCE - CO

**Comment by JavierFerreira** [comment]
**lurch: add W-033749

**Comment by coriobriensfdo** [comment]
**lurch: attach W-033749

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vc3QAA" target="_blank">W-033749</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
