### ISSUE TITLE
BDI - Field names starting with an integer and then followed by a space will return an error during field mapping

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4594]
Field names starting with an integer and then followed by a space will return an error during field mapping due to the Integer being considered as a namespace by the platform. 

Certain field names starting with an integer and followed by a separation will cause the API to take that first integer as a namespace. For instance, a field label starting with 1-2 or 1/2, Salesforce will append an X since it begins with an integer and the symbol will be considered a space, so the Field name will actually be X1_2. This causes the field APi to be considered as ‘1_2_xxxxxx’ , which causes the 1 to be seen as a namespace by the platform.
These fields will return an error and the field mapping doesnt get created (see img).

Pre-conditions:
1- Having a field following the syntax from above
Steps:
1- Access the mapping UI
2- Click on your object group
3- Click on new field mapping
4- Use your field from preconditions to create a mapping
Result:
Error from image
![Screen Shot 2019-09-10 at 4 16 13 PM](https://user-images.githubusercontent.com/37851761/65359706-30267880-dbb2-11e9-9e72-bd8f1c8e5da9.png)

Additional details can be found on the WI.

Edited by CCE - CO

**Comment by JavierFerreira** [comment]
**lurch: attach W-035945

**Comment by coriobriensfdo** [comment]
**lurch: attach W-035945

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAbEQAW" target="_blank">W-035945</a>

**Comment by mbeaty-sf** [comment]
W-7783064
