### ISSUE TITLE
BDI - Error creating record message when clicking new/save

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4595]
An 'error id - null' error message will intermittently display on packaged orgs after clicking on New in order to create a DI. Seems to only be reproducible if AM is enabled on the org.

Intermittently, on Beta Builds, clicking on Save to create a DI or clicking on New to open the form will return the error from the image. Its very hard to reproduce and the steps aren’t all that reliable, but it seems to be showing when inputting values on fields from an additional object mapped through the Advanced Mapping UI and Saving.
Sometimes it will throw the error on Save, and sometimes it will error when clicking new after creating a DI

Pre-conditions:
- Advanced Mapping enabled
- Object mapping created for an additional object

Steps:
1- Create a new DI and input values on fields for additional object
2- Click Save in order to save your DI
3- Click on New to create a new DI
Expected result:
No error is shown and DI form opens correctly always

Actual result:
Platform will sometimes return the error from image when clicking Save or New

![Screen Shot 2019-08-20 at 10 14 28 AM](https://user-images.githubusercontent.com/37851761/65359898-c5c20800-dbb2-11e9-8680-55c87f00c63b.png)

Additional details in WI

Edited by CCE - CO

**Comment by JavierFerreira** [comment]
**lurch: attach W-035569

**Comment by coriobriensfdo** [comment]
**lurch: attach W-035569

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9u0QAC" target="_blank">W-035569</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
