### ISSUE TITLE
BDI - Help text mapping with a valid core object prefix with an invalid field name will return an error when processing

### ISSUE THREAD

**Issue by Lucia-Juarez** [SalesforceFoundation/NPSP#4596]
If an invalid helptext mapping is created, the DIs fail to process even if that field is not used. 

Having a help text mapping with a valid core object prefix such as Opportunity or Payment, but an invalid field name, BDI will return an error when processing a DI, even if the field isn’t being used in your DI. The error from that failing DI is appearing on every other DI on batch 
 
Pre-conditions: 
- Having an invalid help text mapping 
 
Steps: 
1- Create a new DI 
2- Save 
3- Attempt to process 
 
Expected result: Before, we were letting the DI process with no errors but the value wasn’t being mapped due to the invalid help text mapping 
 
Actual result: Unfriendly error from image, DIs fail in batch and the error is added to other DIs in batch.

![Screen Shot 2019-08-30 at 5 33 46 PM](https://user-images.githubusercontent.com/37851761/65360058-48e35e00-dbb3-11e9-8168-f9f78c4c3052.png)

Edited by CCE - CO

**Comment by Lucia-Juarez** [comment]
**lurch: attach W-035654

**Comment by coriobriensfdo** [comment]
**lurch: attach W-035654

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CA7TQAW" target="_blank">W-035654</a>

**Comment by judisohn** [comment]
Closed as help text mapping has been deprecated in favor of Advanced Mapping.
