### ISSUE TITLE
BDI “Attempt to de-reference null object” error on a valid negative scenario, it's preventing valid Data Import records from processing

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4597]
" Attempt to de-reference null object' errors are persisting through to subsequent DIs

If a DI processing fails with “Attempt to de-reference null object” because it has data from an already deleted field (this is expected). All the following DIs with valid data fail with the same message (not expected), even if the failed DI is deleted from the list view. This makes the DI functionality unusable from that point onwards.

Pre-Conditions:
Advanced Mapping should be enabled when starting.
Have a custom field mapped through UI

Steps to reproduce:
1- Create a DI with data on the field from precondition (but don’t process the DI yet)
2- Go to CMT and delete the field mapping for the field on step 1
3- Go to Object Manager and delete the field from the Data Import Object
4- Go to NPSP Data import again, choose All from list view and start Import process with “Single Match or create”. This will give “Attempt to de-reference null object” but it is expected.
5- Go back to DI list view and delete the failed DI.
7- Refresh the page and proceed to create a new DI with valid information (the field from the previous steps is no longer present on the DI object).
8- Process the DI that has all valid data.
Expected Result: The new DI with valid data should be processed correctly without any issue.
Actual result: New DI fails with message “attempt to de-reference null object” even if all the data entered is valid.

**Comment by JavierFerreira** [comment]
**lurch: attach W-035485

**Comment by coriobriensfdo** [comment]
**lurch: attach W-035485

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9koQAC" target="_blank">W-035485</a>

**Comment by mbeaty-sf** [comment]
W-7783066

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phmMQAQ&title=npsp-data-import-attempt-to-de-reference-null-object-error-persists-to-valid-records) in the Trailblazer Community for updates.
