### ISSUE TITLE
BDI - Advanced Mapping: Two fields can be mapped to the same field on a target object

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4599]
If two fields on DI pointing to a same field on a target object, the DI is processed with data filled on both fields which have the same target, but the data is getting copied over to the target field belonging to whichever duplicate mapping was created last. The DI is processed correctly but whatever data the user inputs on the first created mapping is lost.

Migration utility is not validating if a help text mapping to migrate uses a target field already used through UI mapping. This lets the user have two field mappings that point to the same target field after turning CMT on again, which should not be possible. 

Pre-Conditions:
Advanced Mapping should be enabled when starting

Steps to reproduce:
1- Map a field from a Core object through UI
2- Copy the api from that field, and turn CMT off
3- Go to another field on DI that’s not used on step 1 and make a help text mapping with the api copied as target field.
4- Turn on CMT again.
Expected Result: 
User should not be able to have 2 field mappings for the same target field
Actual result: 
The help text mapping is still migrated even when the target field is already being used on a UI mapping. Which leaves the user with 2 mappings for the same target field.

Additional details on the WI

Edited by CCE - CO

**Comment by JavierFerreira** [comment]
**lurch: attach W-035025

**Comment by coriobriensfdo** [comment]
**lurch: attach W-035025

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C8phQAC" target="_blank">W-035025</a>

**Comment by mbeaty-sf** [comment]
W-7783067
