### ISSUE TITLE
BDI - Double clicking on certain parts of the Advanced mapping toggle screen will enable/disable the toggle (FIREFOX Only)

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4600]
You can currently click on certain surrounding sections of the AM toggle page and enable/disable the toggle on Firefox.

Double clicking anywhere in the area from the image will enable/disable the toggle for Advanced Mapping
Pre-conditions:
1- Being on the cmt toggle page
Steps:
1- Double click anywhere on the area from the image
Expected result:
Toggle only works if pressing on the actual toggle
Actual:
Double clicking anywhere on that area will toggle it

Additional details on WI

Edited by CCE - CO

**Comment by JavierFerreira** [comment]
**lurch: attach W-035860

**Comment by coriobriensfdo** [comment]
**lurch: attach W-035860

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAQVQA4" target="_blank">W-035860</a>

**Comment by ameyersalesforce** [comment]
Nevering - edge case
