### ISSUE TITLE
BDI: When Donation Matching Rules total character limit of 255 is exceeded you can't create batch 

### ISSUE THREAD

**Issue by Lucia-Juarez** [SalesforceFoundation/NPSP#4601]
If joined characters for all fields set for matching rules add up to more than 255 an error is displayed.

The "Donation Matching Rule" field is currently limited to a length of 255 characters due to its data type being “Text”. 
This limits the user when creating batches that use an amount of fields that surpasses the established 255 length character limit.
 
Steps to reproduce:
 
1- Open the Wizard from the Batch Gift Entry page.
2- Enter the mandatory and click next.
3- Click next.
4- Click next.
5- Add all available fields under “Donation Matching Rule”.
6- Save.
 
 
Expected results:
The site allows the user to save their progress and create the batch.
 
Actual results:
Save button becomes unresponsive and no error is displayed. The user cant finish creating the batch.
Additional details in WI

Edited by CCE - CO

**Comment by Lucia-Juarez** [comment]
**lurch: attach W-029955

**Comment by coriobriensfdo** [comment]
**lurch: attach W-029955

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPjuQAE" target="_blank">W-029955</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
