### ISSUE TITLE
BDI - Advanced Mapping: Help text mapping using other symbols ( : , =, @, etc) will convert to Advanced Mapping without error

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4602]
Special characters are currently being considered as valid by our migration utility when migrating into AM.

Pre-Conditions: Org should be prerelease with Winter20 and CMT should be off.
Steps to reproduce:
1- Create a Helptext mapping with a valid Object and field relationship, but instead of a dot between the object and field enter another symbol.
2- Turn CMT on.
Expected Result: Helptext should only work and be migrated using a dot between the Object and the field. And if helptexts are  created using these symbols, when CMT is enabled these should appear on Migration error table.
Actual Result: Helptexts using various symbols including :, =, @, etc are migrated when CMT is enabled without any error shown.

**Comment by JavierFerreira** [comment]
**lurch: attach W-035854

**Comment by coriobriensfdo** [comment]
**lurch: attach W-035854

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAQ1QAO" target="_blank">W-035854</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
