### ISSUE TITLE
Winter 20 Pre-release - BGE UX - Design of entry form displaying with bad spacing between label and fields.

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4604]
Multi-picklists and picklists are currently causing layout issues with the entry form on BGE(Winter 20' orgs).

Pre-Conditions: Org should be prerelease with Winter20

Steps to reproduce:
1- Go to Batch Gift Entry and create a batch that includes a picklist field.
2- Verify layout on entry form and separation between the labels and the fields.

Expected Result: Previous to this pre-release all the fields had a short distance between the label and the field, and it was the same for all types (see image 1 attached).

Actual Result: Only picklist fields show the same distance as previous versions between the label and the field itself. All other types currently have a much bigger separation. (see image 2 attached).

Actual:
![Screen Shot 2019-09-06 at 4 59 10 PM](https://user-images.githubusercontent.com/37851761/65361326-05d7b980-dbb8-11e9-8171-79a853b3b8c4.png)

Expected:
![Screen Shot 2019-09-06 at 4 57 40 PM](https://user-images.githubusercontent.com/37851761/65361330-096b4080-dbb8-11e9-8bae-7d79a386369c.png)

**Comment by JavierFerreira** [comment]
**lurch: attach W-035858

**Comment by coriobriensfdo** [comment]
**lurch: attach W-035858

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAQLQA4" target="_blank">W-035858</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
