### ISSUE TITLE
BGE Grid - "Maximum SOQL offset allowed is 2000" error on batches larger than 2000

### ISSUE THREAD

**Issue by JavierFerreira** [SalesforceFoundation/NPSP#4608]
We are currently experiencing an error message in batches with 2100 records or more, which is being shown to the user when attempting to scroll past this number in the data table.

The error message reads: "Maximum SOQL offset allowed is 2000" and blocks the user from scrolling past the 2100th record.

**Comment by JavierFerreira** [comment]
**lurch: attach W-031170

**Comment by coriobriensfdo** [comment]
**lurch: attach W-031170

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fRKSQA2" target="_blank">W-031170</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
