### ISSUE TITLE
BGE - Row level error persisting through inline editing

### ISSUE THREAD

**Issue by Lucia-Juarez** [SalesforceFoundation/NPSP#4609]
If a row on BGE has an error and it is edited to meet expected value, the error message on the row persists.

Getting the row level error “matched against multiple opportunities” after attempting to match will make this particular DI unusable since inline editing will keep returning the same error after processing.

Pre-conditions:
- Having an Account or Contact with two opportunities which have unpaid payments, same donation amount and same donation date
- Being in BGE
- Set donation matching behaviour to Single match or create

Steps to reproduce:
- Attempt to match using the data from pre-conditions
- Once the “Matched to multiple opportunities..” error is displayed attempt inline editing and change the Donation amount and/or Donation Date to something that doesnt match anything in the account/contact
- Process the batch

Expected result:
After processing a new Oppty should be created for that Account/Contact with the information from inline editing the row

Actual result:
Processing fails, no new Oppty is created and the same error is displayed

Additional detail in WI

Edited by CCE - CO

**Comment by Lucia-Juarez** [comment]
**lurch: attach W-032086

**Comment by coriobriensfdo** [comment]
**lurch: attach W-032086

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlryQAC" target="_blank">W-032086</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
