### ISSUE TITLE
BGE Wizard - Scrolling is broken for firefox

### ISSUE THREAD

**Issue by Lucia-Juarez** [SalesforceFoundation/NPSP#4610]
Unable to scroll on BGE wizard if browser being used is Mozilla Firefox.

Scrolling for firefox is currently broken on all stages of the wizard. Scrolling to the bottom will cause the side scrolling bar to be “stuck” and wont allow users to scroll back up
 
Pre-conditions:
-Being in BGE
 
Steps to reproduce:
1- Open any batch or hit New Batch
2- Access the wizard through Edit Batch or New Batch
3- Use the scroll bar to go to the bottom
4- Try scrolling back up
 
Expected result:
Scroll bar moves up and down no issues
 
Actual Result:
Scroll bar gets stuck at the bottom

Additional detail in WI

Edited by CCE - CO

**Comment by Lucia-Juarez** [comment]
**lurch: attach W-031972

**Comment by coriobriensfdo** [comment]
**lurch: attach W-031972

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Lli8QAC" target="_blank">W-031972</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
