### ISSUE TITLE
BGE Wizard - Fields can be put above Donation Date in sorting

### ISSUE THREAD

**Issue by Lucia-Juarez** [SalesforceFoundation/NPSP#4611]
Donation Amount and Donation date fields should be above all the other fields and the order for  them should not be editable. 
But currently when sorting, fields can be put above donation date on BGE wizard.

**Pre-requisites:**
1- Enter BGE Wizard
 
**Steps to reproduce:**
1- Access the BGE wizard
2- Move to the Select Fields stage
3- Add a field from available to selected fields
4- Use the sorting arrows to move the field upwards
 
**Expected result:**
Order of the fields is maintained for Donation Amount and Donation Date. The added field will show up third in order for the grid, after those two fields
 
**Actual result:**
The added field is not visually moved between Donation amount and Donation date but you can see the order change in the grid

Edited by CCE: MB

**Comment by Lucia-Juarez** [comment]
**lurch: attach W-031419

**Comment by mbeaty-sf** [comment]
**lurch: attach W-031419

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LkzSQAS" target="_blank">W-031419</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
