### ISSUE TITLE
Multi-Line Addresses on Contact Insertion Result in Unnecessary Account Update

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4614]
In the NPSP 3.157 release, we optimized DML operations around Contact with Address insertions. However, Contacts with multi-line Street Addresses are still causing an unnecessary Account update. As a result, the Order of Execution for Contacts with Single-Line Addresses vs. Multi-Line Addresses is different and may cause unexpected results.

When we do a comparison in [ADDR_Addresses_TDTM](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/ADDR_Addresses_TDTM.cls) to determine if we need to refresh the Household Account's Address, we check to see if the Billing Street value is equal to the Address record's concatenated Mailing Street 1 and 2 fields. Even though they theoretically match, Apex is not seeing it that way, so we unnecessarily do another update to the Account... 

**_My full analysis of the order of execution and potential fix will be linked on our internal Work Item._**

Single-Line:
![Screen Shot 2019-09-17 at 6 55 36 PM](https://user-images.githubusercontent.com/29731456/65188358-3abf0180-da3c-11e9-946d-d7e0c16c5f30.png)

Multi-Line:
![Screen Shot 2019-09-17 at 6 52 27 PM](https://user-images.githubusercontent.com/29731456/65188325-2549d780-da3c-11e9-8563-d9ea91c6a15f.png)

### Relevant Code 
[shouldUpdateAddress() method:](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/ADDR_Addresses_TDTM.cls#L560-L581
)
Specifically, Line 568, it's not seeing the line break as the same:
`            !equalsCaseSensitive((String) sObj.get(prefix + 'Street'), getMultilineStreet(addr)) ||
`

And as a result, we add that Account to the listAccUpdate variable on Line 337.  We then add that Account to the dmlWrapper on Lines 373-375.
 ```
if (listAccUpdate.size() > 0) {
            dmlWrapper.objectsToUpdate.addAll((List<SObject>)listAccUpdate);
}
```
This then causes all of our Account Trigger Handlers to run again on Account Update.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAxLQAW" target="_blank">W-036153</a>
