### ISSUE TITLE
Payment Mapping Causes Errors when Same Field Labels are Mapped

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4644]
**Error**
When 2 fields have the same label on Opportunity and Payment, and both are mapped via NPSP Payment Mappings, error thrown:

**Error Message**

_npsp.TDTM_Opportunity: execution of AfterInsert caused by: System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, npsp.TDTM_Opportunity: execution of AfterUpdate caused by: System.SObjectException: SObject row was retrieved via SOQL without querying the requested field: Opportunity.Payment_Method__c (npsp) : [] (npsp)_

**Steps to Reproduce**
1. Create 2 fields on Opportunity with same label
 i.  "Payment Method" (Payment_Method__c) - Picklist
 ii.  "Payment Method" (test_Payment_Method__c) - Text(255)
2. Create 1 field on Payment
 i. "Payment Method" (Payment_Method__c) - Text(255)
3. NPSP Settings > Donations > Payment Mappings
 i. Create Payment Mapping of **Opportunity "Payment Method" (Payment_Method__c) _Picklist_** >>> **Payment "Payment Method" (npe01__Payment_Method__c) _Picklist_**
 ii. **Opportunity "Payment Method" (test_Payment_Method__c) _Text(255)_** >>> **Payment "Payment Method" (Payment_Method__c) _Text(255)_**
4. Create an Opportunity from Contact record 
5. Error will appear at top of Opportunity creation modal

![image](https://user-images.githubusercontent.com/53280203/65648774-93504a80-dfb8-11e9-9267-dae67bc0c861.png)

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by mbeaty-sf** [comment]
Originating HUB post - https://powerofus.force.com/s/question/0D51E000052naLhSAI/payment-mapping-fields-with-the-same-field-label-in-payment-mapping-may-be-causing-errors

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBCzQAO" target="_blank">W-036310</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
