### ISSUE TITLE
Opportunity -> Account (Contact Soft Credit) Does not Calculate Correctly if Previously Won Opportunity Changes to Lost

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4679]
When Account Total Soft Credits rollup is created via the documented steps (http://powerofus.force.com/s/article/NPSP-Soft-Credits-Overview#ariaid-title7), Soft Credits calculate correctly when Opportunity is Closed/Won. However, if there is only one Soft Credited Opportunity associated with the Contact, the Household where the Account Total Soft Credits rollup is located, does not update correctly when that Opportunity is changed to Closed/Lost.

**Steps to Recreate**

1. Create Account Total Soft Credits rollup for Households as outlined in instructions: http://powerofus.force.com/s/article/NPSP-Soft-Credits-Overview#ariaid-title7
2. Find or create Account (Organization Record Type)
3. Create Account Opportunity from Account (Organization) record, and ensure stage is associated with "Won" status
4. Add Contact to Opportunity's Contact Roles with role as "Soft Credit"
5. Recalculate Rollups on Contact record to ensure that Total Soft Credits updates to reflect amount
6. Recalculate Rollups on Contact's Household record to ensure that the Account Total Soft Credits rollup field updates to reflect amount
7. Return to created Opportunity and update status to a "Closed/Lost" status
8. Recalculate Rollups on Contact record
9. Recalculate Rollups on Contact's Household record

**Expected Result**

1. Contact's Soft Credit Rollups will be updated to show the Opportunity's value removed from totals, as the Opp is Closed/Lost. 
2. Contact Household record's Account Total Soft Credits rollup field will be updated to show the Opportunity's value removed from the totals, as the Opp is Closed/Lost

**Actual Result**

1. Contact's Soft Credit Rollups updated to show the Opportunity's value removed from totals.
2. Contact Household record's Account Total Soft Credits rollup field **does not update to show the Opportunity's value removed from the totals**.

**Additional Issue**
- Deleting the Contact Role from the Opportunity, and running Recalculate Rollups on the Household will not remove the Account Total Soft Credits value either.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by mbeaty-sf** [comment]
https://powerofus.force.com/s/question/0D51E000053MJEeSAO/customizable-rollups-do-not-recalculate-when-a-donation-is-withdrawn

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBmTQAW" target="_blank">W-036664</a>

**Comment by mbeaty-sf** [comment]
Issue shares overlap with GitHub issue: https://github.com/SalesforceFoundation/Cumulus/issues/3597

**Comment by jensanald** [comment]
Also, Account Soft Credits do not recalculate if the AS is deleted. Any estimate when this might be resolved? Many thanks!!

**Comment by coriobriensfdo** [comment]
@jensanald yeah we got that one documented on the work item internally as well. Sorry no ETA on the fix just yet but I'll escalate with the team.
