### ISSUE TITLE
Multi-Currency Causing Multiple GAU Allocations

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4702]
When multi-currency is enabled, creating and Opportunity in an org where NPSP Settings has a Default GAU and relating it to a Campaign that has a GAU Allocation tied to it, creates 2 allocations, splitting the value differently than indicated.

**Steps to Recreate**
1. Ensure that Multi-Currency is enabled and create another currency in addition to the default
2. Create a General Accounting Unit (GAU) 
3. Set it as Default in NPSP Settings > Donations > GAU Allocations > Set Default Allocations to **True** and lookup the GAU that you created in step 1
4. Create a new Campaign with a the GAU you created in step 1 (the same one you set in the NPSP Settings as the Default GAU)
5. Create an Opportunity with currency CAD (currency other than the default), and Primary Campaign Source as the Campaign you created in previous step
**Result:** An Opportunity is created with one GAU Allocation

**2nd Part of Recreation**
1. Create a new GAU
2. Create a new Campaign and set the GAU Allocation to the GAU you created in step 1
3. Create an Opportunity with currency CAD (currency other than the default), and Primary Campaign Source as the Campaign you created in previous step
**Result:** 2 Allocations associated to Opportunity, amounts allocated not consistent with set values. 

Example:
![image](https://user-images.githubusercontent.com/53280203/66963119-dc883d00-f040-11e9-9d8a-d489f3c3a2a0.png)

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CCFGQA4" target="_blank">W-036915</a>

**Comment by mpusto** [comment]
I believe this is fixed by https://github.com/SalesforceFoundation/NPSP/pull/5000#issuecomment-578372724 How do we make sure it is closed and incorporated into release notes?
