### ISSUE TITLE
Remove Default Actions from Package

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4718]
Any Salesforce org comes with default Actions for things like New Case, New Contact, New Note, etc. At some point, these defaults also got included in our package. So, customers see both the packaged version of these Actions, as well as the ones included in their org. They can't edit our Packaged Version. Can we remove/deprecate them? Existing customers can then delete them from their orgs and new customers will only have the de-duped defaults.

**Defaults in Orgs:**
![default](https://user-images.githubusercontent.com/29731456/67394394-180b9580-f572-11e9-9cca-3c6cb95bafaa.png)

**What Our Customers See:**
![trial](https://user-images.githubusercontent.com/29731456/67394402-1fcb3a00-f572-11e9-885c-89bd9fd3dc33.png)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HnpwQAC" target="_blank">W-037059</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
