### ISSUE TITLE
BGE - Advanced Mapping: 400 Bad Request when Deleting a field that has Advanced Mapping configured

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#4771]
[Hub thread](https://powerofus.force.com/s/question/0D51E000055ejrUSAQ/potential-bug-400-bad-request-when-deleting-a-field-that-has-advanced-mapping-configured)

**Issue:**
When Advanced Mapping is configured in the org (Running NPSP 3.162 or 3.164), but the field being mapped is deleted, returning to the Object Group's field mapping page shows an error in the UI.
400 Bad Request Invalid field name YOUR CUSTOM FIELD__c
![Error](https://user-images.githubusercontent.com/37851761/68254089-87f03600-ffde-11e9-8238-ca7056e36939.png)

**Steps to recreate:**
1. Create a custom field on NPSP Data Import Object
2. Configure a Field Mapping for this field to a target object (I used Opportunity)
3. Delete the custom field
4. Navigate back to NPSP Settings>System Tools>Advanced Mapping>Select Object Group (View Field Mappings dropdown)
5. Page will not load and error appears
6. The Custom Metadata Type record for the custom field still exists, which may be the cause of the problem. 

**Workaround: Option 1**
1. Recreate field with same API name
2. Delete field mapping
3. Delete field

**Workaround: Option 2**
1. Navigate to Setup>Custom Metadata Types>Data Import Field Mappings, and locate the mapping for your custom field. Delete the mapping. 
![Screen Shot 2019-11-05 at 2 56 26 PM](https://user-images.githubusercontent.com/37851761/68254079-832b8200-ffde-11e9-8c09-6fb6c7f08fa9.png)

**Comment by coriobriensfdo** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoOrQAK" target="_blank">W-037381</a>

**Comment by mbeaty-sf** [comment]
Fix was released in conjunction with others in [NPSP 3.162](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.162)
