### ISSUE TITLE
BDI/BGE improve messaging for duplicate value error on unique fields

### ISSUE THREAD

**Issue by cpose** [SalesforceFoundation/NPSP#4782]
Error message in BDI/BGE when the value entered on a Unique field is a duplicate. 
The error message we display on BGE is also persistent, since there is no way to close it except for refreshing the browser

Pre-conditions: 
For BGE have a batch set up with “Unique ID” as the only matching field.

Steps to reproduce:
1- Create a new “External ID” field on DI object
2- Map this field to “Unique ID” field on Opportunity object using help text or Advanced Mapping
3- Create a new DI record and input a value on “External ID” field.
4- Process the Batch, if on BDI change the “matching field” to Unique ID before processing.
5- Create a new DI with different values on all fields except for External ID, on this field input same one from step 3.

Expected result: Error message should state clearly that there is already an Opportunity record with the current Unique ID.

Actual result: An error is displayed with the ID of the the Data Import record.

**Comment by cpose** [comment]
**lurch: attach W-037483

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HodiQAC" target="_blank">W-037483</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
