### ISSUE TITLE
Data Import Advanced Mapping: Campaign Member import fails 

### ISSUE THREAD

**Issue by ptewson-sfdo** [SalesforceFoundation/NPSP#4788]
**Summary**

With Advanced Mapping enabled, attempting to import a campaign member for an imported or matched contact fails with message 'You do not have permissions to modify CampaignMember.CampaignId"'

**Workaround**
1. Map "npsp__DonationCampaignImported__c" to CampaignId on Campaign Member 1 Group

2. On DataImport__c, populate the NAME of the campaign into Campaign Name (npsp__Donation_Campaign_Name__c) but leave npsp__DonationCampaignImported__c blank

3. Record should process successfully with campaign member successfully created

**Steps to Repeat**

1. Enable Advanced Mapping
2. Add field to DataImport__c: 
    * Campaign_Member_1_Imported__c (text)
    * Campaign_Member_1_Imported_Status__c (text)
    * Campaign_Member_1_Status__c (text)
    * Campaign_Member_1_Campaign__c (text)
3. Create new mapping object group, Campaign Member 1
    * Links to Campaign Member
    * Child of Contact1 through ContactID
    * Campaign Id-> Campaign_Member_1_Campaign
    * Status -> Campaign_Member_1_Status
    * imported record id -> Campaign_Member_1_Imported__c
    * imported record status -> Campaign_Member_1_Imported_Status__c 
4. Create a Campaign and copy the SFID of the campaign
5. Create a new DataImport__c
    * Populate Contact1 Imported with Contact ID
    * Donation Donor: Contact1
    * Populate Donation Amount and Date
    * Populate Campaign_Member_1_Status - "Sent"
    * Populate Campaign_Member_1_Campaign - Id from above Campaign 
6. Process the DI

**ACTUAL**: Import fails with message "You do not have permissions to modify CampaignMember.CampaignId"
**EXPECTED**: Data Import processes successfully, Adds Contact as a member of campaign with CM status "Sent"

Thread on the HUB: https://powerofus.force.com/s/question/0D51E000056SJOHSA4/advanced-mapping-campaign-members-error

**Comment by ptewson-sfdo** [comment]
**lurch attach: W-037554

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HolNQAS" target="_blank">W-037554</a>
