### ISSUE TITLE
If Salesforce Duplicate Management is enabled, Lead Conversion is blocked if 'Alert' is checked

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4793]
**Issue**
When Account Duplicate Rules have "Alert" on "Create," even when excluding the Household Account Record Type, upon an attempt to convert returns error: 

> `Error: ConvertLead failed. First exception on row 0; first error: DUPLICATES_DETECTED, Use one of these records?: []`

<br>
<br>

**Note**
This was partially [fixed](https://github.com/SalesforceFoundation/Cumulus/issues/1669) for Contact Merge and Manage Household, but it is still an issue with Lead Conversion. Hub thread [here](https://powerofus.force.com/s/question/0D58000003ulnJBCAY/duplicate-rule-causing-error-when-converting-lead) plus multiple support cases. 

Even with [Respect Duplicate Settings checkbox](https://github.com/SalesforceFoundation/Cumulus/blob/71c26b8d0fb949f5ca1b9fac20eb7f0b6daca35d/src/classes/UTIL_DMLService.cls#L42) enabled, the 'Alert' box must be unchecked to avoid a lead conversion error. Multiple customers are reporting this as undesirable behavior. 

If the Duplicate Settings are set to 'Allow' we should allow the transaction to complete and report the error on the ending record, similar to behavior had the record been created manually.

**Steps to Reproduce**

1. Create a Scratch Org with NPSP
2. Create a Matching Rule on Account
a.  Object: Account 
b.  Rule Name: Organization Account Simple 
c.  Unique Name: Organization_Account_Simple  
d.  Matching Criteria: (Account: NameFUZZY: COMPANY NAMEMatchBlank = FALSE) AND (Account: ParentFUZZY: COMPANY NAMEMatchBlank = TRUE)
e.  Status: Active (Activate it once created)
3. Create a Duplicate Rule
a.  Rule Name: Organization Account Duplicate Rule
b.  Object: Account
c.  Record-Level Security: Bypass sharing rules
d.  Action On Create: Allow
e.  Operations On Create
 _**i.  Alert Checked
 ii.  Report Checked**_
f.  Action On Edit: Allow
g.  Operations On Edit
_**i. Alert Checked 
ii. Report Checked**_
h.  Alert Text: Use one of these records?
i.  Active: Checked (Activate it once created)
j.  Matching Rule: Organization Account Simple
k.  Matching Criteria: (Account: NameFUZZY: COMPANY NAMEMatchBlank = FALSE) AND (Account: ParentFUZZY: COMPANY NAMEMatchBlank = TRUE)
l.  Conditions: Account: Account Record Type EQUALS Organization
4. In NPSP Settings > System Tools > Error Notifications > enable Respect Duplicate Rule Settings
5. Create a new Organization Account (for ex: ABC)
6. Create a new Lead with following sample information
a.  First Name: John
b.  Last Name: Wilson
c.  Company: ABC & Save
7. Now on the lead record click on Convert button
8. Before you Convert
a.  Make sure Account option is set to "Create Household Account"
b.  Make sure Affiliated Account is set to "Affiliate with Existing Account: ABC"
c.  Leave the remaining options as is
9. Click Convert

<br>
<br>

**Cause**

The Lead Convert Class - LD_LeadConvertOverride_CTRL.cls works to generate a Household Account Record Type, but does so by first generating an Organization Account Record Type, and then converting it, causing an error to be thrown:

https://github.com/SalesforceFoundation/NPSP/blob/a91e66e6bfdf55ce0e3d3dedbe770ec3483dee3f/src/classes/LD_LeadConvertOverride_CTRL.cls#L426

<br>
<br>

**Workaround**
No workaround present at this time, other than unchecking the "Alert" notification on "Create" for the Account Duplicate rule, but this will in turn exclude manual creation of Accounts from being flagged by duplicate rules outside of Lead conversion if the only criteria is record type.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoqmQAC" target="_blank">W-037608</a>

**Comment by mbeaty-sf** [comment]
W-8560988

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phUSQAY&title=error-while-converting-leads-duplicates_detected-use-on-one-of-the-records) in the Trailblazer Community for updates.
