### ISSUE TITLE
In Chome Version 78.0.3904.97 - Manage Household "Exclude from Naming" Checkboxes require double clicks to check

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4796]
**Issue**
In a Household Account record, clicking the "Manage Household" button loads the page that allows you to exclude certain Household Members from Household Name, Formal Greeting, Informal Greeting." 

Upon loading this page, attempts to click on these checkboxes in order to exclude a Contact from these namings require a double click instead of a single click.

**Steps to Reproduce** 
1. In Chrome, open a Household Account record.
2. Click the Manage Household button on the Household Account page
3. Before clicking anything else on the page, attempt to click any of the checkboxes for Household Name, Formal Greeting, Informal Greeting.
![image](https://user-images.githubusercontent.com/53280203/68897383-43515280-06e2-11ea-8028-6b1418965c24.png)
4. Attempt to check any of these 3 boxes with a single click. Only double clicks will allow these boxes to be checked

**Additional Notes**
- Clicking any other checkboxes on the page, further down, such as "Auto Naming" will allow you to return to the Household Name, Formal Greeting, Informal Greeting checkboxes and check them with a single click
- This issue did not appear in Safari when attempting to reproduce

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HosOQAS" target="_blank">W-037626</a>

**Comment by jesslopez-sf** [comment]
W-7781166

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phUIQAY&title=manage-household-exclude-from-naming-checkboxes-require-double-clicks-to-check-in-chrome-as-of-version-78-0-3904-97) in the Trailblazer Community for updates.
