### ISSUE TITLE
Manage Household Page not Allowing Search for Contacts to Add

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4798]
**Issue**
On a Household Account record, clicking on the Manage Household button brings you to the typical household management page; however, when typing in a Contact to find in "Find a Contact or Add a New Contact to Household" you are unable to click on the magnifying glass icon, or hit enter to search for any Contacts.

**Steps to Reproduce**
1. Create at least 5 Contacts with the same names, but different addresses for visual differentiation
2. On a Household Account record, click "Manage Household button"
3. Start typing a new in the "Find a Contact or Add a New Contact to Household" search area, the name of one of your Contacts, you will see 3 appear, but if you created 5 Contacts, at least 1 of them should be missing from the preview list.
4. Hit enter, or try to click the magnifying glass, or select the first line in the drop down menu 🔎 "_name_" in Contacts, and notice there is a short blink, but no pop-up or search results appear

**Additional Notes**
- This issue was reproduced in Google Chrome, Edge, and Safari

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HovcQAC" target="_blank">W-037649</a>

**Comment by mbeaty-sf** [comment]
W-7781165

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000phU8QAI&title=manage-household-page-not-allowing-search-for-contacts-to-add) in the Trailblazer Community for updates.
