### ISSUE TITLE
NPSP Data Import GAU Allocation, Conflicting with Default GAU Allocation on Import

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4875]
**Issue**
When importing a record through NPSP data importer, if the Opportunity has a GAU Allocation in it to be created/matched AND NPSP Settings has Default GAU Allocations enabled referencing the same GAU, the import fails.

**Steps to Recreate**
1. Create General Accounting Unit
2. Reference General Accounting Unit created in NPSP Settings Default General Accounting Unit section
3. Create an NPSP Data Import record that has Opportunity values, and a GAU allocation, referencing the GAU created in step 1.
4. In NPSP Data Imports, start the data import
5. An error is encountered upon the import attempt, reading:

`Update failed. First exception on row 0 with id **<<GAU Record ID>>**; first error: ENTITY_IS_DELETED, entity is deleted: []`

**Workaround**
- By disabling NPSP Settings > Donations > GAU Allocations > Default Allocations **AND** Default General Accounting Unit, the NPSP Data Import record can import without issue.
- By removing the GAU Allocation reference to the General Accounting Unit on the NPSP Data Import record, the Default General Accounting Unit will attach to the Opportunity upon import; however, it will **not** be referenced on the NPSP Data Import record that it was created from

**Comment by mbeaty-sf** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HphrQAC" target="_blank">W-038069</a>

**Comment by allisonletts** [comment]
Looking at the Hub, this appears to be an ongoing issue. As a temporary fix, could some mention of this known issue and workarounds be added to the instructions? I believe that it would make customers more comfortable to know that they are not doing something wrong.

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlEWQAY&title=npsp-data-import-gau-allocation-conflicting-with-default-gau-allocation-on-import) in the Trailblazer Community for updates.
