### ISSUE TITLE
Customizable Rollups: Duplicate field selected error in Soft Credit rollup job

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4899]
Issue emerging with NPSP 3.166 release. 

With Customizable Rollups enabled and no changes made to out of the box rollups, Soft Credit Rollup job is failing with an error that is visible in the NPSP Error Log:

```
npsp__Largest_Soft_Credit_Amount__c,npsp__Largest_Soft_Credit_Date__c,npo02__LastOppAmount__c

^

ERROR at Row:1:Column:259

duplicate field selected: Amount

Rollups State:
```

This error does not occur with legacy rollups.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hq8TQAS" target="_blank">W-038326</a>
