### ISSUE TITLE
Advanced Mapping Component Error in Sandbox

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4912]
**Issue**
In sandbox org, clicking on _NPSP Settings > System Tools > Data Import Advanced Mapping_ (once it has been enabled), turn on _Setup > Develop > Lightning Components > Debug Mode_. When attempting to access Data Import Advanced Mapping again the pictured error is displayed:

![image](https://user-images.githubusercontent.com/53280203/71530849-e7f9af00-28a0-11ea-8a49-b47810948dd5.png)

**Steps to Replicate**
- Create Sandbox Org
- In NPSP Settings > System Tools > enable the Data Import Advanced Mapping
- In Setup > Develop > Lightning Components > enable Debug Mode for your user
- Try to access Data Import Advanced Mapping again and see the pictured error above

**Workaround**
- Disable Debug Mode for Lightning Components and access to the Data Import Advanced Mapping will be restored.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqFPQA0" target="_blank">W-038383</a>
