### ISSUE TITLE
Getting Started Page link errors

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#4913]
**Issue:** 
In NPSP, the Getting Started Tab has three broken links. 
**1.** In the "2. Join the Community" tile, the link for "Hub Community Weekly Office Hours" should point to "https://powerofus.force.com/s/article/SFDO-CS-Hub-Community-Office-Hours", but it's resolving to "https://powerofus.force.com/articles/Customer_Service/Salesforce-com-Foundation-Weekly-Office-Hours?" instead, which is giving an error.

**2.**  In the "3. Dive Deeper" tile, the link for "Getting Started with Salesforce for Nonprofits" should point to "https://powerofus.force.com/s/article/NPSP-BP-Salesforce-Fundamentals", but it's resolving to "https://powerofus.force.com/articles/Best_Practice_Business_Process/Salesforce-Fundamentals?" instead, which is giving an error.

<img width="777" alt="Screen Shot 2019-12-27 at 3 24 39 PM" src="https://user-images.githubusercontent.com/37851761/71534580-0c638480-28bd-11ea-81ca-9fa4336b323e.png">

**3.** The link to view more NPSP How-To videos resolves to a 404. It currently points to an incorrect URL: https://www.youtube.com/user/SalesforceFoundation, but should be pointing to the Playlist for the NPSP Videography video's URL: https://www.youtube.com/playlist?list=PLU8xqF8ZASbXWAHIF0SB1P9_3G4vvRMXI

![NPSP Homescreen](https://user-images.githubusercontent.com/37851761/75174264-249d2780-56e5-11ea-9377-8b54bff33281.png)
![Screen Shot 2020-02-24 at 9 01 42 AM](https://user-images.githubusercontent.com/37851761/75174052-b6f0fb80-56e4-11ea-8eaf-74e19d942454.png)

Steps to **Recreate:**
1. Log into a Salesforce org with the NPSP installed. I've tested in the most current version as of today, which is 3.167.
2. Navigate to the "Getting Started" tab (issue happens in both Lightning Experience and Classic).
3. Click on the "Hub Community Weekly Office Hours", the "Getting Started with Salesforce for Nonprofits", and "View more on our Youtube Channel" links. 
4. **Expected Result:** You should land on the correct locations.
**Actual Result:** Resolves to the wrong URLs and and errors are displayed. 

**Likely cause:** URL's have been changed.

**Comment by coriobriensfdo** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqFZQA0" target="_blank">W-038385</a>

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
