### ISSUE TITLE
Customizable Rollups: Account Soft Credits not updated when Opportunity Contact Role deleted

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#4927]
**Issue**
Contact is given a Contact Role on Opportunity that creates a Soft Credit for the Contact. User created Account Soft Credit Rollups and calculates Household Member's total Soft Credits. If the Soft Credit Contact Role was attached incorrectly and then is removed, the Household Account Soft Credit Rollups and Contact Soft Credit Rollups will not update correctly.

**Steps to Create**

1. Create a field on Account called Total Household Soft Credits
2. Create a Customizable Rollup pointing towards this field that:
        i. Target Object: Account
        ii. Target Field: Total Household Soft Credits
        iii. Operation: Sum
        iv. Time Frame: All Time
        v. Rollup Type: Opportunity -> Account (Contact Soft Credit)
        vi. Filter Group: Opps: Won (SC)
        vii. Amount Field: Soft Credit: Amount
3. Create an Opportunity
4. Add Soft Credit Contact Role onto the created Opportunity
5. Recalculate Rollups on Contact and Household Account
6. Return to the Opportunity you added the Contact Role to, and delete it
7. Run Recalculate Rollups on Contact and Household Account again

**Expected Result**
Contact and Household Account Soft Credits should zero out

**Actual Result**
The previous value of the Opportunity the Contact had a Soft Credit Contact Role on remains in the Rollup calculation

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqKPQA0" target="_blank">W-038444</a>
