### ISSUE TITLE
Payment Scheduler: CRUC causes Non-System Admin to see NPSP Settings Button at Top of Page

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#4934]
When a non-System Admin clicks on the "Schedule Payments" button and views the Payment Wizard VF Page (npsp__PMT_PaymentWizard), an NPSP Settings button displays at the top and they do not have a section to create a payment schedule.

This is happening because their Profile does not have access to the npe01__Contacts_And_Orgs_Settings__c Custom Setting.

We display an NPSP Settings button if the following criteria are true:
https://github.com/SalesforceFoundation/NPSP/blob/master/src/pages/PMT_PaymentWizard.page#L55-L63
- the Payment object .isCreateable(), isDeletable(), and  isAccessible().
- the Contact and Org Custom Setting's Automatic Payment Creation field is unchecked (npe01__Payments_Enabled__c)
paymentsSettings.npe01__Payments_Enabled__c == false

The "Require Customize Application permission for direct read access to custom settings" Critical Update was just auto-activated in orgs. If a profile doesn't have explicit permission to that Custom Setting, it thinks npe01__Payments_Enabled__c == false even if it's checked off. As a result, it displays the NPSP Settings button.

The overall fix for this is to grant Profiles access to that Custom Setting. However, there may need to be some additional code written to see that the User actually has permission to a Custom Setting so we don't display this button incorrectly.

![Screen Shot 2020-01-06 at 3 31 53 PM](https://user-images.githubusercontent.com/29731456/71846935-b8655680-3099-11ea-8c3a-6ddd59050e6f.png)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqO2QAK" target="_blank">W-038477</a>

**Comment by coriobriensfdo** [comment]
[Another Hub Thread.](https://powerofus.force.com/s/question/0D51E000059phuOSAQ/customize-application-permission-for-npsp-custom-metadata-types-and-custom-settings-for-read-access)
