### ISSUE TITLE
Payment Allocations Bug with certain rounding conditions

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/NPSP#4936]
Currently, if a Payment Allocation gets created that's an "odd" amount, it gets set to a very precise decimal, 49.9996784% as an example, which doesn't match up to its "parent" Opportunity Allocation.

This typically happens when splitting a Payment with an odd decimal place.

**Comment by markross-sfdo** [comment]
**lurch: attach W-036125

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
