### ISSUE TITLE
Gift Entry: Error if Account1 is Donor Type to update open Household Opportunity

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#4940]
_Update 7/23/2020: This error persists in Gift Entry. The issue is if 'Donor Type' is set to 'Account1' and the Household Account is selected, rather than if 'Contact1' is selected with corresponding Primary Contact. If the Contact is selected, the gift updates without error._

Household accounts were assumed to not be supported on BGE, however currently if a Household has open Opportunities, they are being displayed in “Review Donations” feature.
But if selected, will fail on processing with an error unrelated to Account Type.

1- A Household Account should be created after a Contact record is created.
2- An open Opportunity should be created for the Household account.
<br>
**Steps to Repeat**

**Scenario 1**
1- Create a Batch on Gift
2- Under “New Gift” choose “Account” as Donor Type and the HouseHold from pre-condition on Account field.
3- Click on “Review Donations” message that appears on upper-left.
4- Click on “Update this Payment”.
5- Fill the other mandatory fields including a bigger amount than opportunity from pre-condition.
6- Process the Batch.

**Expected Result:** 
If Household is not supported as donor on BGE, “Review Donations” should not display its open Opps.

**Actual Result:**

If a Household account with Open Opportunities is chosen on a new Gift, “Review Donations” appears to be available but processing fails with error “Required fields are missing: [StageName]” or matching is not respected.
<br>

**Scenario 2**

1. Create a scratch org
2. Enable Advanced Mapping from NPSP Settings
3. Enable Gift Entry
4. Make sure permissions are assigned correctly
5. Create a new Contact
6. Go to the new Contact's Household Account and create a new pledged donation from account page
7. Now, go to GE tab
8. Click on New Single Gift Entry
9. Fill in the details
a.  Donor Type - Account1
b.  Existing Donor Organization Account - HH Account you created
c.  You will see a popup: This donor has pending donations. Review Donations
d.  Click on Review Donations and choose the existing pledged donation
e.  Update this Opportunity
f.  Fill in remaining required fields and Save

The Batch will process without issue; however, when you return to the Household Account record you will notice that rather than the Opportunity being updated, a duplicate Opportunity is created with the Stage: Closed Won.

**Comment by judisohn** [comment]
**lurch: attach W-037119

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HnvaQAC" target="_blank">W-037119</a>

**Comment by aschwartz-arkchicago** [comment]
Is there any update on this? We are experiencing the same issue.

**Comment by judisohn** [comment]
Hi @aschwartz-arkchicago It should work if you have a Contact that you're relating the donation to rather than the Household Account record. Make sure you're using Gift Entry rather than the older Batch Gift Entry, as that's where any future fix will be applied.

**Comment by judisohn** [comment]
Attached to new bug [W-7862352](https://gus.lightning.force.com/a07B0000008WTXSIA4)

**Comment by jkenzer** [comment]
Is there any plan to triage and fix issues like this that have been open for over 2 years?

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlEOQAY&title=gift-entry-error-if-account1-is-donor-type-to-update-open-household-opportunity) in the Trailblazer Community for updates.

**Comment by kporray1** [comment]
@jkenzer @aschwartz-arkchicago Please see this related [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlEOQAY&title=gift-entry-error-if-account1-is-donor-type-to-update-open-household-opportunity), and make sure to click 'This Issue Affects me' to raise visibility and receive updates.

**Comment by jkenzer** [comment]
@kporray1 awesome! Done.
