### ISSUE TITLE
Unmanaged Package installation URLs Request

### ISSUE THREAD

**Issue by ricxsar** [SalesforceFoundation/NPSP#4942]
Good day.

I am a salesforce developer which uses NPSP as a dependency. We are considering transitioning our development to Unlocked package and we need the complete dependency lists (installation URLs) including the unmanaged metadata for us to create the package.

We can possible create a dedicated unlocked package for those metadata but we're afraid about maintaining it ourselves and it will also increase the our dependency tree.

Is it possible to disclose their installation URLs? 

![image](https://user-images.githubusercontent.com/8968902/72135921-85390500-33c2-11ea-95bc-288456e8d244.png)

**Comment by coriobriensfdo** [comment]
@ricxsar we don't provide support here in GitHub and Issues are logged only for bugs against the product. 
Instead, we have a forum for customers and partners called the Power of Us Hub. We have a [Nonprofit developer group](https://powerofus.force.com/s/group/0F980000000CjxLCAS/nonprofit-salesforce-developers) where you can post your question and get some assistance. 

Thanks!

**Comment by ricxsar** [comment]
I have posted a question Power of Us Hub. Please have them a look and hoping they can assist me. Thanks!

https://powerofus.force.com/s/question/0D51E00005ALdAKSA1/how-to-define-npsp-and-its-requirements-as-a-dependency-of-unlocked-package
