### ISSUE TITLE
Error visible in NPSP Settings- npsp:RD2_EnablementDelegate$controller$handleDryRunError

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#4965]
**Issue:**
In an org with version 3.168, navigating to NPSP Settings displays an error on each page.

"This page has an error. You might just need to refresh it. Action failed: npsp:RD2_EnablementDelegate$controller$handleDryRunError [response is not defined] Failing descriptor: {npsp:RD2_EnablementDelegate$controller$handleDryRunError}"

![Screen Shot 2020-01-15 at 11 31 01 AM](https://user-images.githubusercontent.com/37851761/72466696-3e665900-378e-11ea-906d-64c9f6f43aed.png)

**Steps to Repro:**

1. In an org with 3.168 installed, navigate to NPSP Settings. 
2. Notice error along bottom of screen on any page. Happens with or without CRLP enabled, and without any hidden RD2 code enabled.

Further investigation details to be added to Work Item.

**Comment by coriobriensfdo** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqqkQAC" target="_blank">W-038698</a>
