### ISSUE TITLE
Having an issue with using Manage Household button with portal users

### ISSUE THREAD

**Issue by ramtinworld** [SalesforceFoundation/NPSP#4971]
Hi,

We are trying to use the Manage Household button and bring in contacts from other HH Accounts together however we get the following error:

**Merge failed. First exception on row 0 with id 001XXXXXXXXXXXX; first error: MERGE_FAILED, When merging portal enabled accounts, the master record must be portal enabled.: []**

The contact that we are trying to merge into the HH is a Customer Community User.

Is this a known issue or are we missing something?

Thanks

**Comment by coriobriensfdo** [comment]
Hi @ramtinworld we don't provide support here in Github, but you can post in the [Power of Us Hub](https://powerofus.force.com/publogin. 

Take a look at [this post](https://powerofus.force.com/s/question/0D580000032F0gbCAC/npsp3-contact-merge-vs-community-user), which may help.
