### ISSUE TITLE
BGE Wizard - Fields are misaligned

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#4974]
[Hub Thread](https://powerofus.force.com/s/question/0D51E00005B93GrSAJ/more-contact-fields-visible-on-batch-gift-entry-search)

**Issue:**
When using Firefox (and as of Jan 20th, Chrome), fields in the New Gift page of the wizard are misaligned. 
<img width="1406" alt="Screen Shot 2020-01-17 at 10 00 13 AM" src="https://user-images.githubusercontent.com/37851761/72634802-333b3680-3910-11ea-860a-4dccd3c80762.png">

This is not hindering using or tabbing through the fields. Resizing the page does not correct the issue, though different fields become more or less out of alignment as a result.

Note: on Jan 17th this issue was only affecting the wizard page when viewed in Firefox, however as of Jan 20th, the issue is now appearing in Chrome.
![Screen Shot 2020-01-20 at 10 42 43 AM](https://user-images.githubusercontent.com/37851761/72750855-df7c5780-3b72-11ea-84a8-e263aeda430e.png)

**Comment by coriobriensfdo** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hqy4QAC" target="_blank">W-038783</a>
