### ISSUE TITLE
Move TDTM to metadata

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/NPSP#5069]
Since Trigger Handler data is actually metadata, and it should be active upon trigger deployment, it should be moved from Custom Settings to Custom Metadata.

Is this on the roadmap?

**Comment by coriobriensfdo** [comment]
Hi @ckoppelman, we don't give support or answer help questions here in GitHub. Can you instead please post your questions to the Power of Us Hub? Feel free to post this in the [NPSP Group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack). 

Thanks!
