### ISSUE TITLE
duplicate field selected: CurrencyIsoCode AccountContactSoftCredit on Jan 1st

### ISSUE THREAD

**Issue by aplatonov-dev** [SalesforceFoundation/NPSP#5091]
The Nightly Job has failed with the following error on January first:

npo02_OppsClosedLastYearc,npo02OppsClosedThisYearc,npo02OppsClosed2YearsAgo_c ^ ERROR at Row:1:Column:287 duplicate field selected: CurrencyIsoCode
Rollups State:|CRLP.AccountContactSoftCredit

Thanks!

**Comment by coriobriensfdo** [comment]
Hi @aplatonov-dev , we don't support our products here in GitHub. Can you post in the Power of Us Hub, using the [Nonprofit Success Pack group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack)?
