### ISSUE TITLE
NPSP Error Notification Recipient Code References Hard-Coded String

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5097]
In NPSP Settings, under Error Handling, you can choose to have None, Chatter Group, All Sys Admins, or Users with System Admin Permissions receive Error Notifications. However, the validation of who is included in the "catch all" of the "All Sys Admins" option is based on a text String of the profile matching exactly 'System Administrator'. If a user wishes to create a System Admin Profile with different permissions, they either have to send errors to a single user, or they are required to use the System Administrator profile to send to more than one user.

**Apex Classes**
Found here, the User's emails are chosen based on the `UTIL_Profile.SYSTEM_ADMINISTRATOR` in this class https://github.com/SalesforceFoundation/NPSP/blob/3987af18636c50af00bafed11bc2c3401c704a26/src/classes/ERR_Notifier.cls#L148

which references the string in `UTIL_Profile` - https://github.com/SalesforceFoundation/NPSP/blob/3987af18636c50af00bafed11bc2c3401c704a26/src/classes/UTIL_Profile.cls#L38

**Workarounds**
While a custom profile named "System Administrator" can be created, this creates two profiles with exactly the same name, and does not allow for a wider range of users to be notified via email of any errors.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hs28QAC" target="_blank">W-039305</a>

**Comment by mbeaty-sf** [comment]
W-7781157

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  W-7781157
