### ISSUE TITLE
The Account.BDE_Entry_FS fieldset has a reference to RecordTypeId

### ISSUE THREAD

**Issue by dlisovsky** [SalesforceFoundation/NPSP#5128]
Hi Team,

Is there a reason to add the [reference](https://github.com/SalesforceFoundation/NPSP/commit/300b6cf4d1c53dcb5c9020e3b12c4334bb2eaa2f) by @davidhabib  to RecordTypeId in the Account BDE_Entry_FS fieldset as there are no Record Types in npsp?

I'm trying to build a package on top of the npsp and unable to create a package version due to this conflict.

![image](https://user-images.githubusercontent.com/4610433/74656430-27f15a00-519f-11ea-8424-2b27a608e644.png)
![image](https://user-images.githubusercontent.com/4610433/74656472-3dff1a80-519f-11ea-9fba-1c311a170d5a.png)

Thanks in advance!

**Comment by jamesbsfdc** [comment]
Hi there

Do you have access to the Power of Us Hub? If so would you mind posting this there so we can route it to the correct person?  https://powerofus.force.com/s/article/SFDO-BP-Ask-Questions-in-the-Hub

Not sure if this helps but when NPSP is installed by our web-based installer, MetaDeploy at https://install.salesforce.org/products/npsp/install, some unpackaged metadata is also installed. which includes account and opportunity record types. You can see this in the yml file: https://github.com/SalesforceFoundation/NPSP/blob/master/cumulusci.yml

James

**Comment by dlisovsky** [comment]
Hi @jamesbsfdc - sorry for posting such question here, I just tried to find any details on this. Thank you for sending me to the Power of Us Hub, I've joined the community and found the same question. In case any have the same question - currently, there is no workaround and the hotfix is just to create a small package (as a dependency prior to the npsp) with included Account/Opportunity Record Type.

https://powerofus.force.com/s/question/0D51E0000513xS4SAI/error-when-creating-a-second-generation-2gp-package-with-a-dependency-to-npsp

I'm still pretty interested how SF created npsp package with the dependency to Record Type but with no Record Type in the package. 

Thank you!

**Comment by jamesbsfdc** [comment]
No problem, its a public holiday in the US and Canada today so I am home alone managing the fort but I can check with the team tomorrow. 

In case it helps this is the thread on the Partner Community that Jason Smith was referring to in the comments on that Hub post: https://partners.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000001tcz&fId=0D53A00004d0uMd

Not sure if you also have access to Partner Community? If not I can post the useful comments from the  thread here

**Comment by dlisovsky** [comment]
Thank you for providing the link to the Partner Community, I have access so I'll be following this topic. It also would be great if you could have a look with the team when you get a chance. The problem becomes pretty popular with 2GP packaging model. 

Maybe just remove the Record Type Id from the fieldsets? Anyway, you guys better know the solution!

Enjoy your holiday @jamesbsfdc!

**Comment by dlisovsky** [comment]
Hey @jamesbsfdc  - new Packaging update has resolved my issue: https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_sfdx_packaging_skip_validation.htm

**Comment by iandrosov** [comment]
I am still see this issue on create version of unlocked package.  
This error I get on sfdx-cli/7.112.1 darwin-x64 node-v14.17.4\
@coriobriensfdo 

Request in progress. Sleeping 30 seconds. Will wait a total of 90 more seconds before timing out. Current Status='Verifying dependencies'
ERROR running force:package:version:create:  Multiple errors occurred:
(1) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.BDE_Entry_FS) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.BDE_Entry_FS: In field: RecordTypeId - no CustomField named Account.RecordTypeId found
(2) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.BDE_List_FS) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.BDE_List_FS: In field: RecordTypeId - no CustomField named Account.RecordTypeId found
(3) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.Manage_Household_Custom) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.Manage_Household_Custom: In field: RecordTypeId - no CustomField named Account.RecordTypeId found

**Comment by coriobriensfdo** [comment]
> I am still see this issue on create version of unlocked package.
> This error I get on sfdx-cli/7.112.1 darwin-x64 node-v14.17.4
> @coriobriensfdo
> 
> Request in progress. Sleeping 30 seconds. Will wait a total of 90 more seconds before timing out. Current Status='Verifying dependencies'
> ERROR running force📦version:create: Multiple errors occurred:
> (1) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.BDE_Entry_FS) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.BDE_Entry_FS: In field: RecordTypeId - no CustomField named Account.RecordTypeId found
> (2) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.BDE_List_FS) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.BDE_List_FS: In field: RecordTypeId - no CustomField named Account.RecordTypeId found
> (3) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.Manage_Household_Custom) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.Manage_Household_Custom: In field: RecordTypeId - no CustomField named Account.RecordTypeId found

@iandrosov we don't provide support here on GitHub. Your best bet is to [log a case](https://help.salesforce.com/supportandservices?id=createCase&topic=Salesforceorg_Products_TOPIC) so that the Support team can assist. If needed a bug can be recorded internally for the NPSP team to review.
