### ISSUE TITLE
NPSP Settings Fails to Load in Microsoft Edge Browser

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5146]
This issue was reported by @annejackson. When navigating to the NPSP Settings page in Microsoft Edge, the page fails to load. Only a blank screen appears. The browser console shows a red error displaying only "null". The System Admin Profile does have access to all Apex classes. 

<img width="1362" alt="Screen Shot 2020-02-20 at 10 08 46 AM" src="https://user-images.githubusercontent.com/29731456/74947565-096ea700-53c9-11ea-964a-b37f4780bee1.png">

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsRWQA0" target="_blank">W-039537</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
