### ISSUE TITLE
Customizable Rollups: In multi-currency orgs custom number rollups are calculated with a conversion value

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#5159]
### Summary of Issue

In orgs that have multicurrency enabled, when you create a customizable rollup to rollup a custom number field on the opportunity to a custom number field on the contact or account the calculation is applying currency conversions to the number field in situations where the currency of one or more opportunities differs from the contact's currency. In situations where the currency of the opportunity matches the contact currency the rollup is calculated correctly. 

### Example Use Case

A nonprofit wants to record the number of tickets sold for their events so they create a custom Opportunity number field called "# Tickets Purchased". Each opportunity will record the number of tickets a contact or account has purchased for each event the nonprofit runs. The nonprofit would like to be able to rollup onto the contact or account record the total number of tickets each contact or account has purchased across all events they run.

### Config Steps to Reproduce:

1. Enable Multicurrency
2. Create a new currency with a conversion rate value not equal to 1: e.g
----- USD (Corporate Currency)
----- GBP (2.000000)
3. Create a number field on Opportunity: 
----- Name: Test Number
----- Field Type: Number(18, 0)
4. Create a number field on Contacts:
----- Name: Test Number
----- Field Type: Number(18, 0)
5. Create a new customizable rollup to rollup the opportunity number field to the contact number field:
----- Target Object = Contact
----- Target Field = Test Number
----- Operation = SUM
----- Time Frame = All Time
----- Rollup Type = Opportunity -> Contact (Hard Credit)
----- Filter Group = No Filter Group
----- Amount Field = Opportunity:Test Number

### Test Data

1. Create a new Contact
----- Name = **Contact A**
----- Contact Currency = USD - U.S. Dollar
2. Create a new Opportunity for **Contact A**
----- Amount = 100
----- Test Number = 100
----- Contact Currency = USD - U.S. Dollar
----- Stage = Posted
3. Create a new Opportunity for **Contact A**
----- Amount = 30
----- Test Number = 30
----- Contact Currency = GBP - British Pound
----- Stage = Posted

4. Create a new Contact
----- Name = **Contact B**
----- Contact Currency = GBP - British Pound
5. Create a new Opportunity for **Contact B**
----- Amount = 50
----- Test Number = 50
----- Contact Currency = GBP - British Pound
----- Stage = Posted
6. Create a new Opportunity for **Contact B**
----- Amount = 10
----- Test Number = 10
----- Contact Currency = USD - U.S. Dollar
----- Stage = Posted

7. Create a new Contact
----- Name = **Contact C**
----- Contact Currency = USD - U.S. Dollar
8. Create a new Opportunity for **Contact C**
----- Amount = 20
----- Test Number = 20
----- Contact Currency = USD - U.S. Dollar
----- Stage = Posted
9. Create a new Opportunity for **Contact C**
----- Amount = 70
----- Test Number = 70
----- Contact Currency = USD - U.S. Dollar
----- Stage = Posted

### Expected vs Actual Results

**Contact A** 
Expected value in Test Number rollup field: 130 (100 + 30)
Actual value in Test Number rollup field: 115 (30/2 +100) - INCORRECT

**Contact B**
Expected value in Test Number rollup field: 60 (50 +10)
Actual value in Test Number rollup field: 70 (10*2 + 50) - INCORRECT

**Contact C**
Expected value in Test Number rollup field: 90 (20 +70)
Actual value in Test Number rollup field: 90 - CORRECT

**Comment by jamesbsfdc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsZaQAK" target="_blank">W-039635</a>
