### ISSUE TITLE
Last Membership Level and Last Membership Origin Rollups pull older values when blanks present on Last Membership

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5160]
### **Issue**
When a Contact has more than one Membership Opportunity record associated to them, if the Membership Level and Membership Origin are blank on the most recent Membership, but populated in a previous Opportunity, those values are pulled into the rollup and create an incorrect picture of the data.

****Note -- This is only present in Customizable Rollups, and not in User Defined Rollups**

### **Example**

A Contact (or Account) with two Membership Opportunities, as follows:

_Opp 1 (most recent Close Date, but it has empty Member Level and Origin):_
_Amount_: **$5**
_Close Date_: **2/13/2020**
_Member Level_:
_Membership Origin_:
_Membership Start Date_: **2/13/2020**
_Membership End Date_: **2/13/2021**

_Opp 2 (older but has a non-empty value for all corresponding fields):_
_Amount_: $250.00
_Close Date_: 2/12/2019
_Member Level_: **Gold**
_Membership Origin_: **New**
_Membership Start Date_: 2/12/2019
_Membership End Date_: 2/12/2020

When using Customizable Rollups, we see at Account and Contact level:

Last Membership Amount: $5.00
Last Membership Level: Gold (from the older Opp)
Last Membership Origin: New (from the older Opp)
Last Membership Date: 2/13/2020
Last Membership End Date: 2/13/2021

### **Steps to Replicate**

1. Find a Contact record
2. Create a Membership Opportunity with a Membership Start Date and Close Date a year ago (the exact timeframe doesn't matter as long as it is older than the second Membership Opportunity created)
3. Populate the Membership End Date with a date that ends before the next Membership Opportunity's "Membership Start Date" and "Close Date"
4. Populate the Membership Level and Membership Origin with a value
5. Save the Opportunity

6. Create another Membership Opportunity on the same Contact record
7. Populate the Close Date and Membership Start Date to be after the Membership End Date of the Last Membership Opportunity
8. Save the Opportunity

9. Recalculate the Rollups on the Contact record associated with the Opportunities that you just created
10. See that the values in the Last Membership Level and Last Membership Origin are pulled from the older Opportunity, not the most recent one 

### **Workaround**
Switching from Customizable Rollups back to User Defined Rollups allows for the batch job to pull in blank values from the most recent Membership Opportunity.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hse6QAC" target="_blank">W-039693</a>

**Comment by mbeaty-sf** [comment]
Related Hub thread - https://powerofus.force.com/s/question/0D51E00005EGXYMSA5/testing-customizable-rollups-im-finding-that-last-membership-originlevel-on-account-and-contact-skip-over-blank-values-on-opps-to-the-latest-nonblank-value-can-those-rollups-be-adjusted-to-count-emptyblank

**Comment by mbeaty-sf** [comment]
W-7781163

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlENQAY&title=last-membership-level-and-last-membership-origin-rollups-pull-older-values-when-blanks-present-on-last-membership) in the Trailblazer Community for updates.
