### ISSUE TITLE
Multi-currency Org Account Rollups Calculating Incorrectly

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5185]
**Issue**
When an org has several currencies, rollups are calculating different values for several rollups.

**Steps to Reproduce**
1. Activate Multi-currency in the org
2. Create at least 3 currencies with different values
3. Create an Account record, and set its currency to one of the currencies, but one different from the Organization's default
4. Create an Opportunity relating to that Account record, and choose it as a currency that is not the Organization default, and is not the same currency that is the Account's currency
5. Check the rollups on the Account and see the the values differ on several of the rollups:

![image](https://user-images.githubusercontent.com/53280203/75498412-f127fa80-597b-11ea-843e-f0cfd2a6e484.png)

The above results were produced where:

The Company (Corporate) Currency - USD
The Organization's Account Currency - EUR
The Opportunity's Currency - MXN -- Amount: 100

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Ht1mQAC" target="_blank">W-039860</a>
