### ISSUE TITLE
Customizable Rollups Calculating with/without Advanced Currency Management when Enabled

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5186]
**Issue**
When Advanced Currency Management is turned on, some Customizable Rollups are calculating values based on the Advanced Currency Management exchange rate, and others are calculating based on the current standard Multi-Currency values.

This example happed with Advanced Currency Management **ON** but NPSP "Use Dated Values when available" **OFF**

![image](https://user-images.githubusercontent.com/53280203/75501404-cd1ce700-5984-11ea-9aff-66d49753b976.png)

**Steps to Reproduce**
1. Turn on Currency Management in an Org and set Corporate (default) currency for the Org to USD at 1.00
2. Create another currency and put in an exchange rate
3. Create an Account record
4. Create an Opportunity record related to the Account record, and ensure that you set the Opportunity Currency to a value of a currency other than the Corporate (default) currency
5. Turn on Advanced Currency Management
6. Edit the Exchange Rates for today and put a different exchange rate for the currency of the Opportunity created in step 4
7. Return to the Account record and recalculate the rollups
8. Last Gift Amount displays value based on the exchange rate for standard Currency Management entered first, the other rollups show as those using Advanced Currency Management value, input in step 6

**Note**
This is with the NPSP Settings "Use Dated Exchange Rates if available" option in NPSP Settings > Batch Data Processes > Batch Process Settings turned **OFF** but checking the box to ON does not change the values of the rollups

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Ht1rQAC" target="_blank">W-039861</a>

**Comment by mbeaty-sf** [comment]
Related Issue https://github.com/SalesforceFoundation/NPSP/issues/4450

**Comment by mbeaty-sf** [comment]
W-7781123

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlEMQAY&title=customizable-rollups-calculating-with-without-advanced-currency-management-enabled) in the Trailblazer Community for updates.
