### ISSUE TITLE
NPSP Data Import Batch Process Batch

### ISSUE THREAD

**Issue by seanrmsy** [SalesforceFoundation/NPSP#5194]
I'm getting an error when trying to Process Batch in NPSP Data Import.

Steps to reproduce:
1. Go to NPSP Data Import Batch from app launch
2. Select a Batch
3. Click "Process Batch"

The error message is Page BDI_DataImport does not exist. This is in Lightning.

**Comment by coriobriensfdo** [comment]
Hi @seanrmsy we actually don't support the products here in GitHub. Can you instead post in the Power of Us Hub? We've got a group for the [NPSP](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) you can post in.
