### ISSUE TITLE
Adding TDTM Triggers to cache for test classes ignores Load Order

### ISSUE THREAD

**Issue by koenwesselman** [SalesforceFoundation/NPSP#5196]
When I add a Trigger Handler record to the cached Trigger Handler records like this:
`List<npsp__Trigger_Handler__c> listHandlers = npsp.TDTM_Config_API.getCachedRecords();
listHandlers.add(triggerHandlerRecord); `

It runs the Trigger Handlers in the order that I've added them to the cache, rather than based on the Load Order field.

**Comment by coriobriensfdo** [comment]
Hi @koenwesselman we don't provide support, even for the Trigger Handlers here in GitHub. Instead, can you please post in the [Power of Us Hub NPSP](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) group? You can also tag the Developers group for help and if there's a bug in the package we can re-open.
