### ISSUE TITLE
Gift entry: Open in batch table throwing component error when allocation widget is present and no allocation is added.

### ISSUE THREAD

**Issue by deepmalamehta** [SalesforceFoundation/NPSP#5208]
Details and Steps to Reproduce:-
1. Create a template with Allocation bundle.
2. Create/open a batch with the same template.
3. Add a gift in the batch without any allocation. A new row should be added to the table.
4. Click "Open" in the same row to open the gift from the row in batch gift form.

Expected result:
Form loads with data from row

Actual result:
Component error
<img width="777" alt="Screen Shot 2020-02-26 at 10 08 27 AM" src="https://user-images.githubusercontent.com/42785185/76004245-0b9f2e00-5ebe-11ea-8dad-8bce535c12b3.png">

**Comment by deepmalamehta** [comment]
**lurch: attach W-039797

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsrNQAS" target="_blank">W-039797</a>

**Comment by kenlewis-sfdo** [comment]
Fixed by: https://github.com/SalesforceFoundation/NPSP/pull/5151/commits/a0edf6b93d35a34d592dff2965e23442561574fd
