### ISSUE TITLE
Gift Entry: Batch level defaults are not rendering on the form

### ISSUE THREAD

**Issue by deepmalamehta** [SalesforceFoundation/NPSP#5209]
As a gift entry user, I want to be able to set batch level defaults when I'm creating a batch, and have those display on the form when it's rendered so that I don't need to re-enter those values.
 Steps:
1. Create a new batch using gift entry.
2. Enter Default values in "Set Default Values" tab in the batch modal.
3. Save and create the batch.
**Expected:** Batch level default values should be rendered with the form.
**Actual**: Batch level default valued not being set on the form

**Comment by deepmalamehta** [comment]
**lurch: attach W-038958

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrEMQA0" target="_blank">W-038958</a>
