### ISSUE TITLE
Gift Entry: Checkboxes are always required on form templates

### ISSUE THREAD

**Issue by ptewson-sfdo** [SalesforceFoundation/NPSP#5217]
As a gift entry user, I want to be able to include checkbox fields that are mapped from Data Import checkboxes to target object checkboxes without them being flagged as required on the form template

Map checkbox field in Advanced mapping (e.g. DI "Opp Do Not Automatically Create Payment" -> "Do Not Automatically Create Payment")
In Gift Entry, Create new form template, and open Opportunity group
Expected: "Do Not Automatically Create Payment" is not marked as required (red asterix, can save template w/o field on form)
Actual: "Do Not Automatically Create Payment" is marked as required and template cannot be saved without the field included on the form.

**Comment by ameyersalesforce** [comment]
**lurch: attach W-040038
