### ISSUE TITLE
NPSP Data Importer - Clears "Household Account Imported" Field on Dry Run

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5245]
If User is attempting to import new Contacts (i.e. other family members) to a Household Account, and populates the NPSP Data Import import with Household Account IDs in the Household Account Imported field, they provide the correct link to a Household Account. However, if the User runs a "Dry Run" then the Household Account Imported field is cleared out if "Dry Run - Matched None" is the Contact1 Import Status. (If a match is found, then the Household Account Imported field is populated with the matching Contact's household, as expected).

**Steps to Recreate**
1. Create a Contact with a Household Account
2. Create an NPSP Data Import record and populate the field "Household Account Imported" field with the ID of the Household Account created in step 1
3. Do a Dry Run of the NPSP Data Import
4. Return to the NPSP Data Import record and see that the Household Account Imported field now displays blank and the Contact1 Imported Status is Dry Run - Matched None

**Workaround**
If it is known that the Contacts being imported need to be attached to an existing Household, then go immediately to Begin Data Import, skipping Dry Run, to start the import process to create the Contacts and add them to the existing Household. The NPSP Data Importer's matching against First Name, Last Name, and Email will still run during the import process, but if no match is found, the Contact will be correctly created and added to the pre-defined Household based on the Household Account Imported field's value.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtdNQAS" target="_blank">W-040191</a>

**Comment by mbeaty-sf** [comment]
W-7781168

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlE3QAI&title=npsp-data-importer-clears-household-account-imported-field-on-dry-run) in the Trailblazer Community for updates.
