### ISSUE TITLE
Gift Entry: Picklist field values are not getting populated when selecting a record in Gift entry

### ISSUE THREAD

**Issue by deepmalamehta** [SalesforceFoundation/NPSP#5250]
When we select any object in the Gift entry form, all the related values should get populated. However, We do not see picklist fields resonate with the same behavior. This is also true for template level/batch level default field values.

![Screen Shot 2020-03-06 at 3 45 06 PM](https://user-images.githubusercontent.com/42785185/76789035-471ce080-6779-11ea-91d7-f4aa304bb789.png)

**Steps to Reproduce**
1. Add Opportunity Record Type ID onto a Gift Entry template
2. When filling out the form, choose an Opportunity Record Type from the picklist in the field Opportunity: Record Type ID
3. Save the entry
4. See that the field on the Dry Run record on the batch shows the Opportunity: Record Type ID, not the text string
5. The record you saved on the batch displays under Status: "Dry Run - Error" and under Error: "Invalid Donation Record Type Name"

![image](https://user-images.githubusercontent.com/53280203/78065158-b5e86500-7347-11ea-8fcd-67e6ed2c16cc.png)

**Expected Behaviour**
The submitted record should properly translate the selected Record Type to the string the NPSP Data Importer expects, instead of converting it to the ID.

**Workarounds**
Manually updating the field on the NPSP Data Import records, and then returning to the Gift Entry batch and running "Batch Dry Run" again will update the Status to "Dry Run - Validated" and allow you to proceed with the import as expected.

**Comment by deepmalamehta** [comment]
**lurch: attach W-040105

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtSEQA0" target="_blank">W-040105</a>
