### ISSUE TITLE
Gift entry: Payments with no schedule date will give component error when update payment is selected.

### ISSUE THREAD

**Issue by deepmalamehta** [SalesforceFoundation/NPSP#5254]
Steps to reproduce:
1. Create an opportunity.
2. Create a payment with no scheduled date.
2. From gift entry form, select the donor and update payment in review donations modal.

The component error occurs as shown in the screenshot. it's fixed after you enter a scheduled date.
![Screen Shot 2020-03-16 at 3 37 08 PM](https://user-images.githubusercontent.com/42785185/76812295-aa2a6980-67b1-11ea-92e4-75c0114abf88.png)

**Comment by deepmalamehta** [comment]
**lurch: attach W-040249

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtliQAC" target="_blank">W-040249</a>

**Comment by mbeaty-sf** [comment]
W-7964224

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7964224)
