### ISSUE TITLE
Can not Insert Large Batch to the Opportunity Object in Salesforce

### ISSUE THREAD

**Issue by LGW78** [SalesforceFoundation/NPSP#5260]
The NPSP TDTM Opportunity trigger is not allowing me to insert data into the opportunity object into Salesforce. The error I receive is:
"npsp.TDTM_Opportunity: execution of BeforeInsert

caused by: System.NullPointerException: Attempt to de-reference a null object

Class.npsp.OPP_OpportunityContactRoles_TDTM.setOpportunityAccountField: line 137, column 1
Class.npsp.OPP_OpportunityContactRoles_TDTM.run: line 61, column 1
Class.npsp.TDTM_TriggerHandler.runClass: line 193, column 1
Class.npsp.TDTM_TriggerHandler.run: line 113, column 1
Class.npsp.TDTM_Config_API.run: line 92, column 1
Trigger.npsp.TDTM_Opportunity: line 33, column 1"

**Comment by coriobriensfdo** [comment]
@LGW78 we actually don't provide support here in GitHub. Can you post in the Power of Us Hub instead? We have a [Nonprofit Success Pack group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) you can post in.
