### ISSUE TITLE
NPSP projects pledged donations even though forecast settings are set to zero when recurring profile is written through the api

### ISSUE THREAD

**Issue by markristaino** [SalesforceFoundation/NPSP#5261]
ActionKit has an integration product that writes recurring donations to Salesforce via the api. The recurring pledge setting seem to ignore the forecast months and writes pledges even though that setting is "0".

Steps to reproduce:
1. set npsp forcast months to zero on NPSP setting page
2. write a recurring profile to SF via api
3. check to see if forcast month setting is ignored
![npsp](https://user-images.githubusercontent.com/14279954/77017612-264eb980-6938-11ea-8d67-07d809fdde7a.jpeg)
![pledges](https://user-images.githubusercontent.com/14279954/77017622-29e24080-6938-11ea-93a0-aa67e8fcb451.jpeg)

**Comment by coriobriensfdo** [comment]
@markristaino we don't provide support here in GitHub. Can you post in the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) instead? We've got some developer resources on that side we can loop in and try and confirm if this is actually a bug, or something else. We don't see the same functionality when creating a RD manually when the setting has been changed to 0 (I just tested).

**Comment by markristaino** [comment]
Hi -- this bug is specifically about recurring profiles added through the api and does not occur when added manually via the console. I will post on power of hub though

**Comment by markristaino** [comment]
ok i posted it here:
https://powerofus.force.com/s/feed/0D51E00005FzI8TSAV

**Comment by coriobriensfdo** [comment]
Thanks @markristaino!
