### ISSUE TITLE
When I am adding a dependency of this org I am getting error.

### ISSUE THREAD

**Issue by miteshmsharma** [SalesforceFoundation/NPSP#5262]
I am using source as

sources:
npsp:
github: https://github.com/SalesforceFoundation/NPSP

in my .yml file but when I try to create the sandbox with the NPSP and my own Food-Bank package I get error below.

Error: [Errno 2] No such file or directory: '.cci\projects\NPSP\a7a239223ce04ed37caa877a9e5f00117ce3b297\unpackaged\config\regression_bdi_custom_metadata\customMetadata\npsp__Data_Import_Field_Mapping.Account1_State_Province_843b0878f.md

**Comment by mbeaty-sf** [comment]
Hi @miteshmsharma, if you have further issues in the future please be sure to post on the [Power of Us Hub](https://powerofus.force.com/s/topic/0TO80000000DlHzGAK/nonprofit-success-pack) where the community is active in support for issues like this. Troubleshooting is not provided on Github.
