### ISSUE TITLE
Primary Address Type cannot be changed to "None"

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5266]
If the Mailing Address fields are cleared, then when a user changes the Primary Address Type to "-None-" from "Home" then the field switches back to Home, regardless of user input.

**Steps to Recreate**
1. Create a Contact
2. Add an Address into Mailing Address
3. Set the Primary Address Type to "Home"
4. Delete the values in the Mailing Address fields
5. Change the Primary Address Type field to -None-
 
**Result**
Primary Address Type changes back to Home, despite the manual update to -None-

The order of Field History changes that occur shows the change of the field, and then the creation and deletion of a new address _after_ Primary Address Type is changed by the user:

![image](https://user-images.githubusercontent.com/53280203/77126916-eb1bbb80-6a07-11ea-9530-8d8dc04e1942.png)

**Workaround**
There does not appear to be a way to update that field value once it has been changed from -None-

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HttiQAC" target="_blank">W-040327</a>

**Comment by mbeaty-sf** [comment]
Related Hub post - https://powerofus.force.com/s/question/0D51E00005FzMZmSAN/cant-reset-primary-address-type-to-none-after-removing-address

**Comment by jesslopez-sf** [comment]
The behavior changed in NPSP 3.201 -- now the value is changing to "Mailing". Closing this item out and created new item (per engineering team): https://github.com/SalesforceFoundation/NPSP/issues/6522
