### ISSUE TITLE
Audit Fields set as Required on Gift Entry Batch Header at Template Creation

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5273]
Upon creation of a new Gift Entry Template, on the Batch Header section of the template creation adds Created by ID, Created Date, Last Modified by ID, and Last Modified Date as required fields, without Users selecting them. Because they are pulled into the Batch Header in this way, they are required fields and Users must populate them.

**Steps to Reproduce**
1. Enable _"Set Audit Fields upon Record Creation" and "Update Records with Inactive Owners"_ in Setup > User Interface
2. Through Profile permissions or through assigned Permission Set, enable _"Set Audit Fields upon Record Creation"_ for your User
3. Navigate to Gift Entry Tab
4. Click "New Template"
5. Fill in fields as needed and proceed to "Batch Header," the last step in the Template creation
6. See that the fields mentioned above have been automatically pulled into the Batch Header, greyed out, and indicate required fields

![image](https://user-images.githubusercontent.com/53280203/77370564-650cb700-6d1e-11ea-8bd6-dc1a538f12e6.png)

**Workaround**
Typically these permissions are assigned to User records for integration or migration purposes as the "Set Audit Fields upon Record Creation" assigned via Profile or Permission Set to a User allows for the insertion of values into system fields via the API only. Removing this permission from the User creating the Batch Template removes these fields from automatically being pulled into the Batch Header

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtyrQAC" target="_blank">W-040374</a>

**Comment by mbeaty-sf** [comment]
Related Hub Post - https://powerofus.force.com/s/question/0D51E00005GfdADSAZ/anyone-else-experiencing-these-issues-with-the-new-gift-entry-tool

**Comment by ameyersalesforce** [comment]
Nevering this because there is a clear and easy workaround
