### ISSUE TITLE
Error Received after NPSP 3.172 Update - REQUEST_RUNNING_TOO_LONG]

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5281]
When the Nonprofit Success Pack version 3.172 which was pushed to production orgs on Tuesday 24 / morning of Wednesday 25 March, 2020, customers received the following error:

`npsp__UTIL_OrgTelemetry_BATCH: "First error: [REQUEST_RUNNING_TOO_LONG] Your request was running for too long, and has been stopped."`

**Error Message**
Error #1:

Error Type: Batch Apex error
Error Date: 2020-03-25 01:13:49
Message: "First error: [REQUEST_RUNNING_TOO_LONG] Your request was running for too long, and has been stopped."
Context: npsp__UTIL_OrgTelemetry_BATCH

Stack Trace:
null

----------

The feature parameter records for the associated org ID indicates the root cause may may related to the negative integer for the feature parameter:

Feature Parameter: FP-0062
Feature Parameter Full Name: npsp__Data_CountGERowsLast30DaysBatch
Feature Parameter Value: -1

**Comment by mbeaty-sf** [comment]
**lurch: attach W-040424

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hu3wQAC" target="_blank">W-040424</a>

**Comment by mbeaty-sf** [comment]
This issue was fixed in [NPSP Release 3.175](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.175)
