### ISSUE TITLE
Change Owner in Campaign caused Oracle Database error (Exception_Thrown)

### ISSUE THREAD

**Issue by jmun-imentor** [SalesforceFoundation/NPSP#5282]
Hi,
Change Owner (standard button) in Campaign is causing Oracle Database error (**Exception_Thrown**)

`ADV_PackageInfo_SVA` class is using unqualified sObject parameters to run the job  - The assigned variables are `gem_Advancement_Setting__mdt` , `Advancement_Setting__mdt` , `gem_GEM_API_Settings__mdt` and `GEM_API_Settings__mdt`.
This error occurs since 3/10/2020 NPSP updates. Please look into it.
Here is the user debug log:

`50115:59:08.14 (61806898)|METHOD_ENTRY|[94]|01p0M000002F4UM|npsp.ADV_PackageInfo_SVC.useAdv()
50615:59:08.14 (61867609)|METHOD_ENTRY|[148]|01p0M000002F4UM|npsp.ADV_PackageInfo_SVC.setup()
51115:59:08.14 (61921178)|METHOD_ENTRY|[64]|01p30000001ib89|npsp.UTIL_CustomSettingsFacade.getOrgContactsSettings()
52015:59:08.14 (62973906)|VARIABLE_ASSIGNMENT|[340]|npsp.UTIL_CustomSettingsFacade.orgContactsSettings|
52415:59:08.14 (63153008)|METHOD_EXIT|[64]|01p30000001ib89|npsp.UTIL_CustomSettingsFacade.getOrgContactsSettings()
52615:59:08.14 (63261445)|VARIABLE_ASSIGNMENT|[64]|orgSetting|
53015:59:08.14 (63320666)|VARIABLE_ASSIGNMENT|[67]|isManaged|false
55115:59:08.14 (64397862)|VARIABLE_ASSIGNMENT|[70]|this.npsp__Advancement_Namespace__c|"gem"|0x136ecba5
56015:59:08.14 (64574974)|VARIABLE_ASSIGNMENT|[74]|settingsObjs|["Advancement_Setting_ (4 more) ...","GEM_API_Settings__md (1 more) ..."]|0x3fd10004
56915:59:08.14 (64673934)|VARIABLE_ASSIGNMENT|[75]|useGEMFields|["Use_Advancement__c","Use_GEM__c"]|0x5b3ca937
57315:59:08.14 (64715034)|VARIABLE_ASSIGNMENT|[77]|found|false
57715:59:08.14 (64752630)|VARIABLE_ASSIGNMENT|[79]|i|0
59215:59:08.14 (65080416)**|EXCEPTION_THROWN|[82]|System.InvalidParameterValueException: Invalid sobject provided. The Schema.describeSObject() methods does not support the gem__Advancement_Setting__mdt sobject as a parameter. The sobject provided does not exist.**
59615:59:08.14 (65478517)|VARIABLE_ASSIGNMENT|[85]|e|"common.apex.runtime.impl.ExecutionException: Invalid sobject provided. The Schema.describeSObject() methods does not support the gem__Advancement_Setting__mdt sobject as a parameter. The sobject provided does not exist."|0x5927d444
60715:59:08.14 (65678301)|**EXCEPTION_THROWN|[87]|System.InvalidParameterValueException: Invalid sobject provided. The Schema.describeSObject() methods does not support the Advancement_Setting__mdt sobject as a parameter. The sobject provided does not exist.**
61115:59:08.14 (65882277)|VARIABLE_ASSIGNMENT|[89]|ex|"common.apex.runtime.impl.ExecutionException: Invalid sobject provided. The Schema.describeSObject() methods does not support the Advancement_Setting__mdt sobject as a parameter. The sobject provided does not exist."|0x12e18d5
61515:59:08.14 (65919414)|VARIABLE_ASSIGNMENT|[90]|i|1
62915:59:08.14 (66110541)**|EXCEPTION_THROWN|[82]|System.InvalidParameterValueException: Invalid sobject provided. The Schema.describeSObject() methods does not support the gem__GEM_API_Settings__mdt sobject as a parameter. The sobject provided does not exist.**
63315:59:08.14 (66289517)|VARIABLE_ASSIGNMENT|[85]|e|"common.apex.runtime.impl.ExecutionException: Invalid sobject provided. The Schema.describeSObject() methods does not support the gem__GEM_API_Settings__mdt sobject as a parameter. The sobject provided does not exist."|0x36c8e9d4
64415:59:08.14 (66432823)|EXCEPTION_THROWN|[87]|System.InvalidParameterValueException: Invalid sobject provided. The Schema.describeSObject() methods does not support the GEM_API_Settings__mdt sobject as a parameter. The sobject provided does not exist.
64815:59:08.14 (66616868)|VARIABLE_ASSIGNMENT|[89]|ex|"common.apex.runtime.impl.ExecutionException: Invalid sobject provided. The Schema.describeSObject() methods does not support the GEM_API_Settings__mdt sobject as a parameter. The sobject provided does not exist."|0x8038b2b
65215:59:08.14 (66648834)|VARIABLE_ASSIGNMENT|[90]|i|2
65815:59:08.14 (66710669)|VARIABLE_ASSIGNMENT|[96]|npsp.ADV_PackageInfo_SVC.setupCalled|true
66015:59:08.14 (66727658)|METHOD_EXIT|[148]|01p0M000002F4UM|npsp.ADV_PackageInfo_SVC.setup()
66315:59:08.14 (66753098)|METHOD_EXIT|[94]|01p0M000002F4UM|npsp.ADV_PackageInfo_SVC.useAdv()`

**Comment by jmun-imentor** [comment]
<img width="1546" alt="Change Campaign Owner Error - Exception Thrown" src="https://user-images.githubusercontent.com/56774891/77585972-c3bb6780-6ebb-11ea-9a5d-12e62fb4473e.PNG">

**Comment by jmun-imentor** [comment]
![InkedChange Campaign Owner Error - Exception Thrown_LI](https://user-images.githubusercontent.com/56774891/77586238-34628400-6ebc-11ea-9c2c-04a68a045caf.jpg)

**Comment by coriobriensfdo** [comment]
Hi @jmun-imentor We don't provide support here in our GitHub org. Can you post this in the Power of Us Hub [Gem group](https://powerofus.force.com/s/group/0F91E000000XbvASAS/gift-entry-manager-gem) or log a [case with Salesforce](https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case) if you're not in the Hub?
