### ISSUE TITLE
Gift Entry "Batches" Tab only shows 10 records, based on last added "Field to Display"

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5292]
In the Gift Entry Object, when a user clicks on the Batches tab to see previous batches, they are shown 10 records only, and cannot see batches in that tab beyond that. When user chooses "Select Fields to Display" and saves, the List View is updated to show the last 10 records based on that field just added through the "Select Fields to Display" option, making an inconsistent and challenging user experience.

**Steps to Reproduce**
1. In Gift Entry, create more than 10 batches with at least 1 entry to allow them to save
2. Click the "Batches" tab and see 10 of the batches that you have created
3. Click the gear icon in the Batches window and select "Select Fields to Display"
4. Add a new field and save
5. See that the List View has been refreshed, and depending on the field, some batches may no longer be visible through this view

![2020-03-31_12-51-58 (1)](https://user-images.githubusercontent.com/53280203/78069413-ed0e4480-734e-11ea-9674-a673fe6dda00.gif)

**Workaround**
To view all batches, go to NPSP Data Import Batches Object to see all batches and enter them.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HuGgQAK" target="_blank">W-040545</a>
