### ISSUE TITLE
Gift Entry: batch gifts table does not display user-defined field labels in headers

### ISSUE THREAD

**Issue by kenlewis-sfdo** [SalesforceFoundation/NPSP#5342]
When entering gifts for a batch, the column headers on the batch gifts table use the default label (Object Group and the field label) instead of the User-defined label set in the Template Builder.

![giftentrycustomlabel](https://user-images.githubusercontent.com/46458081/79285389-4b204900-7e72-11ea-96a6-54969ef626c2.png)

![giftentrybatchtableheader](https://user-images.githubusercontent.com/46458081/79285420-60957300-7e72-11ea-847f-7bea2d1c8e9a.png)

**Comment by judisohn** [comment]
**lurch: attach W-040810

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hur4QAC" target="_blank">W-040810</a>
