### ISSUE TITLE
Customizable Rollups: Using a null value date filter in a Filter Group generates a System.NullPointerException

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#5344]
### Summary of Issue

Adding a date field filter to a filter group that filters on a null value (either equal or not equal to null) will result in a System.NullPointerException error when the rollup code runs.

example Filter Group filter:
Ask Date Equals 
OR 
Ask Date Not Equals

Full Message of error:
Argument cannot be null.
Rollups State:

### Example Use Case

A nonprofit uses the npsp__Ask_Date__c field on opportunities. It is used to record whether there was a specific ask made for the donation vs whether the donation was unsolicited.  If there was an ask the npsp__Ask_Date__c is populated with the date of the ask. If the donation was unsolicited the npsp__Ask_Date__c field will be blank. 

The nonprofit wants to create a rollup field on contacts which stores the number of opportunities that were associated with an ask for each contact.

### Config Steps to Reproduce:

1. Create a number field on Contact
----- Name: Number of solicited donations
----- Field Type: Number(18, 0)
2. Create a new customizable rollup filter group in NPSP Settings
----- Name: Test Group
----- Name: Description
----- Filter Rule:
		- Object: Opportunity
		- Field: Won
		- Operator: Equals
		- Value: TRUE
----- Filter Rule:
		- Object: Opportunity
		- Field: Ask Date
		- Operator: Not Equals
		- Value: 
3. Create a new customizable rollup
	- Target Object: Contact
	- Target Field: Number of solicited donations
	- Active: TRUE
	- Description: Test
	- Operation: Count
	- Time Frame: All Time
	- Rollup Type: Opportunity -> Contact (Hard Credit)
	- Filter Group: Test Group
4. Create two closed won opportunities - one that has a npsp__Ask_Date__c populated and one which does not
5. Run the Rollup Donations Batch job
6. Check the NPSP Error object and note errors:
	- Context Type: CRLP.ContactHardCredit
	- Error Type: System.NullPointerException
	- Full Message: Argument cannot be null. Rollups State
	- Stack Trace: Stacktrace available at the time of saving the record - (npsp)

Note: The filter group date filter also generates an error in the rollup for Ask Date Equals 

### Expected vs Actual Results

Expected: Rollup calculates successfully and populates the 'Number of solicited donations' field on contacts
Actual: The rollup calculation generates an error and the "Number of solicited donations" is not populated 

### Workaround
A workaround is to create a formula checkbox field on opportunity which evaluates against the Ask Date field and to use this formula field instead of Ask Date in the filter group

**Comment by jamesbsfdc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HutKQAS" target="_blank">W-040832</a>

**Comment by mbeaty-sf** [comment]
W-7781162

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlEHQAY&title=customizable-rollups-using-a-null-value-date-filter-in-a-filter-group-generates-a-system-nullpointerexception) in the Trailblazer Community for updates.
