### ISSUE TITLE
Schedule Payments on payments related list does not handle negative amounts

### ISSUE THREAD

**Issue by preeti-lightful** [SalesforceFoundation/NPSP#5398]
Hello,

Schedule payments button works really well for my client, only thing is it does not handle negative payments, my client has some repayments to handle I am not sure how to handle that in the best way.

Code lies in 
pages/PMT_PaymentWizard.page
classes/PMT_PaymentWizard_CTRL.cls

is there any way to override some of these classes? or do something about it?

![image](https://user-images.githubusercontent.com/32099339/80734019-6e9bf280-8b06-11ea-94ec-460e52128804.png)

**Comment by coriobriensfdo** [comment]
Hi @preeti-lightful we don't provide support for issues or feature requests here on GitHub. Can you post in the Power of Us Hub for[ advice](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack), and/or file a new [Idea](https://powerofus.force.com/s/ideas) the any changes you're proposing?
