### ISSUE TITLE
Enhanced Recurring Donations Migration Validation Picklist Error

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5409]
Existing customers who run the **Validate Migration** process on the "Upgrade to Enhanced Recurring Donation" page may receive an error regarding restricted picklist values on the **Recurring Type field**:
`Recurring Type: bad value for restricted picklist field: Fixed`

![Screen Shot 2020-05-01 at 5 17 19 PM](https://user-images.githubusercontent.com/29731456/80842471-a884fb80-8bcf-11ea-92eb-8a45b4f0d735.png)

### Workaround

- Go to Setup --> Object Manager --> Recurring Donation
- Click on Fields & Relationships
- Click on **Recurring Type**
- Scroll down to Values and click the New button. Enter: Fixed
- Save.

### Full Error
![Screen Shot 2020-05-01 at 5 18 13 PM](https://user-images.githubusercontent.com/29731456/80842613-0c0f2900-8bd0-11ea-8fe0-cb10aeed1b50.png)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZnOQAU" target="_blank">W-041168</a>
