### ISSUE TITLE
Customizable Rollups: GAU Batch: duplicate field selected

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5412]
If customers create a Filter Group related to GAUs and add a Filter Rule which uses the General Accounting Unit field, they receive a "duplicate field selected: General_Accounting_Unit__c" error when their CRLP_GAU_BATCH runs.

### Full Error
```
duplicate field selected: General_Accounting_Unit__c

SELECT Id,General_Accounting_Unit__c,Amount__c,Opportunity__r.IsWon,Opportunity__r.Amount,Opportunity__r.IsClosed,Opportunity__r.AccountId,Opportunity__r.Primary_Contact__c,Opportunity__r.CloseDate,Opportunity__r.npe01__Member_Level__c,Opportunity__r.npe01__Membership_Origin__c,Opportunity__r.npe01__Membership_End_Date__c,Opportunity__r.npe01__Membership_Start_Date__c,Opportunity__r.Id,General_Accounting_Unit__c 
FROM Allocation__c 
WHERE General_Accounting_Unit__c 
IN :recordIds 
ORDER BY General_Accounting_Unit__c, CreatedDate ASC
```

### Stack Trace
```
Stacktrace available at the time of saving the record -
Class.CRLP_Batch_Base_Skew.start: line 112, column 1
```

### Analysis
Seemed semi-similar to this error we had on Soft Credit Rollup jobs a few months ago but resolved:
[https://github.com/SalesforceFoundation/NPSP/issues/4899
](https://github.com/SalesforceFoundation/NPSP/issues/4899
)PR: [https://github.com/SalesforceFoundation/NPSP/pull/4901](https://github.com/SalesforceFoundation/NPSP/pull/4901)

We build the query in CRLP_Query_SEL. [Lines 145-147 add the General_Accounting_Unit__c field to the query that was previously built on line 128 and 143.](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/CRLP_Query_SEL.cls#L145-L147)
```
if (detailObject == Allocation__c.SObjectType) {
   mainSoql += ',' + SObjectType.Allocation__c.fields.General_Accounting_Unit__c.getName();
}
```

In an unmanaged scratch org, I modified those lines to only add the General_Accounting_Unit__c field if the mainSoql String didn't already contain it. This resolved the error.
```
if (detailObject == Allocation__c.SObjectType) {
   if(!mainSoql.contains(SObjectType.Allocation__c.fields.General_Accounting_Unit__c.getName())){
      mainSoql += ',' + SObjectType.Allocation__c.fields.General_Accounting_Unit__c.getName();
   }
}
```

### Steps to Repeat

- Enable Customizable Rollups
- Create General Accounting Unit (Name = ‘Restricted Fund’)
- Create Contact
- Create Opportunity associated with Contact
- Click the Manage Allocations button on the Opportunity and assign 100% to the Restricted Fund.
- Go to the Restricted Fund detail page. Click the Recalculate Rollups button
- Confirm no errors

Now, go to NPSP Settings → Customizable Rollups → Configure → View Filter Groups
- Add a new Filter Group and make sure you have a Filter Rule with the following criteria:
- - Object: GAU Allocation
- - Field: General Accounting Unit
- - Operator: Equals
- - Value: Restricted Fund
- Save and go to your Restricted Fund detail page.
- Click the Recalculate Rollups button.
- You will receive a “duplicate field” error when viewing the Error Log in NPSP Settings.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZqhQAE" target="_blank">W-041208</a>

**Comment by mbeaty-sf** [comment]
W-7528632

**Comment by briangazamilehigh** [comment]
Is there a work around for this issue? And is there a target for deployment of the resolution to close the issue?

We are running NPSP version 3.207 and have run into some reporting issued with GAU Rollups

Thanks!

**Comment by jesslopez-sf** [comment]
Hi @briangazamilehigh , I don't see a delivery date for it yet. If you haven't already opened a Case for this, please do so that we can tie your report to the bug we have in our system. I'll also let the team know that we've had another report surface. Thank you!

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlECQAY&title=customizable-rollups-gau-batch-duplicate-field-selected) in the Trailblazer Community for updates.
