### ISSUE TITLE
Gift Entry tab throws null object error when standard data mapping group is empty

### ISSUE THREAD

**Issue by davidchengIC** [SalesforceFoundation/NPSP#5416]
I've enabled the new Gift Entry feature in a sandbox.  I'm getting an error "Attempt to de-reference a null object" error when I click on the tab.  This is because I've deleted all field mappings for the standard Payment Group because we want to use the Linvio Payment object instead of the NPSP Payment.

If I put one field mapping back into the standard Payment Group, then the error goes away, but we don't want this.

**Comment by coriobriensfdo** [comment]
[Hub Post](https://powerofus.force.com/s/question/0D51E00005B5ZFLSA3/gift-entry-tab-throws-error-when-data-mapping-group-is-empty)

**Comment by mbeaty-sf** [comment]
**lurch: attach W-039432

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsGBQA0" target="_blank">W-039432</a>

**Comment by mbeaty-sf** [comment]
Additional related [Hub post](https://powerofus.force.com/s/question/0D51E00005JKQKlSAP/error-attempt-to-dereference-a-null-object)
