### ISSUE TITLE
System fields present on batch template cause unhelpful error when permission removed

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5426]
Users creating batches that have "Set Audit Fields upon Record Creation" and/or "Update Records with Inactive Owners" User Permissions, will see system fields included in the batch template by default, and automatically required: 

- Created By ID
- Created Date
- Last Modified By ID
- Last Modified Date

![image](https://user-images.githubusercontent.com/53280203/81221960-6c1f1a00-8f98-11ea-8247-3b8294618d81.png)

When a user is in the batch, trying to set these values, there is an error as these fields are not meant to be manually edited.

To rectify this, the User creating the template should have the permission removed; however, if a they attempt to edit a template that included those system fields before the permission was removed, attempting to edit it again will provide an unhelpful error, in terms of describing the issue:

![image](https://user-images.githubusercontent.com/53280203/81222094-9e307c00-8f98-11ea-8c9e-d9cc0dcced7d.png)

**Steps to Recreate**
1. Enable Gift Entry in Org
2. In Setup > User Interface > check the **Enable "Set Audit Fields upon Record Creation" and "Update Records with Inactive Owners" User Permissions** setting
3. Create a Permission set that included the permission from step 2, and assign it to your User
4. Go to Gift Entry and create a new Batch Template, notice that the system fields are included in the Batch Header, the third page in the creation process, save the template
5. Remove the permission set created in step 3 from your user record
6. Return to the Gift Entry template you created and attempt to edit it. When you attempt to edit the third page, the Batch Header, notice the error shown in the picture above

**Workaround**
Create the template with a User that does not have the "Set Audit Fields upon Record Creation" and "Update Records with Inactive Owners" permissions active, **do not clone the previous template**, and the system fields will not be included.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZyWQAU" target="_blank">W-041289</a>

**Comment by mbeaty-sf** [comment]
Another thread - https://powerofus.force.com/s/question/0D51E00005JMEsESAX/gift-entry-batch-header-now-requiring-extra-system-fields

**Comment by psadie-sfdo** [comment]
Manually closing this issue since the related [PR](https://github.com/SalesforceFoundation/NPSP/pull/5534/commits/0fe80c03b3d3e65d56586316e6accebc69634d69) has been merged.
