### ISSUE TITLE
Removing Primary Contact without First Name on Manage Household page does not actually remove Primary Contact

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5427]
2 Contacts with no First Name are added to a Household through the Manage Household button. If the original Contact that was Primary Contact of the Household the Manage Household button was push on is removed:

- The Manage Household page's Primary Contact field is not cleared out
- Upon saving, the original Primary Contact remains the Household's Primary Contact
- Both Contacts are merged into the new Household

![2020-05-06_14-17-44 (1)](https://user-images.githubusercontent.com/53280203/81241189-77853c00-8fbe-11ea-99bc-b04b02d21886.gif)

**Steps to Recreate**
1. Create a contact without a first name
2. Visit that household, and add another contact without a first name to the same household
3. Click Manage Household
4. Click "X" on the contact that is currently a Primary Contact. Leave the Primary Contact field untouched
5. Click "Remove" on the modal that appears.
6. Click Save
7. Notice that the household name may change briefly. The Primary Contact field is still the same as before

**Workaround**
Give the Contacts placeholder First Name values, in order for the Household separation process to properly execute.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZyqQAE" target="_blank">W-041293</a>

**Comment by mbeaty-sf** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000007hZyqQAE" target="_blank">W-041293</a>

**Comment by mbeaty-sf** [comment]
W-7540256

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlE7QAI&title=removing-primary-contact-without-first-name-on-manage-household-page-does-not-actually-remove-primary-contact) in the Trailblazer Community for updates.
