### ISSUE TITLE
Gift Entry - Error: You do not have permissions to access npsp__Allocation__c.npsp__Payment__c

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5436]
Upon following the setup steps for Gift Entry, when trying to run a dry run or import a gift, error is displayed: **You do not have permissions to access npsp__Allocation__c.npsp__Payment__c**

The configuration steps for Gift Entry (https://powerofus.force.com/s/article/NPSP-Configure-Gift-Entry) do not include the field on GAU Allocations: Payment (npsp__Allocation__c.npsp__Payment__c)

**Steps to Recreate**
1. Follow Setup steps - https://powerofus.force.com/s/article/NPSP-Configure-Gift-Entry
2. Try to create gifts in a batch for Gift Entry
3. Notice that the error is displayed on gifts entered

**Workaround**
Go to the Permission Set created for Gift Entry > add GAU Allocations > Payment field: update to Read/Edit Permissions as needed

**Comment by mbeaty-sf** [comment]
**lurch: attach W-039144

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hri7QAC" target="_blank">W-039144</a>

**Comment by dfuller114** [comment]
issue fixed by #5927
