### ISSUE TITLE
Existing Recurring Donation with "Day of Month" as 29th creates Error and Partially Stops Upgrade of Enhanced Recurring Donations

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5437]
When following the steps in NPSP Settings to upgrade to Enhanced Recurring Donations, if an Org has existing Recurring Donations that has a value in Day of Month field as 29th, or 30th, Enhanced Recurring Donations Upgrade partially fails, meaning that on the Validation under step 4 of the Upgrade Recurring Donations Setting, user cannot proceed to "Ready to Migrate" button.

![image](https://user-images.githubusercontent.com/53280203/81448647-95c07880-9133-11ea-9765-90ce0ccaefbb.png)

![image](https://user-images.githubusercontent.com/53280203/81448669-9f49e080-9133-11ea-9273-b0928359bd99.png)

<br>
<br>

**Steps to Reproduce**
1. Create a Recurring Donation in an org where Enhanced Recurring Donations is not enabled yet.
2. On the Recurring Donation, set the "Day of Month" (npsp__DayOfMonth__c) to 29 or 30 and save record
3. Go to NPSP Settings and follow through the Enhanced Recurring Donation setup wizard.
4. When clicking on the "Validate Migration" button, notice the error notification, and that the "Read to Migrate" button will not appear
5. Go to NPSP Settings > System Tools > Error Log and see that there is an error for the Recurring Donation

After running the validation, any attempt at creating or editing a Recurring Donation with a Day of Month value of 29th or 30th will result in an error:

![image](https://user-images.githubusercontent.com/53280203/81448634-8f320100-9133-11ea-99a0-2dd5937f3bd1.png)
![image](https://user-images.githubusercontent.com/53280203/81449515-45e2b100-9135-11ea-9776-ae1b7109151a.png)

During this time the Instalments will not load, until the number is corrected to be <= 28 OR set to Last Day of Month:
![image](https://user-images.githubusercontent.com/53280203/81449149-7a09a200-9134-11ea-9c9b-ac629d232bbf.png)

<br>
<br>

**Workaround**
None at this time.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007ha7OQAQ" target="_blank">W-041362</a>
