### ISSUE TITLE
Contact Address doesn't prefill in Gift Entry

### ISSUE THREAD

**Issue by ameyersalesforce** [SalesforceFoundation/NPSP#5439]
Steps to repro:
1. Create a household contact record
2. Add a Mailing Address
3. In Gift Entry, select the contact as the donor
4. See that other related information (email, phone) correctly displays, but address does not

Other notes:
* Address display works correctly for organization accounts

**Comment by melissabarber** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007ha9qQAA" target="_blank">W-041372</a>

**Comment by melissabarber** [comment]
Workaround for this limitation documented here: https://powerofus.force.com/s/article/NPSP-Configure-Gift-Entry#ariaid-title8

**Comment by davidchengIC** [comment]
@melissabarber Can you post an updated link for the workaround?

**Comment by melissabarber** [comment]
https://help.salesforce.com/s/articleView?id=sfdo.npsp_gift_entry.htm
