### ISSUE TITLE
"First error: duplicate field selected: npsp__Payment_Type__c" when processing DI records

### ISSUE THREAD

**Issue by ameyersalesforce** [SalesforceFoundation/NPSP#5444]
[Hub Post](https://powerofus.force.com/s/question/0D51E00005B7Nh3/new-behavior-generating-error-with-npsp-3175-first-error-duplicate-field-selected-npsppaymenttypec)

**Steps to reproduce:**
1. Enable Advanced Mapping 
2. Add a custom field Payment Type (Payment_Type__c) onto the DI object
3. Add a custom field Payment Type (Payment_Type__c) onto the Payment object
4. Map Payment Type through Advanced Mapping
5. Attempt to process a DI record and get an error

Note that this issue was introduced when we added the Payment_Type__c field on the DI into the managed package on 5/5, version 3.175

**Comment by ameyersalesforce** [comment]
**lurch: add

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007haBrQAI" target="_blank">W-041396</a>

**Comment by mbeaty-sf** [comment]
Another instance of this - https://powerofus.force.com/s/question/0D51E00005TUGk2SAH/two-problems-implementing-the-apex-update

**Comment by mbeaty-sf** [comment]
W-7781025
