### ISSUE TITLE
In One-to-One model, how to redirect to a Contact record when I access an Account record.

### ISSUE THREAD

**Issue by shinchit** [SalesforceFoundation/NPSP#5451]
Hi.

In NPSP v3.175 environment, I selected One-to-One model.
In my old environment (Contacts & Organizations's version is 2.1.4), creating a Contact creates an Account with the surname and first name reversed. And when I visited an Account record, I was redirected to a Contact record.

I want this redirect to be performed even in the latest NPSP environment. Is there a setting method?

**Comment by jamesbsfdc** [comment]
Hi @shinchit 

Unfortunately we don't provide support via GitHub issues. Would you mind posting this in the Power of Us Hub? We can reply to your post there and direct you to relevant resources? 

If you are working with a nonprofit or educational institution you can login to the Power of Us Hub with your production login. Let me know if you do not have access.

**Comment by shinchit** [comment]
Hi @jamesbsfdc .
Thank you for your reply.

I understand.
I'll try to access Power of Us Hub.
