### ISSUE TITLE
Upgrade to Enhanced Recurring Donation Failing because of npsp__DayOfMonth__c]

### ISSUE THREAD

**Issue by AimGee** [SalesforceFoundation/NPSP#5456]
Receiving the error below when I am validating migration: I can confirm that the value 30 exists as an option in the mentioned picklist

npsp.TDTM_RecurringDonation: execution of AfterUpdate caused by: System.DmlException: Insert failed. First exception on row 0; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, Day of Month: bad value for restricted picklist field: 30: [npsp__DayOfMonth__c] (npsp)

**Comment by coriobriensfdo** [comment]
Hi @AimGee this is a [known issue](https://github.com/SalesforceFoundation/NPSP/issues/5437) (we closed it this week). We don't actually provide support here in GitHub though, so can I ask you to post in the Power of Us Hub [NPSP Group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) if you have any further issues or questions?
