### ISSUE TITLE
Scheduled Jobs Fail With "Unable to retrieve file from FFX, transient error"

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5501]
Some customers have reported seeing the following errors when some NPSP nightly batch jobs run:

```
Developer script exception
Unable to retrieve file from FFX, transient error?
```

This also shows up in Setup -->Scheduled Jobs with the following error:
**_Scheduler: failed to execute scheduled job: jobId: 7071N0000BXtfQQ, class: common.apex.async.AsyncApexJobObject, reason: Unable to retrieve file from FFX, transient error?: 7071N0000BXtfQQ_**

<img width="1490" alt="Screen Shot 2021-01-13 at 1 12 27 PM" src="https://user-images.githubusercontent.com/29731456/104492054-1bd56e80-55a1-11eb-9742-17fdbca61c60.png">

Not all customers are impacted by this issue. We've seen most cases around the following Scheduled Jobs:

- NPSP 01A - Customizable Rollups - Account Hard Credit 
- NPSP 02A - Customizable Rollups - Contact Hard Credit

The workaround at this time is to delete the affected Scheduled Job(s) and reschedule. [Instructions for rescheduling NPSP jobs can be found here](https://powerofus.force.com/s/article/NPSP-Edit-or-Reschedule-NPSP-Scheduled-Jobs). Summary below:

1. Go to Setup --> Scheduled Jobs.
2. Click the "Del" link next to the Scheduled Job throwing the error.
3. Then, go to **NPSP Settings** | **Bulk Data Processes** | **Batch Process Settings**. This will automatically reschedule the default NPSP Scheduled jobs... unless you have the option for "Don't Auto Schedule Default NPSP Jobs" checked off. (If that's the case, you'll need to go to Setup --> Apex Classes and click the Schedule Apex button).

**Comment by jesslopez-sf** [comment]
W-7591724
W-7591770

**Comment by jesslopez-sf** [comment]
SFDO: W-8718207

**Comment by ameyersalesforce** [comment]
Closing this issue without providing a product resolution because it's a one-time issue that will not recur (as far as we can control) and the potential productized resolution is too risky and complex. Steps to resolve are in the ticket above and are posted in the Hub.
