### ISSUE TITLE
NPSP Data Import Batches - records not loading

### ISSUE THREAD

**Issue by delan-flywheel** [SalesforceFoundation/NPSP#5502]
**Issue**
When trying to view NPSP Data Import Batches records, the records will not load.

Specifically, we are currently only able to view NPSP Data Import Batch records that do not have the Gift Batch checkbox populated. The one test record we created without the Gift Batch checkbox populated does load for the user. I am not sure why that is.

**Steps to Reproduce**
1. Create a Batch Gift Entry with the Gift Batch checkbox filled in. 
2. Move to the NPSP Data Import Batches view.
3. The record will not load.

**Expected Result**
When a user clicks on a record, they should be able to view the record and work with it to upload donations and gifts.

**Actual Result**
The records do not load, although surrounding Salesforce page components do load.

Screenshots of the test record that does load and one of all the other records that are not loading should follow.

![npspdataimportnotloading](https://user-images.githubusercontent.com/52504590/82574238-cc938700-9b54-11ea-81be-b903863fc675.PNG)

![npspdataimporttestloading](https://user-images.githubusercontent.com/52504590/82574256-d0bfa480-9b54-11ea-912e-7f06840aed0c.PNG)

**Comment by mbeaty-sf** [comment]
Hi @delan-flywheel thank you for writing up such a detailed Issue; however, we don't provide support on Github. Can you please post this in the [Power of Us Hub - Nonprofit Success Pack group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) so we can support it there? Thank you!

**Comment by seeintl** [comment]
any solution for this?

**Comment by jamesbsfdc** [comment]
@seeintl This is a closed issue and we do not provide support via Github

Please log a support case if you are facing an issue: 
https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case
