### ISSUE TITLE
Enhanced Recurring Donations: Installment Number and Installment Name fields incorrectly counting for Open Recurring Type

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#5512]
[**Hub Post**](https://powerofus.force.com/s/question/0D51E00005JMpXuSAL/enhanced-recurring-donation-installment-number)

**Issue**:
Child Opty Donations on an Open Recurring Type Enhanced Recurring Donation are incorrectly counting the Recurring Donation Installment Number and Recurring Donation Installment Name fields. 
When the "Open" ERD is created, the first Opty's "Recurring Donation Installment Number" is set as 1, and "Recurring Donation Installment Name" formula field is resulting as (1 of 0). The second Opty (created when the first is marked Closed/Won), is also set as 1 with the name resulting as (1 of 0). The third however (created when the second is marked as Closed/Won) is  "Recurring Donation Installment Number" = 2, and "Recurring Donation Installment Name" = 2 of 0. 

**Steps to Reproduce:**

1. In an org that has been upgraded to Enhanced Recurring Donations, create a new Enhanced Recurring Donation with the Recurring Type as "Open". 
2. Note the resulting child Opty has an Installment Number =1 and Installment Name = 1 of 0. _Expected result:_ The Installment Number would be 1 and the Installment Name would be 1 of 1.
3. Mark that child Opty as Closed/Won and save. 
4. Refresh, and note that a second child Opty has been created.
_Expected result:_ The second child Opty should be created with Installment Number and Installment Name as 2, and 2 of 2 respectively.
Actual result: The second child Opty has been created with Installment Number and Installment Name as 1, and 1 of 0 respectively.
5. Open the second child Opty and mark it as Closed/Won. 
6. Refresh, and note that a third child Opty has been created.
_Expected result:_ The third child Opty should be created with Installment Number and Installment Name as 3, and 3 of 3 respectively.
Actual result: The second child Opty has been created with Installment Number and Installment Name as 2, and 2 of 0 respectively.

![Screen Shot 2020-05-22 at 11 10 45 AM](https://user-images.githubusercontent.com/37851761/82696930-e7c9c980-9c1c-11ea-9f0b-c4335b1fd88b.png)

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hajFQAQ" target="_blank">W-041639</a>

**Comment by RadSFDeveloper** [comment]
@coriobriensfdo , when a future Opp is *Closed Won*, Salesforce automatically sets its Close Date to today. This is standard Salesforce and we cannot override it.
If the future Opp Close Date was within 3 days of the next Installment Opp date, the connection between the Opp and Installment would not be lost. However, we have June 22 to May 22 date difference, thus installment the RD2 framework will create a new Opp for June 22 since the next installment Opp date is June 22 and there is no matching Opp for the date. This is expected.
Is the above data result of specific testing to reproduce the issue?
FYI @mpusto , @force2b

**Comment by coriobriensfdo** [comment]
Thanks for clarifying re: SF defaulting the Close Date to today when I mark as Closed/Won. I hadn't noticed that before! :) I'll remove that portion of the Issue.

**Comment by RadSFDeveloper** [comment]
No prob, thanks for the verification @coriobriensfdo !

**Comment by mpusto** [comment]
Correct WI: [W-7608925](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000088ocvIAA/view)

**Comment by DDshoyland** [comment]
Still experiencing this issue. Is there a batch job we can run through NPSP Settings to correct this?

**Comment by jamesbsfdc** [comment]
Hi Sondre, we don't offer support via GitHub issues. Would you mind posting in the Power of Us Hub about this or logging a support case. Thanks

**Comment by DDshoyland** [comment]
Thanks for the quick response! Posted through Power of Us by a colleague: [https://powerofus.force.com/s/feed/0D57y00000FV0mKCAT]
