### ISSUE TITLE
Enhanced Recurring Donations: Automatic Naming using Primary Contact name instead of Account Name for non-HH RD's

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#5514]
**Issue:**

With RD2 we can add an Account and a Contact at the same time. This is ideal for orgs that want to report RD’s on the HH Account. 
But, when adding an Organization Account (or any non HH Account), and also including the Contact (say this is a company that’s giving a gift, and I need to track the contact person involved) also happens to have her own Household Account), there is some unexpected behaviour around the Automated RD Naming. Instead of using the Account's name as expected, the RD and child Donation Opty's are named using the Contact's name.

This is only applicable for Enhanced RD's because you can't select both an Account and a Contact on Legacy Recurring Donations.

**Steps to Reproduce:**

1. In an org with ERD enabled and Automatic Recurring Donation Naming turned on, click New on the Recurring Donations Tab.
2. Add an Organization Account (or any other non Household Account) to the Account field. Leave the Contact field empty for now. Complete other required fields and Save to create the new RD.
3. Note the RD Name reflects the Account Name $Amount - Recurring as expected. Note the related child Donation Opty's also reflect the Company Name.
4. Click Edit, and add a Contact that resides in a Household Account, and click Save. 
_Expected:_ The RD and child Donation Opty's will keep the naming format as is, the Company Name.
_Actual:_ The RD and child Donation Opty's are renamed to reflect the Contact's name.

If the RD is initially created with the Company Name in Account and the contact in Contact, the same results occur (uses Contact name rather than Company Name).

Using Company as Account:
![Screen Shot 2020-05-22 at 2 23 34 PM](https://user-images.githubusercontent.com/37851761/82712162-4d797e00-9c3c-11ea-9df1-69732e1488ce.png)

Editing to add Contact:
![Screen Shot 2020-05-22 at 2 23 52 PM](https://user-images.githubusercontent.com/37851761/82712163-4e121480-9c3c-11ea-9836-9a35daa814a1.png)

Final unexpected result:
![Screen Shot 2020-05-22 at 2 24 04 PM](https://user-images.githubusercontent.com/37851761/82712166-4eaaab00-9c3c-11ea-8eae-bb52a07e70fd.png)

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hajeQAA" target="_blank">W-041644</a>

**Comment by mbeaty-sf** [comment]
Issue Closed in [NPSP Release 3.179](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.179)
