### ISSUE TITLE
Payment Authorization Token Error Surfaced During Advanced Mapping Enablement

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5529]
When enabling Advanced Mapping via NPSP Settings, customers may see a warning about an invalid Help Text Mapping for the **Payment Authorization Token** field. This can be ignored for now and should not affect current functionality.

**Steps to Repeat**

- Go to NPSP Settings --> System Tools --> Advanced Mapping for Data Import & Gift Entry
- Click the toggle to enable Advanced Mapping

![Screen Shot 2020-06-01 at 9 33 29 AM](https://user-images.githubusercontent.com/29731456/83414400-71cb1c80-a3eb-11ea-9f50-f9191cc20cc4.png)
![Screen Shot 2020-06-01 at 9 33 35 AM](https://user-images.githubusercontent.com/29731456/83414403-74c60d00-a3eb-11ea-8448-adccfaca2f9d.png)

**Comment by jesslopez-sf** [comment]
**lurch: attach W-041131

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZgrQAE" target="_blank">W-041131</a>
