### ISSUE TITLE
Opty Naming Class: "Attempt to de-reference a null object." error when Site Guest User creates an Opportunity

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#5533]
**Issue:** When Padlock Site Guest User security settings are enabled and Default Site Guest User record owner option is used for force.com sites, the NPSP Classes built as "with sharing" are failing. Query's run as the Site Guest User that need to locate a record owned by another User (due to default enabled) cannot find the record as Sharing Rules fire after Triggers.

**Steps to Reproduce** (in an org that has NPSP and an Opty Naming rule configured in NPSP Settings):
1. Enable Sites and create a Site URL to create a Site Guest User
2. Enable Padlock ("Secure guest user record access" on Sharing Settings page in Setup)
3. Enable "Assign new records created by Salesforce Sites guest users to a default owner in the org" setting on Sites page. Define a default on the site itself. 
4. Use the Site URL to create an Opportunity record (for example as part of an ISV partner integration), and note the error. While the error is received, the Opty record should be created as expected. The NPSP Opty naming class "Opp_OpportunityNaming" will have failed to run, preventing the name of the new Opty from being set per the naming rule.
5. Delete the Opty Naming Rule in NPSP Settings or disable the default setting and test again. Note there is no error when the Opty is created.

_For further details see internal GUS Investigation W-7544682_

**Cause:** The NPSP's Opty Naming class Opp_OpportunityNaming is setup as "With Sharing", which prevents the Site Guest User running the naming class from locating the newly created Opty during it's SOQL Query. 
**Potential Solution:** Modify the Opty Naming class Opp_OpportunityNaming to use "Inherited Sharing". Initial testing of this solution has been successful, however additional risk assessment and testing is needed.

**Comment by coriobriensfdo** [comment]
**lurch: attach: W-042146

**Comment by coriobriensfdo** [comment]
**lurch: attach W-042146

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbfmQAA" target="_blank">W-042146</a>
