### ISSUE TITLE
Contact Deletion Confirmation Pop-Up Doesn't Appear in Lightning

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5542]
When you delete a Contact in Salesforce (out of the box, no NPSP installed), a popup appears and asks if you're sure you want to delete the Contact. This works in both Classic and Lightning.

**Classic:**
![Screen Shot 2020-06-03 at 4 34 36 PM](https://user-images.githubusercontent.com/29731456/83686390-2154ea00-a5b8-11ea-8ed3-b23c8e434a33.png)

**Lightning**
![Popup Lightning](https://user-images.githubusercontent.com/29731456/83686413-287bf800-a5b8-11ea-9036-e3f4e4ea53ea.png)

If you apply a Visualforce Override to the Delete Button on the Contact, however, the popup fails to load in Lightning. We apply an override of CON_DeleteContactOverride to that button in order to display options to the customer when they delete a Contact who is the last Contact within a Household Account. 

The Contact Delete button does not have a Lightning-specific Override the way that some default Buttons do. 

### Steps to Repeat
1. In org with NPSP and Lightning experience, create a Contact. 
2. Delete the Contact. It will take you right to our override page asking if you'd like to delete the Account as well (among other options).
3. Switch to Classic
4. Create a Contact
5. Delete that Contact. A javascript pop-up appears asking you to confirm if you really want to delete the Contact. If you agree, it will take you to our override page.
6. Now go to Setup --> Object Manager --> Contacts --> Buttons, Links, and Actions. Click the down arrow next to "Delete" and select Edit.
7. Choose the "No Override" option and click Save.
8. Create a Contact.
9. Delete that Contact. Observe a pop-up asking you to confirm if you'd like to delete the Contact.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbBjQAI" target="_blank">W-041871</a>

**Comment by mbeaty-sf** [comment]
W-7656779

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlE2QAI&title=contact-deletion-confirmation-pop-up-doesn-t-appear-in-lightning-experience) in the Trailblazer Community for updates.
