### ISSUE TITLE
Translation Workbench Override causes Component Error in Gift Entry

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5546]
If a field has been translated/overridden through Translation Workbench, Advanced Mapping/Gift Entry it causes a a Component Error Pop-up when starting a new batch, or using Single Gift Entry, with a template referencing that field.

AND

When trying to delete the field from a template where it is referenced.

**Example 1**
Component Error Pop-up when starting batch with template that references Translation Overridden:

![image](https://user-images.githubusercontent.com/53280203/83914187-95f96700-a725-11ea-813d-5615b9b80804.png)
![image](https://user-images.githubusercontent.com/53280203/83914204-9db90b80-a725-11ea-9f06-c2a88f9cf242.png)

**Example 2**
Component Error Pop-up when trying to remove error causing field from template

Trying to delete renamed field from template
![image](https://user-images.githubusercontent.com/53280203/83914464-1c15ad80-a726-11ea-8a83-a7b37449d880.png)

Showing that the same field reference, while no Advanced Mapping has been additionally created, can be added to the page as well:
![image](https://user-images.githubusercontent.com/53280203/83914535-3f405d00-a726-11ea-95fe-709d5b108f1f.png)

**Steps to Reproduce**
1. Spin up a scratch org with NPSP 3.176 or higher installed
2. Goto Translation Workbench > Override > and select the filters as below
![image](https://user-images.githubusercontent.com/53280203/83914576-53845a00-a726-11ea-9bc1-f8c3e4dd320a.png)
3. Now choose any field for ex: Donation Date
4. Override it to Gift Date and save
5. Now follow the steps on this doc(https://powerofus.force.com/s/article/NPSP-Configure-Gift-Entry) and set up Gift Entry
6. Goto App Launcher
7. Open Gift Entry
8. Click on New Single Gift
8a. Alternatively create new batch and upon proceeding to enter first gift, encounter error
9. Fill in the details and click save

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by mbeaty-sf** [comment]
W-7781024

**Comment by kporray1** [comment]
Please follow this[ Known Issue ](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlDxQAI&title=translation-workbench-override-causes-component-error-in-gift-entry)in the Trailblazer Community for updates.
