### ISSUE TITLE
Deleting Field from Advanced Mapping causes Gift Entry Script Error

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5566]
Gift Entry uses the Default Gift Entry Template for Single Gift Entry, but also manually created batches. There are two similar scenarios:

1. If a user deletes a custom field that is used in an Advanced Field Mapping reference, Gift Entry, and Advanced Field Mapping become inaccessible until the Custom Metadata Type is deleted manually. 

NPSP Settings > System Tools > Advanced Mapping for Data Import & Gift Entry > **Configure Advanced Mapping**
![image](https://user-images.githubusercontent.com/53280203/84448241-f47b8500-abfe-11ea-876a-b716fc66e15e.png)

<br>
<br>

**Gift Entry**
![image](https://user-images.githubusercontent.com/53280203/84447171-28a17680-abfc-11ea-8171-c31f24eb9db8.png)

2. If a field that is referenced in the initial Default Gift Entry Template creation static resource (https://github.com/SalesforceFoundation/NPSP/blob/master/src/staticresources/DefaultGiftEntryTemplate.resource) is removed from that Advanced Mapping.

Then the error persists in Single Gift Entry, creating a Batch with the Default Template, and when editing the Default Template to try to remove the field in question.

![image](https://user-images.githubusercontent.com/53280203/84448347-46bca600-abff-11ea-8e37-5d343a4de059.png)

<br>
<br>

**Steps to Reproduce**

_Scenario 1_
1. Create custom field on Object, such as Payment Object, 
2. Create custom field on NPSP Data Import Object
3. Enable and configure Advanced Field Mapping and Gift Entry if you have not already (https://powerofus.force.com/s/article/NPSP-Configure-Gift-Entry)
4. Create a new Field Mapping under the Object Group of the Object you created the custom field for in step 1
5. Delete the field you created in Step 1
6. Attempt to access NPSP Settings > System Tools > Advanced Mapping for Data Import & Gift Entry > **Configure Advanced Mapping**
7. See error pictured in scenario 1 above, cannot proceed

_Scenario 2_
1. Go to NPSP Settings > System Tools > Advanced Mapping for Data Import & Gift Entry > **Configure Advanced Mapping**
2. Find Payment Object Group
3. Access Field Mapping in Payment Group
4. Delete the "Payment Method" Field Mapping
5. Go to Gift Entry
6. Edit the Default Gift Entry Template
7. Attempt to delete the Payment Method field from the template
8. See error pictured in scenario 2 above

<br>
<br>

**Workaround**

_Scenario 1_

- If user wants to add the field back, either create a field with the exact same name as before, or find the field mapping in the Custom Metadata Type and delete it and recreate the mapping in Advanced Field Mapping.
- If user wants to get rid of the field entirely, go to Custom Metadata Types > Data Import Field Mappings > Manage Data Import Field Mappings > find the field mapping referencing the target field you deleted, and delete the Data Import Field Mapping Custom Metadata

_Scenario 2_
- Custom Metadata Types > Data Import Field Mappings > Manage Data Import Field Mappings > find the field removed from Advanced Field Mapping and uncheck the "IsDeleted" checkbox to allow the Payment method to appear again in the template

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbSLQAY" target="_blank">W-042035</a>

**Comment by coriobriensfdo** [comment]
See Issue #5567 to reference specific Advanced Mapping error

**Comment by mbeaty-sf** [comment]
W-7781023

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7781023)
