### ISSUE TITLE
Advanced Mapping: Error "500 Server Error Invalid field name ‘<deleted field>'" 

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#5567]
[Hub Post](https://powerofus.force.com/s/feed/0D51E00005K551HSAR)

**Issue:**
Error is presenting within NPSP Settings Advanced Mapping setup when a deleted field has already been mapped in Advanced Mapping.
Error: "500 Server Error Invalid field name ‘<deleted field>'". Deleted field represents whichever field was deleted (API name).
![Screen Shot 2020-06-01 at 10 12 19 AM](https://user-images.githubusercontent.com/37851761/84522919-4dddc580-ac8c-11ea-928e-4dc7098026ff.png)
See similarly related error #5566 

**Cause:**
Advanced Mapping stores field mapping in the Data Import Field Mapping Custom Metadata Type. The Target API Name is a text field containing the api name of the field; it’s not a lookup to the actual field (if it were, it would prevent the field from being deleted since it was referenced in a CMT).

**Proposed Solutions:**
1. At minimum can the presented error message be refined to be more explanatory to the user? The current error message doesn't allow most users to determine the cause, and sort out how to resolve it.
2. Add Error resolution and workaround instructions to the [Troubleshoot the NPSP](https://powerofus.force.com/s/article/NPSP-Troubleshooting) Doc and [Advanced Mapping](https://powerofus.force.com/s/article/NPSP-Enable-Convert-Advanced-Mapping) doc (wherever appropriate) 
3. Investigate how we could prevent the deletion of a field that is referenced in Advanced Mapping.

**Workarounds:**
To remove the error and allow access to the Advanced Mapping settings, Admin can either restore or recreate the deleted field using the exact name. If removed from Mapping before deleting, deleting the field won't cause an error. 
Another option is for the Admin to delete the CMT record for that field in Setup --> Custom Metadata Types --> Data Import Field Mapping.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbTbQAI" target="_blank">W-042049</a>

**Comment by mbeaty-sf** [comment]
W-7691710

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7691710)
