### ISSUE TITLE
"See Duplicate Contact" option on NPSP Contact Merge shows error: Map key <DRS Record ID> not found in map

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#5568]
[Hub Post](https://powerofus.force.com/s/question/0D51E00005K6dpUSAR/error-when-trying-to-use-duplicate-contact-button-on-contact-merge)

**Issue:**
When a Contact is created that matches a Lead, a Duplicate Record Set (DRS) is created using a Lead duplicate rule. When the customer clicks on the See Duplicate Contacts button on the NPSP Contact Merge tab, the CON_ContactMerge_CTRL class has a method called showDuplicateRecordSets, which is failing. It's attempting to locate all the contacts related to the first contact, but it's failing as there are no contacts (there are Leads).
<img width="922" alt="Screen Shot 2020-06-12 at 4 28 18 PM" src="https://user-images.githubusercontent.com/37851761/84554620-9073c200-accd-11ea-960f-fbf127e52699.png">

Error:
<img width="1367" alt="Screen Shot 2020-06-12 at 4 29 57 PM" src="https://user-images.githubusercontent.com/37851761/84554638-a08ba180-accd-11ea-884e-623cf59b53dc.png">

Full Error: 
*Map key <DRS ID> not found in map*
*Error is in expression '{!URLFOR($Action.Contact.View, firstContactOfDRS[drs.Id])}' in component <apex:repeat> in page npsp:con_contactmerge*

Seems to be failing in the showDuplicateRecordSets method, in the CON_ContactMerge_CTRL class, here (https://github.com/SalesforceFoundation/NPSP/blob/49dab6a0ff6d190ec131ed184d27870d7e49ee01/src/classes/CON_ContactMerge_CTRL.cls#L1025). 
This part (https://github.com/SalesforceFoundation/NPSP/blob/49dab6a0ff6d190ec131ed184d27870d7e49ee01/src/classes/CON_ContactMerge_CTRL.cls#L1056) is supposed to locate all contacts related to the first contact and display them per the point of the method, but it’s failing. I believe because there are no contacts, there are leads related to the first contact. 

**Steps to Reproduce:**
1. In an org with the NPSP, Duplicate Management, and the “Standard Rule for Contacts with Duplicate Leads” duplicate rule enabled, create a Lead. 
2. Create a matching Contact record with matching First/Last name as the Lead.
3. Confirm a new Duplicate Record Set has been automatically created and that it used the “Standard Rule for Contacts with Duplicate Leads” duplicate rule.
<img width="1100" alt="Screen Shot 2020-06-12 at 4 34 35 PM" src="https://user-images.githubusercontent.com/37851761/84554691-e5173d00-accd-11ea-9ba5-f929da6cb6d3.png">
4. Click on the Contact Merge tab, then the "See Duplicate Contacts" button. 

Expected Behaviour: Page is displayed showing no contacts to merge based on existing DRS records:
<img width="1355" alt="Screen Shot 2020-06-12 at 4 45 57 PM" src="https://user-images.githubusercontent.com/37851761/84554732-24de2480-acce-11ea-82b6-6da50ca1a5ad.png">

Actual Behaviour: Error is displayed.

**Comment by coriobriensfdo** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbU5QAI" target="_blank">W-042055</a>

**Comment by coriobriensfdo** [comment]
[New Hub post.](https://powerofus.force.com/s/question/0D51E00005Ku4WISAZ/see-duplicate-contacts-insufficient-access)

**Comment by mbeaty-sf** [comment]
[W-7693961](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008S1AGIA0/view)

**Comment by mbeaty-sf** [comment]
[Additional Hub Post](https://powerofus.force.com/s/question/0D51E00005PBgzISAT/error-when-viewing-see-duplicate-contacts)

**Comment by coriobriensfdo** [comment]
[Another Hub post](https://powerofus.force.com/s/question/0D51E00005Q3FtrSAF/issues-with-contact-merge-function-see-duplicate-contacts)

**Comment by sd5000** [comment]
We're seeing this same issue too but it's not related to matching Leads, just matching duplicate contacts.

**Comment by JoolsBaxter** [comment]
I am having the same issue in a client's production org, but is fine in the sandbox.  Based on Contact duplicate rule - no leads.

**Comment by coriobriensfdo** [comment]
Thanks for letting us know @sd5000 and @JoolsBaxter. I don't have an ETA for the resolution but have asked the Product Managers to take a look.

**Comment by EskayTPL** [comment]
Hi - I'm getting the error message, "Map key 0GK3j000000RRTzGAO not found in map Error is in expression '{!URLFOR($Action.Contact.View, firstContactOfDRS[drs.Id])}' in component <apex:repeat> in page npsp:con_contactmerge" when I got to Contact Merge >> See Duplicate Records. I was using it one day without issue only to get this the next next day. This was last week. Is there anything I can do? Thanks!

**Comment by EskayTPL** [comment]
> Hi - I'm getting the error message, "Map key 0GK3j000000RRTzGAO not found in map Error is in expression '{!URLFOR($Action.Contact.View, firstContactOfDRS[drs.Id])}' in component apex:repeat in page npsp:con_contactmerge" when I got to Contact Merge >> See Duplicate Records. I was using it one day without issue only to get this the next next day. This was last week. Is there anything I can do? Thanks!

I did find the snippet of code, I don't know if that can help me to fix it?
<td>
 <a href="{!URLFOR($Action.Contact.View, firstContactOfDRS[drs.Id])}" class="slds-truncate">
  <apex:outputText value="{!firstContactOfDRS[drs.Id].Name}"/>
 </a>
</td>

**Comment by coriobriensfdo** [comment]
Hi @EskayTPL we don't provide support in GitHub, so I would suggest to either post in the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000CjRe/nonprofit-success-pack) or [create a support case](https://help.salesforce.com/supportandservices?id=createCase&topic=Salesforceorg_Products_TOPIC) for help. Thanks!

**Comment by EskayTPL** [comment]
> Hi @EskayTPL we don't provide support in GitHub, so I would suggest to either post in the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000CjRe/nonprofit-success-pack) or [create a support case](https://help.salesforce.com/supportandservices?id=createCase&topic=Salesforceorg_Products_TOPIC) for help. Thanks!

Thank you for your response, I posted to Power of Us but didn't get a response, so thought maybe I'd try here.

**Comment by coriobriensfdo** [comment]
> > Hi @EskayTPL we don't provide support in GitHub, so I would suggest to either post in the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000CjRe/nonprofit-success-pack) or [create a support case](https://help.salesforce.com/supportandservices?id=createCase&topic=Salesforceorg_Products_TOPIC) for help. Thanks!
> 
> Thank you for your response, I posted to Power of Us but didn't get a response, so thought maybe I'd try here.

Ok then you'll want to go the case option instead @EskayTPL, thanks! :)

**Comment by harvey-BIMA** [comment]
@coriobriensfdo I submitted a case, and they literally sent me the link to this thread. Definitely not a solution LOL

**Comment by coriobriensfdo** [comment]
> @coriobriensfdo I submitted a case, and they literally sent me the link to this thread. Definitely not a solution LOL

Hi @harvey-BIMA as mentioned on the post in the Hub, you can manually deal with the Contact/Lead and that will resolve the error (it should show you that there are no duplicates as there aren't dupes against the Contact). 

As you can see the issue hasn't yet been resolved by the engineering team but i'll flag it up to them again.

**Comment by coriobriensfdo** [comment]
> W-042055

GUS record W-7693961

**Comment by harvey-BIMA** [comment]
@coriobriensfdo That only works if there is just a single Contact/Lead duplicate. Sadly I inherited a database that was not managed properly, and there are thousands of duplicate records. I guess I will be going through them all manually, but it seems like this should be a fundamental feature of data management. Then again, fundamental data management says to not let the duplicates get this bad in the first place. Oh well.

**Comment by coriobriensfdo** [comment]
> @coriobriensfdo That only works if there is just a single Contact/Lead duplicate. Sadly I inherited a database that was not managed properly, and there are thousands of duplicate records. I guess I will be going through them all manually, but it seems like this should be a fundamental feature of data management. Then again, fundamental data management says to not let the duplicates get this bad in the first place. Oh well.

Could you disable your lead matching rules temporarily?
