### ISSUE TITLE
Multi-Select Picklists not Appearing in Gift Entry

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5574]
When a Multi-Select Picklist is created, and mapping in Advanced Mapping, the field is available in Gift Entry; however, upon using the template in a batch, or if added to the Single Gift Entry, Default Gift Entry Template, the field does not appear.

**Steps to Recreate**
1. Create multi-select picklist field on Object of your choosing, e.g. Payment
2. Create matching multi-select picklist field on NPSP Data Importer
3. Create the Mapping between the two fields in the NPSP Settings > System Tools > Advanced Mapping for Data Import & Gift Entry > Configure Advanced Mapping
4. Go to Gift Entry and edit a Template to include the field you mapped in step 3
5. Notice that the field is visible, and can be added to the template. Add it to the template
6. Attempt to create a batch with the template you just added the field to
7. Notice that the field is not visible on the batch, despite having added it to the template

![image](https://user-images.githubusercontent.com/53280203/84835523-a264a600-afe8-11ea-987d-6c813a44e7d2.png)

![image](https://user-images.githubusercontent.com/53280203/84835582-c1633800-afe8-11ea-9325-c10b48080663.png)

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbe0QAA" target="_blank">W-042124</a>

**Comment by mbeaty-sf** [comment]
Related Hub Post: https://powerofus.force.com/s/question/0D51E00005KtO0hSAF/gift-entry-and-multiselect-picklists

**Comment by mbeaty-sf** [comment]
W-7781022

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7781022)
