### ISSUE TITLE
NPSP Settings Should Check for Permissions on Permission Set Assignments instead of Profiles

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5584]
Several recent updates to NPSP check for Admin Access by querying for the permissions associated with the User's Profile - specifically Customize Application, Modify All Data, and Author Apex. 

If, however, a User has these permissions instead assigned via a Permission Set, we don't recognize their admin access and throw an error. 

We check for Profile Permissions in the [isSysAdmin() method of USER_UserService.](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/USER_UserService.cls#L49-L68)
```
Map<Id, Profile> sysAdminProfiles = new Map<Id, Profile>([SELECT Id
                , PermissionsCustomizeApplication
                , PermissionsModifyAllData
                , PermissionsAuthorApex
                FROM Profile
                WHERE PermissionsCustomizeApplication = TRUE
                AND PermissionsModifyAllData = TRUE
                AND PermissionsAuthorApex = TRUE]);`
```

### Suggestion
Take a similar approach to how we check for Customize Application in the [isCustomizeApplicationUser() method of USER_UserService](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/USER_UserService.cls#L75-L89) and query by using PermissionSetAssignment (since Profiles ultimately use these behind the scenes).

```
List<PermissionSetAssignment> permissions = [
            SELECT Id
            FROM PermissionSetAssignment
            WHERE AssigneeId = :userId
            AND PermissionSetId IN (
                SELECT Id
                FROM PermissionSet
                WHERE PermissionsCustomizeApplication = true)
        ];
```

### Steps to Repeat
* Create a Permission Set with the following System Permissions: Author Apex, Customize, Application, and Modify All Data.
* Clone the Standard User Profile and verify it does NOT have the following System Permissions: Author Apex, Customize, Application, and Modify All Data.
* Create a new User and assign to your new Profile. Assign the new Permission Set as well.
* Log in as that User.
* Go to NPSP Settings → Donations → Customizable Rollups. Try to enable Customizable Rollups. Error appears: Error: core.apexpages.exceptions.ApexPagesGenericException: system.security.NoAccessException: Update access denied for npsp__Customizable_Rollup_Settings__c, controller action methods may not execute

![Screen Shot 2020-06-17 at 5 06 13 PM](https://user-images.githubusercontent.com/29731456/84952590-32295380-b0c0-11ea-8ef2-aabc646329c5.png)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbg1QAA" target="_blank">W-042149</a>
