### ISSUE TITLE
Enhanced Recurring Donation Generates 2 Installment Opportunities on Create

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5597]
When creating a Recurring Donation, if there is an update made to either a field that the Enhanced Recurring Donation considers a key field, or a field that is mapped in the Field Mapping section of NPSP Settings for Recurring Donations.

**Steps to Recreate**
1. Follow the Setup steps for enabling Enhanced Recurring Donations (https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide)
2. After upgrading, go to NPSP Settings > Recurring Donations > Recurring Donation Custom Field Mappings and Map **Recurring Donation Name** to Opportunity **Name**
3. Ensure that the Recurring Donation setting "Install Opportunity Auto-Creation = Always Create Next Installment
4. In Setup > Custom Settings > Recurring Donation Settings > Manage the settings and disable "Automatic Recurring Donation Naming"

5. Create a Workflow Rule 
a. **Rule Name** = RD Type Open
b. **Active** = TRUE
c. **Rule Criteria** = Recurring Donation: Recurring Type _equals_ Open
d. **Object** = Recurring Donation
e. **Evaluation Criteria** = Evaluate the rule when a record is created, and any time it's edited to subsequently meet criteria
6. Create a Field Update linked to the Workflow from previous step
a. **Name** = RD Name - Open
b. **Object** = Recurring Donation
c. **Field to Update** = Recurring Donation: Recurring Donation Name
d. **Field Data Type** = Text
e. **Re-evaluate Work Rules after Field Change** = FALSE
f. Formula Value = `npe03__Organization__r.Name &" OPEN RecDon for " &" $"& TEXT(npe03__Amount__c) &" "& TEXT(npe03__Installment_Period__c)`
7. Create a Second Workflow Rule
a. **Rule Name** = RD-Open Exists on Opportunity
b. **Active** = TRUE
c. **Rule Criteria** = (Opportunity: Recurring Donation Installement Name NOT EQUAL to `NULL`) AND (Opportunity: Recurring Donation Installment Name CONTAINS `of 0)`)
d. **Object** = Opportunity
e. **Evaluation Criteria** = Evaluate the rule when a record is created
8. Create a Field Update linked to the Workflow from previous step
a. **Name** = Opportunity Type is New Funding
b. **Object** = Opportunity
c. **Field to Update** = Opportunity: Type
d. **Field Data Type** = Picklist
e. **Re-evaluate Work Rules after Field Change** = FALSE
f. **Formula Value** = `New Funding`
9. Create a Recurring Donation:
a. **Date Established** = <Today's Date>
b. **Recurring Type** = Open
c. **Number of Planned Installments** = 1 (default, do not change)
d. **Amount** = $100
e. **Installment Period** = Monthly
f. **Day of Month** = <1 day after today's date>
g. **Effective Date** = <same date as Date Established>
h. **Recurring Donation Name** = <any value>
10. Save the Recurring Donation
11. Wait a few seconds (in some cases longer depending on if there are other queued processes waiting

**Cause**
Because the Recurring Donation Field Mapping has the Recurring Donation Name mapping to the Opportunity Name, the [RD2_OpportunityEvaluationService.cls](https://github.com/SalesforceFoundation/NPSP/blob/3172d24e313a05faca3b47c2b0b328e64289a61a/src/classes/RD2_OpportunityEvaluationService.cls) reassesses the creation of the Installment Opportunities of the Recurring Donation. Two queueable handlers are created to create Opportunities because there is both a Workflow setting to update the Recurring Donation Name and Opportunity Name, at the same time the Recurring Donation Field Mapping is updating the Opportunity Name. Running asynchronously before the record is actually inserted is what is causing the duplication of actions to generate the Opportunities. This line in the class shows where the Field Mappings are being re-evaluated in the same section, following a list of key fields that automatically trigger a reevaluation - https://github.com/SalesforceFoundation/NPSP/blob/3172d24e313a05faca3b47c2b0b328e64289a61a/src/classes/RD2_OpportunityEvaluationService.cls#L321

**Workaround**
Removing multiple updates made to the same key fields or mapped fields via Recurring Donation settings, via workflow, process builder, code, or Recurring Donation Field Mapping, as listed in the code here:
https://github.com/SalesforceFoundation/NPSP/blob/3172d24e313a05faca3b47c2b0b328e64289a61a/src/classes/RD2_OpportunityEvaluationService.cls#L301

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbkmQAA" target="_blank">W-042193</a>

**Comment by mbeaty-sf** [comment]
Related Hub Post - https://powerofus.force.com/s/question/0D51E00005KsmHTSAZ/enhanced-recurring-donations-instituting-custom-naming-on-recurring-donations-related-opportunities
