### ISSUE TITLE
Clicking in/out of lookups in Gift Entry doesn't close the search results

### ISSUE THREAD

**Issue by ameyersalesforce** [SalesforceFoundation/NPSP#5600]
Steps to repro:

1. On the gift entry form, type a search term into a lookup field that returns at least one result.
2. Without selecting a search result, click out of the lookup field
3. The search result list does not disappear

**Comment by coriobriensfdo** [comment]
**lurch: attach W-041797

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007haxMQAQ" target="_blank">W-041797</a>

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
