### ISSUE TITLE
Lookup search results take a long time to load in Gift Entry

### ISSUE THREAD

**Issue by ameyersalesforce** [SalesforceFoundation/NPSP#5601]
Sometimes, especially in larger orgs, it takes a long time to return search results from lookup fields in Gift Entry. In some orgs, the search times out entirely.

See more detail here: https://powerofus.force.com/s/question/0D51E00005K3pzNSAR/gift-entry-contact-search-does-not-display-expanded-search-results

**Comment by coriobriensfdo** [comment]
**lurch: attach W-041797

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007haxMQAQ" target="_blank">W-041797</a>

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
