### ISSUE TITLE
Custom error messages for validation rules not displaying on Gift Entry

### ISSUE THREAD

**Issue by ameyersalesforce** [SalesforceFoundation/NPSP#5605]
Validation Rules on NPSP object are appearing at the right time on Gift Entry (when the Condition is met), but the error message chosen doesn't appear.

NOTE: We should test this for both page-level validation messages and field-level validation messages; also need to do some regression on other error message display (with/without CC widget, allocations, errors on DI save and errors on processing, etc). 

Pre-Conditions:
AM & GE should be enabled

Steps to reproduce:
1- Create a Validation rule on the NPSP Data Import object (for example: "npsp__Donation_Amount__c > 10")
2- Enter a custom error message for the Validation Rule
3- Attempt to enter a gift through Batch or Single gift that complies with the Condition (for example: amount 30)

Expected Result: Gift should not be entered and custom error message should be displayed at the top of the page
Actual result: Gift is not entered but error message at the top is blank

**Comment by ameyersalesforce** [comment]
**lurch: attach W-041642

**Comment by coriobriensfdo** [comment]
**lurch: attach W-041642

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hajUQAQ" target="_blank">W-041642</a>
