### ISSUE TITLE
GE - GAU allocations automatically removed from the form if the donor is changed

### ISSUE THREAD

**Issue by Lucia-Juarez** [SalesforceFoundation/NPSP#5606]
When GAU allocations are added, If the chosen donor is removed or changed from the lookup the Allocations disappear too.

Steps to reproduce:
Pre-req: Template/Batch used should have the "GAU Allocations" widget

1- On Gift Entry form, add a donor from "Account Imported" or "Contact Imported" lookup field
2- Add Donation amount and Donation date
3- Add GAU allocations with totals matching the Donation amount
4- Remove the donor from the lookup field

Expected result: Only the donor and other related fields should become blank
Current Result: GAU allocations also disappear.

**Comment by Lucia-Juarez** [comment]
**lurch: attach W-042232

**Comment by coriobriensfdo** [comment]
**lurch: attach W-042232

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbojQAA" target="_blank">W-042232</a>

**Comment by mbeaty-sf** [comment]
W-7782982
