### ISSUE TITLE
GE: Lookup Component malfunctions on RecordType Lookups

### ISSUE THREAD

**Issue by bdvorachek** [SalesforceFoundation/NPSP#5618]
Steps to Reproduce:

1. Enable Gift Entry
2. Edit the default template, add Opportunity RecordTypeId to the form
3. Start a new gift using this form
4. Attempt to search in the Record Type Id field, no results will appear and an error message may display in the chrome console.

Suggested Fix:

Add special handling to fall back to SOQL instead of SOSL whenever dealing with Record Type fields in the `doSearch` function of `GE_LookupController`.

**Comment by bdvorachek** [comment]
**lurch: attach W-042326

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbyyQAA" target="_blank">W-042326</a>
