### ISSUE TITLE
Custom TDTM trigger running asynchronously causes duplicate field selected: npsp__Type__c

### ISSUE THREAD

**Issue by dacmanj** [SalesforceFoundation/NPSP#5621]
Since 5/6 a previously working asynchronous trigger started failing -- corresponding to the release of the npe01__OppPayment__c.npsp__Type__c field (on 5/5). We already had our own Type__c field, which is presumably why this is happening. It seems like this may be related to https://github.com/SalesforceFoundation/NPSP/issues/5444

From looking at the code in [RunFuture](https://github.com/SalesforceFoundation/NPSP/blob/d4ec6621266e3f8edbc0a70bc1d9a84532f85e38/src/classes/TDTM_Runnable.cls#L80) -- it seems like it's including npsp__Type__c twice because it matches the Type__c portion -- could that code possibly be changed to lookup the fields based on the combination of the namespace and the api name to avoid injecting npsp__Type__c twice instead of npsp__Type__c and Type__c? I can't tell for sure because the log isn't including the query in the error.

Unfortunately the logic requires that it be asynchronous and we're trying to avoid refactoring to use the new Type field (or renaming it) because of the number of dependencies on it.

Thanks in advance,
David

**Comment by mbeaty-sf** [comment]
Hi @dacmanj thank you for writing up this issue in detail; however, we don't provide support on Github. Can you please post this in the [Power of Us Hub - Nonprofit Success Pack group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) so we can support it there? Thank you!
