### ISSUE TITLE
Batch Gifts Table Does Not Display Columns for Lookup Fields

### ISSUE THREAD

**Issue by kenlewis-sfdo** [SalesforceFoundation/NPSP#5640]
Batches that were created using a Template that has Lookup fields configured to be visible as Batch Table Columns do not display those Lookup fields in the Batch Gifts table.

Template configuration:
![image](https://user-images.githubusercontent.com/46458081/86413268-9da12280-bc75-11ea-8852-0ca301dd69d9.png)

Gift Entry page for this Batch:
![image](https://user-images.githubusercontent.com/46458081/86413310-b4477980-bc75-11ea-9b1c-59526de4dd7d.png)

Steps to Recreate:
After enabling Advanced Mapping and Gift Entry,
1. Create a Template in Gift Entry that has lookup fields selected as Visible Columns in the Batch Settings -> Batch Table Columns subtab.
2. Create a Batch using that Template
3. Enter a gift for the Batch to observe missing columns

Expected Behavior:
Lookup fields selected as visible in the Template when the Batch is created should display as columns in that Batch's gift table.

**Comment by kenlewis-sfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hcALQAY" target="_blank">W-042439</a>
