### ISSUE TITLE
Batch Gifts Table Does Not Use User-Defined Field Labels as Column Headers

### ISSUE THREAD

**Issue by kenlewis-sfdo** [SalesforceFoundation/NPSP#5641]
Batches created using a Template that has User-defined custom field labels do not use the custom field label as the column header for that field in the Batch's gifts table.

Template configuration:
![image](https://user-images.githubusercontent.com/46458081/86414121-eeb21600-bc77-11ea-9072-84fc3cce3933.png)

Gift Entry page for this Batch:
![image](https://user-images.githubusercontent.com/46458081/86414141-fa9dd800-bc77-11ea-80a2-418bb4e3d308.png)

Steps to Recreate:
After enabling Advanced Mapping and Gift Entry,

1. Create a Template in Gift Entry that has customized field labels in Form Fields -> Configure Form Fields page
2. Create a Batch using that Template
3. Enter a gift for the Batch to observe column headers that do not use the user-defined field labels that were set in the Template

Expected Behavior:
Batches created from Templates with user-defined field labels should use those user-defined values as column headers in the Batch's gifts table.

**Comment by kenlewis-sfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hcAMQAY" target="_blank">W-042440</a>
