### ISSUE TITLE
Gift Entry: Update payments for payments with no scheduled date throws component error and Required fields are missing: [StageName].

### ISSUE THREAD

**Issue by deepmalamehta** [SalesforceFoundation/NPSP#5642]
When I choose "Update payments" in review donations modal for payments with no scheduled date I see the component error. Please refer to the video attached.

Steps to reproduce:
Prerequisites: Automatic payment creation with opportunity is enabled.
1. Create an opportunity for contact.
2. Payment gets created automatically with no scheduled date.
3. Otherwise, create a payment with no scheduled date.
4. Choose the same contact as a donor in GE and click review donations modal.
5. Click update payment.

Result: Component error 
Expected result: Should return to gift entry form with payment details.

6. Try to process payment bypassing component error.
Result: 1. Error: Required fields are missing: [StageName] 
2. Existing imported batch rows are also updated with error.

**Comment by deepmalamehta** [comment]
<img width="646" alt="Screen Shot 2020-07-02 at 4 20 11 PM" src="https://user-images.githubusercontent.com/42785185/86416808-f1186e00-bc7f-11ea-8105-6818c92f5708.png">
<img width="871" alt="Screen Shot 2020-07-02 at 4 20 04 PM" src="https://user-images.githubusercontent.com/42785185/86416814-f2e23180-bc7f-11ea-8afb-35ce6f8dff75.png">

**Comment by deepmalamehta** [comment]
**lurch: attach W-042437

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hcABQAY" target="_blank">W-042437</a>

**Comment by deepmalamehta** [comment]
GUS: W-7964224

**Comment by melissabarber** [comment]
> GUS: W-7964224

@deepmalamehta I think we may already have a WI in GUS for this Issue, but please confirm it's the same one. The one I found is [W-7782990](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008EIXhIAO/view). Thanks!

**Comment by deepmalamehta** [comment]
@melissabarber 

yup , was not able to find this one. but since I added more details can we just keep the new one?

**Comment by melissabarber** [comment]
@deepmalamehta I don't have strong feelings either way. Please just check in with Ali about the duplicate WIs to make sure we close out one of them properly.

**Comment by mbeaty-sf** [comment]
W-7964224

**Comment by kporray1** [comment]
The product team is no longer considering this issue.  (W-7964224)
