### ISSUE TITLE
Gift Entry: Objects Without Name Fields Cause "No such column 'name'" Error

### ISSUE THREAD

**Issue by kenlewis-sfdo** [SalesforceFoundation/NPSP#5647]
When Lookup fields whose related object do not have a "Name" field are included in a Template, the Gift Entry screen shows a "No such column 'name' on entity <ObjectName>" error:

![2020-07-02_16-38-04](https://user-images.githubusercontent.com/46458081/86630344-9170da00-bf81-11ea-8bec-dc55597af916.png)

**Steps to reproduce:**
1. Create a Lookup field on Data Import that is related to an object without a "Name" field (like Case)
2. Create a Lookup field (to Case) on Opportunity
3. Create a Field Mapping for these two fields
4. Create a Template that includes the new Case Lookup field
5. Create a Batch from that Template
6. Open the new Batch and observe the "No such column" error

**Expected behavior:**
Lookups that reference objects without Name fields should not throw an error and should instead use whatever field is used in place of "Name" on these objects (for example, CaseNumber on Case)

**Comment by kenlewis-sfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hcB9QAI" target="_blank">W-042449</a>
