### ISSUE TITLE
Find Matched Gifts Page Limited to 1000 Opportunities

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5651]
If a customer has more than 1000 Opportunities returned on the Find Matched Gifts page (MTCH_FindGifts), the page is blocked from loading due to a limit on the number of records that can be looped over in an <apex:repeat> tag. The error displayed is: 
**_Collection size {some number of 1000}  exceeds maximum size of 1,000._**
![Screen Shot 2020-07-07 at 1 14 52 PM](https://user-images.githubusercontent.com/29731456/86818050-debd7c00-c053-11ea-9f1b-d84fbb828fce.png)

### Limit Information
[More information about this Limit:](https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_vf.htm)
"Maximum collection items that can be iterated in an iteration component such as <apex:pageBlockTable> and <apex:repeat>": 1000

The Limit jumps to 10,000 and you can load over 1000 Opportunities if you add a `readOnly=true` parameter to the <apex:page> tag. However, you are then blocked from updating Opportunities. [I verified that this is not a valid fix the way the page is currently written].

### Root Cause
The problematic query is in [MTCH_FindGifts_CTRL, lines 99-123.](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/MTCH_FindGifts_CTRL.cls#L99-L123)
```
SELECT Id, Name, AccountId, Account.Name, Primary_Contact__c, Primary_Contact__r.Name, Amount, CloseDate, 
Matching_Gift__c, Matching_Gift_Account__c, Matching_Gift_Account__r.Matching_Gift_Percent__c, 
     (SELECT Id, ContactId FROM OpportunityContactRoles WHERE IsPrimary = true AND IsDeleted = false) 
FROM Opportunity 
WHERE ((Matching_Gift__c = null AND StageName IN :closedWonStages 
     AND AccountId = '0011F00000fFLHeQAO' 
     AND (Matching_Gift_Status__c = 'Potential' OR Matching_Gift_Status__c = 'Submitted'))
     OR (Matching_Gift__c = null AND StageName IN :closedWonStages AND Matching_Gift_Account__c = '001xxxxxxxxxxxxxxx' 
     AND (Matching_Gift_Status__c = 'Potential' OR Matching_Gift_Status__c = 'Submitted'))OR Matching_Gift__c = '0061F00000ANMOiQAP') AND Id != '006xxxxxxxxxxxxxxx' 
ORDER BY Name

```

### Workarounds:
No current workarounds for loading the page. Customers with more than 1000 matching Opportunities will need to use a data loading tool to update the matched Opportunities in a different manner. 

### Steps to Repeat
1. Insert an Organization Account; copy the Account Id.
2. Insert 1010 Opportunities associated with that Account.
3. Add the Find Matched Gifts button to the Page Layout associated with your Opportunities.
4. Navigate to one of the newly created Opportunities and click the Find Matched Gifts button. The error will be displayed.
5. Delete 11 Opportunities. 
6. Navigate to one of your Opportunities and click the Find Matched Gifts button. No error is displayed.

**Comment by jesslopez-sf** [comment]
W-7790336

**Comment by TSalman97** [comment]
I was able to slightly get around this but temporarily clearing out the "Matching Gift Account" and "Matching Gift Status" fields using Dataloader for the account that had 1000+ opportunities. Additionally, when there are that many opps on the page, run into frequent apex cpu limit errors when trying to select a matching opp.

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlDTQAY&title=find-matched-gifts-page-limited-to-1000-opportunities) on the Trailblazer Community for updates.
