### ISSUE TITLE
NPSP New Contact creates "Anonymous" Household

### ISSUE THREAD

**Issue by eddieloss** [SalesforceFoundation/NPSP#5658]
Using the NPSP Household data model, when creating a new "Contact" and leaving "Account" blank, a new "Household" account should be created. This is NOT the case.  Rather an "Anonymous" account is created.  This issue appears to have begun on 7/9/20.  A support case has been filed with Salesforce.

**Comment by jesslopez-sf** [comment]
Closing this Issue as duplicate of:
https://github.com/SalesforceFoundation/NPSP/issues/5678
