### ISSUE TITLE
Gift Entry: Updating Deleted Row Shows Empty Error Message

### ISSUE THREAD

**Issue by kenlewis-sfdo** [SalesforceFoundation/NPSP#5660]
Clicking the "Update" button after deleting the open gift from the gifts table displays an empty error message.

**Steps to Reproduce:**
1. Create or Open a Batch in Gift Entry that has one or more gifts entered
2. Open one of the gifts using the "Open" row action in the table
3. Delete the gift using the "Delete" row action in the table
4. Click the "Update" button in the form

**Expected behavior:**
A helpful error message is displayed.

**Actual behavior:**
An empty error message is displayed.

![2020-07-10_16-53-15](https://user-images.githubusercontent.com/46458081/87211631-403d4f00-c2cf-11ea-9684-aaa6f3598c94.png)

**Comment by kenlewis-sfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hcXFQAY" target="_blank">W-042637</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
