### ISSUE TITLE
Gift Entry - Regenerating the Default Gift Entry Template pulls "isDeleted" Custom Metadata references into Template

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5672]
**Issue**

When a user activates Gift Entry, the Custom Metadata Types that are referenced by the [DefaultGiftEntryTemplate.resource](https://github.com/SalesforceFoundation/NPSP/blob/8ea8aca293966d7533e56e404375937fa3576063/src/classes/GE_DefaultTemplate.cls) to create the Default Gift Entry Template can continue to reference Custom Metadata that is marked as "isDeleted" when the Default Gift Entry Template needs to be regenerated via the Custom Settings.

<br>

**Steps to Reproduce**

1. Enable Gift Entry and assign access to your user record via the configuration steps https://powerofus.force.com/s/article/NPSP-Configure-Gift-Entry
2. Open the Gift Entry Tab and view the Default Gift Entry Template
3. Click "Edit" on the Default Gift Entry Template and ensure no errors appear
4. Go to NPSP Settings > System Tools > Advanced Mapping for Data Import & Gift Entry > Configure Advanced Mapping
5. In Configure Advanced Mapping > go to the "Payment" Group and "View Field Mappings"
6. Delete the mapping for "Payment Method" under Payment Object Group's, Field Mappings
7. Return to the Default Gift Entry Template under the Gift Entry Tab and try to edit the template
a. Encounter error: Error Cannot read property 'Source_Field_API_Name' of undefined
b. 
![image](https://user-images.githubusercontent.com/53280203/87610639-bcaea400-c6ba-11ea-97b4-5af80110d769.png)

8. To regenerate the default template, go to Setup > Custom Settings > Gift Entry Settings > Manage > Edit > Clear out the value in the Default Gift Entry Template field and leave it blank and click "Save"
9. Return to the Gift Entry Tab and see a newly, more recently generated, Default Gift Entry Template
10. Click the new Template's name to edit it and encounter the same error as in step 7a.

<br>

**Cause**

The JSON Template references an expected set of fields when generating the default template. At the time the template is generated it expects the fields referenced within ([DefaultGiftEntryTemplate.resource](https://github.com/SalesforceFoundation/NPSP/blob/8ea8aca293966d7533e56e404375937fa3576063/src/classes/GE_DefaultTemplate.cls)), deleting one of these fields, replacing the mapping, changing the field type, or deleting the advanced mapping will cause different errors on the template; however, if these issues are addressed and the Default Gift Entry Template is regenerated, the mapping referenced can still choose to pull in a reference to Custom Metadata that is marked as "isDeleted = true". The [GE_DefaultTemplate.cls](https://github.com/SalesforceFoundation/NPSP/blob/8ea8aca293966d7533e56e404375937fa3576063/src/classes/GE_DefaultTemplate.cls) does not query for "isDeleted = false"

https://github.com/SalesforceFoundation/NPSP/blob/8ea8aca293966d7533e56e404375937fa3576063/src/classes/GE_DefaultTemplate.cls#L216

<br>

**Workaround**

Create a Template from scratch, do not clone from Default Gift Entry Template, or any others that you may currently have that are showing errors. This new template should allow you to pull in any Advanced Field Mappings that are available and working onto the new template, and you can create batches with this template without issue. To allow Single Gift Entry to function without issue with this new template:

Once you create the template, take the ID of the template that you created and go to Setup > Custom Settings > Gift Entry Settings > Manage > Edit, and replace the value in the Default Gift Entry Template field with the ID of the Template that you just created, and Save. Once you do this, the next time you attempt to use Single Gift Entry, it will use the template you took the ID and replaced in Custom Settings, instead of the Default Gift Entry Template that was giving the errors previously.

**Comment by mbeaty-sf** [comment]
W-7829740

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlDOQAY&title=gift-entry-regenerating-the-default-gift-entry-template-pulls-isdeleted-custom-metadata-references-into-template) in the Trailblazer Community for updates.
