### ISSUE TITLE
Gift Entry: Edit batch info is resetting batch column headers.

### ISSUE THREAD

**Issue by deepmalamehta** [SalesforceFoundation/NPSP#5685]
**Description:**
When the user configures batch headers from the batch table and clicks "Edit batch info", Column headers are resetting to template level settings.

**Steps to reproduce:**

Create a batch.
Enter a gift.
Customize batch column headers. Change order and number of columns.
Click Edit batch info.
Return to form.
**Expected result:** Batch column headers should remain as configured in step 3.

**Actual result:** Batch column headers are reset to same as when the form was loaded for the first time.

**Comment by deepmalamehta** [comment]
W-7835292

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlDJQAY&title=gift-entry-edit-batch-info-is-resetting-batch-column-headers) in the Trailblazer Community for updates.
