### ISSUE TITLE
Editing Default GAU Allocations on Existing Gifts Causes Error in Gift Entry

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5699]
**Issue**
If a User in Gift Entry enters an existing Contact and they are prompted, as the Contact has an existing, open, Opportunity or Payment, they can click "Review Donations" and choose to edit the Opportunity or Payment with the information they enter in Gift Entry at this point. If the Opportunity already has a GAU Allocation, assigned by NPSP Default GAU, that GAU is greyed out from being edited, but adding additional Allocations and splitting the amount between them is allowed, but upon save the error is encountered:

`Error: Additional Object JSON - <field name>: Allocation totals can't exceed the amount of the related Payment or Opportunity`

**Update** - There is also a scenario occurring where no error is generated upon save. When editing an existing Opportunity or Payment's GAU Allocations, the record is allowed to save, but the Data Import record does not maintain any updated Allocation data, causing the imported record to default to the Default GAU Allocation.

**Steps to Reproduce**
1. Goto any Contact and create a new pledged donation
2. Verify that default GAU is assigned for this donation. Now, change the GAU to individual allocation
3. Go to Gift Entry > Click "New Single Gift"
4. Fill in the details Contact1 as DonorType, Choose the contact record > Click on Review Donations > Pick the one you just created and "Update this Payment"
5. Now at the bottom click Add New Allocation and add "individual allocation" with full amount and save

**Workaround**
Managing Allocations via the "Manage Allocations" button on the Opportunity record's GAU Allocations Related List will allow for the correct adjustment of the Allocations, in stead of editing them via Gift Entry.

**Comment by mbeaty-sf** [comment]
W-7889396

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlDEQAY&title=gift-entry-editing-default-gau-allocations-on-existing-gifts-causes-error-in-gift-entry) in the Trailblazer Community for updates.
