### ISSUE TITLE
Gift Entry: expect totals to match should mandate values in "expected amount " or "expected gift count".

### ISSUE THREAD

**Issue by deepmalamehta** [SalesforceFoundation/NPSP#5709]
Currently, When I select "Required expected totals match", "expected amount " and "expected gift count" are automatically added to batch details but not required to have values. This results in an error when no value is added in the "expected amount " or "expected gift count". Please see the video attached.

Steps to reproduce:

Edit template and select "Required expected totals match" in batch details.
Do not select "expected amount " and "expected gift count".
Create a batch using the same template.
"expected amount " and "expected gift count" will automatically be added.
Check "Required expected totals match".
Do not enter any value in the "expected amount " and "expected gift count".
Enter gifts and process the batch.
Expected result: Gift should not be saved if there is no value in the "expected amount " or "expected gift count".

Actual Result: Gift can be saved and gives error when the batch is processed.

**Comment by deepmalamehta** [comment]
WI: W-7905666

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlD9QAI&title=gift-entry-expect-totals-to-match-should-mandate-values-in-expected-amount-or-expected-gift-count) in the Trailblazer Community for updates.
