### ISSUE TITLE
Gift Entry: Saving changes to record in platform modal refreshes single gift entry form

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#5727]
GUS WI: [W-7937899](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008I3phIAC/view)

When using the single gift entry form in the Gift Entry app, if you run a search in a lookup field and enter the platform search modal, edit a record within that modal, and save the changes, the gift entry form refreshes in the background. Any data that had been entered in the gift entry form up to that point is lost, but the platform modal is left open.

**Note**: This does not occur when using the batch gift entry form.

**Note 2**: This bug will not be reproducible in the GE app until https://github.com/SalesforceFoundation/NPSP/pull/5708 is merged.

### Steps to Reproduce

1. Open the app menu and navigate to Gift Entry.
2. Click 'New Single Gift'
3. In the 'Existing Donor Contact' field, enter a search term that will return a known contact (or run a search in a lookup field that returns a contact).
4. Click 'Show All Results For _______' to open the platform search modal.
5. On the record you want to edit, click the arrow menu on the right side and click 'Edit'.
6. In the edit modal, make the desired changes and click 'Save'.
7. At this point, the search platform modal remains open, but in the background, the gift entry form will refresh and take you back to the gift entry main page - any data entered thus far will be lost.

![image](https://user-images.githubusercontent.com/55844773/89812186-ba9b0200-db0d-11ea-9401-0e1508cdfaa6.png)

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7937899)
