### ISSUE TITLE
Recurring Donations Batch Job: sObject type 'AsyncApexJob' is not supported

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5738]
If an NPSP Scheduled Job (for example, npsp__RD_RecurringDonations_BATCH) is run as the _Nonprofit Success Pack_ User, it is possible to receive the following error:

**Error Type**: Batch Apex error
**Message**: "First error: sObject type 'AsyncApexJob' is not supported."
**Context**: npsp__RD_RecurringDonations_BATCH

### Resolution
The Scheduled Job should run as an actual User in your Salesforce org. 
1. Go to Setup --> Scheduled Jobs. 
2. Find the job called "NPSP 06 - Recurring Donation Updates".  Click the "Del" link next to it. 
3. Go to the NPSP Settings tab. This will automatically reschedule all of your NPSP jobs as the current User.
4. To confirm, go back to Setup --> Scheduled Jobs. Look at the "Submitted By" column next to the "NPSP 06 - Recurring Donation Updates" job. It should now show your name.
5. If it does NOT show your name or if that job isn't showing up in the list, it likely means that you have a setting toggled on to prevent us from auto-rescheduling jobs. This can be found in NPSP Settings --> Bulk Data Processes --> Batch Process Settings. The checkbox is labeled "Don't Auto Schedule Default NPSP Jobs". 

- If you would like to reschedule all jobs, uncheck this and click Save. 
- If you would ONLY like to reschedule the Recurring Donations Batch job, go to Setup --> Apex Classes. Click the Schedule Apex button and enter the following information:
*** Job Name: NPSP 06 - Recurring Donation Updates
*** Apex Class: RD_RecurringDonations_BATCH
*** Frequency: Weekly; check the boxes next to every day.
*** Set an End Date far into the future and set a preferred time.

**Comment by questgrace** [comment]
For #3 - where is the NPSP Settings tab?

**Comment by judisohn** [comment]
@questgrace Go to waffle menu that's to the far left of your navigation bar, search for 'NPSP Settings' there. You'll need to be a System Administrator to view the NPSP Settings tab.

**Comment by questgrace** [comment]
@judisohn Thanks!  This worked for me!

**Comment by questgrace** [comment]
@judisohn So after the user is an actual user, will it run without failing overnight?  Is there another step I should take, like manually make it run again or should I wait to run overnight?

**Comment by judisohn** [comment]
@questgrace You can run it manually now or wait for it to run overnight. Up to you.

**Comment by jesslopez-sf** [comment]
W-7957832
