### ISSUE TITLE
Gift Entry: Lookup to parent object not populating if importing a child which already exists

### ISSUE THREAD

**Issue by bdvorachek** [SalesforceFoundation/NPSP#5740]
**Issue**

When importing a record that is a child relationship to Opportunity, and that record already exists, we expect the lookup to the Donation/Opportunity to get populated with the ID of the recently created Opportunity. Currently this does not happen.

**Steps to Reproduce**

1. Create a scratch org using the qa_org cci flow. This creates some extra custom objects/mappings needed to reproduce.
2. Edit the default Gift Entry template, ensure that the "CustomObject1Imported" is on the layout
3. Create a CustomObject1 record using this code in the dev console's Anonymous Apex function
  a. `insert new npsp__CustomObject1__c(Name='Test Custom 1');`
4. Start a new gift in Gift Entry using the updated default template 
5. Set the CustomObject1Imported field to the recently created CustomObject1 record.
6. Complete and save the gift, and process it if created in batch mode.
7. Open the CustomObject1 record you created earlier in the standard UI, or do a SOQL query in the dev console.
8. The npsp__Opportunity__c field will be empty, we expect this field to have the ID of the recently created Opportunity/Donation

**Work Item**: [W-7954193](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008U7gnIAC/view)

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7954193)
