### ISSUE TITLE
Find Matched Gifts Updates All Potential Opportunities, Regardless of Selection

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5749]
### Summary
When using the **_Find Matched Gifts_** button on an Opportunity, we display a list of potential Opportunities that a customer may select to associate with the matching gift. If a customer selects or deselects an Opportunity, various tasks will be performed, such as creating/removing Soft Credits. We then call an update on the list of potential Opportunities. We don't filter out just those that we selected or deselected... we update ALL. This leads to Apex CPU timeouts in customer orgs where many potential Opportunities are presented to the customer.

**Expected Behavior:**
If I select 1 Opportunity in the list of potential Opportunities, I would expect just that Opportunity to be updated.

**Actual Behavior**
ALL potential Opportunities are updated. (There might not be any field values changing, but our Trigger Handlers would fire and check for potential Customizable Rollups updates, for example).

### Steps to Repeat
1. Go to NPSP Settings --> Donations --> Customizable Rollups. Enable Customizable Rollups.
2. Create an Organization Account called "Salesforce." Set _Matching Gift Company_ to checked.
3. Create 3 Contacts.
4. Create an Opportunity for each Contact (Record Type = Donation; Amount = 50; Stage = Closed Won; Matching Gift Account = Salesforce; Matching Gift Status = Potential).
5. Create an Opportunity for the Salesforce Account (Record Type = Matching Gift; Amount = 1000; Stage = Closed Won).
6. Click the Find Matched Gifts Action on the Salesforce Opportunity. Three Opportunities should appear. Select just 1 of these Opportunities and hit Save.  All 3 Opportunities will be updated (can be confirmed with time stamp or by checking debug log). 

### Root Cause
In [MTCH_FindGifts_CTRL](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/MTCH_FindGifts_CTRL.cls), the saveChanges() method loops through all potentialGifts and sees if they are selected or not. We then run `update potentialGifts` on line 286 without filtering out the Opportunities that actually need to be updated.

**Suggestion**: add a `List<Opportunity>` and add modified Opportunities to this list. Only update this new `List<Opportunity>` vs. the entire list of Opportunities.

**Comment by jesslopez-sf** [comment]
W-7964240

**Comment by davidchengIC** [comment]
Is this on the roadmap to be fixed?

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlD4QAI&title=find-matched-gifts-updates-all-potential-opportunities-regardless-of-selection) in the Trailblazer Community for updates.
