### ISSUE TITLE
ADDR_Contact_TDTM throws exception when adding Contacts for non-household account types

### ISSUE THREAD

**Issue by tjnoyessf** [SalesforceFoundation/NPSP#5751]
Virtually everywhere else in NPSP when the TDTM is called for non-household accounts, a null check is done before checking value of npe01__SYSTEM_AccountType__c . However, in ADDR_Contact_TDTM at line 117, it does not and fails when I'm loading Contacts for Organization Accounts. There is no restriction prior to this that the Account has to be household and so non-household accounts will have this line executed and will not have a value, likely, in this field. At least in DataLoader.

ADDR_Contact_TDTM.cls:117:                if (a.npe01__SYSTEM_AccountType__c != CAO_Constants.HH_ACCOUNT_TYPE)

I believe the line of code about should have a null check first on the npe01__SYSTEM_AccountType__c. This is done elsewhere in 'general' triggers that can be called for non-household or other NPSP account types.

ACCT_Accounts_TDTM.cls:95:                    if (acc.npe01__SYSTEM_AccountType__c == null || acc.npe01__SYSTEMISINDIVIDUAL__c != true) {
. . .
ACCT_Accounts_TDTM.cls:101:                    if (acc.npe01__SYSTEM_AccountType__c == null || acc.npe01__SYSTEMISINDIVIDUAL__c != true) {

Exception received to my email in our production org:
Apex script unhandled trigger exception by user/organization: 00536000008HTXU/00D36000000JGva

npsp.TDTM_Contact: execution of BeforeInsert

caused by: System.NullPointerException: Attempt to de-reference a null object

Class.npsp.ADDR_Contact_TDTM.run: line 117, column 1
Class.npsp.TDTM_TriggerHandler.runClass: line 193, column 1
Class.npsp.TDTM_TriggerHandler.run: line 113, column 1
Class.npsp.TDTM_Config_API.run: line 92, column 1
Trigger.npsp.TDTM_Contact: line 33, column 1

**Comment by coriobriensfdo** [comment]
Hi @tjnoyessf, we normally don't provide assistance here in Github as all inquires or issues with the NPSP should be posted in the Power of Us Hub, or as a Support case. 
As a start, can I ask you to please post in the [NPSP Group in the Hub](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack)? Also, we can't recreate your issue using the UI, so would appreciate all of your steps to repeat the error. For example, are you inserting via a dataloader tool, or the API? 
If we can repeat the problem outside of your org and need to file this as a bug fix or change against the NPSP we can re-open this Issue record and provide to our engineers.

Thank you!
