### ISSUE TITLE
Enhanced Recurring Donations: Related fields should be updated when "Recurring Period" or "Recurring Type" changes

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/NPSP#5755]
### Summary
When a Recurring Donation is saved with "Recurring Period" = “Advanced” and “Installment Frequency“ greater than one, then when the ”Recurring Period“ is changed to ”Monthly“ on the RD edit form, the record is saved with ”Installment Frequency“ as it was before the change to every month. The ”Installment Frequency“ should be changed to 1 due to "Recurring Period" being set to ”Monthly“ currently.

When the Recurring Donation is saved with “Recurring Type” = “Fixed” and “Number of Planned Installment” specified, then when the “Recurring Type” is changed from “Fixed” to “Open”, the  “Number of Planned Installment” stays as it was for the fixed type and the RD cannot be saved.

### Steps to Repeat

**Scenario 1**

1. View Recurring Donations tab and click [New] 
2. Specify Contact and other fields in Donor Information and Status Information sections. Specify Amount in the Donation Information. Leave "Recurring Type" as Open.
3. Specify "Recurring Period" as "Advanced". Set "Every" to 2 and leave the "Installment Period" to "Months" > [Save]
4. Click [Edit] on the Recurring Donation and set "Recurring Period" to "Monthly" > [Save]

_Expected Result_
- The "Installment Frequency" on Recurring Donation should be equal to 1.

_Actual Result_
- The "Installment Frequency" on Recurring Donation stays 2.

**Scenario 2**

1. View Recurring Donations tab and click [New] 
2. Specify Contact and other fields in Donor Information and Status Information sections. Specify Amount in the Donation Information. 
3. Specify "Recurring Type" as Fixed and specify the "Number of Planned Installments".  > [Save]
4. Click [Edit] on the Recurring Donation and change "Recurring Type" to "Open" > [Save]

_Expected Result_
- The RD is saved as Open "Recurring Type" and  "Number of Planned Installments" is **empty**.

_Actual Result_
- The RD cannot be saved. An error is displayed: "Number of Planned Installments is for Fixed Recurring Donation only. Remove the value in Number of Planned Installments or change the Recurring Type to Fixed.".

### Workaround
- Scenario 1: Edit the Recurring Donation and set "Recurring Period" to "Advanced" and "Every" value to 1 > [Save]
- Scenario 2: The RD cannot be changed from Fixed to Open on the RD entry form. User with a profile having "Mass Edits from Lists" checked in the System Permissions on the profile overview can change the record on the Recurring Donations tab. Inline edit the "Number of Planned Installments" and **remove the value** and set "Recurring Type" to Open > [Save].

**Comment by RadSFDeveloper** [comment]
[W-7972962](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008UIsVIAW/view)

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCzQAI&title=enhanced-recurring-donations-related-fields-should-be-updated-when-recurring-period-or-recurring-type-changes) in the Trailblazer Community for updates.
