### ISSUE TITLE
Enhanced Recurring Donations: Read permission on Day of Month should be required to Pause RD

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/NPSP#5756]
### Summary
When a pause already exists or it is to be created on a Recurring Donation and a user does not have read permission on the "Day of Month" field, an error should be displayed about insufficient permissions. Currently an exception is generated instead of a user friendly error. 

### Steps to Reproduce

1. View a user profile > Object Settings > Recurring Donations > Edit > Uncheck read access next to "Day of Month" field > Save.
2. As the above user, view a Recurring Donation > click [Pause] > select an installment to pause

_Expected Result_
- A user-friendly error is displayed about missing read permission on "Day of Month" field

_Actual Result_
- An exception error is displayed

### Workaround
Update user profile so that "Day of Month" on Recurring Donation SObject has a read permission.

**Comment by RadSFDeveloper** [comment]
[W-7973051](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008UIu8IAG/view)

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCuQAI&title=enhanced-recurring-donations-read-permission-on-day-of-month-should-be-required-to-pause-rd)  in the Trailblazer Community for updates.
