### ISSUE TITLE
Enhanced Recurring Donations: Other information not required on Pause RD field permission error 

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/NPSP#5757]
### Summary
When a user does not have read access on Recurring Donation “Amount”, “Day of Month” and “Payment Method” fields, then no installment is displayed. An error message and [OK] button are displayed as expected. However, the pause description message and the “Paused Reason” field are displayed as well and this additional information is not required.

### Steps to Reproduce

1. View a user profile > Object Settings > Recurring Donations > [Edit] > remove read access on  “Amount”, “Day of Month” and “Payment Method” fields > [Save]
2. Login as the user > view a Recurring Donation record > click [Pause]
3. Verify the page content:

_Expected Result_
- The Recurring Donation name, the installment permission error and the [OK] button are displayed. No other RD/pause information is displayed.

_Actual Result_
- Besides the Recurring Donation name, the installment permission error, and the [OK] button, there are pause page description and Paused Reason field being displayed on the page.

## Workaround
Not applicable, the page displays the error and the [OK] button. User cannot edit or save a pause which is expected. Additional information does not interfere with the page interaction on this error type.

**Comment by RadSFDeveloper** [comment]
[W-7976546](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008ULNxIAO/view)

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCkQAI&title=enhanced-recurring-donations-other-information-not-required-on-pause-rd-field-permission-error) in the Trailblazer Community for updates.
