### ISSUE TITLE
Enhanced Recurring Donations: A non-null value in "Number Planned Installments" for an Open Ended RD causes Next Donation Date to be null

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/NPSP#5766]
### Summary
When an Enhanced Recurring Donation record has a Recurring Type of "Open", a Status of "Active" and a value of 0 in the "Number of Planned Installments" field, the Next Donation Date will be set to null on the RD record.

### Steps to Reproduce

1. Enabled Enhanced RD
1. Create a new Open ended Recurring Donation
2. Using Developer Console, update the RD record to have a value of 0 in the `npe03__Installments__c` field
3. Review the record in the UI
4. Click Edit and change a value such as Amount or Day of Month
5. Save the record

_Expected Result_
- The Next Donation Date will have the correct value

_Actual Result_
- The Next Donation Date is blank.

## Workaround
- Set the value in the `npe03__Installments__c` field to null on all Open ended Recurring Donations using a Data Loader tool or Developer Console

**Comment by force2b** [comment]
[W-7984522](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008IGfLIAW/view)

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCpQAI&title=enhanced-recurring-donations-a-non-null-value-in-number-planned-installments-for-an-open-ended-rd-causes-next-donation-date-to-be-null) in the Trailblazer Community for updates
