### ISSUE TITLE
Contact Merge Button Error When Clicked Twice

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5779]
When a customer clicks the Merge button on the Merge Contacts modal twice, they receive the following error:

"Error: Failed to lock all the records for merging. Please retry from start."
![Screen Shot 2020-08-21 at 3 10 06 PM](https://user-images.githubusercontent.com/29731456/91053937-93eec800-e5f1-11ea-88e4-0860da5ceb0a.png)

The merge does appear to go through, though, since one of the transactions does complete. This error has come up sporadically for several customers. Some say it occurs when they don't double-click the button, but we can't replicate on our own aside from the double-click (my only theory there is that maybe it's a timing issue with slowness/ lots of related records?).

My request here is to have us disable the Merge button when clicked (like we have in many other areas of our product).

### Steps to Repeat.
1. Create Contact with FirstName = 'Test' and LastName = 'Contact'
2. Create Contact with FirstName = 'Test' and LastName = 'Contact'.
3. Go to the Contact Merge tab and search for "Test Contact."
4. Select the Contacts and click Next.
5. Click the blue Merge button.
6. On the modal that appears, click the red Merge button twice. This should throw the error noted above.

### Root Cause
The error is surfaced in [CON_ContactMerge_CTRL](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/CON_ContactMerge_CTRL.cls).

We query for the winning/losing Contacts via [a SOQL query with FOR UPDATE](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/CON_ContactMerge_CTRL.cls#L985-L988), to lock the records:

```
List<Contact> lock = [
SELECT Id
   FROM Contact
   WHERE Id IN :allContacts for update];
```

[The error is thrown during the following block of code because the lock size is not equal to size of allContacts.
](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/CON_ContactMerge_CTRL.cls#L990)
```
if (lock == null || lock.size() != allContacts.size()) {
   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,
      label.npe01.Contact_Merge_Error_Lock_failed + ' ' +
      label.npe01.Contact_Merge_Error_please_retry) );
      return null;
}
```

**Comment by jesslopez-sf** [comment]
W-8001155

**Comment by coriobriensfdo** [comment]
[Another Hub Post.](https://powerofus.force.com/s/question/0D51E00005Q2dnhSAB/why-do-i-keep-getting-error-messages-when-trying-to-merge-contacts)
