### ISSUE TITLE
Gift Entry: Opportunity stage is not being populated based on selected Record Type

### ISSUE THREAD

**Issue by skristem** [SalesforceFoundation/NPSP#5784]
**Description:**
When using the single gift entry form or batch gift form in the Gift Entry app with the template being used has both Record Type and Opportunity Stage fields, if you change the record type, the picklist values on Opportunity Stage field is NOT  being updated with values valid for that particular record type.

**Steps to reproduce:**

1. Open Gift Entry and Edit default template.
2. Add RecordType and Opportunity Stage fields to the default template and Save template.
2. Click on New Single Gift button and on the form select different values for Record Type and verify Stage picklist values.
3. For Batch gift, create a new batch with default template and in the gift entry form select different values for Record Type and verify Stage picklist values.

**Expected**: Opportunity Stage field should be re-populated according to selected RecordType.
**Actual**: Opportunity Stage field values are not getting populated according to selected RecordType.

![Recordtype2](https://user-images.githubusercontent.com/35269171/91102620-61a78f80-e61e-11ea-80e0-07a4ca9ff9ef.jpg)
![Recordtype1](https://user-images.githubusercontent.com/35269171/91102622-62d8bc80-e61e-11ea-9d55-b1cf829beb17.jpg)

**Comment by deepmalamehta** [comment]
W-7973926

**Comment by melissabarber** [comment]
Fixed by PR5763.
