### ISSUE TITLE
Gift Entry OwnerID Advanced Mappings cannot be edited in NPSP 3.183

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5795]
In NPSP versions prior to NPSP 3.183, if a user created an Advanced Mapping for the OwnerId field, and then added it to a Gift Entry template, it was editable. In NPSP 3.183 there was a change regarding allowed lookup functionality, and the platform lookup functionality will not allow editing of this field (https://developer.salesforce.com/docs/component-library/bundle/lightning:inputField/documentation).

**Steps to Recreate**

1. Go to NPSP Settings
2. System Tools > Advanced Mapping and Data Import & Gift Entry and click "Configure Advanced Mapping"
3. Click the "View Field Mapping under the Opportunity Object Group
4. Create a Create New Field Mapping for Owner ID (OwnerId) from NPSP Data Import Object to Owner ID (OwnerId) to the Opportunity and Save. Picture of Field Mapping as shown below:
![image](https://user-images.githubusercontent.com/53280203/91589034-f0155d00-e90d-11ea-876e-a1ae611d5e09.png)
<br>

5. Got to Gift Entry, edit an existing Template
6. Under "Form Fields" > Opportunity find the "Owner ID" mapping that you just created, and add it to a section of the template
7. Save the Template
8. Attempt to create a new batch with this template and in an org with:
i.  NPSP version prior to 3.183: the field **is** editable
ii. NPSP version 3.183: the field is **not** editable

<br>

**Workaround**

Currently no workaround available to allow the editing of this field in Gift Entry until a new release with an update to this field.

**Comment by mbeaty-sf** [comment]
[W-8021858](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008XWEvIAO/view)

**Comment by ameyersalesforce** [comment]
This is caused by this known issue: https://trailblazer.salesforce.com/issues_view?id=a1p3A000000ATQiQAO

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pi1HQAQ&title=gift-entry-ownerid-advanced-mappings-cannot-be-edited) in the Trailblazer Community for updates.
