### ISSUE TITLE
Customizable Rollups & Matching Gifts: Find Matched Gifts causes Duplicate Contact Roles and Partial Soft Credits when multiple gifts from the same Contact are associated with a Matching Gift Opportunity and incorrect amount-driven Soft Credit Rollups.

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#5796]
### Example Use Case

Jane Doe donates regularly to her favourite nonprofit. Her employer matches any donations she makes. The nonprofit receives a cheque from the matching employer at various points during the year. The cheque is a lump sum of all matched donations by employees during a recent period to the nonprofit. Jane has 3 separate donations in Salesforce that are set up correctly to be matched (Closed Won with a Matching Gift Status of Potential or Submitted). The nonprofit would like to create the Matching Gift opportunity in Salesforce and match the 3 existing donations to it. The nonprofit would also like the Soft Credit Rollups fields on Jane Doe to correctly reflect her soft credits as a matching donor. 

### Summary of Issues

Issue 1
When a contact has more than one Opportunity linked to a Matching Gift Opportunity via the Find Matched Gifts component, duplicate Contact Roles and duplicate Partial Soft Credits will be created for the Contact on the Matched Opportunity.

Issue 2
As a result of Issue 1, if Customizable Rollups are enabled and the Matching Donor role is included in the Soft Credit filter group, the Soft Credit Total will be incorrect as the amount from only one of the Partial Soft Credit records will be counted in rollup stats. Other Soft Credit rollups may also display incorrect values (e.g Soft Credit Last N Days, Soft Credit This Year, Largest Soft Credit Amount, Last Soft Credit Amount, First Soft Credit Amount)

Note: Legacy Rollups will calculate any amount-driven Soft Credit rollups correctly, but count-driven ones will be incorrect (e.g Number of Soft Credits).

### Steps to Replicate

**Issue 1**

1. Create an Account:
-- Name: Test Account
-- Matching Gift Company: Checked
-- Matching Gift Percent: 100%
2. Create a Contact:
-- First Name: James
-- Last Name: Browne
3. Create an Opportunity for James Browne
-- Record Type: Donation
-- Primary Contact: James Browne
-- Amount: 50
-- Close Date: (yesterday)
-- Stage: Closed Won
-- Matching Gift Account: Test Organisation
4. Create a 2nd Opportunity for James Browne
-- Record Type: Donation
-- Primary Contact: James Browne
-- Amount: 100
-- Close Date: (today)
-- Stage: Closed Won
-- Matching Gift Account: Test Organisation
5. Create an opportunity for Test Organisation
-- Record Type: Matching Gift
-- Amount: 150
-- Close Date: today
-- Stage: Closed Won
6. Navigate to the newly created Opportunity for Test Organisation
-- Click Find Matched Gifts
-- Select the opportunities created in steps 3 & 4 above and then Save
7. Confirm there are now two Contact Roles and two Partial Soft Credits for James Browne (see screenshot below)
![MatchingGift-DuplicateRoles](https://user-images.githubusercontent.com/59653509/91594162-55db0680-e959-11ea-9b29-9d2012c1094b.png)

**Issue 2**

1. Confirm Customizable Rollups are enabled
2. Confirm the Opps: Won (SC) Filter Group contains a Filter Rule where Role Name In List contains Matched Donor
3. Run Rollup Donations Batch
4. Review the Soft Credit rollup stats for James Browne
-- Soft Credit Total: $50.00 (expected $150.00)
Note: All Soft Credit amount-driven rollup values may be incorrect as only one of the opportunity amounts is being reflected in the rollups

![MatchingGift-IncorrectSoftCredits](https://user-images.githubusercontent.com/59653509/91594260-80c55a80-e959-11ea-984b-739acc0eb8c4.png)

### Workaround

When multiple opportunities from the same contact are to be associated with one Matching Gift Opportunity, aggregate the total of the opportunities and add one Partial Soft Credit via the Manage Soft Credits button. This will result in any amount-drive NPSP Soft Credit rollups being calculated correctly.

Or alternatively, remove the Matching Donor role from the Soft Credit filter group in Customizable Rollups and capture your Matching Donor Soft Credits in separate standard Salesforce rollup summary fields on Contacts, as the relationship between Contacts and Partial Soft Credits is master-detail.

**Comment by jamesbsfdc** [comment]
W-8021360

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pi1CQAQ&title=customizable-rollups-and-matched-gifts-duplicate-ocrs-cause-incorrect-soft-credit-values) in the Trailblazer Community for updates.
