### ISSUE TITLE
“CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:npsp.TDTM_DataImport: execution of AfterUpdatecaused by: System.QueryException: Non-selective query against large object type (more than 200000 rows). 

### ISSUE THREAD

**Issue by Marcio-PSL** [SalesforceFoundation/NPSP#5799]
Hello everyone, 

On 12th August 2020 the Nonprofit Success Pack was auto-updated (most probably after release v3.181). 
After that we started to receive exceptions when trying upsert npsp__DataImport__c records:

_“CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:npsp.TDTM_DataImport: execution of AfterUpdatecaused by: System.QueryException: Non-selective query against large object type (more than 200000 rows). Consider an indexed filter or contact salesforce.com about custom indexing.
Even if a field is indexed a filter might still not be selective when:
1. The filter value includes null (for instance binding with a list that contains null)
2. Data skew exists whereby the number of matching rows is very large (for instance, filtering for a particular foreign key value that occurs many times)(npsp)
:--”_

Seems like the issue is related to the SOQL query in the new BDI_DataImportBatchStatus_TDTM apex class:

[SELECT Id, Batch_Status__c, (SELECT Id, NPSP_Data_Import_Batch__c, Status__c FROM NPSP_Data_Imports__r) FROM DataImportBatch__c WHERE Id](url)

Because in our Production org we have more than 280k Data Import records that are assigned to the same NPSP Data Import Batch record.

Best regards, 

Marcio

**Comment by coriobriensfdo** [comment]
hi @Marcio-PSL we don't provide support here in GutHub. Can you instead post to the Power of Us Hub, in the [NPSP group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack), or [submit a support case.](https://help.salesforce.com/supportandservices?id=createCase&topic=Salesforceorg_Products_TOPIC)

**Comment by Marcio-PSL** [comment]
Sorry.
I will move it to a good channel. 

Thanks  :)
