### ISSUE TITLE
Lead Conversion Error When User is Not Lead Owner In Private Account Sharing Model

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5810]
When a customer has their Account Sharing set to “Private” and a User attempts to use the NPSP Lead Conversion tool on a Lead they don’t own, they receive the following error:

_List has no rows for assignment to SObject_

The error occurs in [LD_LeadConvertOverride_CTRL](https://github.com/SalesforceFoundation/NPSP/blob/a91e66e6bfdf55ce0e3d3dedbe770ec3483dee3f/src/classes/LD_LeadConvertOverride_CTRL.cls) when we run the following query on line 436

```
12:24:09.400 (1404300621)|SOQL_EXECUTE_BEGIN|[436]|Aggregations:0|select id, firstname, lastname, npo02__Household__c, MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry, MailingLatitude, MailingLongitude, HomePhone, Email from contact where id= '003xxxxxxxxxxxxx
12:24:09.400 (1416680139)|SOQL_EXECUTE_END|[436]|Rows:0
```

This occurs after we convert the Lead and then query for the Contact. They don’t have access to the Contact since we create the Contact and Account with the Owner Id set to the Lead’s Owner Id. 

The core Lead Conversion tool does not run into errors when converting Leads for different Owners despite setting the Contact/Account Owner to that of the Lead’s Owner. 

### Temporary Workarounds:
1. On the Lead Conversion screen, switch the Owner to the User converting the Lead.
2. Determine if there are any modifications that can be made to Sharing Rules. 

### Steps to Repeat:
In scratch org:

* Go to Setup → Object Manager → Lead → Buttons, Links, and Actions. Confirm there is an override on the Convert button to: LD_LeadConvertOverride.
* Clone Standard User Profile
    * add Create/Read/Update/Delete for Lead, Contact, and Account (All Fields: Read/Write)
    * Make the Organization Record Type the default Account Record Type for that Profile.
    * Add LD_LeadConvertOverride to Visualforce Page Access
* Create new User and assign to new Profile.
* Go to Setup → Sharing Settings and set Account access to Private.

**Tests:**

_**Test 1:**_
Create Lead as System Admin. Use Lead Conversion tool as System Admin.
Confirm Contact/Account are created successfully.

**_Test 2:_**
Create Lead as System Admin. Use Lead Conversion tool as non-System Admin.
Confirm Error at top of conversion page:
“Error: List has no rows for assignment to SObject.”
![Screen Shot 2020-09-03 at 3 24 47 PM](https://user-images.githubusercontent.com/29731456/92278020-4bbd8880-eec2-11ea-9fc2-0a19eda5293b.png)

**_Test 3:_**
Create Lead As non-System Admin. Use Lead Conversion tool as non-System Admin.
Confirm no error.

**_Test 4:_**
Switch lead conversion to core lead conversion (i.e. remove the override on the Lead Convert button). Create Lead as System Admin. Convert Lead as non-System Admin.

**Comment by jesslopez-sf** [comment]
W-8049112

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCWQAY&title=lead-conversion-error-when-user-is-not-lead-owner-in-private-account-sharing-model) in the Trailblazer Community for updates.
