### ISSUE TITLE
GAU amount field remains greyed out after entering and removing a percent value

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#5819]
WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008csGnIAI/view 

**Description**

If the General Accounting Unit form fields are added to the SGE/BGE form, and a percent value is entered into the Percent field, then erased, the Amount field remains greyed out and unusable.

This does not occur if the same actions are performed on the Amount field - the Percent field becomes usable again if a value is entered in the Amount field and then erased. The only way to make the field usable again is to delete the allocation row with the Delete button and re-add a new allocation row.

**Preconditions:**

GAU widget must be added to the template (which it is on the Default template)

**Steps to Reproduce**

1. Navigate to the Gift Entry App
2. Click 'New Single Gift' button
3. Click 'Add New Allocation' button
4. Type a number in the 'Percent' field. Amount field will be greyed out (as expected).
5. Erase the value from the Percent field. Amount field remains greyed out

**Comment by mbeaty-sf** [comment]
This fix was released in [NPSP 3.200](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.200)
