### ISSUE TITLE
Gift Entry in Multicurrency Enabled Org allows Currency field to be added to Batch Header but does not Import Values

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5830]
If a User is editing or creating a Gift Entry template in an Org that had Multicurrency enabled, they will see a field that can be added to the Batch Header. While this field can be added to the Batch Header, updating the value will not carry over to the Opportunities or Contacts that are in the Batch.

![image](https://user-images.githubusercontent.com/53280203/92981981-2ea03100-f451-11ea-8532-084546a058fe.png)

<br>

**Steps to Recreate**
1. Enable Multicurrency in Org
2. Setup a second currency after the default Org currency
3. Go to Gift Entry and edit a template
4. Navigate Batch Settings > Batch Header > and find a "Currency ISO Code" Checkbox under "Select Batch Header Fields" and check it to add it to the Batch Header. Save.
5. Create a new batch using the template edited in the previous step
6. When creating the Batch, find the Currency ISO Code field and populate it with the _second_ currency that you created in step 2.
7. Enter a Contact and a Donation into the batch as you would normally
8. Once a single Contact and Donation has been created, navigate to the NPSP Data Import Object and find the import record for the Contact and Donation that you just created and notice that the currency is the Org default instead of the currency chosen in the Batch Header
9. Return to the Gift Entry Batch and click "Process Batch" in the top right-hand corner of the page
10. Proceed to Start Import on the next page
11. When the import completes, navigate to the Opportunity that was created and notice that the Opportunity's currency is the default org currency and not that of the currency you chose in the Batch Header originally

<br>

**Workaround**
Create an NPSP Data Import to Opportunity, Currency field mapping. Go to > NPSP Settings > System Tools > Advanced Mapping for Data Import & Gift Entry > and click the Configure Advanced Mapping button. From there go to the Opportunity Object Mapping and click the downward facing arrow to "View Field Mappings". Create a New Field Mapping as pictured below. Once you save, you should now be able to add this to your template and subsequently the batches using that template, and rather than defining it at the Batch Header, you can define it on a per Opportunity basis, or default the value in the batch to be applied to all Opportunities.

**Comment by mbeaty-sf** [comment]
[W-8074700](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008IkkfIAC/view)

**Comment by davidchengIC** [comment]
@mbeaty-sf In your workaround, you mention "as pictured below" but there's no screenshot.  Can you provide the screenshot, or post details about the field mapping itself?  I've tried mapping the Currency field in Data Import object but the target picklist is greyed out so I can't specify the Opportunity's currency field.

**Comment by mbeaty-sf** [comment]
Hi @davidchengIC,

Apologies for the confusion, it does look like I missed the screenshot here, it was a picture of creating the Advanced Mapping to allow the ISO Code to be mapped on the Opportunity Object; however, with the recent update that closed this issue https://github.com/SalesforceFoundation/NPSP/issues/6132, this issue should also be closed as it isn't accessible anymore. I have requested to have it be linked to the release for clarity.
