### ISSUE TITLE
NPSP 3.185 Did not rollout to my full sandbox

### ISSUE THREAD

**Issue by Wycliffe-Julia-Torres** [SalesforceFoundation/NPSP#5858]
It seems that the 3.185 NPSP update that was scheduled to roll out on Sept 16 did not hit my orgs full sandbox. Mysteriously, it did hit all other sandboxes in our org. Is there an update link for sandboxes that I can use to manually push the update on our full sandbox?

**Comment by jamesbsfdc** [comment]
Hi Wycliffe

It is best to post questions like this on the Power of Us Hub rather than GitHub but yes you can upgrade your sandbox manually using the following link: https://test.salesforce.com/packaging/installPackage.apexp?p0=04t1Y000000ks2q
