### ISSUE TITLE
Gift Entry Tab Fails to Load For Users When Assigned “View All Data” Permission

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5873]
If a non-System Admin User is assigned a Permission Set with the "View All Data" Permission, the Gift Entry tab will fail to load. A gray spinner appears and an Uncaught (in Promise) error is surfaced in the browser console.
![Screen Shot 2020-07-29 at 2 06 50 PM](https://user-images.githubusercontent.com/29731456/94081756-55555480-fdcd-11ea-8921-f92f53280422.png)
![Screen Shot 2020-07-29 at 2 05 54 PM](https://user-images.githubusercontent.com/29731456/94144846-a9008600-fe3f-11ea-8ae8-cd8f141f6d7d.png)

### Root Cause:
This is due to a core Salesforce.com bug when accessing a managed package protected Custom Setting that’s referenced within our UTIL_CustomSettingsFacade class. 

### Workarounds:
**Option 1:** Add the View All Custom Settings permission to a Permission Set and assign to relevant Users.
**Option 2**: Remove the View All Data Permission from affected Users. 
**Option 3**: Not recommended… go to Setup —> Schema Settings and uncheck the “Restrict access to custom settings” option.

### Steps to Repeat:
1. Go to NPSP Settings and enable Advanced Mapping, followed by Gift Entry
2. Clone the Standard User Profile and name it “Test Profile”
3. Create a new User (Test User) and assign it to the Test Profile.
4. Assign Gift Entry Recommended Permission Set to System Admin and Test User.
5. Go to Gift Entry Tab as System Admin. Confirm page loads.
6. Go to Gift Entry Tab as Test User. Confirm page loads.
7. Create Permission Set called “VAD Permission Set”  with View All Data permission.
8. Assign to Test User.
9. Go to Gift Entry Tab as Test User. Confirm the page never loads.
10. Modify the “VAD Permission Set” to also include the “View all Custom Settings” permission.
11. Go to Gift Entry Tab as Test User. Confirm page loads.

**Comment by jesslopez-sf** [comment]
W-7222987
W-7863769

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCfQAI&title=gift-entry-tab-fails-to-load-for-users-when-assigned-view-all-data-permission) in the Trailblazer Community for updates.
