### ISSUE TITLE
Error ConvertLead Failed: first exception on row 0, first error: Duplicates Detected, use one of these records?

### ISSUE THREAD

**Issue by SurvivorDebbie** [SalesforceFoundation/NPSP#5884]
Hi.

I have a client who is attempting to convert a lead. She is receiving an error message: Error ConvertLead Failed: first exception on row 0, first error: Duplicates Detected, use one of these records?
Salesforce is saying there is no duplicate. I have run a debug log and honestly, I can only make out a little bit of it. (I am not a developer) The client is in NPSP and no duplication rule seems to apply.
The only thing I can think of at this point is that Salesforce is being finicky about having two households with the same name.
Does anyone have wisdom on this issue?
Thank you!

**Comment by coriobriensfdo** [comment]
Hi @SurvivorDebbie we don't provide support here in GitHub actually. Can you instead please post in the Power of Us Hub? The [NPSP group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) would be best.
