### ISSUE TITLE
Error referencing `GEM_API_Settings__mdt`

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/NPSP#5904]
Two nights ago, I ran some code overnight that updated a Contact record in my prod environment.  We have a regular nightly job that does this, so this happens nearly every night.

Instead of working, it hit an error with this stack trace:

```
caused by: System.InvalidParameterValueException: Invalid sobject provided. The Schema.describeSObject() methods does not support the GEM_API_Settings__mdt sobject as a parameter. The sobject provided does not exist.

Class.npsp.ADV_PackageInfo_SVC.setup: line 87, column 1
Class.npsp.ADV_PackageInfo_SVC.useAdv: line 148, column 1
Class.npsp.TDTM_ObjectDataGateway.__sfdc_listTH: line 94, column 1
Class.npsp.TDTM_ObjectDataGateway.getClassesToCallForObject: line 71, column 1
External entry point
Class.npsp.TDTM_TriggerHandler.run: line 101, column 1
Class.npsp.TDTM_Config_API.run: line 92, column 1
Trigger.npsp.TDTM_Contact: line 33, column 1
```

I think this is [entirely within Cumulus](https://github.com/SalesforceFoundation/NPSP/blob/88adf1b43c636621f73a84faac9efae9bc945f7a/src/classes/ADV_PackageInfo_SVC.cls#L87) (the inner try block in the code below), but I'm confused why your catch block doesn't catch the exception.

```apex
            try { // With Namespace
                Schema.DescribeSObjectResult[] descResult = Schema.describeSObjects(new String[]{orgSetting.Advancement_Namespace__c + '__' + settingsObjs[i]});
                isManaged = true;
                found = true;
            } catch (Exception e) {
                try { // Without Namespace
                    Schema.DescribeSObjectResult[] descResult = Schema.describeSObjects(new String[]{settingsObjs[i]});
                    found = true;
                } catch (Exception ex) {
                    i++;
                }
            }
```

**Comment by jamesbsfdc** [comment]
Hi there

Unfortunately we don't provide support via GitHub. Please could you create a new post for this in the NPSP group in the Power of Us Hub: https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack

Thanks

**Comment by ckoppelman** [comment]
sorry, I followed the link on the README for reporting bugs.
