### ISSUE TITLE
Gift Entry - Lookup Fields Values do not Persist when Defaulted on Template

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5931]
If a Template is created in Gift Entry that includes Lookup fields that have a defaulted value in the saved template, those values are cleared out upon consecutive entry of records.

**Steps to Recreate**
1. Create a new Gift Entry Template 
2. Default the values:
a.  Data Import: Contact1 Imported
b.  Opportunity: Campaign ID
3. Create a new Batch with the Template that you have just created
4. Save your first give, with the values that are defaulted from the Template
5. Notice that the defaulted values in the fields to be entered are now blank. Leave them untouched, enter any other field values you wish, and Save the gift
6. Notice that the gift inherits the previous gift's lookup values that were defaulted in the template, despite them being blank on entry

![2020-10-07_14-35-10 (1)](https://user-images.githubusercontent.com/53280203/95393235-120be300-08af-11eb-859f-6dca315b5252.gif)

<br>

**Workaround**
The values are still appended to the saved Gifts. Ensure that you check the NPDP Data Import records to confirm the values have carried over to those records before saving to verify.

**Comment by mbeaty-sf** [comment]
W-8133954

**Comment by psadie-sfdo** [comment]
Manually closing this issue since the related [PR](https://github.com/SalesforceFoundation/NPSP/pull/5950) has been merged.
