### ISSUE TITLE
Apex governor limit warning

### ISSUE THREAD

**Issue by ingepepe** [SalesforceFoundation/NPSP#5935]
Merging contacts and converting leads send out these warnings:

Operation: /apex/npsp__LD_LeadConvertOverride
By user/organization: 
Caused the following Apex resource warnings:
npsp:Number of SOQL queries: 85 out of 100

Operation: /apex/npsp__CON_ContactMerge
By user/organization:
Caused the following Apex resource warnings:
npsp:Number of SOQL queries: 59 out of 100

**Comment by jamesbsfdc** [comment]
Hi there

We don't provide support via GitHub. Please could you instead post this on the Power of Us Hub NPSP group here: https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack

Thanks 

James
