### ISSUE TITLE
Enhanced Recurring Donations: RD2_EntryForm & Compact density setting - Form fields and labels display misaligned and if a Console app is being used the Recurring Donation cannot be edited

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#5938]
### Summary of Issues

Enhanced Recurring Donations uses a Lightning Component (RD2_EntryForm) to override the New and Edit buttons on Enhanced Recurring Donations. The form displays correctly in the Comfy density setting, however in the Compact density setting fields and labels are misaligned.

In addition if a user is using a Console app combined with the Compact density setting they will be unable to Edit an Enhanced Recurring Donation as they will receive an error message in Winter 21 orgs, or in Summer 20 orgs the form will not open in when clicking on Edit. The only workaround is to change the density setting back to Comfy and edit the Enhanced Recurring Donation

### Steps to Replicate (error when editing Recurring Donation in Console with the Compact density setting)

- Ensure Enhanced Recurring Donations is Enabled
- Ensure the RD2_EntryForm override is applied to the New and Edit buttons on Recurring Donations
- Edit you are using a Console app with the Compact density setting
- Edit a Recurring Donation
- User will receive the following error message in a Winter 21 org. In a Summer 20 org the form will not open (internal auto-created WI for the Winter 21 GACK: W-7996291)
- Workaround: Change the density setting to Cosy and edit the recurring donation

![ERD in Console and Compact](https://user-images.githubusercontent.com/59653509/95768438-423bf300-0cae-11eb-928c-45519660a477.png)

### Steps to Replicate (misalignment in Compact)

- Ensure Enhanced Recurring Donations is Enabled
- Ensure the RD2_EntryForm override is applied to the New and Edit buttons on Recurring Donations
- Create or Edit a Recurring Donation 

**Example 1: Recurring Type = Open; Recurring Period = Monthly**

Issue: Misalignment between cells in column 1 vs columns

![Compact-Open-Monthly](https://user-images.githubusercontent.com/59653509/95768588-7b746300-0cae-11eb-8d6e-468816b8bdea.png)

**Example 2: Recurring Type = Open; Recurring Period = Advanced**

Issue: Misalignment between fields in columns 1, 2 and 3

![Compact-Open-Unselected](https://user-images.githubusercontent.com/59653509/95768640-8f1fc980-0cae-11eb-9df6-3bb54e350322.png)

**Example 3: Recurring Type = Open; Recurring Period = Advanced; Installment Period: Months**

Issue: Misalignment between fields in columns 1 and 2, and 3 and 4, and Day of Month and Effective Date running over 2 lines

![Compact-Open-Months](https://user-images.githubusercontent.com/59653509/95768669-9941c800-0cae-11eb-9c0c-11d3316a6101.png)

**Example 4: Recurring Type = Open; Recurring Period = Advanced; Installment Period: Years**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Open-Years](https://user-images.githubusercontent.com/59653509/95768693-a494f380-0cae-11eb-9eb6-0cd265ea43b8.png)

**Example 5: Recurring Type = Open; Recurring Period = Advanced; Installment Period: Weeks**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Open-Weeks](https://user-images.githubusercontent.com/59653509/95768717-af4f8880-0cae-11eb-93ed-71048963a9d3.png)

**Example 6: Recurring Type = Open; Recurring Period = Advanced; Installment Period: 1st & 15th**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Open-1 15](https://user-images.githubusercontent.com/59653509/95768735-b8d8f080-0cae-11eb-93e8-29db20d483a2.png)

**Example 7: Recurring Type = Open; Recurring Period = Advanced; Installment Period: Days**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Open-Days](https://user-images.githubusercontent.com/59653509/95768752-c2625880-0cae-11eb-93fe-337aa756de1f.png)

**Example 8: Recurring Type = Fixed; Recurring Period = Monthly**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Fixed-Monthly](https://user-images.githubusercontent.com/59653509/95768786-cf7f4780-0cae-11eb-8f41-20869778a34b.png)

**Example 9: Recurring Type = Fixed; Recurring Period = Advanced; Installment Period: Months**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Fixed-Months](https://user-images.githubusercontent.com/59653509/95768817-d9a14600-0cae-11eb-96f4-740cfcaa4d4f.png)

**Example 10: Recurring Type = Fixed; Recurring Period = Advanced; Installment Period: Years**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Fixed-Years](https://user-images.githubusercontent.com/59653509/95768869-e9208f00-0cae-11eb-8f45-142bd94b5557.png)

**Example 11: Recurring Type = Fixed; Recurring Period = Advanced; Installment Period: Weeks**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Fixed-Weeks](https://user-images.githubusercontent.com/59653509/95768907-f6d61480-0cae-11eb-849d-4847dd81c575.png)

**Example 12: Recurring Type = Fixed; Recurring Period = Advanced; Installment Period: 1st & 15th**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Fixed-1 15](https://user-images.githubusercontent.com/59653509/95768943-02294000-0caf-11eb-8b4b-b9fa1460a488.png)

**Example 13: Recurring Type = Fixed; Recurring Period = Advanced; Installment Period: Days**

Issue: Misalignment between fields in column 1, 2 and 3

![Compact-Fixed-Days](https://user-images.githubusercontent.com/59653509/95768979-0e150200-0caf-11eb-8dc2-aab1c26506a1.png)

**Comment by jamesbsfdc** [comment]
W-8204236

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCaQAI&title=enhanced-recurring-donations-recurring-donation-form-fields-misaligned-not-editable-in-console-app) in the Trailblazer Community for updates.
