### ISSUE TITLE
BDI: Cannot use autonumber field as Contact Custom Unique ID

### ISSUE THREAD

**Issue by Filikin** [SalesforceFoundation/NPSP#5946]
Because an autonumbered field cannot be included in the field mapping, if you attempt to use it to match contacts (Contact Custom Unique ID) you get an error like this "SObject row was retrieved via SOQL without querying the requested field: Contact.ConstituentID__c" when you process the batch - it is fine on a dry run.

**Comment by mbeaty-sf** [comment]
Hi @Filikin,

We don't provide support via GitHub. Please could you instead post this on the Power of Us Hub NPSP group here: https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack

Thank you,
Michael

**Comment by Filikin** [comment]
hi Michael,
so are you saying that this isn't a bug?
regards,
Eamon

________________________________
