### ISSUE TITLE
Gift Entry: Sorting on Certain Columns Causes "No Such Column" Error

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#5951]
On the Gift Entry landing page, when I try to sort list view columns (both Batch table and Templates table) by Form Template, LastModified By, Created By, and Owner, I see this error:

"No such column {!Field Name} on entity 'npsp__DataImportBatch__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
![Screen Shot 2020-10-15 at 7 47 02 AM](https://user-images.githubusercontent.com/29731456/96119207-a3381680-0eba-11eb-9861-0cfbccfcfa72.png)

### Steps to Repeat
1. Go to the Gift Entry Tab
2. Go to the Batches sub-tab.
3. Click on the Form Template column header. Confirm the error appears.
4. Now switch to the Templates sub-tab. 
5. Click on the Created By field. Similar error appears.

**Comment by jesslopez-sf** [comment]
W-7859492

**Comment by voduyemi** [comment]
Manually closing this issue since the related [PR](https://github.com/SalesforceFoundation/NPSP/pull/5889) has been merged.
