### ISSUE TITLE
Gift Entry - Entering a Donation with same GAU when Campaign has Default GAU Causes Error but Creates Opportunity, Payment, and Allocation

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5955]
If a User has a default GAU on a Campaign, and a Donation is entered through Gift Entry with any other GAU (including the same one that is on the Campaign), and error is thrown and will not create the record. While the Import Record from Gift Entry shows that there is an error and the import failed, the Opportunity, Payment, and Allocation are still created.

<br>

**Steps to Reproduce**
1. Create a Campaign and assign a General Accounting Unit under the GAU Allocations Related List, and set it to 100%
2. Enter Gift Entry and ensure the following fields are visible on the Template being used to enter the gift:
i.  General Accounting Unit
ii.  Amount (for General Accounting Unit)
iii.  Opportunity: Campaign ID
3. Enter the relevant information to generate a gift, but ensure that the below values are entered:
i.  Opportunity Campaign ID = **The same Campaign created in step 1**
ii.  General Accounting Unit = **any General Accounting Unit**
iii.  Amount (for General Accounting Unit = **Amount matching gift Amount**
4. Click the button "Save & Enter New Gift
5. Click the button "Process Batch", and process the batch to attempt to create the single record
6. The batch shows that errors were encountered; however, an Opportunity, Payment, and GAU Allocation are still generated relating to the Contact
7. Return to the batch to see the Error message:

<br>

- _If the General Accounting Unit fields were added to the batch template manually, then this error appears under the "Error" batch header:_

`GAU Allocation 1: Import Status: Allocation totals can't exceed the amount of the related Payment or Opportunity`

<br>

- _If the General Accounting Unit "Field Bundle" was added to the template, then this error appears under the "Error" batch header:_

`Additional Object JSON - GAU_Allocation_1_bf6a2bca3temp1: Allocation totals can't exceed the amount of the related Payment or Opportunity.`

<br>

**Workaround**
Managing Allocations via the "Manage Allocations" button on the Opportunity record's GAU Allocations Related List will allow for the correct adjustment of the Allocations, in stead of editing them via Gift Entry.

**Comment by mbeaty-sf** [comment]
Related Issue - https://github.com/SalesforceFoundation/NPSP/issues/5699

**Comment by mbeaty-sf** [comment]
W-8226306

**Comment by allisonletts** [comment]
I'm seeing this issue elsewhere as well--if I create a split gift with any GAUs, even when neither is the default for the campaign, I get the same errors. Entering a gift split through Manage Allocations later is a challenging workaround.

**Comment by mbeaty-sf** [comment]
@allisonletts In the org where you are seeing this do you have a Default GAU set in NPSP Settings?

**Comment by allisonletts** [comment]
Yes, and using Subledger so cant turn it off.


Allison Letts
Salesforce Services Group
Attain, LLC
Phone: 215.559.3100 | Email: ahletts@attain.com
________________________________

**Comment by mbeaty-sf** [comment]
Your issue sound like a combination of this one and and this: https://github.com/SalesforceFoundation/NPSP/issues/5699 (though I know that you did not mention this was on editing an existing gift) so what I am wondering is if you have access to a sandbox of the same configuration where you could temporarily disable Accounting Subledger and subsequently Default GAU to see if the error still occurs.

**Comment by kiggy392** [comment]
Seeing this issue a lot for clients using gift entry, they end up creating a lot of duplicates accidentally. If using the Manage Allocations button isn't an option for them, what's the best alternative? Deleting the Opportunity, fixing the data import record, then reimporting?

**Comment by mbeaty-sf** [comment]
Hi @kiggy392,

If you are seeing this issue still, please provide info on the Power of Us Hub in the Gift Entry group for further discussion.

https://powerofus.force.com/s/group/0F91E000000bs7KSAQ/gift-entry

**Comment by kporray1** [comment]
Please follow this [Known Issue ](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCVQAY&title=gift-entry-entering-a-donation-with-same-gau-when-campaign-has-default-gau-causes-error-but-creates-opportunity-payment-and-allocation)in the Trailblazer Community for updates.
