### ISSUE TITLE
Enhanced Recurring Donations - Unable to edit a Recurring Donation if the RD2_EntryForm has already been loaded in an Edit context in the same browser session

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#5968]
### Summary of the Issue

If a user loads the RD2_EntryForm in a record Edit context and then tries to load it again, by editing the same or another recurring donation, in the same session they will not be able to do so. The RD2_EntryForm model will briefly display and then disappear so the user cannot edit the record. Trying to click Edit again on any Recurring Donation will result in the same behaviour, so the user is prevented from editing more than one recurring donation in the same browser session.

Note: The user does not need to actually made an edit to the record when loading the RD2_EntryForm for the 1st time, simply loading the form and then cancelling the form will also result in them not being able to load the form again when editing any record.

### Steps to Replicate

- Ensure Enhanced Recurring Donations is enabled and the RD2_EntryForm is in place as a Lightning Experience Override for the Edit action/button
- Create a new Recurring Donation
- Click Edit on the Recurring Donation, and then Save or Cancel
- Click Edit on the same Recurring Donation, or any other Recurring Donation
- Observe the RD2_EntryForm modal displays briefly but then disappears
- Clicking on Edit again results in the same behaviour

**Potential Workarounds until the issue is addressed**

After editing a Recurring Donation, do one of the following, and then repeat this each time you need to edit more than one Recurring Donation in the same session:

- Force refresh the page (Windows: ctrl + F5; Mac/Apple: Apple + R or command + R; Linux: F5)
- Clear the browser cache
- Logout of Salesforce and then back in

**Comment by jamesbsfdc** [comment]
W-8233811

**Comment by codexmarcel** [comment]
Included in production release 3.188
