### ISSUE TITLE
Enhanced Recurring Donations - Enabling Debug Mode for Lightning Components prevents the viewing of Recurring Donation records and generates an error in Lightning App Builder

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#5970]
### Summary of the Issue

When Enhanced Recurring Donations is enabled, enabling Debug Mode for Lightning Components either generates an error or a blank page when trying to view Recurring Donation records. Additionally, if a user tries to edit the Lightning page in Lightning App Builder they will receive a Lightning error.

### Steps to Replicate

- Ensure Enhanced Recurring Donations is enabled and the NPSP Recurring Donation Lightning page is the default record page
- Enable Debug Mode for Lightning Components (Setup --> Debug Mode Users --> Enable for your test user)
Navigate to a Recurring Donation record
- The 1st time you view a record you will get error 1 below
- If you view the record a 2nd time you will get a blank screen
- Additionally if you edit the page in Lightning App Builder you will receive error 3 below
- Removing the Active Schedules and Upcoming Installments components from the Lightning page and saving the page, or creating a new Lightning page without these components, will prevent you from receiving the error and allow you to view Enhanced Recurring donation records again

**Error 1: 1st time view a recurring donation**

![Error 1](https://user-images.githubusercontent.com/59653509/96691055-581b7900-137c-11eb-89d4-33d83ec8f3e0.png)

**Error 2: 2nd time view a recurring donation**

![Error 2](https://user-images.githubusercontent.com/59653509/96691067-5c479680-137c-11eb-98d9-67fb037c83ac.png)

**Error 3: Lightning App Builder**

![Error 3](https://user-images.githubusercontent.com/59653509/96691106-65d0fe80-137c-11eb-908e-5ca8ae1f06b9.png)

Error Message Text

GACK: -590972623

Action.prototype.finishAction Error [Error in $A.getCallback() [Compiler Error: Invalid @track installments declaration.]

Callback failed: serviceComponent://flexipage.editor.aura.component.FlexipageComponentController/ACTION$loadComponentDefinitions]
new Aura.externalLibraries()@https://customer-computing-4197-dev-ed.lightning.force.com/auraFW/javascript/uB7Kis-nrXhbA1D0ce6Sog/aura_proddebug.js:30619:23
{anonymous}()@https://customer-computing-4197-dev-ed.lightning.force.com/auraFW/javascript/uB7Kis-nrXhbA1D0ce6Sog/aura_proddebug.js:25478:1

### Workaround

Disable Debug Mode for Lightning Components

**Comment by jamesbsfdc** [comment]
W-8244164

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCHQAY&title=enhanced-recurring-donations-enabling-debug-mode-for-lightning-components-prevents-the-viewing-of-recurring-donation-records) in the Trailblazer Community for updates.
