### ISSUE TITLE
Gift Entry Payments: Elevate ID missing on Payment record created after fixing the error on Gift Entry form

### ISSUE THREAD

**Issue by skristem** [SalesforceFoundation/NPSP#5973]
WI- https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008h6SPIAY/view
**Description:**
When there is an error on Gift Entry form but Credit Card is charged, we give the user option to review the form but payment is already created in elevate. When the user corrects the error on the form and saves it, that creates the Opportunity and Payment record in Salesforce but since payment record is created later in salesforce, Elevate Information is missing on the payment record but DI has the elevate information.

Steps to Reproduce:
1. Open Gift Entry and from Templates tab edit the Default Gift Entry Template and add elevate widget to the form and save.
2. Click on New Single Gift button to open the Single Gift page and Enter valid CC data
3. Choose a Non-Household Contact as a donor
4. Attempt processing and payment goes through but the user receives an Error message advising that card was charged but records are not created and asks to review form
At this point, a payment is created in elevate and a DI record is created in Salesforce but no opportunity or payment records are created
5.click on Review Form and change the donor from Contact to Account and select org account and save the gift again

Expected: Opportunity and Payment records are created, DI is imported and the payment record has Elevate Information
Actual: Opportunity and Payment records are created, DI is imported but no Elevate info on payment

**Comment by mbeaty-sf** [comment]
Fixed in [NPSP 3.189](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.189)
