### ISSUE TITLE
Primary Affiliation field cleared on Merge of Contacts with Primary Affiliation of same Account

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#5976]
When merging Contacts that share the same Account as their Primary Affiliation, the winning Contact does not display the Account in the lookup field Primary Affiliation upon merge completion.

<br>

**Steps to Recreate**
1. Create 2 Contacts with the same First Name and Last Name
2. Create an Organization Account
3. Assign the Organization Account created in Step 2 as Primary Affiliation for both Contacts created in Step 1
4. Click on the App Launcher and navigate to Contact Merge
5. Search for the First and Last Name of the Contacts created in Step 1
6. Select both Contacts for merge
7. In Selecting the values to marge, notice that the Primary Affiliation cannot be chosen between winning Contacts as it references the same Account record
8. Click Merge to proceed and acknowledge that the process is not reversible to continue
9. When your page reloads, you will land on the winning Contact page and notice that the Primary Affiliation lookup is present
i.  There are also 2 Affiliation records to the same Account on the newly merged Contact
10. Wait a few seconds and reload the page and notice that the Primary Affiliation is no longer populated, and the 2 Affiliation records have now been reduced to one

<br>

**Cause**
The AFFL_Affiliations_TDTM.cls attempts to find duplicates that are on single Contacts when assessing for the "winning" Primary Affiliation; however, in this case both Contacts have only a single Affiliation record to the same Account.

Because the code is searching for which Affiliation is Primary and which is oldest: https://github.com/SalesforceFoundation/NPSP/blob/7811c16471a5bb12c762849babac6d6566ece107/src/classes/AFFL_Affiliations_TDTM.cls#L659
and generating a unique key to be iterated through: https://github.com/SalesforceFoundation/NPSP/blob/7811c16471a5bb12c762849babac6d6566ece107/src/classes/AFFL_Affiliations_TDTM.cls#L698
based on:

```
        string afflKey = 
            affl.npe5__Contact__c + ':' + 
            affl.npe5__Organization__c + ':' +
            affl.npe5__Role__c + ':' +
            affl.npe5__Status__c + ':' +
            affl.npe5__Description__c + ':' +
            string.valueOf(affl.npe5__StartDate__c) + ':' + 
            string.valueOf(affl.npe5__EndDate__c);
        return afflKey;
```

As the Organization referenced is the same, and you are merging duplicates, these values may very well be identical outside of the affl.npe5__Contact__c, should be Primary, which in this case is both as they are the same Organization Account and immediately following the winning Contact coming out of the merge process is both assigned and removed.

<br>

**Workaround**
The issue is not occurring in the case where there are two different Affiliations, or one Contact is missing an Affiliation as referenced in a previously fixed issue (https://github.com/SalesforceFoundation/NPSP/issues/2753), but if the Affiliation is the same on both Contacts, and removed by the code when the merge is complete, the User will have to go to the Affiliation record: uncheck Primary on the Affiliation record, save, and then check Primary again and save the record to have the NPSP Affiliation class populate the Primary Affiliation field on the Contact.

**Comment by mbeaty-sf** [comment]
W-8253310

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCQQAY&title=primary-affiliation-field-cleared-on-merge-of-contacts-with-primary-affiliation-of-same-account) in the Trailblazer Community for updates.
