### ISSUE TITLE
Dashboard: Correct the "Amount by Range This Year" component in the Giving Range Analysis Dashboard

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#5990]
### Summary of the Issue

The "Amount by Range This Year" component on the Giving Range Analysis Dashboard currently sums by Total Gifts when it should sum by Total Gifts This Year.

See below a screenshot of the "Amount by Range Last Year" and "Amount by Range This Year" components from the Giving Range Analysis Dashboard, with each dashboard summary highlighted in red.

Note: The "Amount by Range Last Year" component summarises by Total Gifts Last Year whereas the "Amount by Range This Year" summarises by the Total Gifts.

![Giving Range Analysis Dashboard](https://user-images.githubusercontent.com/59653509/97417809-033dac80-1900-11eb-89ac-e6723ecefa06.png)

See below a screenshot of the value the component is summarising by, the Account: Total Gifts field, within the Edit Component panel.

![Amount by Range This Year](https://user-images.githubusercontent.com/59653509/97417852-0e90d800-1900-11eb-8094-0dd310ad163f.png)

See below the code segment from GitHub with the sum value highlighted in red.

![Amount by Range This Year - Code](https://user-images.githubusercontent.com/59653509/97417884-19e40380-1900-11eb-90cd-59f1649f9654.png)

### Customer Workaround

As the dashboard is unmanaged, users should manually change the value in the component to **Sum of Total Gifts This Year**

### Solution

Change the Value in the component to Sum of Total Gifts This Year in the Trialforce org and in GitHub.

See suggested code change below:

        <aggregate>Sum</aggregate>
        <axisBinding>y</axisBinding>
        <column>Account.npo02__OppAmountThisYear__c</column>

https://github.com/SalesforceFoundation/NPSP/blob/master/unpackaged/config/reports/dashboards/NPSP_Dashboards/Giving_Range_Analysis.dashboard#L124

**Comment by jamesbsfdc** [comment]
W-8276127

**Comment by melissabarber** [comment]
Fixed by PR 6226.
