### ISSUE TITLE
Gift Entry: Batch number should not be allowed in batch wizard and for field mappings.

### ISSUE THREAD

**Issue by deepmalamehta** [SalesforceFoundation/NPSP#5992]
**Description:** Batch number should not be available to be added to the batch gift wizards enabling users to add and edit batch numbers. The batch number should also not be available for field mappings.

**Steps:**
1. Configure the batch number.
2. Add a batch number to the Gift Entry template in the batch header section
3. Create a new batch.
4. Batch wizard has a batch number field.
5. Create new field mappings for Opportunity/Payments.

**Expected:** The batch number should neither be visible in the batch wizard nor in the drop-down for field mapping window.

**Actual:** The batch number is visible in the batch wizard and field mapping window.
![image](https://user-images.githubusercontent.com/42785185/97480009-13f61e80-1910-11eb-9cc7-d796985e56a2.png)
![image](https://user-images.githubusercontent.com/42785185/97480043-23756780-1910-11eb-965e-a693512afca6.png)

**Comment by deepmalamehta** [comment]
**lurch: attach W-8277712

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCLQAY&title=gift-entry-batch-number-should-not-be-allowed-in-batch-wizard-and-for-field-mappings) in the Trailblazer Community for updates.
