### ISSUE TITLE
Rich text fields prevent batch gift entry table from rendering in namespaced orgs

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6006]
In a namespaced org, if a Rich Text Area field has been added to a template used for Batch Gift Entry, when the BGE form is opened, an error is thrown ("Invalid field name 'npsp__c'") and the batch gift entry table is not rendered. Gifts can still be saved successfully, but the table is not rendered until the Rich Text Area is removed from the form. This does not occur if creating a single gift. This does not occur in non-namespaced orgs.

![image](https://user-images.githubusercontent.com/55844773/98392933-96749180-2026-11eb-99ff-87b0cfa90b19.png)

![image](https://user-images.githubusercontent.com/55844773/98392951-9e343600-2026-11eb-9081-5c630b805bdf.png)

**Steps to Reproduce**

1. Create a Rich text area field on the Contact object (since its mapped to Advanced Mapping by default) and the NPSP Data Import object.
2. Map the two fields together in Advanced Mapping
3. Navigate to the Gift Entry app.
4. Open the default template, and add the rich text field to the template and save it.
5. Create a new batch using the modified default template.
6. When the BGE form opens, the error message will display and the table will not be rendered.
7. Navigate back to the Gift Entry app.
8. Click 'New Single Gift'.
9. When the form opens, note that the error does not occur.

GUS WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008KqXSIA0/view

**Comment by judisohn** [comment]
@schlossmj This is a dupe of #6005 isn't it?

Also

**Comment by schlossmj** [comment]
Thanks for the heads up @judisohn - was unaware this dupe got created. Closing.
