### ISSUE TITLE
Entity is Deleted Error when Saving a Contacts record with no Address and "Address Override" checked

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6022]
**Issue**
Attempting to clear Mailing Address values from a Contact record, and check "Address Override" as TRUE to stop the associated Household from overriding the Contact's blank address, results in an:

`"We hit a snag" entity is deleted` error on the page

It is possible to clear the address, and lookup to address record on a Contact record, allowing the saved Contact to have a blank Address with "Address Override" when they are in a shared Household. In the Manage Household page, if the Contact with the Address Override checkbox as TRUE is being removed, clicking the Save button on the Manage Household page to update the record results in this error:

`Update failed. First exception on row 1 with id <<the id of the Contact being removed>>; first error: ENTITY_IS_DELETED, entity is deleted: []`

<br>

**Steps to Reproduce**

_On single Contact record_
1. Create a Contact record and leave all address fields blank, but check Address Override as TRUE
2. Using the Manage Household button, add both Contacts to the same Household Account
3. Go to one of the 2 Contact's pages and remove all of their address information and check Address Override as TRUE
5. Click Save
6. Encounter **entity is deleted** error

![image](https://user-images.githubusercontent.com/53280203/99008062-4865ff00-24fa-11eb-9df3-f6db18ef793b.png)

<br>
<br>

_In Manage Household Page_
1. Create 2 Contacts with different addresses
2. Using the Manage Household button, add both Contacts to the same Household Account
3. Go to one of the 2 Contact's pages and remove all of their address information and click Save
5. Edit the record again and check Address Override as TRUE and click Save
6. Go to the Household record of both Contacts and attempt to remove the Contact that now has no address, but Address Override as TRUE from step 5, click Save on the Manage Household page
7. Encounter error:

![image](https://user-images.githubusercontent.com/53280203/99008446-0d180000-24fb-11eb-9938-b6238e427244.png)

<br>
<br>

**Workaround**
Put in address values into the Mailing Address fields on the Contact record in question and uncheck Address Override, click Save. If removing from the Household, return to Manage Household page and now remove the Contact. Return to the Contact that is now separated and clear the Address values.

**Comment by mbeaty-sf** [comment]
W-8390396

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kSMQAY&title=address-management-entity-is-deleted-error-when-saving-a-contacts-record-with-no-address-and-address-override-checked

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
