### ISSUE TITLE
Rich Text Fields are not cleared in GE form when entering batch gifts

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6034]
**Description:** Rich text fields are not cleared in the batch gift entry form after saving a gift. This also occurs if you open an existing gift and click the 'Cancel and Clear Form' button - the field remains populated with the gift's value when all other fields are cleared. This does not occur if a template-level default value is set in the field - saving a gift returns the rich text field to its template default value.

**Steps to Recreate:**

1. Map a rich text field to the gift entry form
2. Navigate to the Gift Entry app and add the mapped field to the desired form template
3. Create a new batch using the form template with the rich text field.
4. Enter donor information and "Gift #1" into the rich text field.
5. Save the gift.

**Expected Results:** Gift is saved, and all GE form fields are reset to blank or their default value.

**Actual Results:** Gift is saved, and the rich text field retains whatever text was entered prior to saving the gift - in this case, it would still read "Gift #1".

**Related Investigation**: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008J7tnIAC/view

**WI:** https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008isfYIAQ/view

**Comment by jamesbsfdc** [comment]
W-8430577

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kSHQAY&title=gift-entry-rich-text-field-values-are-not-cleared-in-a-gift-entry-form-after-gifts-have-saved-to-the-batch

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
