### ISSUE TITLE
NPSP Data Import Won't Update Custom Mapped Address Field For Matched Address

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#6043]
### Issue
If you map an NPSP Data Import field to a custom Address field using NPSP Advanced Mapping and NPSP Data Import finds a match to an existing Address record, it will not update the value in the mapped field. (It will populate the value if a new Address record is created, however).

### Root Cause
In [BDI_DataImportService’s importAddresses() method](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/BDI_DataImportService.cls#L1572), we query for existing Address records for that Contact’s Household Account and then [populate the mapHHAddrKeyToId](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/BDI_DataImportService.cls#L1609) (Type = Map<String, Id>). We then construct an Address record with the values from the Data Import record and concatenate the new values using the strKeyOfAddr method. However, this only concatenates the Household_Account__c, MailingStreet__c, MailingCity__c, MailingState__c, and MailingPostalCode__c of that not-yet-committed Address record. 

```
private static String strKeyOfAddr(Address__c addr) {
        return addr.Household_Account__c + addr.MailingStreet__c + addr.MailingCity__c + addr.MailingState__c +
            addr.MailingPostalCode__c;
    }
```

[We determine if an Address record with those values already exists in the system by calling this on line 1642](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/BDI_DataImportService.cls#L1642) :
`Id addressId = mapHHAddrKeyToId.get(strKeyOfAddr(address));`

In this case, because the concatenated values are the same (the only changed value is our custom field), BDI thinks there is nothing to update. So, instead, it sets the dataImport.HomeAddressImported__c to the existing Address Id and the HomeAddressImportStatus__c to ‘Matched’ and never updates the custom field on the matched Address record.
(If one of the concatenated field values would have changed, it would have noted the difference and inserted a new Address record, where the custom field would be populated with the correct value).

### Steps to Repeat:

**Setup:**
1. Enable Advanced Mapping in NPSP Settings
2. Create a custom field on the NPSP Data Import object called My Custom Field (text).
3. Create a custom field on the npsp Address object called My Custom Field (text).
4. In NPSP Settings — Advanced Mapping for Data Import & Gift Entry, click the Configure Advanced Mapping button.
5. View Field Mappings for the Address object group
6. Create a new field mapping for the custom fields you just created.

**Tests:**
1. Insert of new record - success.
    1. Create DI record with new Contact and Address. Fill in custom field.
    2. Go to To Be Imported View and Start Data Import.
    3. Leave config as defaults
    4. Click Begin Data Import Process
    5. Confirm Address record was created and that the custom mapped field has the value entered on the DI record.

2. Update of existing record with custom field updated - fail
    1. Create DI record with same Contact and Address information filled in. Put a different value in the custom field.
    2. Go to To Be Imported View and Start Data Import.
    3. Leave config as defaults
    4. Click Begin Data Import Process
    5. Contact1 Import Status = Matched
    6. Home Address Import Status = Matched
    7. But custom field is not updated.

3. Update of existing record with key field and custom field updated - success
    1. Create DI record with same Contact and Address information filled in. Put a different value in the custom field. Put a different value in the Home City field.
    2. Go to To Be Imported View and Start Data Import.
    3. Leave config as defaults
    4. Click Begin Data Import Process
    5. Contact1 Import Status = Matched
    6. Home Address Import Status = Created
    7. Confirm Address record was created and that the custom mapped field has the value entered on the DI record.

**Comment by jesslopez-sf** [comment]
W-8438809

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kSCQAY&title=npsp-data-import-a-custom-mapped-address-field-will-not-update-a-matched-address

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
