### ISSUE TITLE
Enhanced Recurring Donation: Editing existing RD produces Error Message

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#6071]
[Hub Thread](https://powerofus.force.com/s/feed/0D51E00005USyG0SAL)
[W-8487823](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008jvL8IAI/view)

**Issue:**
Editing an existing Enhanced Recurring Donation record causes an error message to display, even though edited values are saved as expected. 
**Error:**
_Sorry to Interrupt
This page has an error. You might just need to refresh it. First, would you give us some details? (We're reporting this as error ID: 58913069)
Technical Stuff:
[Cannot read property 'apiName' of undefined]
_.handleData()@https://coritrial--rdtesting.lightning.force.com/components/interop/recordEditForm.js:1:5057
eval()@https://coritrial--rdtesting.lightning.force.com/components/interop/recordEditForm.js:1:3041
eval()@https://coritrial--rdtesting.lightning.force.com/components/lightning/inputUtils.js:1:1555_

![Screen Shot 2020-11-23 at 1 17 10 PM](https://user-images.githubusercontent.com/37851761/100021224-ffce0180-2d95-11eb-8844-eb33d49d9a6a.png)

**Steps to Repro:**
1. In an org with Enhanced Recurring Donations enabled, create or locate an existing RD record.
2. Click Edit - You can make a change to a field value or not as the error will happen regardless
3. Click Save
Expected: Record saves and user is taken back to view the RD record
Actual: Error message is displayed, any changes made are applied successfully. 
If you can't repeat, try refreshing your browser tab/window. A pattern has been found where the first attempt to edit causes an error, but there's no error produced on subsequent edits (same record or others) until you refresh your browser tab.

**Comment by davidchengIC** [comment]
The same error occurs when cancelling out of edit, even when you haven't made any changes.  This occurs even when the user has full permissions to Recurring Donation and all fields.

**Comment by coriobriensfdo** [comment]
Update: This is a core Salesforce bug and has been transferred away from Salesforce.org scrum teams. Will close this Issue as it will not be resolved by Salesforce.org. 

@davidchengIC thanks for adding the nuance, I'll make sure Salesforce core see that.

**Comment by nai888** [comment]
@coriobriensfdo Is there anywhere we can track this issue with Salesforce.com? I'm running into this same issue and wondering if there's been any progress on it over there. Thanks!

**Comment by coriobriensfdo** [comment]
@nai888 there isn't a Known Issue for this particular Issue, however Salesforce has resolved the bug in an upcoming release. This should be resolved in the next few weeks, but feel free to re-post here if you don't see that in your org. Sorry for the confusion on this one, we'll make sure there's a KI next time so it's easier to follow.

**Comment by nai888** [comment]
@coriobriensfdo Thanks for the info! Are you referring to Spring '21? I'm running into this issue in a sandbox that's already upgraded.

**Comment by coriobriensfdo** [comment]
It's actually a patch release (Spring '21 Patch 6) so you may already see it resolved in Sandbox :)
