### ISSUE TITLE
Enhanced Recurring Donations: Default "Pledged" Stage not respected when using Pause feature

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/NPSP#6092]
[W-8533401](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008kjePIAQ/view)

**Issue:**

When using the RD2 Pause feature, the newly created Opty doesn't respect the default Stage of "Pledged" and instead uses the Stage of the previous open Opty that was Paused. By design, the NPSP should use the defined Stage within Custom Settings if one is defined. If empty, [NPSP code dictates Pledged should be used](https://github.com/SalesforceFoundation/Recurring_Donations/blob/master/src/labels/CustomLabels.labels#L180).
![Screen Shot 2020-12-03 at 9 03 04 AM](https://user-images.githubusercontent.com/37851761/101070261-f55af700-354f-11eb-8a6d-df9a6b480f6f.png)

**Steps to Repro:**

1. In an org with Enhanced Recurring Donation enabled, create a monthly RD (can be any schedule type however).
2. Navigate to Recurring Donation Custom Settings and ensure “Stage Name for Installment Opportunities” is empty.
3. Note that the upcoming Opty has a stage of Pledged per NPSP default.
4. Edit the upcoming Opty and change Stage from Pledged to another Open Stage value, such as Prospecting.
5. Using Pause button, select that upcoming Opty and choose any Pause reason. Save to pause that Opty.
- Expected: Upcoming Opty will be deleted and new Opty for following month will be created as Pledged Stage value.
- Actual: Upcoming Opty deleted and new Opty for following month created as Prospecting Stage value.
![Screen Shot 2020-12-03 at 9 20 45 AM](https://user-images.githubusercontent.com/37851761/101070413-318e5780-3550-11eb-834d-abba13dfe362.png)

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kS7QAI&title=recurring-donations-default-pledged-stage-not-respected-when-using-pause-feature

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
