### ISSUE TITLE
NPSP Settings - Missing Record Type

### ISSUE THREAD

**Issue by dlisovsky** [SalesforceFoundation/NPSP#6098]
Hi Team,

If there is a managed Record Type on Opportunity with the same name as a custom one - then both are not available in the NPSP Settings (Opportunity Naming) and other Record Type related settings:
![image](https://user-images.githubusercontent.com/4610433/101371999-79004500-38bc-11eb-9c6d-c46e2640d521.png)
![image](https://user-images.githubusercontent.com/4610433/101372128-9cc38b00-38bc-11eb-9d9f-e132fb7056a9.png)

There is an issue in UTIL_RecordTypes.cls class that removes the record type from the list by name if it's not active, it should also check the record type namespace.

![image](https://user-images.githubusercontent.com/4610433/101372462-fb890480-38bc-11eb-840c-bf211d3b33dc.png)

Thank you!

**Comment by mbeaty-sf** [comment]
W-9987330

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kRsQAI&title=npsp-settings-when-there-are-multiple-record-types-with-the-same-name-they-will-not-be-displayed-in-record-type-selection-settings

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
