### ISSUE TITLE
Namespaced fields that start with "r" incorrectly processed by BGE

### ISSUE THREAD

**Issue by bdvorachek** [SalesforceFoundation/NPSP#6113]
**Details**
This bug is specific to this area of code and was discovered during development - https://github.com/SalesforceFoundation/NPSP/blob/4d80ddc64569bc1cbf82154525638512e7244ce8/src/classes/BGE_BatchGiftEntry_UTIL.cls#L296

The intent of the code above is to take a lookup field that ends in `__r` and replace that `__r` with a `__c`

If a field with the name `npsp__Random_Name__c` is mapped and used during entering Gift Entry, the lines of code above will assume that the field is a lookup field and excessively shorten it to `fieldName == 'npsp__c'` after lines 296 and 297 run.

**Fix**

Change 296 to use `.endsWith` instead of `.contains`. 
Change 297 to use `.substringBeforeLast` instead of `.substringBefore`

**Comment by mbeaty-sf** [comment]
W-9987343

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kRnQAI&title=gift-entry-namespaced-fields-that-start-with-r-are-incorrectly-processed-by-gift-entry

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
