### ISSUE TITLE
Batch Gift Entry and Gift Entry - Unable to load Batch for Users with certain Locales

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6125]
**Issue**
Users are able to create batches and access the "Batch Gift Entry" and "Gift Entry" Tabs; however, upon trying to enter a batch to edit it, or add additional Opportunities, the loading stalls and the Batch Gift Entry or Gift Entry components are not loaded.

<br>

**Cause**
When a User is attempting to access with Batch Gift Entry or Gift Entry, and the locale that is set for the user record is of a country that uses "decimal commas" (100,00) as opposed to "decimal points" (100,00), the field `npsp__Batch_Gift_Entry_Version__c` interprets `2` as `2,00` instead of the expected `2.00`. This causes an issue as the value the can be entered in the "Set Component Visibility" section of a Lightning Record Page can only be a "decimal point" number, or whole number. Attempts to enter a "decimal comma" number result in an error. 

![image](https://user-images.githubusercontent.com/53280203/102287721-dfeeb100-3eef-11eb-8b5d-a69674e9518c.png)

Even if a whole number such as `2` is entered on the Lightning Record Page's "Set Component Visibility" section, the system will interpret the value to 2 decimal places, as the `npsp__Batch_Gift_Entry_Version__c` field is `double (4, 2)` and if the User's locale is from a country that uses "decimal commas" then Batch Gift Entry and Gift Entry attempt to intepret the `npsp__Batch_Gift_Entry_Version__c` in that locale, as it checks to see if:

1. `npsp__GiftBatch__c` = TRUE
2. `npsp__Batch_Gift_Entry_Version__c`
 a.  for Batch Gift Entry: `less than 2.0`
 b.  for Git Entry: `greater than or equal to 2.0`
 
 This correlates to the https://github.com/SalesforceFoundation/NPSP/blob/c413295aa556bc0a367daedb47bfe7f816599070/src/classes/BGE_BatchGiftEntry_UTIL.cls#L84
 
 Where the integer referenced includes `.0` which will not provide a valid argument in a "decimal comma" locale.
 
 <br>

**Steps to Reproduce**
1. Setup whichever entry product you are testing against in your org:
a.  Gift Entry - https://powerofus.force.com/s/article/NPSP-Configure-Gift-Entry
b.  Batch Gift Entry (Legacy) - https://powerofus.force.com/s/article/NPSP-Configure-Batch-Gift-Entry
2. Create a new User record
3. Change that newly created User record's locale to "Swedish (Sweden)"
a.  Note: You do **not** need to change language, currency, or timezone for the User record, only the locale
4. Login as that User
5. Attempt to access a batch record from the entry product that you enabled
6. Note that the page will not load and a blank screen persists without the respective page components loading

<br>

**Workaround**
For the affected users, change the locale on their User record to that of a country that utilizes a "decimal point" rather than a "decimal comma".

**Comment by mbeaty-sf** [comment]
W-8585968

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kRiQAI&title=gift-entry-unable-to-load-batch-for-users-with-certain-locales

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
