### ISSUE TITLE
Gift Entry - Currency Incorrectly Displaying and Converting Batch Totals

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6132]
**Issue**
If an org has enabled multi-currency, the values of gifts entered, and totalled under "Total Batch Amount" does not correctly display, or convert, the amount entered in the batch.

As a result of the conversion not correctly correlating by:

1. The Currency defined via the Currency ISO Code field is not changing the Total Batch Amount's currency to match the entered gift's currency/expected batch currency
2. If the batch is set to "Require Expected Totals Match" then the incorrectly converted amount causes issues hindering the batch from being closed and processed

<br>

![image](https://user-images.githubusercontent.com/53280203/102564171-b8364f00-408f-11eb-81a6-9521096653fa.png)

<br>
<br>

**Steps to Reproduce**

1. Enable Advanced Mapping and Gift Entry in Org
2. Go to Setup > Company Information > Edit and check Enable Multiple Currencies and Save
3. From the same page: Setup > Company Information > click "Currency Setup and add a new currency (such as GBP - British Pound) and add a conversion rate of 0.752
4. Update the currency used for running user in British Pounds on their user record
5. Goto Gift Entry
a.  Click on existing template
b.  Go to Batch Settings > Batch Header
c. Check Currency ISO Code
d.  Save
6. Create a new batch
a.  Pick the template you have updated
b.  Give it a batch name
c.  Currency ISO Code - currency you have added in currency setup
d.  Click Next(leave defaults)
e.  Save
7. Enter new gift info
8. Save and notice the "Gifts Entered for" section and compare Donation Amount and Total Batch Amount field shown in different currencies

**Workaround**
The gift values properly carry over to the Data Import Record once saved, and upon importing properly generate based on the User's currency defined on their User record; however, the Total Batch Amount value does not display properly, meaning that if a User has the "Require Expected Totals Match" option on the batch, they are not able to process it. There are two options for different scenarios:

1. Remove the "Require Expected Totals Match" from the Batch Info to allow for the proper processing of the Data Import Records
2. To properly calculate the Total Batch Amount, generate an "NPSP Data Imports with NPSP Data Import Batch" report that can be filtered by the batch and summarize the totals to verify

**Comment by mbeaty-sf** [comment]
W-8598455

**Comment by askebongsaxe** [comment]
Hi. I have a client whose use of gift entry is impeded by this issue. Would it be possible to get a tentative timeline for when this might be scheduled into a release? Just so I can inform my client. Thanks!

**Comment by mbeaty-sf** [comment]
Hi @askebongsaxe,

Unfortunately I do not have a timeline for this issue; however, if you can log a Case for this, we can relate it to the Issue itself so that the product team is aware how many users it is affecting. Please comment the Case # back on this thread so that I can relate it to this post.

**Comment by askebongsaxe** [comment]
Hi @mbeaty-sf. I have logged a support case, and the case number is 40414405. Thank you.
