### ISSUE TITLE
Can't save Batch Gift if "Opportunity: Is Gift Aid Excluded" is unchecked

### ISSUE THREAD

**Issue by geoffhom** [SalesforceFoundation/NPSP#6138]
Screenshot:
<img width="1380" alt="Batch Gift error" src="https://user-images.githubusercontent.com/21103/102895494-66dce580-442a-11eb-827f-be17114b12b8.png">

Steps to reproduce:

1. Add "Opportunity: Is Gift Aid Excluded" to default template
2. Create a new batch
3. (Donor type: Contact 1) (Contact Last Name: any) (Donation Date: any) (Donation Amount: any)
4. Click "Save and Enter New Gift"
5. error occurs

Notes:

1. Everything seemed fine on December 15 (UK) but stopped working on December 17. 
2. If you check and then uncheck "Is Gift Aid Excluded," it saves. 
3. However, this leads to another bug, where the value of that field in the table always reports as true. Screenshot:
<img width="265" alt="Screen Shot 2020-12-22 at 7 44 30 AM" src="https://user-images.githubusercontent.com/21103/102896016-5711d100-442b-11eb-8b9f-5bc570ff6713.png">

1. The table bug was reported: #6126.

**Comment by judisohn** [comment]
Hi @geoffhom What you're referring to is custom for your instance as there is no 'Is Gift Aid Excluded' field in NPSP. Please see if that field is provided from another package or app and you can report this issue to that developer. Thanks!

**Comment by geoffhom** [comment]
Thanks, @judisohn. I'm learning. =) Nevertheless, the code was working until the time of the NPSP release last week, so I'm a bit suspicious. You're right that the field is from a package, though the package hasn't been changed in months. 

Is the proper way to map a checkbox still to use a picklist with values of True and False? (https://powerofus.force.com/s/article/NPSP-Map-Using-Advanced-Mapping#topic-9098)

**Comment by judisohn** [comment]
@geoffhom The best way to troubleshoot further if NPSP is directly involved is to open a support case: https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case Thanks!
