### ISSUE TITLE
Engagement Plan Tasks Reminder Time Inconsistently Displayed after Creation

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6143]
**Issue**
When a User creates an Engagement Plan Task associated with an Engagement Plan Template, they are presented with a picklist of times that are in half-hour increments to choose a reminder time for an email notification to be sent. However, upon saving the Engagement Plan Task's Reminder Time is converted to an Integer. If a User attempts to edit the Task from this Task itself with an actual time for clarity (not through the Visualforce page) an error will be thrown.

**Steps to Reproduce**
1. In an org with NPSP installed, navigate to "Engagement Plan Templates" Tab
2. Click the "New" button from the list view, and you are taken to the Visualforce page to create an Engagement Plan template
3. Fill in all the relevant information for the Engagement Plan Template, and then click the "Add Task" button
4. Fill in required fields and choose a "Reminder Time" from the picklist
5. Save
6. Navigate to the Engagement Plan Template you just created and click the "Related" Tab to Find the "Engagement Plan Tasks" Related List
7. Click the Engagement Plan Task you created in Step 4
8. Find the field "Reminder Time" and see that the value you choose is converted into an integer, seemingly unrelated to the time that you chose

**Cause**
In the code for `EP_Task_UTIL.cls` time is converted into an integer by means of the time, `8:00am` = `8` multiplied by 60 minutes, `8 * 60` = `480` which is displayed on the Task.

The conversion can be seen in the code here:

https://github.com/SalesforceFoundation/NPSP/blob/ef653636c3fe021844f625e06c95e4b62fd7974a/src/classes/EP_Task_UTIL.cls#L280

This integer is appended to the Date to generate the `ReminderDateTime` needed to schedule the reminder. While this format is used to feed into the scheduled Date and Time for the Reminder, it creates confusion for the User when seen on the actual task and editing it outside of the Visualforce page creates an inconsistent experience.

<br>

_Visualforce Page for Engagement Plan Template_
![image](https://user-images.githubusercontent.com/53280203/103046152-0a69eb00-453c-11eb-829a-8abd30fdb5ec.png)

<br>

_The Task that is generated on Save in the Salesforce UI_
![image](https://user-images.githubusercontent.com/53280203/103046206-3b4a2000-453c-11eb-9bc2-ed72cb7e4972.png)

<br>

**Workaround**
If the time is edited on the Engagement Plan Template VisualForrce page, then there is no issue allowing for a time change, but it will still display as an integer on the Task.

**Comment by mbeaty-sf** [comment]
W-8607901

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kRYQAY&title=engagement-plans-tasks-reminder-time-inconsistently-displayed-after-creation

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
