### ISSUE TITLE
Address and Account Updates Are Not Blocked If Contact DML Failures Occur During Address Update

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#6144]
If an Address record is edited directly and updated Contacts within the DMLWrapper include failures, their Account and Address are still updated with the new values. This can lead to data integrity issues between Contacts, their Accounts, and their Address records.

This can occur most likely if there are Duplicate/Matching Rules configured at the Contact level. However, Validation Rules on the Contact are also a factor. 

### Root Cause
[ADDR_Addresses_TDTM](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/ADDR_Addresses_TDTM.cls) runs on Address records in the following contexts: BeforeInsert; BeforeUpdate; AfterInsert; AfterUpdate; AfterDelete. Near the end of the run() method, we send the contents of the dmlWrapper to TDTM_TriggerHandler's processDMLAllOrNothing() method. [We then check for errors and if present, loop through each error to see if the Id is related to an Account or an Address.](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/ADDR_Addresses_TDTM.cls#L184-L202) Finally, we use the addError() method to add the appropriate error message to the Account's Address record (by way of the mapAddressesByAcctId  map) or the Address record itself, which ultimately halts the transaction and prevents the updates from occurring to the Account, Address, and Contacts. 

We don't check to see if any errors occurred at the Contact level. As a result, the Contact update fails silently and the Account/Address update succeeds and data can be out of sync.

### Steps to Repeat
1. Go to NPSP Settings → People → Households and switch Household Naming to something other than the default. [This is done since the Order of Execution differs].
2. Go to NPSP Settings → System Tools → Error Notifications and check the box next to “Respect Duplicate Rule Settings.”
3. Go to Setup → Matching Rules. Deactivate any activated rules. Create a new Contact Matching Rule and set the following to exact match: Last Name, Mailing City, Mailing Zip. Activate the Matching Rule.
4. Go to Setup → Duplicate Rules. Deactivate any activated rules. Create a new Contact Duplicate Rule, set the Action on Create and Edit to “Block” and select the Matching Rule you created above. 
5. Create a new Contact
    1. First Name = Test
    2. LastName = Contact
    3. Mailing Street = 123 1st Avenue
    4. Mailing City = New York
    5. Mailing State = NY
    6. Mailing Zip Code = 12345

6. Create a second Contact
    1. First Name = Another
    2. LastName = Contact
    3. Mailing Street = 123 1st Avenue
    4. Mailing City = New York
    5. Mailing State = NY
    6. Mailing Zip Code = 10000 (make sure it’s different from the first Contact’s Zip Code)
7. Now go to the Address record for the second Contact. Edit the Zip Code to match the first Contact’s Zip Code (12345). 
8. Confirm that the Address and Account have their Zip Code set to 12345. However, the Contact’s Zip Code is still 10000.

### Workaround
Currently, the only workaround is to edit the Contact's mailing address fields instead of the Address's mailing fields. This will trigger the duplicate/matching rule error and will prevent the save.

**Comment by jesslopez-sf** [comment]
W-8612399

**Comment by jialeechau** [comment]
Hi @ameyersalesforce - could you please close this issue when you get the chance? Looks like this issue has been fixed.
