### ISSUE TITLE
NPSP Contact Merge: No Indication of Community User

### ISSUE THREAD

**Issue by drewpiston** [SalesforceFoundation/NPSP#6162]
Despite this previous issue (https://github.com/SalesforceFoundation/NPSP/issues/3338), in LEX there is no way to know which (if any) of the Contacts you are merging are Community Users.

It would be wonderful if we could see who is a Community User, like the below (fabricated) screenshot.

Thanks!

<img width="1216" alt="ContactMerge" src="https://user-images.githubusercontent.com/2659121/104071885-ea365f00-51be-11eb-94e1-242a06982b0f.png">

**Comment by coriobriensfdo** [comment]
Hi @drewpiston thanks for the post, but we don't track feature changes that aren't bugs here in Issues. Instead, you can post the change as an [Idea on the Trailblazer community](https://trailblazer.salesforce.com/ideaSearch).

Alternatively I [found an article ](https://trailblazers.salesforce.com/answers?id=9064S000000Ck1DQAS) that might help you create your own field on the Contact record to represent this, which could then be included in the fields in merge.
