### ISSUE TITLE
Gift Entry: Opportunity Stage not being populated based on Selected Record Type in Template Default

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6166]
**Issue**
This Issue closely mirrors - https://github.com/SalesforceFoundation/NPSP/issues/5784 - with the exception that this is happening when editing or starting a batch in the template default values.

**Steps to Reproduce**
1. Create a new Template in Gift Entry
2. Add Record Type and Opportunity Stage field sot the template
3. Change the Record Type to "Grant" and notice that if you view the picklist values under Stage, they are not updating dynamically based on record type

_Second Scenario_
1. Create a new batch with the template created above
2. Attempt the same steps from Step 3 above and notice that the behaviour is the same

**Expected Result**
When entering Donations in the Gift Entry batch, the Stages picklist will update based on the values defined in the Sales Process by the Opportunity Record Type; this is not happening when editing or creating a batch.

![2021-01-11_17-24-08 (1)](https://user-images.githubusercontent.com/53280203/104257686-dbf07900-5432-11eb-80f8-c353ecf0a419.gif)

**Actual Result**
![2021-01-11_17-13-33 (1)](https://user-images.githubusercontent.com/53280203/104257695-e3178700-5432-11eb-95aa-5be1c7969c4a.gif)

**Workaround**
The Stage values that are displayed in the Template edit and creation screens are the Stages that are tied to the User creating the batch's default Opportunity Record Type. i.e. if Donation is the default Opportunity Record Type, then the Stages shown are the Sales Process tied to that record type. If they default is Grant, then the Sales Process for Grant's Stages are what is shown; subsequently, it may allow a user to achieve the default they want at the batch template level by setting their User's default Opportunity Record Type to the desired type to expose the desired Stages in the picklist.

**Comment by mbeaty-sf** [comment]
W-8687223

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kR9QAI&title=gift-entry-in-a-template-the-opportunity-stage-values-are-not-populated-based-on-the-selected-record-type-default

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
