### ISSUE TITLE
Gift Entry Field-Permission Error Persists after Correction

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6187]
**Issue**
When a User accessing a Gift Entry batch does not have permission access to a field, they are presented with an error telling them:

`Check with your Salesforce admin about your field-level access. You must have permission to edit the following fields: <_Object_: (_<Test_Field__c>_)`

However, if the User that created the template didn't have access to the field and saved the template, even after it is corrected they are presented with the same error. Even if a User with field-level access re-saves the template, the error persists and cannot be cleared on that template which also means that a batch in process cannot be accessed.

<br>

**Steps to Recreate**
1. Create a field on Opportunity
a.  Ensure that you do not provide the field security to the profile of the user that you are currently using
2. Create a field on NPSP Data Import
3. Navigate to NPSP Settings > System Tools > Advanced Mapping for Data Import & Gift Entry > and click Configure Advanced Mapping
4. Create a mapping with the fields created in steps 1 and 2
5. Navigate to Gift Entry and click the "Templates" Tab and create a new Template
6. Add a variety of fields to the template, but include the field that you mapped in step 3
b. Note: When you add it, you will see an error message at the top of the page that says "Field Not Found" but you can still proceed to save
7. Save the template
8. Create a new batch with the template that you just saved and populate the title and leave the other fields as they are
9. Click "Save"
10. Notice that the batch shows the error:
a. `Check with your Salesforce admin about your field-level access. You must have permission to edit the following fields: <_Object_: (_<Test_Field__c>_)`
11. Edit the Template again and add other fields to the template that the User does have field-level access to, and save the template
12. Navigate to the field on the Opportunity that you created in step 1 and change the field-level security so that your User record now has access
13. Return to the batch that you started in step 8 and notice that the error persists

<br>

**Cause**
If a User that does _not_ have access to the field is the one who saves it with the field, the error message is saved into the template's JSON; however, if the access is given back to that User and they edit and saved the template, even if they remove the field, previous batches continue to show that error message.

The error message is written into the JSON of the template at the time the template is saved, but there is no check done against the User field permissions again if the field-level permissions are changed; even if the template is edited and saved again by that User, or another User. Additionally, the error message persists so the point where even if the field is removed, and saved by a User that has the field-level permission, creating a new batch with that template that has now been corrected by a user with permission, either including or excluding the field from the template, the error will still persist on new batches.

The bolded section at the very end of the JSON of a Gift Entry template is what is causing the error to display, and is not cleared out which causes it to persist:
`"permissionErrors":"Opportunity: (<test_field_name__c>)","permissionErrorType":"FLS"}`

<br>

**Workaround**

**_WARNING_** -- Editing the JSON of this template is not something that should be performed unless you are confident in your understanding as accidentally deleting unintended portions can cause other portions of the form to fail.

Currently the only way to correct this is to edit the JSON of the template directly, and is not recommended for the potential to unintentionally cause other issues **as it is a not a one size fits all code adjustment**

**Comment by mbeaty-sf** [comment]
W-8111013

**Comment by ptewson-sfdo** [comment]
A second - and substantially more blunt - workaround is to delete the template and make a new template with the desired fields, once access has been granted to the user.

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kOnQAI&title=gift-entry-field-permission-error-persists-after-correcting-the-field-level-permission

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
