### ISSUE TITLE
Prevent secondary address elements after comma from getting stripped in Cicero integration

### ISSUE THREAD

**Issue by kevinearldenny** [SalesforceFoundation/NPSP#6199]
### Current result

When a user enters a `MailingStreet` that includes a comma with stuff after it (e.g., "3018 Ellwood Ave, 2") the stuff after the comma is being stripped away in the `MailingStreet__c` field after validation. 

### Expected result

When a user has a `MailingStreet` that includes a comma with stuff after it (e.g., "3018 Ellwood Ave, 2") the stuff after the comma should be added back into the `MailingStreet__c` field to prevent it from being lost.

When a user has a `MailingStreet` that does not include a comma, we want to keep doing what we are already doing, which is overwriting `MailingStreet__c` with the street address returned from `match_addr`

**Comment by mbeaty-sf** [comment]
W-8777462

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kOoQAI&title=address-verification-secondary-address-elements-after-comma-are-getting-stripped-in-the-cicero-integration

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
