### ISSUE TITLE
Installation Guide For Developers

### ISSUE THREAD

**Issue by itsaboutcode** [SalesforceFoundation/NPSP#6208]
I want to install this in my dev account. I don't see any instructions about it. If anyone can guide me towards that.

**Comment by judisohn** [comment]
@itsaboutcode All of the NPSP documentation is here: https://powerofus.force.com/s/article/NPSP-Documentation

Installation instructions are here: https://powerofus.force.com/s/article/NPSP-Install

**Comment by itsaboutcode** [comment]
@judisohn - Thanks for the quick response. I want to install from the source. The installation given there are about installing the package. Sorry, I am being new to SF and trying to learn the coding by doing the actual bit and found this project to be perfectly suitable for this.

**Comment by judisohn** [comment]
Sorry, we don't directly support or provide documentation for downloading NPSP unmanaged/from source.

**Comment by itsaboutcode** [comment]
@judisohn - Sorry for asking another naive question but how can someone contribute to this code if I cant install it to my dev hub from the source.

**Comment by judisohn** [comment]
@itsaboutcode While NPSP is open source, we don't actively solicit contributions from developers who are not also actively using it in an org as a managed package. While pull requests are not rejected and we welcome the feedback and collaboration of our customer and partner community, the work in this repository is maintained 99.9% by an internal Salesforce team. If you're not familiar with NPSP already and actively using it in your work and projects, this may not be the best project to consider for contributions.
