### ISSUE TITLE
Error message deleting donation with multiple GAU Allocation

### ISSUE THREAD

**Issue by paquin-christian** [SalesforceFoundation/NPSP#6224]
I have a donation with multiple GAU Allocation (npsp__Allocation__c).   If I delete the donation, I get the following error message:
_**List has no rows for assignment to sObject. Unexpected error has occurred. Your solution provider has been notified (npsp).**_
The donation still gets deleted but the message appears.

If I have only 1 donation, the issue does not occur.

**Comment by jamesbsfdc** [comment]
Hi Christian, we don't offer support via GitHub issues. I was going to suggest creating a post in the Hub but I can see you have already done that. Closing this
