### ISSUE TITLE
Gift Entry - Error toast shown when validation rule is broken

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6229]
**DESCRIPTION:**
If I set a validation rule for the Data Import Object, and then attempt to enter a gift in Single Gift Entry that violates the validation rule, I am shown the following error modal instead of my selected error method in the rule:
![image](https://user-images.githubusercontent.com/55844773/107830519-fe3f2480-6d59-11eb-94bf-2fc33d3bf7b7.png)

Error
,"DMLErrorFieldNameMapping":}

If I perform the same action in Batch Gift Entry, I see the expected error message I chose when setting up the rule (Error message at the top of the page):

**STEPS TO REPRODUCE**

1. Navigate to Setup > Object Manager > NPSP Data Import
2. Set up a validation rule for that object to throw an error if a value in the Donation Amount field entered in Gift Entry is over $50 (npsp__Donation_Amount__c>50)
3. Navigate to the Gift Entry and click New Single Gift
4. Enter a new Gift that is over $50
5. Error toast is shown

**EXPECTED BEHAVIOR:**

User should see this error message instead:

![image](https://user-images.githubusercontent.com/55844773/107830579-29297880-6d5a-11eb-9b65-a488d5fc6df8.png)

**IMPACT TO END-USER :**

Bad UX, even though the rule is still firing when expected

WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000096WNbIAM/view

**Comment by jamesbsfdc** [comment]
This issue can no longer be replicated. 

We have tried to reproduce this with a validation rule on npsp__Donation_Amount__c setting the Error Location to Top of Page or Field: Donation Amount.
