### ISSUE TITLE
Valid gifts fail processing when mixed with erroneous gifts in batch

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6252]
In BGE, if you have a batch that contains both a gift that has failed dry run (and will fail processing, such as a gift assigned to an Org Contact) and a valid gift, batch processing fails for the valid gift as well with an 'Attempt to de-reference a null object' error.

![image](https://user-images.githubusercontent.com/55844773/109184027-8b23ae00-775c-11eb-97f7-946f53ce4b17.png)

**Workaround**: If you delete the invalid gift, and then attempt to re-process the batch, the valid gift processes successfully.

**Steps to Recreate**

1. Create an organization account record.
2. Navigate to the org account record and click 'New Contact', and create a new org-related contact.
3. Create a new contact not associated with the org.
4. Navigate to the Gift Entry app and create a new batch.
5. Create a gift with the Donor Type as Contact1 with both the org-related contact and the non-org related contact.
6. Process the batch.
7. Batch processing fails for both gifts.

GUS WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000097TMlIAM/view

**Comment by mbeaty-sf** [comment]
W-8935413

**Comment by jamesbsfdc** [comment]
This issue has been migrated to the Known Issues site: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kQKQAY&title=gift-entry-valid-gifts-fail-processing-when-mixed-with-erroneous-gifts-in-batch

Please follow the status of the issue there and select "This Issue Affects me" if you are affected by the issue.
