### ISSUE TITLE
Can't add custom implemetion of HH_INaming

### ISSUE THREAD

**Issue by iamiamiamiam** [SalesforceFoundation/NPSP#6254]
Hello,
For simplest implementation of HH_INaming interface (like below).

```java
global class TEST_HH_NameSpec implements npsp.HH_INaming {
    // global TEST_HH_NameSpec(){ System.debug('in'); }
    global String getExampleName(npsp__Household_Naming_Settings__c param0, String param1, List<Contact> param2) { return 'test'; }
    global String getHouseholdFormalGreeting(List<Contact> param0) { return 'test'; }
    global String getHouseholdInformalGreeting(List<Contact> param0) { return 'test'; }
    global String getHouseholdName(List<Contact> param0) { return 'test'; }
    global Set<String> setHouseholdNameFieldsOnContact() { return new Set<String>{'FirstName'}; }
}
```

In a Developer Org (NPSP 3.192) in "Examples for Household Name Format" field I got "Invalid Implementing Class."
In a Sandbox (NPSP 3.193) I see "Maximum stack depth reached: 2"
In logs:
```
11:59:21.2 (24606848)|FATAL_ERROR|System.LimitException: Maximum stack depth reached: 2
Class.TEST_HH_NameSpec.getExampleName: line 3, column 1
Class.npsp.STG_PanelHouseholds_CTRL.strNameSpecExample: line 271, column 1
```

Doesn't matter whether public no-arg constructor is present or not.

Reason for first error I think is incorrect `Type.forName` function being used in NPSP. A note from [docs](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_type.htm):

`"Use this method instead of forName(fullyQualifiedName) if it will be called from a managed package installed in an organization with no defined namespace. To get the name of a local type, set the namespace argument to an empty string or null. For example, Type t = Type.forName('', 'ClassName');."`

But still don't know what is causing second error?

**Comment by jamesbsfdc** [comment]
Hi Ian

We don't provide support via GitHub issues. Please could you post about the issue in the Power of Us Hub or log a support case. 

James
