### ISSUE TITLE
As a user I want to be able to click a Help link at the top of a page in the NPSP so that I can easily access the pertinent Help.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#628]
The "Help for this page" link is standard SFDC functionality. The link can be customized to go to any web page. (It does not have to be SFDC Help.)

We should add links of this nature to all NPSP pages, but only once we have content to link to. Linking to generic content is not advised.

We can do two, possibly three things:
- Start linking to Knowledge Base articles as they become updated and available.
  PRO: Will be able to link to stuff quicker.
  CON: Will need to manually change all of this when we move over to a new Help system down the line.
- Don't start creating these links until we have a new Help system.
  PRO: Will do it the right way the first time.
  CON: This might not be for another year.
- IF the "Help for this page" link is actually editable (my guess is that it is), we could make the link say "NPSP Help," and link to a generic landing page for Help in the KB.
  PRO: Gives the user something, which is better than nothing, and we could do this now.
  CON: Involves manual work to change over to a new Help system down the line.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001frLAAQ" target="_blank">W-008265</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
