### ISSUE TITLE
Recurring Donations Settings can understate successes and failures when an entire batch fails

### ISSUE THREAD

**Issue by rogeramitchell** [SalesforceFoundation/NPSP#6302]
### Background

Recurring Donations have a batch that runs nightly to insert new Opportunities for open ended recurring gifts. It records successes and failures when it finishes in the Recurring Donations Settings custom setting.

### Summary of Issue

- The overnight batch ([`RD_RecurringDonations_BATCH`](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/RD_RecurringDonations_BATCH.cls)) counts the number of records and failures, and updates the **Recurring Donations Settings** custom setting when the batch finishes
- If the batch's execute method hits a platform limit (e.g. Apex CPU limit exceeded), the variables for [number of records](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/RD_RecurringDonations_BATCH.cls#L138) and [failure count](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/RD_RecurringDonations_BATCH.cls#L139) are not incremented
- When these numbers are saved to Recurring Donations Settings, the [success](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/RD_RecurringDonations_BATCH.cls#L156) and [failure](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/RD_RecurringDonations_BATCH.cls#L157) counts are understated

### Potential Solutions

1. Create a new variable that indicates the number of batches that failed, the source of this would be `AsyncApexJob. NumberOfErrors` and can be added as field to the query [here](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/RD_RecurringDonations_BATCH.cls#L152)
1. Approximate the number of failures by multiplying the `AsyncApexJob.NumberOfErrors` (as described above) by the batch size ([`batchSize`](https://github.com/SalesforceFoundation/NPSP/blob/master/src/classes/RD_RecurringDonations_BATCH.cls#L62)); this is not precise because if the final batch fails and contains less records than the total batch size, it would overstate the failures

**Comment by judisohn** [comment]
@rogeramitchell All current and future Recurring Donation development is focused on the Enhanced Recurring Donation model. [You can learn more about it including the steps to upgrade here](https://powerofus.force.com/s/article/NPSP-Recurring-Donations-Overview-and-Setup). As this issue applies to the legacy model in how it creates forecast opportunities and updates batch status, which the new model does not do, we won’t be accepting this as an open issue at this time. I know this wasn't the answer you were hoping for... if you have questions or concerns about upgrading to Enhanced Recurring Donations, please post in the NPSP group in the Hub or open a support case. Thanks!
