### ISSUE TITLE
Gift Entry - Batch Import Status "Failed" but Contact, Opportunity, Payment still created

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6308]
**Issue**
When entering a gift into Gift Entry, if a GAU is entered into the field mapping (not the custom GAU bundle), but the allocation amount or percentage is not populated; upon import the record shows **Status:** `Failed` and **Errors:** `GAU Allocation 1: Import Status: Enter a value in either the Amount field or the Percent field.` This is the same error thrown when attempting to create a GAU Allocation manually and not providing these values and therefore the creation is blocked. The difference is that when this error is encountered in Gift Entry, a Contact, Opportunity, and Payment record are still created, despite the error when creating it through a batch, not Single Gift Entry.

**Steps to Reproduce**
1. Enable Gift Entry in an NPSP installed Org
2. Create a General Accounting Unit record
2. Edit the Default Gift Entry Template and remove the GAU bundle
3. Add these fields to the template:
a.  GAU Allocation 1: General Accounting Unit
b.  GAU Allocation 1: Percent
c.  GAU Allocation 1: Amount
4. Save the Template
5. Create a batch using the Default Gift Entry Template that you have edited
6. Add all necessary fields to create a Contact and a Gift, but in the 3 fields you added to the template, add only the GAU Allocation1: General Accounting Unit via the lookup, do **not** populate the _GAU Allocation 1: Percent_ or _GAU Allocation 1: Amount_
7. Click the "Process Batch" button and attempt to import the Gift
8. Notice that an error appears and that back in the Batch the **Status** is `Failed` and the **Errors** is `GAU Allocation 1: Import Status: Enter a value in either the Amount field or the Percent field.`
9. Notice that the Contact, Opportunity, and Payment have all been created, despite the Status and Error, but no Allocation record*

_Single Gift Entry_
If the same steps above are taken from Step 5, but using Single Gift Entry instead, the creation of the Contact, Opportunity, Payment are blocked by the error.

_*Optional_: In Step 9, it states that no Allocation record was created; however if you set a Default GAU in NPSP Settings will, at the first step, despite the error and creation of an Opportunity, Payment, and Contact, also create a GAU Allocation based on the Default GAU. The same error will still appear, and correcting the Gift by adding the Amount or Percentage through editing in Gift Entry will show a successful import in Gift Entry, but will **not** change the GAU Allocation on the Gift.

**Workaround**
Ensure that the Percentage or Amount fields are populated at the time of the batch import.

**Comment by mbeaty-sf** [comment]
W-9032097

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlCBQAY&title=gift-entry-batch-import-status-failed-but-contact-opportunity-payment-still-created) in the Trailblazer Community for updates.
