### ISSUE TITLE
Enhanced Recurring Donations - Setting the default picklist value for the Recurring Type field to Fixed results in users not being able to enter Number of Planned Installments when creating a new Recurring Donation

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6318]
### Background

The New and Edit buttons on Recurring Donations use a Lightning component form (RD2_EntryForm) to help simplify creating and editing Recurring Donations by users. Elements of this RD2_EntryForm render dynamically, such that editing certain fields renders different form fields

### Issue Summary

By default the Recurring Type field has a default value of Open and the RD2_EntryForm is expected a Recurring Type of Open when a new Recurring Donation is created and so it does not display the Number of Planned Installments field. As a result if an admin changes the default value of the picklist to Fixed, when a user creates a new Recurring Donation they will not be able to see the Number of Planned Installments field during record creation, a field that is crucial when creating a Fixed Recurring Donation.

Relevant code sections
https://github.com/SalesforceFoundation/NPSP/blob/master/src/lwc/rd2EntryFormScheduleSection/rd2EntryFormScheduleSection.js#L371
https://github.com/SalesforceFoundation/NPSP/blob/master/src/lwc/rd2EntryFormScheduleSection/rd2EntryFormScheduleSection.js#L306

### Workarounds

- During record creation, a user can change Recurring Type from Fixed to Open and then back again to Fixed they will be able to see and enter a value for Number of Planned Installments
- After the record has been created, a user could immediately edit the record and enter the desired value for Number of Planned Installments
- An admin can change the default value for Recurring Type back to Open and instruct users to change the value to Fixed when creating a Recurring Donation

**Comment by jamesbsfdc** [comment]
W-9047953

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlC6QAI&title=enhanced-recurring-donations-users-cannot-enter-number-of-planned-installments-when-defaulting-the-recurring-type-field-to-fixed) in the Trailblazer Community for updates.
