### ISSUE TITLE
NPSP Settings: Changing Household Naming Class May Lead to Maximum Stack Depth Reached Error

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#6328]
### Summary
When changing the **Implementing Class** for Household Naming within NPSP Settings, customers may encounter “Maximum Stack Depth Reached” errors. This happens regardless of whether they are entering their own Apex Class name or switching back to the npsp standard `HH_NameSpec `class. 

Sample Stack Trace when I switched to my own class:
```
Maximum stack depth reached: 7
Error is in expression '{!saveSettings}' in component <apex:commandButton> in page npsp:stg_panelhouseholds: Class.JL_HouseholdNaming.getExampleName: line 16, column 1
Class.npsp.HH_HouseholdNamingSettingValidator.validateFormat: line 131, column 1
Class.npsp.HH_HouseholdNamingSettingValidator.validateFormatFields: line 108, column 1
Class.npsp.HH_HouseholdNamingSettingValidator.validate: line 66, column 1
Class.npsp.STG_PanelHouseholds_CTRL.isValidHouseholdNamingSettings: line 80, column 1
Class.npsp.STG_PanelHouseholds_CTRL.isValidSettings: line 70, column 1
Class.npsp.STG_PanelHouseholds_CTRL.saveSettings: line 109, column 1
```

### Root Cause
Typically this occurs when there is an active User Trace configured to use a Debug Level where the Apex Code category level is set to “Finest.” This seems to be the default (at least for scratch orgs), but you can modify it by clicking on the Reset button on the SFDC Dev Console Debug Level itself, or manually editing that category for whatever debug level you are using. Switching to a level such as Debug will resolve the issue completely. 

For good measure, deleting any active User Trace records from Setup→ Debug Logs may also resolve the issue. 

Ultimate root cause: this may be due to a circular reference within the NPSP code that validates household naming classes. And may be related to this Salesforce Known Issue as a result: 
[https://trailblazer.salesforce.com/issues_view?id=a1p3A000001Gv4KQAS](https://trailblazer.salesforce.com/issues_view?id=a1p3A000001Gv4KQAS)

### Workarounds
* Edit the Debug Level associated with your active User Trace in Setup → Debug Logs. Change the Apex Category to “Debug” if it’s set to “Finest”.  If the issue still occurs, delete any active User Trace entries on that page.

* Alternatively, go to Setup → Custom Settings and click Manage next to Household Naming Settings. Paste the name of your Apex class in the Implementing Class field.

### Steps to Repeat
First, create an Apex Class (sample name: JL_HouseholdNaming) and replace the contents of the class with the following code. 
```
global class JL_HouseholdNaming implements npsp.HH_INaming{

    global String getHouseholdName(List<Contact> conList){
        return 'test hh name';
    }
    
    global String getHouseholdFormalGreeting(List<Contact> conList){
        return 'test formal greeting';
    }
    
    global String getHouseholdInformalGreeting(List<Contact> conList){
        return 'test informal greeting';
    }
    
    global String getExampleName(npsp__Household_Naming_Settings__c hns, String strField, List<Contact> conList){
        return 'test example name';
    }
    
    global Set<String> setHouseholdNameFieldsOnContact(){
        return new Set<String>{'FirstName', 'LastName'};
    }
    
}
```

and run these tests:

***Test 1: Enter name of class in NPSP Settings.***

1. Go to NPSP Settings → People → Households and click Edit.
2. Paste the name of your Apex class in the _Implementing Class_ field. (in this case: JL_HouseholdNaming). Click Save.
3. The value is not saved in NPSP Settings or within the Custom Setting. 

***Test 2: Reset Apex Code Category to Debug*** 

1. Close the Dev Console if it’s open.
2. Go to Setup → Debug Logs and click on the Debug Level associated with your active User Trace. Change the Apex code category to “Debug” (it’s likely set to “Finest”).
3. Go to NPSP Settings → People → Households and click Edit.
4. Paste the name of your Apex class in the Implementing Class field. (in this case: JL_HouseholdNaming). Click Save.
5. No errors are displayed. 
6. Create a new Contact (FirstName = Jess; LastName = LopezTwo)
7. Confirm that the Account’s name is “test hh name” and NOT “LopezTwo Household”. This will confirm npsp is using our custom class for household naming. 

***Test 3: Enter name of class directly in  our Custom Setting***

1. Go to NPSP Settings → People → Households and click Edit.
2. Change the Implementing Class to: HH_NameSpec and save.
3. Go to Setup → Custom Settings→ and click Manage next to Household Naming Settings. 
4. Paste the name of your Apex class in the Implementing Class field. (in this case: JL_HouseholdNaming).
5. Create a new Contact (FirstName = Jess; LastName = Lopez)
6. Confirm that the Account’s name is “test hh name” and NOT “Lopez Household”. This will confirm npsp is using our custom class for household naming.

**Comment by jesslopez-sf** [comment]
W-9057136

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlBrQAI&title=npsp-settings-changing-household-naming-class-may-lead-to-maximum-stack-depth-reached-error) in the Trailblazer Community for updates.
