### ISSUE TITLE
Unknown method 'npsp.ADDR_Cicero_Validator.initDynamicFields()'

### ISSUE THREAD

**Issue by brian-summit** [SalesforceFoundation/NPSP#6361]
When visiting this page:
/lightning/n/npsp__NPSP_Settings

The page does not load and displays this Visualforce error:
Unknown method 'npsp.ADDR_Cicero_Validator.initDynamicFields()'
Error is in expression '{!initDynamicFields}' in component <apex:page> in page npsp:stg_paneladdrverification

According to the Installed Packages, we are running these versions:
Nonprofit Success Pack - 3.195
Contacts & Organizations - 3.17
Recurring Donations - 3.21
Households - 3.14
Affiliations - 3.9
Relationships - 3.11

**Comment by jamesbsfdc** [comment]
Hi Brian

Would you mind posting about this in the Power of Us Hub or logging a support case as we don't provide support via GitHub issues. 

Thanks
