### ISSUE TITLE
Schedule Payments: Users are getting a Permissions error when clicking the Schedule Payments button on Opportunities

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6364]
### Background

Nonprofit Success Pack version 3.195 was pushed to Production orgs on 7/8 April 2021. This release included a fix for W-8855391, a bug bounty issue regarding Unauthorized user access to the "Amount" Opportunity field in the Payment Wizard.

The release notes contained the following text:

"Issues Closed
#6327: Unauthorized user can view the "Amount" field of Opportunity items on /apex/PMT_PaymentWizard"

### Issue Summary

Prior to NPSP v3.195 a user without Delete permissions for Opportunities could use the Schedule Payments (Payment Wizard). After the release a user without Delete permissions on Opportunities will receive the following error message when clicking the Schedule Payments button on Opportunities: "You don't have the necessary access to use this feature. Please check with your salesforce administrator".

The enforcement of Delete permissions on Opportunities was a regression.

### Steps to Reproduce

- Create a profile with Read, Create, Edit, Delete on Payments and Create, Read, Edit on Opportunities and assign to a test user
- Login as the test user, click on the Schedule Payments button for any Opportunity OR create an Opportunity, delete the automatic payment and then click on the Schedule Payments button for the Opportunity
- Confirm the use receives the following error: "You don't have the necessary access to use this feature. Please check with your Salesforce Administrator."

### Potential Workaround

Grant users Delete permission on Opportunities. For many customers this is not an appropriate workaround and so we will be addressing this bug with a code change

**Comment by jamesbsfdc** [comment]
W-9117196

**Comment by schlossmj** [comment]
Fix has been merged in and will be released in 230.4.

**Comment by jthall1** [comment]
I currently have some users experiencing this error even though this issue was logged as closed some time ago. The users in question only have Create, Read, and Edit on both Payment and Opportunity objects. Is Delete permission ultimately required for either Opps or Payments?

**Comment by jamesbsfdc** [comment]
Hi @jthall1  We don't provide support via GitHub issues so it is best to log a support case if you need help but answering your question Delete permissions are indeed required for the Payment object

**Comment by MojitoGreen** [comment]
Hello @jthall1 , @jamesbsfdc , in order to create scheduled payments a user needs to have at least read and create on Recurring Donations object (either via a profile or a permission set).

**Comment by jamesbsfdc** [comment]
@MojitoGreen If you are referring to the Schedule Payments button on Payments, I don't believe a user needs any CRUD access for Recurring Donations to be able to use this button. 

If you are seeing unexpected behaviour please log a support case
