### ISSUE TITLE
Gift Entry - Formula Fields do not Populate Fields as Expected in Single Gift Entry

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6368]
**Issue**
When using a formula field to indicate a field's input to change a value for a Gift Entry Batch or Single Gift Entry, the Single Gift Entry path does not import the value as expected. Instead the imported record takes the default field value (in the highlighted case of Record Types), despite the formula showing properly on the Data Import record.

<br>

**Steps to Recreate**

1. Enable Gift Entry in Org
2. Navigate to Setup > Object Manager > Payment > Record Types > and create 3 new Record Types: 
a.  Cash(default)
b.  Check
c.  Credit Card
3. Go to Setup > Object Manager > Payment > Page Layouts > Add the Record Type Field to the page layout and save
4. Go to Setup > Object Manager > NPSP Data import Object > Field and Relationship > Click "New" > Formula > Return Type "Text" > Field Name: "Payment Record Type Id" > Add the below Formula using the Record Type Id's created in step 2

```
CASE(npsp__Payment_Method__c,
     "Cash", "<record type id>",
     "Check", "<record type id>",
     "Credit Card", "<record type id>", 
     "<record type id>"
)
```

5. Goto NPSP Settings > System Tools > Advanced Mapping for Data Import & Gift Entry> Configure Advanced Mapping > Go to Payments and click "View Field Mappings" > Create New Mapping (Map "Payment Record Type Id" to RecordTypeId) and Save
6. Create 1 gift via Batch in Gift Entry, with the values below
7. Create 1 gift via Single Gift Entry, with the values below
a.  Donor Type: Contact1
b.  Existing Donor Contact: Pick any Contact
c.  Donation Date: Today
d.  Donation Amount: Any
e.  Payment Method: Check
f.  Check #: Any

8. The gift entered via Batch will be created as expected and the payment Record Type would be set to Check
9. The other gift created using the Single Gift Entry button will be created as Cash Record Type instead of Check

<br>

**Workaround**
Using another form of automation post insert from the Data Importer could be leveraged pending an update on this Issue.

**Comment by mbeaty-sf** [comment]
W-9114114

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlBmQAI&title=gift-entry-formula-fields-do-not-populate-fields-as-expected-in-single-gift-entry) in the Trailblazer Community for updates.
