### ISSUE TITLE
NPSP Lead Convert Override blocks Validation rule that Account is a Household and not an Organization

### ISSUE THREAD

**Issue by JimBTek** [SalesforceFoundation/NPSP#6372]
We have NPSP where we use Household accounts and Organizations. It causes a LOT of problems if a user is using Gmail sidebar, Calendly, Formstack etc. to insert leads or contact because they all try putting the Company in the standard AccountId field, instead of the Household.  In order to block this we put a simple validation rule on Contact, that checks:

`NOT(ISBLANK(AccountId)) &&  Account.RecordType.DeveloperName  == "Organization"`

Unfortunately this fails, and it fails if we also do: `NOT(ISBLANK(AccountId)) && Account.RecordType.DeveloperName  <> "HH_Account"`  
We have also tried other methods.   Trying to understand `LD_LeadConvertOverride_CTRL.cls` is very challenging, but it seems like the AccountID field may be temporarily set to one Record Type and then switched to the other? 

How can we prevent users from creating bad data and ensuring the AccountId field is only populated with Households? Thank you!

**Comment by jamesbsfdc** [comment]
Hi Jim 

We don't provide support via GitHub issues. If you have access to the Power of Us Hub would you mind posting about this there, or if you don't have access logging a support case? 

Thanks
