### ISSUE TITLE
Custom Household Naming and Greeting interface would benefit from being subclassed instead

### ISSUE THREAD

**Issue by dhallsim** [SalesforceFoundation/NPSP#6373]
I have a scenario where I would like to write code to override the formal and informal greeting automation, but I would like to keep the household naming logic as the default. With the interface implementation, all the methods have to be rewritten. It would be nice if we could subclass the default naming class and override only the methods we care to implement.

**Comment by jamesbsfdc** [comment]
Hi @dhallsim 

We don't provide support via GitHub issues but you are welcome to [create an Idea](https://trailblazer.salesforce.com/ideaSearch?filter=Nonprofit+%3E+Nonprofit+Success+Pack) or submit a pull request if you have suggestions for how you could make this better.
