### ISSUE TITLE
Batch Size Error when updating NPSP Settings

### ISSUE THREAD

**Issue by EvgenijSta** [SalesforceFoundation/NPSP#6381]
NPSP Settings->Recurring Donation->Opportunity Forecast Months. 

When trying to update the value, we receive the error
-------
npsp:Too many query rows: 50001
Error is in expression '{!saveSettings}' in component <apex:commandButton> in page npsp:stg_panelrd: (npsp)

An unexpected error has occurred. Your solution provider has been notified. (npsp)
---------

Apparently NPSP can't handle setting changes when there are more than 50000 records in the system. But it's absolutely necessary to have this ability. Please provide a fix.

**Comment by jamesbsfdc** [comment]
Hi there, we don't provide support via GitHub issues. 

If you have access to the Power of Us Hub please could you post about this issue here: https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack

If you don't have access to the Power of Us Hub please log a support case.
