### ISSUE TITLE
Are we able to repurpose tools here in For-Profit applications?

### ISSUE THREAD

**Issue by franciscoaponte** [SalesforceFoundation/NPSP#6387]
I work with many non profits and have used NPSP heavily. I am wondering if we are allowed to repurpose certain tools for small or large for-profit companies?

**Comment by coriobriensfdo** [comment]
Hi @franciscoaponte we don't provide support here in GitHub, so I'd recommend emailing sfdo-opensource@salesforce.com to connect. When you reach out, can you please clarify your question and give some scenarios where you would look at repurposing the tools?
