### ISSUE TITLE
NPSP Settings tab always resets the load order of NPSP TDTM handlers

### ISSUE THREAD

**Issue by davidchengIC** [SalesforceFoundation/NPSP#6421]
We have written a custom TDTM account handler that must run first, before all NPSP handlers including the HH_Households_TDTM. We've changed the load order of all the NPSP handlers and everything works fine. However, whenever someone opens the NPSP Settings tab, it resets the load order to default for all the NPSP handlers, which we don't want.

Is there any way to prevent this from happening?  It defeats the purpose of TDTM if we can't keep our own load order.

Steps to reproduce:

Increase the Load Order value of each NPSP Account TDTM handler by 1, e.g. 3 becomes 4, 2 becomes 3, etc.

Insert a custom TDTM handler with Load Order 0.

Go to NPSP Settings tab, then go back to the Trigger Handlers list.  The NPSP TDTM load order has reverted to default.

**Comment by jamesbsfdc** [comment]
Hi @davidchengIC Best to post stuff like this on the Hub (which I see you already have ;)) or log a case as we don't provide support via GitHub issues

Thanks
