### ISSUE TITLE
Gift Entry - Setting Defaults on Template does not Preserve Values

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6428]
**Issue** -- _Updated June 6, 2021_
This is when these fields are specifically added, this is not involving the GAU Bundle. 

When the fields GAU Allocation 1: General Accounting Unit and GAU Allocation 2: General Accounting Unit are added to a Template and defaulted to 2 different General Accounting Units, upon starting a batch, the values in these two fields default to the value in the second field (GAU Allocation 2: General Accounting Unit). 

_Update June 6, 2021_ - This issue is also present if there are a series of lookups that point to the same target. i.e. if a User creates 3 Contact Role Object Groups to allow the input of up to 3 different Opportunity Contact Roles, the template is taking the last defaulted value in the **order they are displayed on the template**, and cascading those last defaulted values to the other fields that have the same target field in Advanced Mapping.

The Steps to Reproduce below will replicate this behaviour, but can also be recreated by creating 2 or more custom lookups in separate Object Groupings, pointing to the same target field.

<br>
<br>

**Steps to Reproduce**
1. Create 2 GAUs:
a. Test GAU 1
b. Test GAU 2
2. Enable Gift Entry in Org
3. Create a new Template from the Gift Entry Tab > Templates Sub-Tab
4. Anywhere on the template, add:
a. Advanced Form Fields > GAU Allocation 1 > General Accounting Unit
b. Advanced Form Fields > GAU Allocation 2 > General Accounting Unit
5. Create a batch using the template that you just edited, and at the "Set Default Values" Header in the Batch creation, ensure that you input:
a. GAU Allocation 1: General Accounting Unit: **Test GAU 1**
b. GAU Allocation 2: General Accounting Unit: **Test GAU 2**
6. Click "Save"
7. Notice that the values of the lookups that you defined in the "Set Default Values" section do not reflect the expected values in the batch:
a. GAU Allocation 1: General Accounting Unit: **Test GAU 2**
b. GAU Allocation 2: General Accounting Unit: Test GAU 2

When the expected values were meant to be:
a. GAU Allocation 1: General Accounting Unit: Test GAU 1
b. GAU Allocation 2: General Accounting Unit: Test GAU 2

<br>
<br>

**Cause**
The code that is attempting to pull in the default values designated in the Template is cycling through the loop of values to target fields in the geFormRenderer.js method perpareFormForBatchMode:
https://github.com/SalesforceFoundation/NPSP/blob/aad20ffb747ecda9a037c4bce9cd19617b6a727b/src/lwc/geFormRenderer/geFormRenderer.js#L1148-L1176

As the code is cycling through these values, when it gets to the _last_ value (defined by physically the last field on the template physically) with the same target field, it uses this as the value to populate on the template as the default as it is not expecting multiple field defaults to have the same target. i.e. if Fields are added to a template and appear in a top down orientation:

1. Custom Field 1
2. Custom Field 2
3. Custom Field 3

*The value in the fields defaulted on Custom Field 3 will be the value that is populated for the defaults in Custom Field 2 and Custom Field 1, as Custom Field 3 _physically_ appears last in order on the template.

While the values can differ when manually entered on the batch itself, attempting to set them as a default is what is causing the reverse-cascade (the last default value per target field) of the default values to all the fields with the same target.

We can see here when inspecting the LWC that the Amount field passes through without issue, there is only one reference to the target field Amount (1), on the Opportunity. However for the Allocation field (2), includes 3 different, separate, Object Groups that map to the Allocation Object in an attempt to create 3 separate GAU Allocations, and in the values being passed, we can only see the last value entered is populated.

What was attempted to be defaulted
![image](https://user-images.githubusercontent.com/53280203/121099418-a61aab00-c7ac-11eb-9ef3-980c05fd14a2.png)

What was passed through to the Batch upon saving default values
![image](https://user-images.githubusercontent.com/53280203/121099485-c5b1d380-c7ac-11eb-96a5-00dc276f06e1.png)

![image](https://user-images.githubusercontent.com/53280203/121099448-b5015d80-c7ac-11eb-95df-1bf682674473.png)

<br>
<br>

**Note**

- This behaviour is mirrored when there is a custom field on GAU 
- This behaviour occurs when there is a value populated in the field on the **GAU Allocation 2: General Accounting Unit** Object group i.e. if a value is in the GAU1 field (or custom field on the GAU1 object group), and nothing in the GAU 2 field when setting default values on the template, they will both be blank. If a value is in the GAU2 field (or custom field on the GAU2 object group) then it will be copied to the GAU1 field.
- _Update June 7, 2021_ The above notes confirm that it is the values from the field that receives defaults that is physically _last_ on the template, as they are assessed in order, from top to bottom, of physical location.

**Comment by mbeaty-sf** [comment]
W-9296122

**Comment by mbeaty-sf** [comment]
Issue updated June 7, 2021 with additional information and scope.

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlBcQAI&title=gift-entry-setting-defaults-on-template-does-not-preserve-values) in the Trailblazer Community for updates.
