### ISSUE TITLE
Prevent new Opportunity creation on specific recurring donation

### ISSUE THREAD

**Issue by pcave** [SalesforceFoundation/NPSP#6451]
This is more of a question than issue. Would it be possible to programmatically (via trigger or other) prevent the new open opportunity from being created on specific recurring donations. I know there is the global "Disable All Installments" setting, but we'd need to prevent the creation on specific recurring donations that are created via our integration.

Thanks!

**Comment by judisohn** [comment]
Hi @pcave We don't provide support or troubleshooting on Github Issues. Please ask in the [Power of Us Hub](http://powerofus.force.com) or [open a support case](https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case). Thanks!
