### ISSUE TITLE
"Prevent Address Override" doesn't work as advertised (at least for Cicero)

### ISSUE THREAD

**Issue by mscholtz** [SalesforceFoundation/NPSP#6470]
In the NPSP settings UI, the "Prevent Address Override" option for address verification for Cicero says this:
"Prevents the Cicero API from overwriting Addresses during verification. If an Address field is blank, Cicero updates it."

However, this doesn't seem to be what actually happens.  

Actual behavior we observe when testing:
* doesn't matter if the field starts out blank.  if the box is checked it won't update anything in the address ever
* except Country.  That's always updated regardless of whether the box is checked or not 

It would be great if it did work as described in the settings.  Cicero in particular is not always consistent with how it formats addresses.  (It can return "CA" or "California" at different times.)  So for orgs that are particular about address formatting, it would be great to tell Cicero not to overwrite what they have while still allowing it to update missing info.

I believe the relevant code is here: https://github.com/SalesforceFoundation/NPSP/blob/aad20ffb747ecda9a037c4bce9cd19617b6a727b/src/classes/ADDR_Cicero_Validator.cls#L198

And that would explain the behavior.  The block starting on line 198 does not check if the fields are empty to start with, it only checks if the Prevent Override box is checked.  And the update to Country is outside of the if block.  

@coriobriensfdo FYI

**Comment by jamesbsfdc** [comment]
Hi @mscholtz 

Please could you log a support case for this? If you use the following link when logged into an org it should pre-populate the correct categories so the case is assigned to the Salesforce.org case queue. 
https://help.salesforce.com/supportandservices?id=createCase&topic=Salesforceorg_Products_TOPIC&category=Nonprofit_Success_Pack_(NPSP)&question=I_have_an_error_with_Nonprofit_Success_Pack_NPSP

Thanks
