### ISSUE TITLE
NPSP Data Importer Dry Run Not Performing Contact Insensitive Unique ID Matching

### ISSUE THREAD

**Issue by hayeswise** [SalesforceFoundation/NPSP#6472]
The NPSP Data Importer Dry Run does not detect a match when using a Contact Custom Unique ID under these conditions:
1. The Contact's unique ID field and corresponding NPSP Data Import fields are configured per the NPSP documentation at [Connect Objects and Fields with Advanced Mapping](https://powerofus.force.com/s/article/NPSP-Map-Using-Advanced-Mapping) - specifically, the Contact's unique id is not case sensitive
2. A NPSP Data Import's corresponding field value has a letter with a different case than a Contact's unique ID value where the values are a case _insensitive_ match but not a case _sensitive_ match.

For example, if my Contact's "Unique ID" is "ABC,123", I would expect a match where a NPSP Data Import's "Contact1 Unique ID" is "Abc,123". 

My imported data does not include "Contact2 Unique ID" values; however, I have configured the NPSP advance mapping and the NPSP Data Import object to handle it.

I would prefer that the NPSP Data Importer to perform the case insensitive comparisons if the unique ID is configured that way.  If that cannot be done, update the documentation to reflect the actual behavior.

**Comment by jamesbsfdc** [comment]
Hi Brian, thanks for reporting this but please could you log a support case for this as we don't provide support via GitHub issues and someone will need to validate this? If you use the following link when logged into the org it should pre-populate the correct categories so the case is assigned to the Salesforce.org case queue. 
https://help.salesforce.com/supportandservices?id=createCase&topic=Salesforceorg_Products_TOPIC&category=Nonprofit_Success_Pack_(NPSP)&question=I_have_an_error_with_Nonprofit_Success_Pack_NPSP

**Comment by hayeswise** [comment]
Yes.  Sorry for reposting - I thought I had made a mistake and forgot to submit.
