### ISSUE TITLE
Error thrown if saving template without clicking Form Fields tab

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6482]
In the Gift Entry template builder, if you open an existing template, then click 'Save & Close' without clicking the 'Form Fields' tab, an Error modal appears that reads 'Please review the following: Form Fields'. This occurs even if all requirements for saving the template are already met (Template is named, required form fields added to the template, batch table populated).

![image](https://user-images.githubusercontent.com/55844773/121549335-c54b4f80-c9db-11eb-9e31-add0db242ab3.png)

This also occurs if you create a new template. If you fill in the template 'Name' field on the Template Info tab (which is the only required field not pre-populated by default), then click Save & Close, the error appears.

I noticed this issue occurring in scratch orgs created in the NPSP repository only (prerelease org shape, qa_org_2gp flow). If I created a scratch org using the same org shape and flow from the Elevate-NPSP-Connector org, this issue does not occur. There's a chance this could be related to the test CustomObject1-3 objects that are automatically created when creating a scratch org in the NPSP repository.

**Workaround**: When editing a template, click the 'Form Fields' tab, and the error will not be thrown on save.

**Steps to Reproduce (Existing Template)**

1. Navigate to the Gift Entry app.
2. Click the 'Templates' tab.
3. Create, or open, an existing template that has all required conditions met (Template is named, required form fields added to the template, batch table populated (Template is named, required form fields added to the template, batch table populated with at least one column). Do not make any changes.
4. Click 'Save & Close'.
5. Error will be thrown.

**Steps to Reproduce (New Template)**

1. Navigate to the Gift Entry app.
2. Click the 'Templates' tab.
3. Click 'Create Template'.
4. In the Template Info tab, fill in the Template Name field.
5. Click 'Save & Close' without viewing other tabs.
6. Error will be thrown.

**Comment by schlossmj** [comment]
W-9425273

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlBYQAY&title=gift-entry-error-thrown-if-saving-template-without-clicking-form-fields-tab) in the Trailblazer Community for updates.
