### ISSUE TITLE
Batch number formats cannot be deactivated or activated from table

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6512]
On the NPSP settings page, if attempting to deactivate or activate an existing batch number format from the Batch Number Formats table, the following error message is thrown:

`Cannot save auto-number format. Please review the errors and try again. undefined`

![image](https://user-images.githubusercontent.com/55844773/123442329-c87d3880-d5a2-11eb-8acf-0ffa810aeb86.png)

This issue does not occur when creating a new batch number format. If you create a new inactive format, or use the 'Save & Activate' button, this does not occur, and the format is successfully activated and applied. This is not occurring in orgs running SFDO 230.

**Expected**: No error should be thrown when performing this action.

**Actual**: Error is thrown when attempting to deactivate the batch number.

**Steps to Recreate:**

1. Create a scratch org running 232.
2. Navigate to NPSP Settings > Advanced Mapping for Data Import & Gift Entry
3. In the Batch Numbers section, enter a number format into the Display Format field (acb-{000}), and click 'Save & Activate'.
4. Number format is activated.
5. Click the arrow menu next to the number format in the Batch Numbers table, and then click 'Deactivate'.
6. Error is thrown in section.
7. Conversely, create an inactive batch number format (Click 'Save').
8. From the batch numbers table, click 'Activate'.
9. Same error is thrown.

GUS work item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000N0o0YAC/view

**Comment by schlossmj** [comment]
W-9329987

**Comment by mbeaty-sf** [comment]
This fix was released in [NPSP 3.201](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.201)
