### ISSUE TITLE
Invalid Elevate field values escape error handling in GE form

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6513]
When using the Gift Entry app, when entering information into the Elevate widget, if a user fills out the Gift Entry form with valid values, but enters an invalid value into one of the Elevate widget form fields (I was able to recreate with the CVC and expiry date fields), then attempts to save/authorize the gift, a timeout error occurs in the form instead of the form submission being outright blocked due to the invalid form value. I have noticed this occurring for the following fields:

1. CVC
2. Expiration Date
![image](https://user-images.githubusercontent.com/55844773/123443444-e7c89580-d5a3-11eb-8c19-6660ab1bf023.png)

**Steps to Reproduce:**

1. Navigate to the Gift Entry app
2. Click 'Templates' and create or edit a template.
3. In the template builder, add the Elevate widget to the template and save it
4. Click 'New Single Gift'.
5. Fill out the entire Gift Entry form with valid values.
6. In the CVC field, enter only two numbers. Inline validation error should display
7. Click 'Save'.
8. Form processes and results in a timeout.

GUS WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000NaM1YAK/view

**Comment by schlossmj** [comment]
W-9359512

**Comment by judisohn** [comment]
Trailblazer Community Known Issue [here](https://trailblazer.salesforce.com/issues_view?title=sfdo-elevate-invalid-field-values-escape-error-handling-in-gift-entry-form&Id=a1p4V000001U52F).

**Comment by mbeaty-sf** [comment]
This fix was released in [NPSP 3.201](https://github.com/SalesforceFoundation/NPSP/issues/6514#:~:text=This%20fix%20was%20released%20in%20NPSP%203.201)
