### ISSUE TITLE
Elevate CC fields don't render after submitting batch gift

### ISSUE THREAD

**Issue by schlossmj** [SalesforceFoundation/NPSP#6514]
If 'Credit Card' is set as the default payment method value for a template, this causes the Elevate credit card input fields to not render after submitting a credit-card-paid gift. This also occurs if a validation rule is in place.

![image](https://user-images.githubusercontent.com/55844773/123444615-1430e180-d5a5-11eb-8348-45444f121fd5.png)

**Steps to Recreate:**

1. Create/edit a template
2. Add Elevate widget to the template
3. Set default value for Payment Method picklist field to 'Credit Card'.
4. Create a new batch using the template
5. When the BGE form loads, create a new gift with Credit Card as the payment method, input test card details, and save the gift.
6. Gift is saved, but when the form clears/reloads, the credit card input fields in the Elevate widget are not rendered.

**Workaround**: Change payment method to a different value, then back to credit card to render the input fields.

GUS WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000AyYoYAK/view

**Comment by schlossmj** [comment]
W-9142643

**Comment by judisohn** [comment]
Trailblazer Community Known Issue for Elevate [here](https://trailblazer.salesforce.com/issues_view?title=sfdo-elevate-credit-card-fields-don-t-render-after-submitting-batch-gift&Id=a1p4V000001U52Z).

**Comment by mbeaty-sf** [comment]
This fix was released in [NPSP 3.201](https://github.com/SalesforceFoundation/NPSP/releases/tag/rel%2F3.201)
