### ISSUE TITLE
Household v3.15 Exclude naming functionality

### ISSUE THREAD

**Issue by mrainboldt** [SalesforceFoundation/NPSP#6525]
Household version 3.15 is not respecting excluding from formal and informal naming fields.  Works fine in v3.14

**Comment by jamesbsfdc** [comment]
Hi @mrainboldt  Would you mind posting about this on the Hub in the NPSP group (https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) or logging a support case (https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case) as we do not provide support via GitHub issues
