### ISSUE TITLE
As a user, I can specify how Last Membership Date is calculated, so I can customize the system to my needs.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#654]
Nonprofit Starter Pack — Melanie Robey (Greater Baltimore Cultural Alliance)

Anyone know if there's a way to update the formula so that "Last Membership Date" pulls from the most recent "Membership Start Date" and not the "Close Date"? This becomes an issue for us when a member is invoiced for a membership (pledged), but does not pay until after their membership start date. The posted close date (date of the check or online payment) is not reflective of the actual membership start date. Thanks! #NPSP

Kevin's response: Maybe a settings toggle to use one or the other? We can't just change it outright for anybody already depending on the currently logic, but it shouldn't be too hard to make available as an option in the membership settings area.

**Comment by kbromer** [comment]
**lurch: attach W-007270

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYGAAY" target="_blank">W-007270</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.

Customizable Rollups allow Users to customize the calculation based on Membership records - https://powerofus.force.com/s/article/NPSP-Cust-Rollups-Overview
