### ISSUE TITLE
When using the Manage Household button, users in certain locales will receive a "value outside of valid range on numeric field" error when Data Integration rules are active

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6542]
### Background

Customers can enable Data Integration Rules in their org. See the documentation here:
https://help.salesforce.com/articleView?id=data_dot_com_clean_admin_set_up_clean_rules.htm&type=0
https://help.salesforce.com/articleView?id=sf.ddc_data_integration_rule_activating.htm&type=5

These rules allow geolocation data to be automatically added to Contact and Account records upon creation or update. This data is stored in the following fields on with the Contacts/Accounts Address Compound fields:

- Latitude (e.g MailingLatitude on Contact and BillingLatitude on Contact)
- Longitude (e.g MailingLongitude on Contact and BillingLongitude on Contact)
- Accuracy (e.g MailingGeocodeAccuracy on Contact and BillingGeocodeAccuracy on Account)

### Issue Summary

Under certain conditions, a user trying to edit an account via the Manage Household button may receive an error similar to the following:

_Update failed. First exception on row 0 with id 0032F00000imzrZQAQ; first error: NUMBER_OUTSIDE_VALID_RANGE, Billing Latitude: value outside of valid range on numeric field:XXXXXXXX [BillingLatitude]_

The user will receive this error if the following two conditions are true:
- The user editing the record via the Manage Household button has a User Locale that uses a decimal comma as the decimal separator in number fields (as opposed to locale's that use a decimal point)
- The Latitude/Longitude fields of the Account, or Contacts at the Account, contain values

For 1, a Contact or Account will have a values in the Geolocation fields if the following rules Data Integration Rules are or have been active in the org, and the Contact or Account has an address
- Geocodes for Contact Mailing Address
- Geocodes for Account Billing Address

### Steps to Replicate

1. Activate the following Data Integration Rules: Geocodes for Contact Mailing Address Geocodes for Account Billing Address
2. Create a contact, ensuring you specify a complete address in the Mailing Address fields
3. You can confirm the Latitude/Longitude fields now have geolocation values via the API or via a custom report type (as the fields are not visible in standard report types)
4. Change the Locale on your User record to one that uses a decimal comma as the decimal separator in number fields e.g French (France)
5. Navigate to the Household Account of the Contact created in Step 2 and click Manage Household
6. Click the Save button, with or without making a change on the page

### Potential Workarounds

- Do not use the Manage Household button to edit household data
- Change your user locale to one that uses a decimal point as the decimal separator rather than a decimal comma (see Locales help doc: https://help.salesforce.com/articleView?id=sf.admin_supported_locales.htm&type=5)
- Create two text fields on Contact for Longitude and Latitude, and the same on Account. In the Data Integration rules for Billing and Mailing Addresses, change the mappings to populate these custom fields rather than the standard fields upon update
- Disable and do not use Data Integration Rules for Billing and Mailing Addresses

**Comment by judisohn** [comment]
[W-9595949](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000R5IuYAK/view)

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlBXQAY&title=users-receive-a-value-outside-of-valid-range-on-numeric-field-error-when-using-the-manage-household-button-and-data-integration-rules-are-active) in the Trailblazer Community for updates.
