### ISSUE TITLE
New pledged opportunity is not creating when click on refresh opportunity button on Recurring Donation.

### ISSUE THREAD

**Issue by saritarajendralad** [SalesforceFoundation/NPSP#6574]
I am facing this issue in production environment. Even though previous opportunity closed, system failing to create new pledged/open opportunity
This is happening only with certain records.
Any help would be appreciated.

**Comment by jesslopez-sf** [comment]
Hi @saritarajendralad  - Would you mind posting about this on the Hub in the NPSP group (https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) or logging a support case (https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case) as we do not provide support via GitHub issues? Thank you!
