### ISSUE TITLE
Gift Entry - Opportunity: Campaign ID is not available to be selected in Form Fields

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6576]
**Issue**
When editing a Gift Entry template, by default the Opportunity: Campaign ID is included on a newly created Default Gift Entry Template; however, if the field is removed from the template, it is not available as a field to be added or removed from the Form Fields section.

**Workaround**
- Create the template again from scratch and regenerate as the default if it is the default template that is affected.

**Comment by mbeaty-sf** [comment]
W-9664152

**Comment by tjg1019** [comment]
I have also found this in my orgs.

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlBSQAY&title=gift-entry-opportunity-campaign-id-is-not-available-to-be-selected-in-form-fields) in the Trailblazer Community for updates.
