### ISSUE TITLE
As a user, I would like to get feedback only for the batch processes of the page I'm looking at

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#659]
Currently the batch process updater looks at all batch processes running. We could make it smarted to update the progress bar according only to the ones on the page.

**Comment by kbromer** [comment]
**lurch: attach W-007376

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZzAAI" target="_blank">W-007376</a>
