### ISSUE TITLE
Gift Entry - Templates that include Account1 Website throws error when entered without protocol (http://, ftp://, etc.)

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6608]
**Issue**
When a template includes the website field for Account1, and the field is populated with an address such as: www.salesforce.com instead of http://www.salesforce.com, and error is thrown: "You have entered an invalid format." However, when edited on the Account's page, the website field allows for input of web addresses without the preceding protocol. This also means that if you create an Account with a web address (ex. www.salesforce.com), and then you have the website field on your Gift Entry template and you pull up an existing account with that website field populated, when you attempt to save a gift, this error will be thrown.

**Steps to Reproduce**
1. Create an organization account with Account Website field filled in(for.ex: www.test.com)
2. Enable Advanced Mapping and Gift Entry from NPSP Settings
3. From App Launcher goto Gift Entry
4. Click on New Template and give it a name and add Website field under Account1 to the form fields
5. Click on New Batch and use the above created template
6. Give it a name, Next & Save
7. Now Choose Donation Donor as Account1
8. For Existing Donor Organization Account pick the one you have created above
9. At the bottom you'll notice website is auto filled in and now try saving it.
a.  Actual Results: Error: "You have entered an invalid format"
b.  Expected Results: Gift is entered using the same website address that is used on the account record

**Workaround**
1. Remove the website field from your Gift Entry Template
2. You can enter all web addresses with http:// and ensure that there is validation on the field to maintain that structure to avoid this error if they are pull up in a Gift Entry batch.

**Comment by mbeaty-sf** [comment]
W-9749117

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pYrrQAE&title=gift-entry-templates-that-include-account1-website-throws-error-when-entered-without-protocol-http-ftp-etc) in the Trailblazer Community for updates.
