### ISSUE TITLE
Unlocked package verision create Validation of NPSP dependency failed

### ISSUE THREAD

**Issue by iandrosov** [SalesforceFoundation/NPSP#6614]
While creating unlocked package version that has NPSP list of dependencies and record types get error
sfdx force:package:version:create --package "PKGName"  --tag 'Release 1.0.0' --installationkeybypass -v lwchub -w 10
Only way to make package with skip validation that make package not useful to install.
DevHub ensured has the NPSP record types installed. Even try to use another devhub that has entire NPSP set up and my app as well but that fail with similar errors. How to work around this in sfdx?

Request in progress. Sleeping 30 seconds. Will wait a total of 90 more seconds before timing out. Current Status='Verifying dependencies'
ERROR running force:package:version:create:  Multiple errors occurred:
(1) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.BDE_Entry_FS) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.BDE_Entry_FS: In field: RecordTypeId - no CustomField named Account.RecordTypeId found
(2) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.BDE_List_FS) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.BDE_List_FS: In field: RecordTypeId - no CustomField named Account.RecordTypeId found
(3) An error occurred while trying to install a package dependency, ID 04t1Y000001I8yU: (Account.Manage_Household_Custom) In field: RecordTypeId - no CustomField named Account.RecordTypeId found, Details: Account.Manage_Household_Custom: In field: RecordTypeId - no CustomField named Account.RecordTypeId found

**Comment by judisohn** [comment]
Hi @iandrosov We do not provide support through Github. 

I'd recommend the [Salesforce DX group](https://trailhead.salesforce.com/trailblazer-community/groups/0F93A000000HTp1SAG?tab=discussion) in the Trailblazer Community. I don't think this problem is specific to NPSP.
