### ISSUE TITLE
Error with NPSP Data Import

### ISSUE THREAD

**Issue by lsilman-tlycs** [SalesforceFoundation/NPSP#6616]
Using NPSP Data Imports now throws an error "Invalid field name 'utm_campaign__c', first observed in latest release 3.205

**Comment by mbeaty-sf** [comment]
Hi @lsilman-tlycs,

We don't provide support via GitHub Issues. Please post on the Power of Us Hub (https://powerofus.force.com/), here is the NPSP Group (https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) Alternatively, please log a Case(https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case).

Thank you
