### ISSUE TITLE
Creating Customizable Rollups with non-Romanized Characters Randomly Results in Failure

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6637]
**Issue**
If a User's language is in a non-Romanized alphabet language, such as Japanese (日本語), when creating a new Customizable Rollup the creation fails, seemingly randomly.

**Cause**
When creating a rollup, the API name generation method is not able to properly parse the Japanese field name as expected, resulting in only the secondary part of the name which is generate via: https://github.com/SalesforceFoundation/NPSP/blob/5363fa8f8ae3ef46a5f305c49e7af4e492a4f0cf/force-app/main/default/classes/CRLP_RollupCMT.cls#L633

Normally, the randomly generated second part of the API name would be sufficient in cases where the code could not properly truncate the first page of the name; however, in this case, when the Object name cannot be truncated and appended, it leaves only the hex generated name which has a 9:7 odds of choosing a number as the first character, which is not allowed when creating API names.

For example: Creating a Rollup on a Contact would typically take the Object: **Contact** and truncate it to **Con** and append that to a hex generated 8 digits, looking something like **Con8b31e6ba** but when the Object cannot be parsed because it is in non-Romanized characters, it would just be created as **8b31e6ba** which would throw an error because it starts with a number.

Through the use of debug statements, we can see the code working properly, despite the Field itself having a Japanese label, the User's language is English, meaning the Object name is properly identified and truncated:

_User Language: English_
![image](https://user-images.githubusercontent.com/53280203/131011990-9e42f250-5613-40d2-b0ac-b8b586d6e5b1.png)

1. [Object is captured from the previous line, and the ':' is replaced with an underscore](https://github.com/SalesforceFoundation/NPSP/blob/5363fa8f8ae3ef46a5f305c49e7af4e492a4f0cf/force-app/main/default/classes/CRLP_RollupCMT.cls#L628)
2. [Underscore is replaced with _blank_](https://github.com/SalesforceFoundation/NPSP/blob/5363fa8f8ae3ef46a5f305c49e7af4e492a4f0cf/force-app/main/default/classes/CRLP_RollupCMT.cls#L628)
3. [Object Name is truncated](https://github.com/SalesforceFoundation/NPSP/blob/5363fa8f8ae3ef46a5f305c49e7af4e492a4f0cf/force-app/main/default/classes/CRLP_RollupCMT.cls#L635)
4. [Truncated Object name identified to joining to full API name](https://github.com/SalesforceFoundation/NPSP/blob/5363fa8f8ae3ef46a5f305c49e7af4e492a4f0cf/force-app/main/default/classes/CRLP_RollupCMT.cls#L635)
5. [Truncated Object Name and hex-generated random 8 characters are combined to create API name](https://github.com/SalesforceFoundation/NPSP/blob/5363fa8f8ae3ef46a5f305c49e7af4e492a4f0cf/force-app/main/default/classes/CRLP_RollupCMT.cls#L635)

_User Language: Japanese_
![image](https://user-images.githubusercontent.com/53280203/131015884-45ada909-94b1-4b29-9859-fe1f15d78c0d.png)

In the Japanese version we can see that in 1 through 3, the Object 取引先責任者 (Contact) is not recognized, and we see the transformation attempt that happened in the English version, but it results in a blank value being generated, shown in step 4. Then in the final combination, because the Object name was not properly identified and truncated, there is no value to be appended to the randomly generated hex value, leaving it as the only value to be used to generate a name. In the case of the screenshot, this value was not accepted and resulted in an error that would not allow the saving of the rollup: 
![image](https://user-images.githubusercontent.com/53280203/131017127-50da37ac-e764-4e0f-b4f7-72a750662ff9.png)

This is why in certain cases saving a Rollup in a non-Romanized alphabet language will work, and other times not, seemingly without a pattern.

**Steps to Replicate**
1. Create a target field for a customizable rollup, such as a Number field (18,0)
2. Switch your User record's language to be a non-Romanized (Japanese, Russian, Thai, etc.)
3. Navigate to NPSP Settings > Donations > Customizable Rollups
4. Create a Rollup with the target field you created in step 1
5. Fill out all necessary values to create the rollup
6. Click Save
7. **Note:** This is where is left up to chance, as the name that is generated could be chosen to start with a number, or a letter. If the Rollup saves correctly, delete it and try the steps again until you receive the error as merely hitting "Save" again will not generate a new name, it will attempt to save the same API name again. If you want to see the API Name Generated for your Rollup (as a failed one will still save in Custom Metadata Types, but will be marked as isDeleted: true) Navigate to Setup > Custom Code > Custom Metadata Types > Rollups > Click "Manage" and find the Rollup with the field name you had selected as your target. Note the API name starts with a number.

**Workaround**
Attempting to recreate the rollup again will attempt to randomly generate the 8 characters at the end of the Custom Metadata Type API Name, so trying to create the Rollup again after the failure will give another change to receive a name without it starting with a number. This will need to be the method until there is a fix put in the code.

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pYr3QAE&title=creating-customizable-rollups-with-non-romanized-characters-randomly-results-in-failure) in the Trailblazer Community for updates.
