### ISSUE TITLE
Validation Rule Firing when using Gift Entry when Criteria Not Fulfilled for Rule to Fire

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6641]
**Issue**

When entering a new Gift into Gift Entry a validation rule is being trigger on the Payment Object that should not be. The validation rule is meant to check if the Paid checkbox is TRUE, then the Payment Method should be filled in as well. However, despite both values being filled in, the Validation Rule error still fires and is displayed on Failure information on the Gift Entry entry, and the DI record (which is still created with the values properly saving, but with failure information).

Steps to Reproduce

1. Create a scratch org and enable Gift Entry and assign Permissions to your User
2. Create a validation rule with the following criteria:
3. npe01__Paid__c = TRUE && ISBLANK(TEXT(npe01__Payment_Method__c))
4. Go to gift entry and select "New Single Gift"
5. Fill in the following fields:
a. Donation Type: Contact1
b. Payment Paid: True
c. Contact first and last name: Any value
d. Donation Date: Any value
e. Donation Amount: Any value
f. Payment Method: Any value
6. Select save and notice the error: "A validation rule is preventing the record from saving: You must select a Payment Method before marking as Paid."

**Actual result**: Validation rule error is thrown.
**Expected result**: No validation rule error is thrown.

**Workaround**
Entering the Values, or updating them directly on the DI record will allow you to process and dave them if the failure information is cleared out.

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pYqfQAE&title=validation-rule-firing-when-using-gift-entry-when-criteria-not-fulfilled-for-rule-to-fire) in the Trailblazer Community for updates.
