### ISSUE TITLE
Getting unexpected error, while creating a new payment record

### ISSUE THREAD

**Issue by preeti-lightful** [SalesforceFoundation/NPSP#6645]
Getting error, while creating a new payment record with a new opportunity record as a system admin.
Any idea here ? I  tried creating a new record but was unable to save that, I created a new opp record but now I am unable to edit that as well, it shows the same error?

![NPSP_payment issue](https://user-images.githubusercontent.com/32099339/131675391-82228a58-445f-4ccc-bd02-97dd351030c0.png)
We are suspecting issues are coming after the winter 22 salesforce release to sandboxes.

**Comment by judisohn** [comment]
Please open a case as we don't provide any customer/partner support in GitHub. Thank you!
