### ISSUE TITLE
Number of Household Members Field Is Not Recalculating When Last Contact is Deleted From Account

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#6646]
### Summary
If a customer deletes the last Contact from an Account (either in the UI and selecting the “Delete Contact and Leave Account Empty” option) or via Apex/API, the Number of Household Members is not being reset to 0. (The Account Name is also not being reset to Anonymous Household).

There are no Unit Tests that assert that Number of Household Members is 0 when there are 0 Contacts under an Account. I replicated this in both the latest version of NPSP (3.206) as well as a release 20 releases back (3.186), so this is not a recent regression. 

### Root Cause
We are not calling the HouseholdNamingService in AfterDelete context. We call processAccountsAfterDelete() in [ACCT_IndividualAccounts_TDTM](https://github.com/SalesforceFoundation/NPSP/blob/main/force-app/main/default/classes/ACCT_IndividualAccounts_TDTM.cls#L321-L345) (AfterDelete)

* this.Contacts is null since newlist is null
* oldContactById is populated
* deleted Contact gets passed to processAccountsAfterDelete()
* Query for Contacts under that Account (0 found)
* needsAccountUpdate boolean = (if the contact list under that Account is not empty or the Account has Opportunities) && it’s a Household Account, set needsAccountUpdate to true. In our case, it’s false.
    `07:23:05.797 (3640867949)|VARIABLE_ASSIGNMENT|[336]|needsAccountUpdate|false`
    Because it’s false, we don’t add it to the householdIdsToUpdate List and when we call updateHouseholds(), there’s nothing in that list.

If you delete a Contact from the Manage Household page (when it’s the only Contact in the Household Account) and click Save, the Account is renamed to Anonymous Household and the Number of Household Members _is_ correctly set to 0 due to code in HH_ContainerHelper.js.

### Steps to Repeat
1. Create a Contact (First Name = Single; Last Name = Contact)
2. Delete that Contact. When given the option to also delete the Household Account as well, choose the option to “Delete Contact and Leave Empty Account”. This is essentially the same as a customer deleting one or more Contacts via Apex or API.
3. Confirm Contact is deleted and that the Account is still called “Contact Household”. It also still shows Number of Household Members (npsp__Number_of_Household_Members__c) as 1 instead of 0.

**Comment by jesslopez-sf** [comment]
W-9832597

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pYqeQAE&title=number-of-household-members-field-is-not-recalculating-when-last-contact-is-deleted-from-account) in the Trailblazer Community for updates.

**Comment by schieco** [comment]
So it definitely happens all the time that people are not using a manage household page for this - sometimes it's done via flow (moving/removing people in households), sometimes via code... so I am not clear why this is closed. Simply saying "use a custom page for this" is not a viable solution.

**Comment by jamesbsfdc** [comment]
Hi @schieco The GitHub issue was closed because we have migrated open NPSP Issues to the Salesforce Known Issues site and closed their respective issue on GitHub. See the post above from Jess for the link to the known issue. 

You can select This Issue Affects Me to receive updates above the issue. This also allows us to better track the impact from known issues
