### ISSUE TITLE
Gift Entry - GAU Allocation Bundle Allows Users to Bypass Amount or Percent Values and Creates Records Erroneously

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6652]
**Issue**
If a User is using the GAU Allocation bundle, and they do not fill in the Amount or Percentage fields, a warning pops up on attempting to save the gift:

![image](https://user-images.githubusercontent.com/53280203/132914154-12d05aa8-4b52-45ec-8955-2ae00c1ad855.png)

But clicking "Save & Enter New Gift" will allow the User to continue and save the gift regardless. When processing the batch, while the error that is shown below is displayed on the DI records, and in the Batch on those records, the Opportunity and Payment records are still created, Opportunity GAU Allocations are created (with blank amount and percent values), but Payment Allocations (from Accounting Subledger settings) are not created. On each record, the error is displayed:

_Error occurred while processing the Opportunity record associated with Allocation <record ID> (ALL-16). Details: Enter a value in either the Amount field or the Percent field._

Even though the records are created

**Steps to Replicate**

1. Ensure that your Gift Entry template has the GAU Allocation bundle on it
2. Create a new Gift Entry batch
3. Fill in the Contact and Gift requirements
4. Click the "Add Allocation" button
5. Fill in the GAU, but leave the Amount and Percentage blank
6. Note the error message that pops up, but click "Save & Enter New Gift" and notice that the Gift can still be added to the Batch

**Note** -- when a default GAU is set in NPSP Settings, and appears in the GAU Allocation bundle, this error also appears.

Attempting this with the GAU1 field instead of the GAU Bundle, will result in another error, but will not write the records erroneously.

![image](https://user-images.githubusercontent.com/53280203/140436001-1a4c8cd3-0eae-49da-99e5-a060a75eff4a.png)

**Workaround**
None at this time, as regardless of the error message showing, upon processing the batch the gift is still created with the Opportunity GAU Allocations as blank.

**Comment by mbeaty-sf** [comment]
W-9883123

**Comment by mbeaty-sf** [comment]
This Issue has been updated to note that when a default GAU is set in NPSP Settings, this same error occurs with the GAU added overriding the default GAU, and Allocating the Opportunity to the manually added GAU only, with blank values in the amount and percent fields.

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pYP5QAM&title=gift-entry-gau-allocation-bundle-allows-users-to-bypass-amount-or-percent-values-and-creates-records-erroneously) in the Trailblazer Community for updates.
