### ISSUE TITLE
Gift Entry - Updating Opportunities with a Single Payment Record Causes Close Date to be Overwritten with Payment Scheduled Date

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6666]
**Issue**
When updating an Existing Gift with a single unpaid Payment, the Donation Date, which carries to the Opportunity Close Date field, has its date overwritten by the unpaid Payment's Scheduled Date field value. This happens when you select "Update Payment" under "Review Donations" model that appears in Gift Entry when you select an existing Contact with open Opportunities, and if there is only a single unpaid Payment on that Opportunity, the only option to select is Update Payment (or Create New Payment). If there is more than 1 Payment on the Opportunity the "Update Opportunity" option is available to be clicked, which will preserve the Opportunity Close Date as it had been previously entered.

**Steps to Replicate**

1. Create an NPSP-installed org
2. Create a new Contact
3. Go to Setup >> Object Manager >> Opportunity >> Fields and Relationship >> Set History Tracking >> select Close Date and Stage
4. Create a new Opportunity associated with the Contact created in step 2
a. Name: Test Opportunity
b. Account name: <Household of Contact created in Step 2>
c. Primary contact: <Contact created in Step 2>
d. Amount: $1
e. Close Date: <several days in the past>
f. Stage: Prospecting (or any non-Closed/Won or Closed/Lost state)
11. Go to Opportunity created in step 4 >> Go to the related list >> Payments >> Open the Payment >> Click Edit change the Schedule payment to a future date (several days in the future)
12. Go to Gift Entry >> Click on new Batch >> Select "Default Gift Entry Template" >> Name the Batch >> Leave the default values as is and click save.
13. Enter the below information on the Gift Entry screen
14. Donation Donor: Contact1
15. Contact1: <Contact created in Step 2>
16. You will see the message "This donor has pending donations. Review donation" >> Click Review Donations >> Select the Update Payment from the modal
17. Notice that upon choosing Update Payment, and the modal closing, the Donation Date is updated to the Payment's Scheduled Date and is no longer the Close Date that was selected on the Opportunity when input in Step 4
18. Import the Batch
19. Notice that the Opportunity's close Date has been updated to the Payment's Scheduled Date

**Cause**

In the case where there is a single unpaid Payment on an open Opportunity, "Update Opportunity" is greyed out, and a User is then required to choose "Update Payment" if they want to make any changes to an existing Opportunity/Payment in Gift Entry. When there are 2 or more Payments, then the option to "Update Opportunity" is present, and clicking that will allow the Opportunity's Close Date to be preserved upon save (unless otherwise manually changed when pulled into Gift Entry); however, even in the situation where there are multiple Payments, if a User chooses to "Update Payment" the Opportunity Close Date is still updates to the Payment's Scheduled Date.

**Workaround**

Automation can be leveraged (Flow, Workflow, Process Builder) in order to revert the Close Date back to the proper date; however, a help article sometimes referenced in this situation will not work in this scenario (https://help.salesforce.com/s/articleView?id=000323585&type=1) as there are 2 updates made through code before the Workflow fires:

1. Opportunity Close Date > Payment Scheduled Date
2. Payment Scheduled Date > Today's Date (automated upon close of Opportunity's Payments)
3. *Here when the Workflow referenced in the Help article fires, is it referencing "PriorValue" so that means is it referencing the Payment Schedule Date from Step 2, rather than the desired Opportunity Close Date originally input, referenced in Step

**Comment by mbeaty-sf** [comment]
W-7780864

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pYPTQA2&title=gift-entry-updating-opportunities-with-a-single-payment-record-causes-close-date-to-be-overwritten-with-payment-scheduled-date) in the Trailblazer Community for updates.
