### ISSUE TITLE
Gift Entry - If Amount Target Field is Changed in Advanced Mapping, Error Displayed in New and Existing Batches

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6673]
**Issue**

If a User changes the target field of Amount in Advanced Mapping, while NPSP Data Import will still import and map the field properly, Gift Entry displays an error (Gift Entry also still imports the value correct, but the error is off-putting and displays every time).

**Steps to Reproduce**

1. In an org with NPSP installed
2. Go to Setup >> Object Manager >> Opportunity >> Fields and Relationship >> Click New >> Select "Currency" >> Name it as testcurrency
3. Go to NPSP Settings >> System Tools >> Advanced Mapping for Data Import & Gift Entry >> Configure Advanced mapping >> Opportunity >> Change the field mapping from "npsp__Donation_Amount__c to amount" to "npsp__Donation_Amount__c to testcurrency__c"
4. Go to Gift Entry >> Template >> Create a new Template >> Verify the Form fields have Opportunity: testcurrency__c
5. Go to Gift entry >> Click New Batch > You will see the below error:

Cannot read properties of undefined (reading 'DeveloperName')'

**Comment by mbeaty-sf** [comment]
W-9946997

**Comment by jesslopez-sf** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pYPOQA2&title=gift-entry-if-amount-target-field-is-changed-in-advanced-mapping-error-displayed-in-new-and-existing-batches) in the Trailblazer Community for updates.
