### ISSUE TITLE
Gift Entry - Decimal Comma Currency Locales cause Amount to be Inflated by two zeros on save

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6675]
**Issue**
When a User has a locale set to a currency that utilizes a decimal comma when trying to access Gift Entry Batch, they will not be able to as a result of Issue https://github.com/SalesforceFoundation/NPSP/issues/6125. When they instead access Single Gift Entry, while they will be able to access the page, the Amount field will incorrectly adjust the amount to be 2 zeros more than User is actually inputting whether they use a `,` or `.` to dictate the cents of an Amount.

**Steps to Reproduce**

1. Navigate to your User record and change the locale to French (France)
a. Optional for visual conistency: Navigate to Company Settings > Company Information and change the Currency Locale to French (France) - EUR 
2. Navigate to Gift Entry
3. Select Single Gift Entry
4. Enter Contact1 and Contact fields required
5. Enter an Amount value 100,00 or 100.00
6. Click save

_Outcome_: The amount is changed to 10 000,00 if using decimal commas, or 10,000.00 if you are using decimals
_Expected Outcome_: The amount should reflect the amount entered, 100,00 should be that, but it is being

**Comment by mbeaty-sf** [comment]
W-9954778

**Comment by andreisidiom** [comment]
I am facing this issue in Salesforce NPSP.
Is there a planned official correction for it? 
Any expected date for patch to be applied?

**Comment by jamesbsfdc** [comment]
Hi @andreisidiom We don't have an expected date to patch this currently. 

Would you mind logging a support case about this, referencing the bug and also posting back here with the case number? The support engineer will link your case to the bug internally. Additional support cases help with gauging the potential customer impact of specific issues.

Thanks

**Comment by jesslopez-sf** [comment]
Please follow [this Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pYP4QAM&title=gift-entry-decimal-comma-currency-locales-cause-amount-to-be-inflated-by-two-zeros-on-save) in the Trailblazer Community for updates.
