### ISSUE TITLE
Remove or change the Batch Gift Entry reference text in NPSP Settings

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6678]
### Issue Summary

Batch Gift Entry in NPSP was retired in version 3.202 - effective in production orgs from 13 July 2021. See announcements here:

- https://powerofus.force.com/s/feed/0D57y00000JHFm5CAH
- https://powerofus.force.com/s/feed/0D51E00005acDV1SAM

With the retirement, users can still access Batch Gift Entry records but they are no longer able to process these records using BGE.

The issue is the STG_PanelDataImportAdvancedMapping page within NPSP Settings (NPSP Settings --> System Tools --> Advanced Mapping for Data Import & Gift Entry) still contains the following text which is confusing and misleading for users, as it suggests it is possible to continue to use Batch Gift Entry instead of Gift Entry.

"If preferred, you can disable Gift Entry and instead use older Batch Gift Entry (or Single Gift Entry, if using GEM)."

The text is stored in the geBodyGiftEntryHelp label and associated translation files:
https://github.com/SalesforceFoundation/NPSP/blob/main/force-app/main/default/labels/CustomLabels.labels-meta.xml#L6737

**Comment by jamesbsfdc** [comment]
W-9968552

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlA7QAI&title=remove-or-change-the-batch-gift-entry-reference-text-in-npsp-settings) in the Trailblazer Community for updates.
