### ISSUE TITLE
Issues in between NPSP releases

### ISSUE THREAD

**Issue by preeti-lightful** [SalesforceFoundation/NPSP#6679]
I was trying to deploy some non NPSP related things to A sandbox yesterday, like Opportunity object fields etc and getting this validation error though I didn't have this field in my package

The error was : 
`Opportunity.npsp__Acknowledgment_Status__c | Custom Field | 2346 | 13 | Cannot modify managed object: entity=CustomFieldDefinition, component=00N4J000003HDh6, field=Description, state=installed: newValue='The acknowledgement status of this Opportunity.', oldValue='The acknowledgement status of this Opportunity. '`

Today Morning I see the error disappeared and See NPSP has updated in My target Org along with this field 
![image](https://user-images.githubusercontent.com/32099339/135444399-319e78c3-43b3-43f2-9937-b9b450dd9a5c.png)
![image](https://user-images.githubusercontent.com/32099339/135444493-c797a47e-da5d-4ee7-8238-4755caad52ce.png)

My issue is I spent a couple of hours yesterday to rectify this issue and It was caused by NPSP package. I even checked the beta package files and now Checked the new release file, there is no mention of a change of this field Opportunity.npsp__Acknowledgment_Status__c , But I can for sure see the field is changed I can see the extra space has been removed which was there yesterday.

Could we please get some clarification on this?

**Comment by jamesbsfdc** [comment]
Hi Preeti

We don't offer support via GitHub issues. Please log a support case if you want someone in the team to review this.

Thanks

James
