### ISSUE TITLE
Probabilistic Encryption on Contact Name Results In Installation/Upgrade Failures

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#6689]
If customers have encrypted the Contact Name field with Probabilistic encryption, they may encounter errors installing NPSP or receiving our updates.

### Error:
"Could not process MDAPI response: Update of InstalledPackage npsp: Error: (Contact.NPSP_Contact_Personal_Email_Match) The following fields are invalid: FirstName., Details: Contact.NPSP_Contact_Personal_Email_Match: The following fields are invalid: FirstName
<img width="1201" alt="Screen Shot 2021-10-11 at 10 38 56 AM" src="https://user-images.githubusercontent.com/29731456/137031680-88d71198-41b7-4a98-972a-ece3731c7a3b.png">

### Root Cause:
Probabilistic encryption is not compatible with matching rules. The [documentation](https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/security_pe_matching_rules.htm) states that determination encryption should be used instead. 

### Workaround:
Switch the encryption type to one of the Deterministic Encryption options.

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlA6QAI&title=probabilistic-encryption-on-contact-name-results-in-installation-upgrade-failures) in the Trailblazer Community for updates.
