### ISSUE TITLE
BDI/NPSP Data Import: Duplicate Opportunities when importing Recurring Donations with Campaigns via BDI

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6695]
### Background

The [Summer 2021 release](https://powerofus.force.com/s/feed/0D57y00000JHFm5CAH) of NPSP (v3.202) introduced functionality to allow a user to import Recurring Donations via Batch Data Import (if Enhanced Recurring Donations is enabled).

### Issue Summary

A user who is importing Recurring Donation records with NPSP Data Import will notice that if they populate the Campaign Name (npsp__Donation_Campaign_Name__c) or the Donation Campaign Source (npsp__DonationCampaignImported__c) fields but none of the Opportunity fields on NPSP Data Import, that two opportunity records are created instead of one when processing the record. Both opportunities will be associated to the imported recurring donation record.

One of the opportunities will have an amount that matches what the user entered in the Recurring Donation Amount field (npsp__Recurring_Donation_Amount__c) whereas the other opportunity will not have an amount.

### Steps to Replicate

1. Ensure Enhanced Recurring Donations is enabled
2. Create an NPSP Data Import with the following field values:
Contact1 First Name: John
Contact1 Last Name: Smith
Campaign Name: Test
Recurring Donation Amount: 5
Recurring Donation Day of Month: (Today's day in month)
Recurring Donation Installment Period: Monthly
Recurring Donation Installment Frequency: 1
Recurring Donation Name: Test
3. Process the NPSP Data Import record
4. Notice that two opportunities are created instead of one and the NPSP Data Import record has populated the Donation Imported, Donation Imported Status and associated fields

### Workaround

If a user is importing Recurring Donation records they should populate opportunity data as well as recurring donation data in the NPSP Data Import record. These opportunity values will be used to create the opportunity record as an "open" or closed-won" stage depending on the value in the Donation Stage field. This will result in only one opportunity being created, with the opportunity being linked to the importing recurring donation via the Recurring Donation lookup field on the opportunity.

**Comment by melissabarber** [comment]
Manually closing issue because PR to fix was already merged.
