### ISSUE TITLE
Gift Entry - Rounding Error when Allocating Gifts of Certain Values

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6710]
**Issue**
In certain scenarios, entering a Gift of certain values and allocating them is causing a calculation issue that throws an error saying that the Allocations do not match the Amount of the Gift, when the values do add up correctly to 2 decimal places.

**Steps to Reproduce**
1. In an NPSP-installed org, with Gift Entry enabled
2. Create 2 General Allocation Units
3. Create a new Contact
4. Ensure your User has access to Gift Entry via the Permissions: https://powerofus.force.com/s/article/NPSP-Configure-Gift-Entry
5. Navigate to Gift Entry via the App Launcher and create a new Template, and ensure that the GAU Bundle is added to the template
6. Click "New Batch" button and ensure that you select the template that you just created
7. Fill in Data: 
a.  Donor Type: Contact1
b.  Donor Contact: Test SFDO
c.  Opportunity Amount: 873.18
Click Manage allocations:
a.  General Accounting Unit: GAU2, Amount: $611.23
b.  General Accounting Unit: GAU3, Amount: $261.95

Result: You will see "The total amount doesn't match the Amount" upon entering the allocations even though the amount matches the GAU allocations.

**Cause**
In the `geFormWidgetAllocation.js', the method `isOverAllocated` is returning a calculation that is > than the Amount of the Opportunity, by $ XX.xx00000000001.

The line of code where the issue occurs: https://github.com/SalesforceFoundation/NPSP/blob/5363fa8f8ae3ef46a5f305c49e7af4e492a4f0cf/force-app/main/default/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js#L125-L126

In the steps to replicate, these values for `allocatedAmount` and `totalAmount` are represented as follows in the above method:
![image](https://user-images.githubusercontent.com/53280203/138971573-83133f4d-2fe8-43ef-a872-81270100696b.png)

Subsequently the comparison of the values is returning an error when checked against: the `validate()` method:
https://github.com/SalesforceFoundation/NPSP/blob/5363fa8f8ae3ef46a5f305c49e7af4e492a4f0cf/force-app/main/default/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js#L241-L257

**Workaround**
The Gift can still be saved and imported; however, the error message will persist when the Gift is edited.

**Comment by hannah-west-CBF** [comment]
@mbeaty-sf  I think you have a typo in your writeup here.  Under Steps to Reproduce > Step 7 > Click Manage Allocations,  one of the GAU Allocation amounts should be $611.23.  The other is accurate at $261.95.  Gift total is accurate at $873.18. 
 This case originate with our org and we're following progress.  Thanks!

**Comment by mbeaty-sf** [comment]
Updated, thank you @hannah-west-CBF!

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlA0QAI&title=gift-entry-rounding-error-when-allocating-gifts-of-certain-values) in the Trailblazer Community for updates.
