### ISSUE TITLE
Manage Household Page Fails to Load If Customer Does Not Have Access to New Undeliverable Address Fields

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#6733]
### Summary
Customers are unable to view the **_Manage Households_** page after receiving the NPSP 3.209 update (released to sandboxes on November 4 and Production on November 16). This is due to a field access issue on 3 new fields introduced in the update. The page shows a never-ending spinner, with an Account error vaguely visible in the background.

### Workaround
While we address this within the product, please grant access to the following fields:

- **Account object**: Read and Edit access to Undeliverable Billing Address (npsp__Undeliverable_Address__c)
- **Contact object**: Read and Edit access to Undeliverable Mailing Address (npsp__Undeliverable_Address__c)
- **Address object:** Read access to Undeliverable (npsp__Undeliverable__c)

### Screenshot
![Screen Shot 2021-11-05 at 11 51 44 AM](https://user-images.githubusercontent.com/29731456/140546535-a6618f1e-9aa0-4a54-8d14-973caa69bf78.png)

**Comment by jesslopez-sf** [comment]
W-10135728

**Comment by redmondke** [comment]
@jesslopez-sf I attempted this workaround with multiple profiles in the past few days. The workaround works for our _SysAdmin_ profile, but does not work for our other profiles. Our SysAdmin profile has the _Edit Read Only Fields_ permission, setting it apart from the others. As such, I believe the workaround instructions here are wrong - profiles need **edit access** to these fields, not just read access.

**Comment by jamesbsfdc** [comment]
Thanks for reporting @redmondke, I think you are right. We'll get this updated once we validate it

**Comment by jesslopez-sf** [comment]
Thank you so much, @redmondke ! We definitely missed that in our workaround. I've updated the description above. We did find that we could get away with just Read access on the Address object's Undeliverable field (but needed edit on both the Contact and Account fields). If you saw otherwise in your org, please let us know.

**Comment by dellsystem** [comment]
Thanks, this fixed the neverending spinner issue for my org. In my case, I had initially granted edit access just to the Undeliverable Billing Address field on Account, not realising that Contact and Address had new fields too. That resulted in a different error message:

> This page has an error. You might just need to refresh it. Error in $A.getCallback() [self.reportError is not a function] Callback failed: apex://npsp.HH_Container_LCTRL/ACTION$getContacts Failing descriptor: {markup://npsp:HH_Container}

The error went away after granting edit access to the other fields.

**Comment by sarafigal** [comment]
This still isn't working for me. Can someone help me understand where to look for where I might have missed a step involved in creating the permissions needed? ARGH. This hang up is creating problems down the line with my sync between SF and QBO

**Comment by jamesbsfdc** [comment]
@sarafigal We don't provide support via GitHub issues. Please instead create a support case with steps to reproduce and grant login access to an org affected by the issue

See help article
https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case
