### ISSUE TITLE
NPSP Gift Entry: null input to JSON parser error

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#6734]
This issue was introduced in NPSP 3.209 (234 release).

### Summary

This error message can display in 3 scenarios:
1. **With default GAU Allocations enabled in NPSP Settings, using the GAU Allocation Field Bundle on a Template**
If a customer uses a Template that includes the GAU Allocation field bundle and they do not add or edit that default GAU on their Gift Entry form (batch or single mode).

2. **With default GAU Allocations enabled in NPSP Settings, using the GAU Allocation Fields Instead of the Field Bundle**
If a customer uses a Template that includes the GAU Allocation individual fields (vs. the bundle) and they do not enter data in those fields in their Gift Entry form (batch or single mode).

3. **Without default GAU Allocations enabled in NPSP Settings, using the GAU Allocation Field Bundle on a Template**
If a customer adds a new Allocation via the field bundle, but then clicks the Delete button OR if they leave the Amount and Percentage field blank.

In all scenarios, a  null pointer error occurs and we display the following error at the top of the page: _null input to JSON parser._ If they navigate away from the page and attempt to view the batch, there is a never-ending spinner and they cannot get into the batch.

<img width="381" alt="Screen Shot 2021-11-05 at 2 40 22 PM" src="https://user-images.githubusercontent.com/29731456/140563953-b2a76cc5-ec4f-4666-b123-fe9a3be72164.png">

### Root Cause

Null pointer due to invalid  GAU Allocation JSON in associated Data Import record's Additional_Object_JSON__c field.

The Chrome Console shows the following error:
```
exceptionType: System.NullPointerException"
message: System.NullPointerException"
stackTrace: Class.System.JSON.deserialize: line 15, column 1
Class.npsp.AdditionalObjectJSON.instantiateDynamicSourceGroup: line 108, column 1
Class.npsp.AdditionalObjectJSON.<init>: line 44, column 1
Class.npsp.Gift.populateSoftCreditsFromAdditionalObjectJSON: line 188, column 1
Class.npsp.Gift.populateSoftCredits: line 174, column 1
Class.npsp.Gift.<init>: line 72, column 1
Class.npsp.Gifts.all: line 93, column 1
Class.npsp.GiftBatchDTO.<init>: line 62, column 1
Class.npsp.GiftBatchService.viewModelWithLimitsAndOffsets: line 73, column 1
Class.npsp.GE_GiftEntryController.getGiftBatchViewWithLimitsAndOffsets: line 112, column 1
```

The Additional_Object_JSON__c field contains a value similar to this, which ultimately triggers the parsing null pointer.
`{"GAU_Allocation_1_417f7189c":[]}`

### Workaround
See comment from James below

### Steps to Repeat
**Setup:**
- Enable Advanced Mapping and Gift Entry in NPSP Settings, and set a default GAU in NPSP Settings

**Scenario 1:**
- Go to Gift Entry Tab and clone default template. The template includes the GAU bundle by default.
- Create new batch from template. Enter Contact and Donation info. Upon save, error will appear. 

**Scenario 2:**
- Go to Gift Entry Tab and clone default template. Remove GAU Allocation field bundle and replace with GAU 1 Allocation individual fields.
- Create new batch from template. Enter Contact and Donation info. Leave GAU 1 fields blank. Upon save, error will appear. 

**Scenario 3:**
- Go to NPSP Settings and disable the default GAU Allocation.
- Create a new batch from the template created during scenario 1 (i.e. it will include the GAU Allocation field bundle)
- Create new batch from template. Enter Contact and Donation info. 
- Click the Add New Allocation button. Hit the Delete button next to it. Upon save, error will appear.

**Comment by jesslopez-sf** [comment]
W-10136165

**Comment by jamesbsfdc** [comment]
### Workaround

If you are still in the batch after receiving the "null input to JSON parser" error, do not navigate away from the batch as when you return to it you will not be able to load it (see never-ending spinner referenced above)

If the Gift you are entering SHOULD NOT have a General Accounting Unit associated with it in the batch:
- Click "Cancel & Clear Form"
- Re-enter the Gift without clicking on "Add New Allocation"

If the Gift you are entering SHOULD have a General Accounting Unit associated with it in the batch:
- Click "Add New Allocation"
- Enter the allocation data you want associated with the Gift
- Click Update
