### ISSUE TITLE
Deleting contacts from a non-Household account renames the account

### ISSUE THREAD

**Issue by forrestpolaris** [SalesforceFoundation/NPSP#6751]
Hi all -- After updating to NPSP 3.209, we started experiencing an issue where non-Household accounts would be renamed to "Anonymous Household" after any contact in that account is deleted (as long as there is at least 1 contact remaining.) We are using the household territory model, but these contacts are not in or affiliated with a household account (per the account's record type.)

We've written up a simple failing test case here:
```Apex
// NON_HOUSEHOLD_CONTACT_RT and NON_HOUSEHOLD_CONTACT_RT are record types specific to our org.
@isTest
static void itPreservesNonHouseholdAccountNamesOnContactDelete() {
  Account acc = new Account(Name = 'Test Account', RecordTypeId = NON_HOUSEHOLD_RT);
  insert acc;
  Contact con1 = new Contact(AccountId = acc.Id, FirstName = 'Test 1', LastName = 'Person', RecordTypeId = NON_HOUSEHOLD_CONTACT_RT);
  Contact con2 = new Contact(AccountId = acc.Id, FirstName = 'Test 2', LastName = 'Person', RecordTypeId = NON_HOUSEHOLD_CONTACT_RT);
  insert new List<Contact> { con1, con2 };

  Test.startTest();
  delete con1;
  Test.stopTest();

  acc = [SELECT Id, Name FROM Account WHERE Id = :acc.Id];
  System.assertEquals('Test Account', acc.Name);
}
```

It appears that the account is updated in this via the `ACCT_IndividualAccounts_TDTM` AfterDelete trigger:
```
Class.npsp.HouseholdNamingService.updateHouseholdNameAndMemberCount: line 122, column 1
Class.npsp.Households.updateNameAndMemberCount: line 217, column 1
Class.npsp.Households.updateHouseholds: line 180, column 1
Class.npsp.Households.handleContactDeletion: line 131, column 1
Class.npsp.ContactAdapter.onAfterDelete: line 216, column 1
Class.npsp.ACCT_IndividualAccounts_TDTM.run: line 72, column 1
```

It doesn't look like the code in that path filters the accounts to just household accounts. I would expect `ContactAdapter.onAfterDelete`'s call to `getHouseholdsFor` would just return household accounts, but it appears to return all accounts of any record type for the given contacts.

Thanks!

**Comment by jamesbsfdc** [comment]
Hi @forrestpolaris  Please log a support case as we don't provide support via GitHub issues. 

In the case creation form if you select the following it should ensure it gets assigned to the correct case queue

* Product: Salesforce.org (http://salesforce.org/) Products
* Topic: Nonprofit Cloud
