### ISSUE TITLE
Deleting a contact from a non-Household account renames the Account Name and populates the Primary Contact field

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6755]
### Background

NPSP 3.209 included some refactor work for accounts and contacts which introduced this new bug when contacts are deleted. 

### Issue Summary

**Scenario 1:** 
If an organisational account (i.e any account that is not a household account) has more than one contact directly associated with it, and one of the contacts in the account is deleted the account name of the organisation account will be renamed to "Anonymous Household" and the Primary Contact lookup field on the account will be populated with an existing contact in the account.

**Scenario 2:**
If customers are using the Individual Account Model (NPSP Settings --> People --> Account Model), their Contacts are associated with 1 Account, typically named "Individual". If a customer deletes one Contact from this Account, the Account is renamed to "Anonymous Household".

**Scenario 3:**
Customers may also encounter this bug when merging contacts, where the contacts being merged are not both household contacts. If using the Individual (Bucket) Account Model please also see issue: https://github.com/SalesforceFoundation/NPSP/issues/6772

**Note:** The organisation or individual account will not be renamed when you delete the last contact in the account

### Steps to Reproduce

**Scenario 1:**
1. Create a new account "Test Organization" ensuring the Account Record Type is not the household account record type i.e Record Type = Organization
2. Create a business contact "Test Contact 1" for this account i.e ensure the Account Name field on the contact is "Test Organization"
3. Create a 2nd business contact "Test Contact 2" for this account as per step 2
4. Delete either "Test Contact 1" or "Test Contact 2"
5. Confirm the Account Name of "Test Organization" has been changed to "Anonymous Household" and the Primary Contact lookup field has been populated with a link to the remaining contact

**Scenario 2:**
1. Go to NPSP Settings --> People --> Account Model and switch to the Individual Account Model.
2. Create 3 Contacts and leave their Account blank. They will be associated with an Account named "Individual."
3. Delete one of the Contacts. The Account is renamed to "Anonymous Household."

**Scenario 3:**
1. Go to NPSP Settings --> People --> Account Model and switch to the Individual Account Model.
2. Create 3 Contacts and leave their Account blank. They will be associated with an Account named "Individual."
3. Merge 2 of these contacts. The Account is renamed to "Anonymous Household."

### Workarounds
**Scenario 1:** 
Do not directly delete the contact. First, clear the Account Name value in the Contact you want to delete, which will result in a household account being created for the contact, then delete the contact.

**Scenario 2:**
Do not directly delete the contact. Create a new Organisation Account. Edit the Contact and switch its Account value to that organisational Account. Save and then delete the Contact.

**Scenario 3:**
Unfortunately there is no viable workaround for this scenario that is less onerous than simply renaming the Anonymous Account back to it's original name

**Comment by jamesbsfdc** [comment]
W-10227258

**Comment by robinmlindemann** [comment]
In our case, the entire Organization name is overwritten and all users under that org are reassigned to individual Anonymous Households, so we lose track of who was initially associated to that Account.  Huge problem for my current client.

**Comment by daveybradders** [comment]
Same here Robin - fortunately we have Field Tracking enabled on the name field, which helped a lot for a particular client.

**Comment by jamesbsfdc** [comment]
@robinmlindemann  Could you log a support case about this and post back here with the case number? We've not observed the behaviour you describe of existing account-contacts being switched to household-contacts in any reports so far and I was not able to see this when debugging the issue so I would appreciate seeing your setup. 

@daveybradders No update yet on a fix. Please follow the issue and you will be updated when anything changes.

**Comment by robinmlindemann** [comment]
Case created.

***@***.***

**Comment by robinmlindemann** [comment]
@jamesbsfdc 

I opened a ticket, as you requested.  Received a response from support directing me back to THIS post.  Good times.

I'll keep following for a solution.

**Comment by jamesbsfdc** [comment]
@robinmlindemann I don't work in the support organisation. Can you post your case number and I'll get in touch with the person working your case?

**Comment by Filikin** [comment]
Just had a panic call with a client - they have an account for each homeless service. They deleted a contact record connected to the account and as far as they could see the account had disappeared - and all the contacts were now connected to an Anonymous household. Of course the problem was this renaming issue.
I am going to add a validation rule to prevent services been renamed (they have a record type of Service)

**Comment by Filikin** [comment]
At least the solution was just to rename the account - the bug didn't create any new accounts

**Comment by Filikin** [comment]
Interesting - adding a validation rule to prevent the org been renamed fixes the problem. The contact still gets deleted but the org name is unchanged. I was expecting to see an error message, but this is better

**Comment by kgaubert** [comment]
This is similar to an issue we just found. 

We use the Individual Account Model. A user deleted 4 duplicate contact records and noticed that over 300 contacts Account Name changed to Anonymous Household. None of these contacts are related at all.

**Comment by jesslopez-sf** [comment]
I just updated the Github Issue to reflect this behavior when customers are using the Individual Account Model.

**Comment by terishipp** [comment]
I created a record-triggered flow that renames the Account to its prior value when it changes to Anonymous Household. Works like a charm!

**Comment by RiderM780** [comment]
I believe for scenario 3 this has been an issue for a while - I use the Manage Household button to add the duplicate contact to the master record household and then Merge Contact. The duplicated account is deleted 9sent to the recycle bin) and the Master Household account remain. Is this the same scenario?

**Comment by jamesbsfdc** [comment]
@RiderM780  This sounds different. The scenario as described above is in the context of this bug only - and was not something that happened prior to the recent release.

**Comment by schieco** [comment]
This is a huge issue for our clients as well - they cannot merge contacts under a non-household account any longer without this issue! Could we get an update on ETA for a fix, please? They are highly displeased with NPSP at the moment as two of the clients just implemented it.

**Comment by anekola** [comment]
Salesforce support told me this yesterday: _"We are still in the process of trying to fix this problem. Testing found some additional issues we are fixing. This is taking a bit of time so I do apologize for the delay on getting a fix to you. Once I have a release date I will provide it to you. A fix will most likely not be available till late January at the earliest due to a release moratorium for the holidays."_

**Comment by KarenKing999** [comment]
My organization is having one of the issues reported above, not being able to merge contacts. I'm commenting here to be part of the discussion and communication of the resolution.

**Comment by dokimion** [comment]
Hello, I see that my org has 3.211. Does that mean that the fix has been deployed?

**Comment by jamesbsfdc** [comment]
Hi @dokimion  Yes this issue was fixed in the 3.211 release which was pushed to orgs late last week. If you are still experiencing the issue or other unexpected behaviour please log a support case:
https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case
