### ISSUE TITLE
Gift Entry: Users receiving a "System.LimitException: npsp:Too many SOQL queries: 101" error when processing a batch

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6757]
Updated: 3 Dec 2021

### Background

Gift Entry allows a user to enter a new gift or to update an existing gift.  NPSP 3.209 introduced some new functionality to allow users to use a Soft Credit bundle within Gift Entry and also included some refactoring of existing Gift Entry code. 

### Issue Summary

One of the SOQL queries being executed when a user processes a Gift Entry batch is querying all NPSP Data Import records associated with the batch that have a value in the DonationImported__c field on NPSP Data Import. For each row returned we then query the associated opportunity and contact roles. Cumulatively the number of queries being executed will exceed the total number of SOQL queries governor limit if the number of records in the batch with DonationImported__c exceeds 45. 

https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_apexgov.htm

What this means in practice is you cannot process a batch if the batch contains 45 gifts that have either been processed or will update update existing gifts. 

Here are some examples: 

- Batch A contains 45 unprocessed new gifts. The user should be able to process these gifts however if after processing the 45 gifts they create a new gift in the batch and attempt to process the batch again they will receive the SOQL error.

- Batch B contains 45 unprocessed existing gifts that correspond to existing open opportunities (i.e the user wants these opportunities to be updated to indicate payment has been received). The user should be able to process these gifts however if after processing the 45 gifts they create a new gift or add a gift that should update an existing open opportunity and attempt to process the batch again they will receive the SOQL error. 

- Batch C contains 100 unprocessed new gifts. The user should be able to process the batch however if after processing the gifts they add any new gifts to the batch they will be unable to process the batch again. 

- Batch D contains 100 unprocessed existing gifts that correspond to existing open opportunities (i.e the user wants these opportunities to be updated to indicate payment has been received). The user will not be able to process the batch. They will need to reduce the batch to 45 or fewer before they can process the batch. 

### Steps to Reproduce

1. Create a new Gift Entry batch
2. Import and process 45 records within the batch such that all records have a status of Imported
3. Create a new gift within the batch and attempt to process this
4. Confirm you receive a "npsp:Too many SOQL queries: 101" error

### Workaround
Process records via a new batch rather than an existing one if the batch already contains 45 or more records with value in the DonationImported__c field on NPSP Data Import.

For example: If you want to add 100 or more records to a batch that already contains 45 processed records, create a new batch, add the 100 records to the new batch and process these in bulk. Also see the examples above for scenarios.

Another option is to add gifts to a spreadsheet and use NPSP Data Import to process the records rather than Gift Entry
https://powerofus.force.com/s/article/NPSP-Configure-Data-Importer-Options
https://trailhead.salesforce.com/content/learn/projects/import-your-data-using-npsp-data-importer

**Comment by jamesbsfdc** [comment]
W-10244877

**Comment by Filikin** [comment]
I am getting this error on a new batch with 75 records.
Is there a parameter to set the batch size to avoid the "too many SOQL queries"

**Comment by jamesbsfdc** [comment]
@Filikin Please could you log a support case and post back here with the case number as I could not replicate that behaviour in testing. 

The parameter than has controlled the batch size in the past is not being used so unfortunately does not help with this bug

**Comment by Filikin** [comment]
Thanks James,
It is case #41732407
Regards,
Eamon

**Comment by lpeabody-park** [comment]
This is also our case #41700124. 

Limiting batches to <45 entries at peak workload season is not a viable long term workaround. Certainly hoping you will be able issue a fix asap. 
Best, Laura

**Comment by DebbieN-SF** [comment]
Our case number is #41725655

I split batches to sub 45 and they processed ok, so at least we have a short term workaround.

**Comment by jamesbsfdc** [comment]
@lpeabody-park  Another workaround, would be to add gifts to a spreadsheet and use NPSP Data Import to mass import the  data into the NPSP Data Import object. From there the records could be processed en-mass. I appreciate this is undesirable but just offering alternative options
https://trailhead.salesforce.com/content/learn/projects/import-your-data-using-npsp-data-importer

**Comment by jamesbsfdc** [comment]
@Filikin Would you mind granting support login-as access to your org on the case? Note: Salesforce.com rather than Salesforce.org in the login-as options

**Comment by Filikin** [comment]
Hi James,
That is done now.
This batch will show the error:
https://dublinsimoncommunity.lightning.force.com/lightning/r/npsp__DataImportBatch__c/a0n09000001PKhkAAG/view
regards,
Eamon

**Comment by jamesbsfdc** [comment]
@Filikin Thanks for the case and login access. Support will respond back on the case later today but unfortunately the news is not good. Your batch contains gifts that are being matched against existing opportunities/payments so the workaround above of being able to process the batch in bulk if it does not already contain over 45 processed records does not apply. 

As the "Donation Imported" field on NPSP Data Import is populated for these records the problem query will look over each of these donations twice and so this is why you are hitting the SOQL error. I'm afraid you will not be able to process the batch as it contains too many records. 

You would need to either: 
1. Reduce the records in the batch down to 45 or under and process the other gifts in a separate batch
2. Abandon the batch and use the spreadsheet / NPSP Data Import approach mentioned above

For 1 above, you could create a new batch (batch 2) grab the ID of the batch and then mass update the NPSP Data Import Batch with the ID of batch 2 for some of the records from batch 1 such that you have 45 records in batch 1 and the remaining ones in batch 2. This should allow you to process both batches. 

If the approaches above do not work or you run into issues please reply back on the case

**Comment by jamesbsfdc** [comment]
FYI I've updated the issue above to make it clearer when you will and will not experience the error

**Comment by Filikin** [comment]
thanks James, is there any timeframe on a fix?

**Comment by jamesbsfdc** [comment]
@Filikin I cannot say at the moment but given our release schedule it may be a while before this is patched unfortunately
