### ISSUE TITLE
Household Naming Services Causes Additional Account Update When Referenced Field Values are Null

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#6762]
### Issue
If household naming and greeting settings include fields that are null on records, NPSP is doing an unnecessary Account update, causing additional SOQL query/DML operation counts in governor limits. The default Informal Greeting setting, for example, includes Contacts’ First Names. So if a Contact is inserted without a First Name, this condition will occur.

### Root Cause
**Using the Informal Greeting as an example:**
When TDTM_Account first fires in Before Update context, ADDR_Account_TDTM sees the null value in Informal Greeting (since First Name is blank) and replaces the null value with our replacement label (“REPLACE”). [The isInformalGreetingReplaceable() method passes the value to isReplaceable which returns true if the field value is null, ‘’, or “REPLACE”. It’s null here, so we overwrite it with “REPLACE”.]
```
10:04:27.0 (1123951202)|VARIABLE_ASSIGNMENT|[486]|fieldValue|null
...
these are the lines that show it being replaced by the "REPLACE" text:
10:04:27.0 (1124856854)|STATEMENT_EXECUTE|[452]
10:04:27.0 (1124868848)|METHOD_ENTRY|[452]|01p2100000EK5uF|HouseholdNamingService.nameReplacementText()
```

When ADDR_Account_TDTM then fires in After Update context, we see that the newList contains that REPLACE value in the Informal Greeting field:
```
10:04:27.0 (1181315672)|VARIABLE_ASSIGNMENT|[47]|listNew|[
{
  "Number_of_Household_Members__c": 1,
  "LastModifiedDate": "2021-12-01T18:04:27.000Z",
  "npo02__LastOppAmount__c": 0.0,
  "Matching_Gift_Company__c": false,
  "npo02__OppAmount2YearsAgo__c": 0.0,
  "Name": "lopez5000 Household",
  "npo02__LastMembershipAmount__c": 0.0,
  "npe01__One2OneContact__c": "0032100000wj50MAAQ",
  "npo02__OppsClosed2YearsAgo__c": 0,
  "CreatedById": "00521000008inDUAAY",
  "npo02__OppsClosedLastYear__c": 0,
  "OwnerId": "00521000008inDUAAY",
  "npo02__OppsClosedThisYear__c": 0,
  "RecordTypeId": "01221000002le7kAAA",
  "Grantmaker__c": false,
  "CustomizableRollups_UseSkewMode__c": false,
  "IsDeleted": false,
  "npo02__Formal_Greeting__c": "lopez5000",
  "npe01__SYSTEM_AccountType__c": "Household Account",
  "npo02__TotalMembershipOppAmount__c": 0.0,
  "npe01__SYSTEMIsIndividual__c": true,
  "npo02__OppAmountThisYear__c": 0.0,
  "npo02__TotalOppAmount__c": 0.0,
  "npo02__LargestAmount__c": 0.0,
  "npo02__NumberOfClosedOpps__c": 0,
  "SystemModstamp": "2021-12-01T18:04:27.000Z",
  "Type": "Household",
  "CleanStatus": "Pending",
  "npo02__NumberOfMembershipOpps__c": 0,
  "npo02__OppsClosedLastNDays__c": 0,
  "CreatedDate": "2021-12-01T18:04:26.000Z",
  "npo02__OppAmountLastYear__c": 0.0,
  "Undeliverable_Address__c": false,
  "npo02__SmallestAmount__c": 0.0,
  "Id": "0012100000y4E0vAAE",
  "npo02__AverageAmount__c": 0.0,
  "npo02__OppAmountLastNDays__c": 0.0,
  "LastModifiedById": "00521000008inDUAAY",
  "npo02__Informal_Greeting__c": "REPLACE"
}]
```
AccountAdapter.renameHouseholdsNeedingNameUpdate() is called, which calls Households.updateNameAndMemberCount(getHouseholdsNeedingNameUpdate());  The updateNameAndMemberCount() calls householdNamingService.updateHouseholdNameAndMemberCount synchronously since there’s only one household Account to process. This is the method which ultimately will determine if there are updates to be made to the Name, Informal Greeting, and Greeting fields. If so, do those updates (in this case, we'll set the Informal Greeting to the FirstName value which is null), and we call the unitOfWork.registerDirty() method with all of these values:

```
10:04:27.0 (1322958842)|VARIABLE_ASSIGNMENT|[57]|sObjects|[
{
    "Id": "0012100000y4E0vAAE",
    "Name": "lopez5000 Household",
    "npo02__Formal_Greeting__c": "lopez5000",
    "npo02__Informal_Greeting__c": "",
    "Number_of_Household_Members__c": 1
}
```
Finally, we call unitOfWork.save(), which results in an Account update within the context of the previous Account update.

When compared with a log where a First and Last Name are inserted, no field values have changed, so nothing is registered as “dirty”. When we call unitOfWork.save(), there’s nothing to update and the extra Account update doesn’t happen.

### Steps to Repeat

1. Create a Contact with only a Last Name.
2. Compare to creating a Contact with a First and Last Name.

### Limits Comparisons
In a scratch org with only npsp installed, there are 17 SOQL queries that run during both scenarios. But when the FirstName is missing, there are 3 DML operations instead of 2 (an extra Account update occurring within the Account’s After Update context). Here’s a comparison of 3 different npsp versions... in general, SOQL queries are down, as well as DML operations. 

I created 3 scratch orgs with different versions of npsp and compared results (i.e. I checked out the release tags for these 3 versions and ran the dev_org cci flow). 
![Screen Shot 2021-12-03 at 11 31 27 AM](https://user-images.githubusercontent.com/29731456/144641571-b21b38ce-8cb9-4c18-a627-e11432ce2820.png)

### Workaround
If you are running into governor limits such as Too Many SOQL Queries within certain transactions which would run npsp household naming (inserting/updating Contacts), add a First Name to the data. Limits would likely only be reached within test classes when multiple operations are happening in one transaction. Otherwise, there is likely some recursion happening on Account update.

**Comment by jesslopez-sf** [comment]
W-10264165

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dl9qQAA&title=household-naming-services-causes-additional-account-update-when-referenced-field-values-are-null) in the Trailblazer Community for updates.
