### ISSUE TITLE
error on gift entry for npsp_payment_type__c

### ISSUE THREAD

**Issue by JasonRS31** [SalesforceFoundation/NPSP#6763]
Getting an error on gift entry trying to Process Batch. (attached)
Note - the auto-creating payments is disabled 
I've verified the mapping and npsp_Payment_type__c is only mapped once (attached)
I've deleted that field, tried to do a batch, and got the same error

It worked fine on October 2021, but tried again in December 2021 and getting the error. 
I've tried different batches, still getting errors
![Screen Shot 2021-12-04 at 8 23 59 AM](https://user-images.githubusercontent.com/95539950/144716977-e101b671-c5a0-4b68-ba06-928b0fcc0e0b.png)
![image (6)](https://user-images.githubusercontent.com/95539950/144716983-182ba17c-0468-48ec-b51e-2d1787b965ac.png)

.

**Comment by judisohn** [comment]
We do not provide direct support of issues here in Github. Please open a support case for further troubleshooting assistance. Thanks!
