### ISSUE TITLE
Users receiving a "Required fields are missing:Household_Account__c" or similar errors when creating Contacts

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6764]
### Issue Summary

Post the Winter 22 release of NPSP some customers have reported receiving errors when trying to create contacts where the contact is flagged as a potential duplicate record if Respect Duplicate Rule Settings is not enabled in NPSP Settings and the org has an active Account Duplicate Rule set to Alert on Create and the rule is evaluating duplicates based on Billing Address information.

In Lightning, when the user tries to create a contact with a mailing address they receive the following error:
- Required fields are missing:Household_Account__c

In Classic, the same user will receive the following error:
- Required fields are missing:Account

In a pre-Winter 22 (NPSP 3.208) org the user will receive an error similar to the following in both Lightning and Classic:
- Failed to create Account for Contact (NAME OF CONTACT). Use one of these records?

### Root Cause
This didn't crop up previously because we inserted Addresses in the Account AfterInsert context (i.e. we definitely always had an AccountId that we could associate with an Address). In 3.209, we insert the Address after the Account, both within the Contact BeforeInsert context [ACCT_IndividualAccounts_TDTM]. This is done in the HouseholdService.insertNewHouseholds() method, specifically within a code block like this:
https://github.com/SalesforceFoundation/NPSP/blob/1a87809620c57c6719a58d0f66c478427bcab68a/force-app/main/service/HouseholdService.cls#L384-L390

I think we could probably get around this scenario if we added some kind of check somewhere to check for a null AccountId prior to attempting to insert the Household Addresses. 

### Steps to Replicate

Ensure the following settings are in place:
- Respect Duplicate Rule Settings: Disabled
- Standard Account Duplicate Rule: Enabled (Operations On Create: Alert)
- Household Account Addresses Disabled: Disabled

Create a contact, ensuring a mailing address is entered

Create a 2nd contact with the exact same name and mailing address

### Workarounds

Check "Respect Duplicate Rule Settings" In NPSP Settings --> System Tools --> Error Notifications
or
Update the Account Duplicate Rule to uncheck Alert on Operations On Create

**Comment by jamesbsfdc** [comment]
W-10269485

**Comment by jesslopez-sf** [comment]
Updated with root cause

**Comment by commuter05** [comment]
The workaround has not resolved the issue for us.  We have removed all alerts on our account and contact duplicate rules. The system is now displaying an error of "FIELD_CUSTOM_VALIDATION_EXCEPTION" whereas it used to display "DUPLICATES_DETECTED". This different error is now preventing custom code intended to process a matching step for dupes.

**Comment by judisohn** [comment]
@commuter05 We do not provide direct support in Github. [Please open a support case.] Thanks. (https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case)

**Comment by commuter05** [comment]
Thank you @judisohn, it has been opened for almost a month now, just writing to inform the work around isn't working for us, as others may find it helpful.

**Comment by jamesbsfdc** [comment]
@commuter05 Can you share the support case number?

**Comment by commuter05** [comment]
@jamesbsfdc  Case #41765371

**Comment by jamesbsfdc** [comment]
Thanks @commuter05 I've made an internal post on the case.

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dl9lQAA&title=users-receive-a-required-fields-are-missing-household_account__c-or-similar-errors-when-creating-contacts) in the Trailblazer community for updates.
