### ISSUE TITLE
Issue with different currencies

### ISSUE THREAD

**Issue by sebrunt** [SalesforceFoundation/NPSP#6780]
I have custom object Gift__c and I have a task to transfer gift__c to payment.
The issue is that the associated opportunity with the gift__c has different currencies. And when I copy all the fields and try to insert payment, it gives me an error: 
`System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, You can't modify Payment currencies directly. Update the parent Opportunity's currency, and NPSP will automatically update the currency of all related Payment records.: []`

How can I resolve this? Can I disable validation rule?

**Comment by jamesbsfdc** [comment]
Hi @sebrunt Please could you log a support case for this if you require support. See this help article: https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case

We do not provide support via GitHub issues. 

For what it is worth this behaviour is expected. The currently of a payment has to match that of the parent opportunity.
