### ISSUE TITLE
Gift Entry - Multiple Clicks of "Process Batch" Button Generates Multiple Opportunities

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/NPSP#6784]
**Issue**
When ready to process a batch in Gift Entry, if the "Process Batch" button is clicked more than once quickly (as if you are opening a file on your desktop), multiple ApexJobs are queued up generating multiple opportunities from the same NPSP batch and NPSP Data Import record.

**Steps to Recreate**
1. In an NPSP Org with Gift Entry enabled
2. Create a Gift Entry batch
3. Enter a gift and save it
4. Navigate on the page to the "Process Batch" button and click is several times rapidly
5. After a moment, access to the buttons will disappear and a "Processing" page will overlay the batch page
6. If you now navigate to the Contact or Account for the Opportunity you just created, then you will see that there is more than one instance of the gift you entered in the batch

In the replication steps, this is what the field history tracking showed when clicking the "Process Batch"

![image](https://user-images.githubusercontent.com/53280203/146454327-d5d1c364-272d-4710-9ca5-c1744b085fb3.png)

**Workaround**
This issue only seems to occur on first import of the batch if there is more than one click in rapid succession on the Process Batch button. If the "Process Batch" is only clicked once, the batch will process without issue.

**Comment by mbeaty-sf** [comment]
[W-10278181](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000W88MAYAZ/view)

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dl9gQAA&title=gift-entry-multiple-clicks-of-process-batch-button-generates-multiple-opportunities) in the Trailblazer Community for updates.
