### ISSUE TITLE
Household formal greeting not populating when primary contact changes in the household 

### ISSUE THREAD

**Issue by deepthikudrathaya** [SalesforceFoundation/NPSP#6794]
Household formal greeting not populating when primary contact changes. when the primary contact changes in a household, the formal greeting doesnt change as per the primary contact For example: I create Micky Mouse, then I create Minnie Mouse and add Minnie to Micky’s houshold. Micky is primary and mentioned first in the Formal greeting. But when I change the primary of the household to Minnie, Micky is still mentioned first in the formal greeting which is incorrect and should have Minnie mentioned first in the formal greeting

**Comment by jamesbsfdc** [comment]
Hi @deepthikudrathaya  Would you mind logging a support case (https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case) as we don't provide support via Github issues.
