### ISSUE TITLE
Recurring Donations: Customers with greater than 99,999 Recurring Donations will receive a "STRING_TOO_LONG" error when they upgrade to Enhanced Recurring Donations

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/NPSP#6808]
### Background

During the Enhanced Recurring Donations upgrade process we store the results of the Dry Run and the Data Migration jobs as JSON in the "Enhanced RD Data Migration State" field on the Recurring Donations custom setting. The character limit for this field is 255 characters.

### Issue Summary

If a customer who has more than 99,999 Recurring Donations tries to upgrade they will receive an error when the Data Migration completes as the "Enhanced RD Data Migration State" field cannot hold the JSON data associated with both the Dry Run and Data Migration job results.

e.g for a customer with 100,000 Recurring Donations the following sample would total up to 258 characters

{"run":{"total":100000,"processed":100000,"failed":0,"completedDate":"2022-01-13T15:26:27.078Z","batchId":"70754000032i2O0AAI"},"dryRun":{"total":100000,"processed":100000,"failed":0,"completedDate":"2022-01-13T15:18:07.525Z","batchId":"70754000032i0g7AAA"}}

### Steps to Reproduce

1. Create a scratch org that is using Legacy Recurring Donations
2. Insert 100,000 Recurring Donations
3. Run the Dry Run validation job, wait for it to complete and then run the Data Migration job
4. Confirm you receive a STRING_TOO_LONG error on the Recurring Donation upgrade page in NPSP Settings when the Data Migration job completes, and an associated error is created in the NPSP Error log object

### Workaround

The error message can be ignored as it only relates to the update of the custom setting value.

**Comment by jamesbsfdc** [comment]
W-10431505

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dl9bQAA&title=customers-with-greater-than-99-999-recurring-donations-will-receive-a-string_too_long-error-when-they-upgrade-to-enhanced-recurring-donations) in the Trailblazer Community for updates.
