### ISSUE TITLE
Deleting Opportunity Contact Role Is Not Reflected In Contact Soft Credit Customizable Rollups

### ISSUE THREAD

**Issue by chrisbanm** [SalesforceFoundation/NPSP#6827]
We decided that we didn't want to have NPSP create OCR with role of 'Household Member'. So I turned off that feature and mass deleted any OCR with a role of "Household Member' That was a couple of months ago. But we still have contacts that have Soft Credit summary fields (First, Last, Number, Sum) that still reflect those missing OCR's as if they hadn't been deleted even though they are definitely no longer in the database. These deleted OCR's should no longer be contributing to these soft credit summaries.

**Comment by jamesbsfdc** [comment]
Hi @chrisbanm  We don't offer support via GitHub issues. Please can you log a support case. 
https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case

**Comment by chrisbanm** [comment]
This doesn't seem to be a support issue but rather a bug. If OCR's are deleted, shouldn't that affect the rollups that summarize Soft Credits on the Contact? I have logged a support issue, but I still think this is a bug, or at least a completely undocumented and unexpected behavior.

**Comment by jamesbsfdc** [comment]
Hi @chrisbanm  The process by which something gets acknowledged as a bug starts with a support case. 

The issue you are seeing needs to be replicated, and validated that it is something that is not just specific to your org/setup. If it is reproducible outside of your org then it needs to be confirmed whether this is working as expected, a product limitation, a product bug, a documentation bug or there is not already a bug logged for it. 

Also if there is indeed a confirmed bug, having a case associated to the bugs help to inform decisions around prioritisation for addressing it in the backlog. 

Thanks
