### ISSUE TITLE
Partial Soft Credit Role should be picklist to match OCR Role

### ISSUE THREAD

**Issue by jenniferbodiford-bbbsa** [SalesforceFoundation/NPSP#6835]
npsp__Partial_Soft_Credit__c.npsp__Role_Name__c is of type Text(255).  However, both npsp__Account_Soft_Credit__c.npsp__Role__c and OpportunityContactRole.Role are configured as picklist data types.  

The standard "New" button displays the Role as a free text field when on a Partial Soft Credit list view.  The User has the ability to enter any value in that field, and the value is then saved to npsp__Partial_Soft_Credit__c.npsp__Role_Name__c and also to the OpportunityContactRole.Role picklist as an inactive value.  This clutters the options and does not create good data consistency.

The URL "Manage Soft Credits" button, however only provides selectable values from the OpportunityContactRole.Role picklist.

It is also important to note that the NPSP Settings > Customizable code also reconciles to the OpportunityContactRole.Role picklist.  

Current workaround: hide "New" button on Partial Soft Credits so the user is forced to use the "Manage Soft Credits" functionality.  And create a validation rule on the Partial Soft Credits object that disallows any value not configured in the OpportunityContactRole.Role picklist to prevent data imports from inserting non-configured values.  The latter not being a great because if a new value is added to the OpportunityContactRole.Role picklist, the validation rule must also be manually updated to accommodate the new value.

![image](https://user-images.githubusercontent.com/64929981/152550353-1bbf2291-3c4a-4238-913a-01af268434fa.png)
![image](https://user-images.githubusercontent.com/64929981/152550416-289b5231-1390-4585-9e49-72e0bedb1e27.png)
![image](https://user-images.githubusercontent.com/64929981/152550459-c4a5e4d1-d2c5-49a9-bd54-c97d057001d9.png)
![image](https://user-images.githubusercontent.com/64929981/152550608-4981283b-ba3a-4593-9834-28cd8ecba76a.png)

Steps to repeat:

1. Login as user
2. Create new Opportunity
3. From Opportunity, select Partial Soft Credits related list quick link
4. New
5. Add a Contact and enter a bogus Role
6. Save
7. View the Contact Roles related list quick link and see bogus Role
8. Confirm inactive OCR Role picklist value but navigating to Settings > Object Manager > Opportunity Contact Role > Role

**Comment by judisohn** [comment]
@jenniferbodiford-bbbsa Thanks for reporting and the great idea and steps, however, this is a request for an enhancement and not a bug so please create an [Idea for this on the IdeaExchange](https://ideas.salesforce.com/s/search#t=All&sort=relevancy&f:@sfcategoryfull=[Nonprofit%7CNonprofit%20Success%20Pack]) if one doesn't already exist. Thank you!
