### ISSUE TITLE
Batches screen / list view has duplicated columns

### ISSUE THREAD

**Issue by tcharles12** [SalesforceFoundation/NPSP#6875]
This is happening in a partial sandbox. Columns on the Batches screen are duplicated. When I open up the list view field options and select one of the fields to remove, "both" of the fields get removed (which makes sense, because there are not actually two fields). The configuration looks correct and field mappings look correct, so I'm not sure why this is happening.

I tried to replicate this in a full sandbox, and I could not replicate the issue, so perhaps this is a glitch in only certain sandboxes.

![Screen Shot 2022-03-02 at 5 52 09 PM](https://user-images.githubusercontent.com/42197522/157105167-ff679f62-5626-4d3c-a185-6d2c78b7da74.png)

**Comment by judisohn** [comment]
Hi @tcharles12 We do not provide any support through Github issues. Please [open a support case](https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case) so your issue can be isolated and replicated. Thanks!
