### ISSUE TITLE
How to fix - Attempt to de-reference a null object - While trying to Import Campaign Members

### ISSUE THREAD

**Issue by DariusDixon** [SalesforceFoundation/NPSP#6878]
Hello,

I'm trying to import campaign members via npsp data import object, but keep running into the Attempt to de-reference a null object. 
![Npsp1](https://user-images.githubusercontent.com/56740411/157457748-0d614eec-184f-4871-ab37-7de89fd7e25b.PNG)
![Npsp3](https://user-images.githubusercontent.com/56740411/157458043-e4d47256-55ea-46c3-bbe9-b47f80e3fd6a.PNG)

![Npsp2](https://user-images.githubusercontent.com/56740411/157457756-b1d68185-675c-4147-8caa-bb062ff28729.PNG)

**Comment by jamesbsfdc** [comment]
Hi @DariusDixon We do not provide support via GitHub issues. Please could you log a support case for this. In the case creation form if you select the following it should ensure it gets assigned to the correct case queue

* Product: NonProfit, Education and Power of Us
* Topic: Non Profit Cloud
