### ISSUE TITLE
NPSP: Duplicate Merge is not showing all the records in the report

### ISSUE THREAD

**Issue by Rlivingst** [SalesforceFoundation/NPSP#6927]
Referencing this old issue: https://github.com/SalesforceFoundation/NPSP/issues/5593

We have a client that is trying to merge duplicates, but the duplicate merge feature does not show the records that are listed in the Duplicate Items Report. I can't figure out what's going wrong. When they try to run jobs, it fails. I saw the old issue above, but I didn't see any resolution. Does anybody know what would cause this?

**Comment by judisohn** [comment]
@Rlivingst We don't offer support here in Github and there's intentionally no community engagement here. Please post in the [Trailblazer Community](https://trailhead.salesforce.com/trailblazer-community/groups/0F9300000001ocxCAA) or open a [support ticket](https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case). Thanks!
