### ISSUE TITLE
Payment rollups not recalculating in batch

### ISSUE THREAD

**Issue by karenzelevinsky** [SalesforceFoundation/NPSP#6965]
I set up NPSP customizable rollups based on Payments rather than Opportunities. I realized after calculating them for the first time that I was missing a record type filter. I added it and now new opportunities work correctly, and if I click the "Recalculate Rollups" button on an account it corrects the rollup amount for that one account, but running the Rollup Donations Batch doesn't recalculate everything so all the other accounts are still wrong. Shouldn't running the full Recalculate Batch also update payment-based rollups? Thanks!

**Comment by jamesbsfdc** [comment]
Hi @karenzelevinsky We don't offer support via GitHub issues. Please log a support case if you need help from Salesforce or post in an NPSP group in the Trailblazer Community if you want help from the community.
