### ISSUE TITLE
Updates to Relationship record not syncing fields to Reciprocal Relationship record - Enable Custom Field Sync is enabled

### ISSUE THREAD

**Issue by chriswattposse** [SalesforceFoundation/NPSP#7223]
In NPSP Settings > Relationships, we have the Enable Custom Field Sync box checked. Updates to fields that are not selected in the "Fields to Exclude from Sync" section are not syncing to the Reciprocal Relationship record. Aren't fields supposed to sync unless they are explicitly excluded from Sync while Custom Field Sync is enabled? Is there any reason why they would not be syncing?

**Comment by judisohn** [comment]
FYI @chriswattposse - folks from Salesforce and the general community don't monitor and troubleshoot issues here @chriswattposse - you're better off posting in the Trailblazer Community or opening a support case.
