### ISSUE TITLE
Feature/better UI for address dates

### ISSUE THREAD

**Issue by greenstork** [SalesforceFoundation/NPSP#803]
The date selection for when a seasonal address is valid could use a custom UI. Choosing a start day and date and end day and date was confusing in the standard Salesforce UI in the absence of a data picker of some sort.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001frtAAA" target="_blank">W-008267</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
