### ISSUE TITLE
As a developer, I'd like to programmatically initiate household account renaming through apex

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/NPSP#864]
If using a custom naming format, such as "{{!FirstName} {!Middle_Initial__c} {!LastName}", the standard trigger on the Contact object will not flag a change to the Middle_Initial__c as a reason to re-evaluate the household naming. A custom trigger, however could detect that change and make a call to the NPSP class to handle the naming updates.

**Comment by njjc** [comment]
We should kick off renaming when the Household Naming Order field is changed.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fryAAA" target="_blank">W-008268</a>

**Comment by njjc** [comment]
We should also make an [invocable method](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_annotation_InvocableMethod.htm) so people can kick it off from process builder, as well.

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
