### ISSUE TITLE
Separate grace period for each membership type

### ISSUE THREAD

**Issue by aaronbauman** [SalesforceFoundation/NPSP#982]
I'm working with a client who has several very different types of membership, and needs different grace periods for two different types. Would be really useful to expose this through NPSP settings.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsYAAQ" target="_blank">W-008276</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
